### ISSUE TITLE
Definição de Mentor

### ISSUE THREAD

**Issue by woliveiras** [training-center/mentoria#1]
Vamos usar essa issue para deixar fixado a definição do que o Mentor vai fazer para, depois, subirmos um arquivo com esse guide no repo. :)

cc: @baltazarparra @danilovaz @LFeh @JGcarv @willycamargo @icaromh @sanderweb @augustoabreu @robsonbittencourt

**Comment by woliveiras** [comment]
Pra mim, o Mentor é o cara que vai auxiliar a pessoa na carreira.

No caso ele deve ajudar a pessoa a definir um plano de estudos com base no que ela já conhece e onde quer chegar, levantar pontos que ele conhece sobre mercado de trabalho e apresentar para essa pessoa ter uma visão sobre como o mercado funciona, se a mesma ainda não conhecer esses pontos (como ressaltar a importância do inglês, etc) para montar um plano de carreira.

Basicamente ajuda a remover barreiras na carreira da pessoa, certo?

**Comment by danilovaz** [comment]
Dois dos maiores mentores que já existiram podem nos guiar nessa definição.

> **Always pass on what you have learned** - *Mestre Yoda*

O mentor é uma pessoa que busca repassar seus conhecimentos e experiências, preparando o indivíduo para situações críticas e aconselhando para situações de sucesso na área de comum interesse.

> **Jacket on, jacket off** - * Mr. Han*

O mentor faz isso através de disciplina contínua das partes envolvidas; buscando sempre incentivar o indivíduo a extrair o seu melhor e jamais deve humilhar, rebaixar ou desmerecer o pupílo por não conseguir alcançar os objetivos que lhe foram confiados.

**Comment by woliveiras** [comment]
Cara, esse trecho dessa issue vai ficar no manifesto! Com certeza. Falou bonito.

**Comment by danilovaz** [comment]
@woliveiras tamojunto! :smile:

**Comment by baltazarparra** [comment]
Acho que a gente poderia começar com um numero bem limitado de mentores, pra tirar a ideia do papel. Sugiro pedir ajuda de desenvolvedores com mais bagagem, para indicar possíveis mentores para esse inicio.

**Comment by woliveiras** [comment]
Já da pra tacar pau nisso! Bora chamar nas comunidades, nos conhecidos, etc os caras que podem ajudar a votar nos mentores e já começar a selecionar os caras?

**Comment by jlamim** [comment]
Eu posso me autoindicar como mentor. Tenho uma boa bagagem com desenvolvimento web, afinal, já são 10 anos atuando nessa área.

**Comment by woliveiras** [comment]
Já comenta [aqui](https://github.com/training-center/mentoria/issues/5) @jlamim

**Comment by woliveiras** [comment]
Basicamente já temos como deveria ser [o perfil dos mentores](https://github.com/training-center/mentoria/issues/1#issuecomment-207592225), certo?

Podemos fechar essa issue e já tacar pau procurar uma bancada pra escolher os primeiros mentores?

**Comment by woliveiras** [comment]
Enfatizei sobre o Mentor [aqui](https://github.com/training-center/mentoria#quero-ser-um-mentor).

Se tudo estiver OK, podemos fechar a issue e tratar sobre a bancada que vai avaliar os mentores em outra issue.

**Comment by danilovaz** [comment]
@woliveiras sim sim, essa também está OK. acho que agora devemos nos concentrar em como será a avaliação dos mentores

**Comment by woliveiras** [comment]
Show cara!
