### ISSUE TITLE
[Quero ser mentor] de Desenvolvimento Web - Foco em PHP e JS

### ISSUE THREAD

**Issue by WendellAdriel** [training-center/mentoria#10]
**Nome:** Wendell Adriel Luiz Silva

**Mini descrição:** Tenho 23 anos, sou formado em Análise e Desenvolvimento de Sistemas, sou um Zend Certified PHP Engineer e Scrum Fundamentals Certified. Atuo como Analista Desenvolvedor Web e também como Criador e Tutor da CodeShare. Trabalho com desenvolvimento de sites e softwares há 7 anos e sempre procuro me manter atualizado nas melhores tecnologias e metodologias no desenvolvimento de softwares. Há alguns anos estou focado no desenvolvimento para Web. Já fiz (e continuo fazendo) diversos cursos na área de desenvolvimento e conheço diversas linguagens e tecnologias. Gosto muito do desenvolvimento Front-End, porém prefiro o desenvolvimento Back-End e minhas linguagens preferidas são PHP, Ruby, Python e Java. Recentemente também um grande fã de desenvolvimento utilizando a MEAN Stack.

**Links:**
- **[Github](https://github.com/WendellAdriel)**
- **[Linkedin](https://br.linkedin.com/in/wendelladrielti/en)**
- **[Página pessoal](http://wendelladriel.github.io)**
- **[Projeto pessoal](http://codeshare.com.br)**
- **[Blog](http://education.codeshare.com.br)**
- **[Facebook](https://facebook.com/wendell.adriel.7)**
- **[Twitter](https://twitter.com/wendell_adriel)**

**Comment by woliveiras** [comment]
Pode abrir PR seguindo isso [aqui](https://github.com/training-center/mentoria#quero-ser-um-mentor) mano @WendellAdriel
