### ISSUE TITLE
Preciso de um(a) mentor(a) FullStack com foco em Java e Javascript

### ISSUE THREAD

**Issue by marcoblos** [training-center/mentoria#100]
E ai pessoal, tudo bem?
Meu nome é **Marco Antonio Blos de Souza**, trabalho como desenvolvedor _fullstack_ a aproximadamente 2 anos e 4 meses, sempre na mesma empresa. Tudo está indo bem, consigo me "virar", resolver os problemas do dia a dia, estudar para a faculdade, estudar inglês e ainda tirar um tempo para estudar o que eu deveria saber para complementar meu conhecimento afim de desempenhar melhor o meu trabalho, enfim, uma correria, exatamente igual a vida de todo mundo! hahaha
O que me fez chegar até aqui e pedir ajuda é que conforme o tempo passa e eu consigo "enxergar" um pouco mais longe, eu percebo a quantidade de coisas que eu ainda tenho que aprender. Isso por um lado é super legal, pois dá muita motivação de continuar estudando e aprendendo coisas novas, porém, não posso esquecer de que não posso desviar demais o foco do meu dia a dia, se eu fizer isso, talvez eu não consiga aproveitar determinado conhecimento para o meu momento atual. Entendem? Sei que vocês entendem.. ;P
Conhecimentos:
Java, Javascript (ES5 e Ecmascript 2015), Sql, SpringBoot, Maven, NPM, AngularJS.
Deixo claro também que esses conhecimentos ainda são superficiais e que eu deveria reforçá-los, mas, diante de toda a "chuva" de informações que se tem quando começamos a escutar _podcasts_, se interessar pela comunidade, nem que seja somente olhando alguns trabalhos para tentar entender melhor de código, sem realmente participar, etc, **não sei onde e no que focar**, para ser mais atrativo, perante o mercado e principalmente para a minha própria evolução.
Acho que escrevi demais, é isso aí! hahaha

[Facebook](https://pt-br.facebook.com/people/Marco-Antonio/1394020870)
[Linkedin](https://www.linkedin.com/in/marco-antonio-blos-de-souza-09471645?trk=nav_responsive_tab_profile)

**Comment by woliveiras** [comment]
> Entendem? Sei que vocês entendem.. ;P

KKKKKKK

Com certeza @marcoblos. :joy: 

> Java

Uuuuurrgh :cold_sweat: :cold_sweat:

Vamos ver se alguém dos @training-center/mentors consegue te ajudar.

Com as linguagens, eu só conseguiria ajudar com o JavaScript, mas, se quiser, podemos trocar uma ideia sobre carreira.

**Comment by marcoblos** [comment]
Obrigado pela rápida resposta @woliveiras
Com toda a certeza eu aceito conversar sobre carreira e digo mais: não me importaria nada de focar em JavaScript.
Qualquer conhecimento é _SEMPRE_ bem vindo.
Inclusive na empresa onde eu trabalho, tem uma equipe que está trabalhando com Node (só conheço uma equipe que trabalha com node aqui na empresa).
Então, estou a disposição.
Abraço! :smile:

**Comment by woliveiras** [comment]
:metal: 

Show de bola cara!

Vou te chamar no Facebook pra gente trocar uma ideia.

**Comment by woliveiras** [comment]
CC: @wesleycoder

**Comment by wesleycoder** [comment]
Eu já estava de olho nessa issue já só esperando a aceitação do #102 para dizer que eu estava querendo adotar o @marcoblos como pupilo ^^.
E aí @marcoblos o que acha?
Podemos combinar como fazer?

**Comment by woliveiras** [comment]
:raised_hands:

**Comment by marcoblos** [comment]
@wesleycoder com certeza aceito tua ajuda mano!
Acabei de te adicionar no FB, se quiser, conversamos por lá mesmo!
:sunny:

**Comment by marcoblos** [comment]
@woliveiras estou tentando entender porque a label de Java é vermelha! :joy:

**Comment by woliveiras** [comment]
É cor de perigo/fique longe, mano! kkkkk

**Comment by woliveiras** [comment]
Em JS é amarelo por que a pessoa tem de pensar umas duas vezes antes de escolher. HUAHUAHAU 😂

**Comment by wesleycoder** [comment]
Concordo plenamente com as cores escolhidas!!! :laughing:

**Comment by marcoblos** [comment]
HAHAHAHA, não vou comentar essa escolha de cores, preconceito é feio! :joy:

**Comment by woliveiras** [comment]
UHAUHAHUUAUHAUHAUAHUHUA

**Comment by marcoblos** [comment]
@woliveiras tem algum slack pra nós? :dart:

**Comment by woliveiras** [comment]
Pro mentoria em específico não @marcoblos, mas tem pro Training Center: https://ctgroups.herokuapp.com/

Falando nisso, você me lembrou que preciso colocar isso no repositório!

**Comment by woliveiras** [comment]
Mano @marcoblos só falta atualizar seu perfil com o link pro perfil do mentor e podemos fechar essa issue, né?

**Comment by marcoblos** [comment]
@woliveiras isso aí! Hoje a noite em casa eu faço o MR adicionando o @wesleycoder no meu perfil. Eu faço o MR linkando pra fechar essa issue daí.

**Comment by woliveiras** [comment]
:metal:

**Comment by marcoblos** [comment]
@wesleycoder alterei finalmente, mano! hahaha
https://github.com/training-center/mentoria/pull/107

**Comment by woliveiras** [comment]
Sucesso manos! 

Agora vou fechar a issue. Qualquer coisa é só dar um salve. :smile:
