### ISSUE TITLE
Mentoria fixa, é possível?

### ISSUE THREAD

**Issue by cezarlz** [training-center/mentoria#1035]
Oi pessoal, tudo bem? Meu nome é Cezar, sou desenvolvedor web desde 2010 e já passei por muitas tendências e fases hehe, comecei com PHP, depois de dediquei ao front-end porém até hoje gosto de fazer alguma coisa com backend.

Recentemente me mudei para Berlim, na Alemanha, para ser frontend engineer e recentemente me tornei squad lead do time onde trabalho (aqui temos muuuuitos times).

Eu já fui mentor aqui no Training Center e pelo que me lembro ajudei uns 5 ou 6 pessoas via email. Agora com as coisas mais estabilizadas na minha vida, eu gostaria de voltar a ser mentor porém de um jeito diferente (não sei se alguém já fez isso aqui, desculpe).

Eu gostaria de ser mentor fixo de 3 pessoas e com espaço de 30 minutos por semana para uma conversa por Skype sobre qualquer assunto que eu possa ajudar durante 3 meses. As conversas poderão sobre qualquer assunto desde carreira, soft skills, tecnologia, frameworks, linguagens de programação, tudo que eu puder ajudar baseando-se na minha carreira e experiência. Quero ajudar durante 3 meses e então começar uma nova "turma". Durante as semanas podemos falar normalmente via email.

As conversas via Skype seriam toda quinta-feira começando às 20:30 e terminando às 22:00 (Horário da Alemanha). Respectivamente 15:30 e 17:00 no Brasil, horário de Brasília. Eu sei que o horário não ajuda muito...

É possível? O que preciso fazer para começar?  

Obrigado!

**Comment by luizbills** [comment]
Colega, vai fundo. Aqui no mentoria não estabelecemos regras mais (se é que um dia teve).

> É possível? O que preciso fazer para começar?

Basta só encontrar os seus mentorados :)

**Comment by woliveiras** [comment]
> Eu gostaria de ser mentor fixo de 3 pessoas e com espaço de 30 minutos por semana para uma conversa por Skype sobre qualquer assunto que eu possa ajudar durante 3 meses.

Isso seria lindo, mano!!

**Comment by ericdouglas** [comment]
@cezarlz ideia excelente cara. Acredito imensamente nessa abordagem bem direta/pessoal, acho muito poderosa. Parabéns de verdade pela disposição em ajudar outras pessoas.

**Comment by cezarlz** [comment]
Obrigado pessoal, disponibilizei um form para começar a escolher os candidatos: https://goo.gl/forms/4ptErKbuwLrjwarU2
