### ISSUE TITLE
Preciso de Mentor Front-end

### ISSUE THREAD

**Issue by MarcioSouz** [training-center/mentoria#104]
**Nome:** Marcio Alves

**Descrição:** Atualmente eu me encontro estudando, bom começo na Universidade semana que vem, como Análise e Desenvolvimento de Sistemas, amo Programação, passei a gostar de programação devido aos códigos, e de ver sites de outras empresas fora de padrão... Hoje eu tenho um conhecimento básico, em relação a área em si da Programação, adquiri este conhecimento através, de videos do youtube mesmo e alguns sites que ensinam, isso antes de eu decidir em querer a começar estudar Análise... Bom meu intuito aqui é tirar as minhas dúvidas com vocês, e aprendendo com vocês, estarei sempre grato em retribui-los o favor...

**Nível de conhecimento atual:** Básico 

**Contatos:**

[E-mail](mailto:marciiosouza@outlook.com)
[Facebook](https://www.facebook.com/MarciioSouzah)
[Twitter](https://twitter.com/MarciioSouz)

**Comment by wesleycoder** [comment]
@woliveiras, esse é o pupilo da minha cidade que comentei, auxiliem ele na criação do perfil #105. Confere aí. Tks.

**Comment by woliveiras** [comment]
Show de bola cara!
