### ISSUE TITLE
Preciso de mentoria em front end

### ISSUE THREAD

**Issue by allonsmandy** [training-center/mentoria#1089]
Pessoal, enviei no form já faz um tempo meu cadastro precisando de mentoria. Não sei se o projeto ainda está na ativa, por isso vou tentar mandar esta issue...

Tenho 18 anos e estou começando minha carreira em front end, mas já tive experiencias no passado com ela. Este ano estou focando bastante em cursos online, não faço faculdade, então por isto vez ou outra me sinto perdida por ter tantos conteúdos...

Atualmente estou focada no css e javascript, também estudo node e coisinhas de design e ux :) Preciso muito de um mentor, gostaria muito de ajuda no front e principalmente na carreira :(

obrigada de qualquer forma <3

**Comment by jcserracampos** [comment]
@allangrds O projeto continua ativo.
Vamos encontrar uma boa pessoa mentora para lhe auxiliar.

Se já tiver encontrado, só fechar a issue.
