### ISSUE TITLE
Estou iniciando e preciso de um mentor(a) para me ajudar a organizar meu caminho de estudos

### ISSUE THREAD

**Issue by AnaVargasF** [training-center/mentoria#1099]
Olá, tudo bem? 
Na minha adolescência estudei um pouco de HTML e CSS, mas por motivos pessoais precisei parar. Em agosto resolvi retornar meus estudos de programação com JavaScript. Estudei nas 2 últimas semanas, mas não estou rendendo e por isso acredito que devo voltar e estudar melhor HTML e CSS.
Estou precisando de um mentor(a) de HTML, CSS e JavaScript para me ajudar a estruturar o meu caminho de estudo. Tenho o objetivo de conseguir Freelas/Trabalho até dezembro, por isso estabeleci algumas metas de setembro até dezembro. Mas, se possível, gostaria de ajuda para melhorá-las. Tenho disponível 2h diárias para estudo. 

Desde já agradeço.
Ana

**Comment by jcserracampos** [comment]
@AnaVargasF entra em contato comigo no Telegram e vamos ver se conseguimos alinhar.

**Comment by AnaVargasF** [comment]
@jcserracampos Eu não tenho Telegram. Poderia ser pelo e-mail ou twitter?

**Comment by jcserracampos** [comment]
@AnaVargasF Pode ser Twitter.
É o mesmo que aqui.

**Comment by AnaVargasF** [comment]
@jcserracampos O meu Twitter é @AnaVargas_F
