### ISSUE TITLE
Preciso de um mentor em Front-end com foco em Javascript

### ISSUE THREAD

**Issue by luzaosalles** [training-center/mentoria#110]
**Nome:** Lucas Sales

**Descrição:** 22 anos, Designer Gráfico nível **rookie** atualmente estudando Marketing. Cuido da parte de Marketing Digital de uma empresa com foco no **_inbound marketing_**, faço a manutenção do site e do blog da empresa, crio conteúdo, campanhas e tudo mais, e ainda tá sobrando tempo pra aprimorar as técnicas **front-end** tudo. Tenho noção de HTML e CSS, agora preciso aprender os conceitos de Javascript pra poder usar aqueles plugins maravilhosos e saber onde mexer quando der um problema. Enfim, issaê! 

**Nível de conhecimento atual:** Em Javascript: Só sei o nome. HTML e CSS: 6.5/10

**Contatos:** [facebook.com/luvetica](https://facebook.com/luvetica) / [linkedin.com/lucas-sales](http://ow.ly/YvzC303qN9P) / [twitter.com/luvetica](https://twitter.com/luvetica)

**Comment by woliveiras** [comment]
Fala @luzaosalles 

Bem vindo cara!

Vamos ver se alguém dos @training-center/mentors consegue te ajudar.

**Comment by wesleycoder** [comment]
Opa, esse pupilo é meu! Hahaha!
Eu já estou aconselhando ele, fui eu quem apresentou o projeto para ele.
Acho q ele já pode criar o PR com o perfil dele.

**Comment by woliveiras** [comment]
Ai sim @wesleycoder!!

Assim é sucesso ein cara.

**Comment by woliveiras** [comment]
Tudo OK, galera.

Fechando a issue.
