### ISSUE TITLE
Plataforma para cadastro dos mentorados

### ISSUE THREAD

**Issue by fredsonchaves07** [training-center/mentoria#1110]
E ai galera. Tudo tranquilo?

Eu sou novo por aqui e fiquei um pouco perdido na questão das mentorias.

Tem alguma plataforma que solicite alguma mentoria? Ou seja, algum tipo de cadastro de mentorados?

**Comment by jcserracampos** [comment]
@fredsonchaves07 é só você contactar uma pessoa que está listada como disponível e ver se ela pode lhe atender.

**Comment by fredsonchaves07** [comment]
Sem querer encomadar mais, onde posso encontrar a lista de pessoas disponíveis? Tem algum link específico?

**Comment by mauricioabreu** [comment]
@fredsonchaves07 aqui: https://github.com/training-center/mentoria/blob/master/mentors-list.md

Obs.: esse link no README. Boa sorte na procura de mentor 🤗

**Comment by fredsonchaves07** [comment]
Show! Valeu galera :)
