### ISSUE TITLE
Mentoria em Javascript / Front-end

### ISSUE THREAD

**Issue by MarcoMonteiro94** [training-center/mentoria#1112]
Olá! 

Me chamo Marco, tenho 24 anos e estudo programação voltada ao front-end tem mais ou menos um ano. Estou tentando ingressar no mercado de trabalho, mas me falta muita prática e falta de assimilação em alguns conteúdos. Busco auxilio para conseguir quebrar essa barreira inicial e conseguir construir meus próprios projetos!

Obrigado :)

marcomonteiro94@hotmail.com

**Comment by LeoVitale** [comment]
Fala @MarcoMonteiro94 tudo bem?
Você ainda procura algum mentor de FrontEnd? 

Abs

**Comment by MarcoMonteiro94** [comment]
Fala @LeoVitale !

Esqueci de dar close nessa issue. Já estou sendo mentorado pelo @wesleycoder . Te agradeço muitíssimo a oportunidade!
