### ISSUE TITLE
Preciso de um(a) mentor(a) de programação

### ISSUE THREAD

**Issue by GabiDias** [training-center/mentoria#112]
**Nome:** Gabrielle Dias
**Descrição:** Aprender mais sobre programação e Web
**Nível de conhecimento atual:** Estou na faculdade de ADS e meus conhecimentos foram adquiridos por meio de um curso Técnico de Informatica.
**Contatos:** gabi_dias5@hotmail.com

**Comment by woliveiras** [comment]
Bem vinda @GabiDias!

Vamos ver se alguém dos @training-center/mentors consegue te ajudar.

**Comment by wesleycoder** [comment]
Esta é uma pupila que veio por indicação do nosso outro integrante @MarcioSouz.
Mais uma de quem vou tomar conta também.
É sempre bom ver a comunidade crescendo!
Vou ajudá-la à criar o PR com o perfil.

**Comment by woliveiras** [comment]
Show de bola @wesleycoder 

Parabéns cara!

**Comment by Baco23** [comment]
Bom dia. Parabéns pelo projeto, nota mil!

Uma pergunta: a tutoria é individual? Pois tenho interesse em aprender mais sobre programação. Sou advogado, mas tem um mês que comecei uma faculdade de ADS. Posso integrar o grupo, ou tenho que "requisitar" um tutor só pra mim?

Abcss e obrigado.

**Comment by Baco23** [comment]
Bom dia. Parabéns pelo projeto, nota mil!

Uma pergunta: a tutoria é individual? Pois tenho interesse em aprender mais sobre programação. Sou advogado, mas tem um mês que comecei uma faculdade de ADS. Posso integrar o grupo, ou tenho que "requisitar" um tutor só pra mim?

Abcss e obrigado.

**Comment by dorianneto** [comment]
@Baco23 a mentoria é individual. Cria lá uma issue solicitando um mentor que com certeza irá chover de gente querendo ajudar ;)
