### ISSUE TITLE
Preciso de um(a) mentor(a) de Front End

### ISSUE THREAD

**Issue by genorchiomento** [training-center/mentoria#115]
## Genor Alberto Chiomento Junior

Estudante de Ciência da Computação e analista de homologação e suporte. Fazendo cursos na internet, como o Alura para melhorar front end e aprender mais sobre outras tecnologias.
Quero aperfeiçoar o meu front end e futuramente pegar um pouco do back end para ter noção.
Quero trabalhar pra mim mesmo (empreender) ou me tornar um freelancer, pretendo ter um blog para postar meu aprendizado e dicas para as pessoas que tiverem vontade de aprender também.
Meu nível é básico, brinco com front end a pouco tempo, mas sempre tento melhorar.

- [Meu Facebook](https://pt-br.facebook.com/gchiomento)
- [Meu GitHub](https://github.com/genorchiomento)
- genor.chiomento@gmail.com

**Comment by woliveiras** [comment]
Bem vindo @genorchiomento!

Vamos ver se alguém dos @training-center/mentors consegue te ajudar.

**Comment by wesleycoder** [comment]
@genorchiomento ainda tenho espaço na agenda para mais um pupilo, talvez eu possa suprir suas expectativas, que tal me contactar por qualquer canal no meu [perfil](https://github.com/training-center/mentoria/blob/master/mentores/perfis/wesley_queiroz.md) para bater-mos um papo?

**Comment by woliveiras** [comment]
Boa @wesleycoder

**Comment by genorchiomento** [comment]
@wesleycoder uhuu! Vou entrar em contato! o/ 

Gracias @woliveiras

**Comment by woliveiras** [comment]
Tudo dando certo entre vocês @genorchiomento e @wesleycoder?

**Comment by wesleycoder** [comment]
Sim, já conversamos e o @genorchiomento ficou de preparar o perfil dele, em breve ele deve mandar o PR.

**Comment by woliveiras** [comment]
Perfeito @wesleycoder :smile:

**Comment by wesleycoder** [comment]
@woliveiras pode fechar essa issue, o PR #120 já teve o `merge` feito.

**Comment by woliveiras** [comment]
Valeu por avisar @wesleycoder! 😁
