### ISSUE TITLE
Mentor Desenvolvimento Web (Iniciante)

### ISSUE THREAD

**Issue by Aline-Sampaio** [training-center/mentoria#1151]
Meu nome é Aline eu estudo programação a uns meses mas tenho receio de sair da teoria porque não sei muito bem quais passos seguir, pois mesmo tendo objetivos nítidos a quantidade de informação, cursos e tecnologias me deixam um tanto perdida. Já vi situações que indicam aprender sobre o sistema operacional antes de aprender uma linguagem, enquanto outros Devs indicam começar por uma linguagem direto. Isso me faz recomeçar várias vezes o mesmo caminho, por isso queria saber se alguém poderia ser o meu mentor por um tempo só para me ajudar nesse inicio caótico. 
Obrigada.

**Comment by wilcorrea** [comment]
Oi Aline, eu tenho bons conhecimentos sobre JavaScript e PHP. Posso ficar a sua disposição e podemos marcar algumas chamadas caso seja do seu interesse.
Sobre por onde começar gosto de acreditar que depende de onde você quer chegar. Por isso seria mais legal a gente conversar para poder entender melhor sua história e ver qual plano é possível traçar. No fundo todos os caminhos levam ao mar = )

**Comment by Aline-Sampaio** [comment]
Oi William quero sim. Você pode me enviar um email ou me passar o seu? 
alineg.sampaio@outlook.com ai marcamos um horário para conversar.
Obrigada pela sua disposição em ajudar.

**Comment by jcserracampos** [comment]
Fechando provisoriamente.
Se não der certo a mentoria, basta abrir uma nova issue <3
