### ISSUE TITLE
Preciso de um mentor JavaScript 

### ISSUE THREAD

**Issue by aldairandre** [training-center/mentoria#1157]
Olá meu nome é Aldair Dos Santos André sou Angolano e tenho 21 ano, ja faz um tempão que eu tento aprender Javascript e meio que não consigo sempre entender sempre que chega na momento de estudo de Objetos, funções e arrays, pior ainda quando se fala de manipulação do DOM parece ser algo complicado, estou estudando sempre mais eu preciso mesmo de ajuda.

**Comment by wilcorrea** [comment]
hey @aldairandre me chama no `wilcorrea@gmail.com` ou no https://t.me/wilcorrea

**Comment by aldairandre** [comment]
Olá William, estou mandando esse email para saber como será a sua mentoria
para comigo.
Eu estou frequentemente no WhatsApp meu número +224924569259

**Comment by aldairandre** [comment]
Olá vc poderia verificar a sua caixa de email, mande te um email @wilcorrea

**Comment by evertoncabral** [comment]
@aldairandre , me passa seu perfil do Linked In pra conversarmos? Eu tentei te add no whatsapp mas não consegui :/

**Comment by aldairandre** [comment]
Olá @evertoncabral , me passa seu whtatsapp que eu mando uma msg eu ainda não criei nenhum perfil no Linked.

**Comment by coderamos** [comment]
@aldairandre tudo certo? me chama no linkedin que eu te ajudo: https://www.linkedin.com/in/coderamos/
