### ISSUE TITLE
Olá! Gostaria de um(a) mentor(a) Front End!

### ISSUE THREAD

**Issue by adlagomes** [training-center/mentoria#1158]
Comecei a estudar por conta própria em fevereiro desse ano (2021), mas acabei entrando num curso de programador web e perdi uns dois meses aprendendo java e muita coisa teórica. Resolvi parar o curso e recomeçar no html e css e depois javascript. To com sentimento de ter perdido tempo e gostaria muito de começar logo a trabalhar na área. Tenho tempo integral para me dedicar aos estudos mas não consigo me planejar direito, são muitas coisas.

**Comment by hmassareli** [comment]
Olá! ainda precisa de ajuda?
meu linkedin é linkedin é: 
[](https://www.linkedin.com/in/henrique-castilho-massareli-66a4a914b/)
