### ISSUE TITLE
Procuro mentoria para python e django (back end)

### ISSUE THREAD

**Issue by NahLima** [training-center/mentoria#1159]
Boa noite! Sou a Naiara tenho pouquíssimo tempo em programação, conclui minha transição de carreira este ano. Consegui uma oportunidade como desenvolvedora back end  jr. Tenho algumas dificuldades e gostaria de um acompanhamento para melhorar meu desenvolvimento na empresa, meu raciocínio lógico e técnicas. Fico no aguardo! :)

**Comment by mauricioabreu** [comment]
Oi, Naiara, tudo bem?

Acho que posso te ajudar com isso. Hoje já faço mentoria no trabalho de outras pessoas júnior e fiz outras duas através do mentoria.

Quer bater um papo sobre seus problemas?

**Comment by NahLima** [comment]
Oi Mauricio quero conversar sim! Como continuamos?

**Comment by mauricioabreu** [comment]
Oi Naiara! Vi que me adicionou no linkedidn. Podemos trocar ideia da mentoria por lá e depois ver o que fica melhor.
Abraço!
