### ISSUE TITLE
Procura-se de um(a) mentor(a) de Front, pendendo para UX

### ISSUE THREAD

**Issue by jaqueventurim** [training-center/mentoria#116]
Meu nome é **Jaqueline Venturim**, sou estudante de Sistemas de Informação, mas descobri minha paixão inabalável por UX <3.
Quero aprender Front pra ajudar na minha carreira de UX. Como faço faculdade de técnologia já estudei um pouco de HTML, CSS. Sei um teko de Java (porque não curto, mas sou obrigada a estudar) e tô aprendendo Android.
Já surgiram várias oportunidades de eu ajudar em algum site como front, mas sempre desisto porque não consigo quebrar a primeira barreira de codar num projeto, e não nos exercícios da aula ):

Bom, ia amar ter uma pessoa pra me guiar e me ajudar a passar por essa barreira e depois ficar orgulhosa de eu poder repassar o meu conhecimento pra comunidade 💃 

Ps.: seria ótimo se você também soubesse Git, pois to começando num projeto agora e to me matando pra mexer no repositório hahaha

**Curtiu a descrição? Amou? Quer entrar nesse desafio comigo pra gente ahazar?**

Então fala comigo por algum desses aqui oh  
                                                                          
[Facebook](https://www.facebook.com/jaqueventurim)
[Twitter](https://twitter.com/jaqueventurim)
[Git](https://github.com/jaqueventurim/)

**Comment by woliveiras** [comment]
Excelente descrição @jaqueventurim! 😄 

Vamos ver se alguém dos @training-center/mentors consegue te ajudar.

**Comment by ubirajarapelli** [comment]
@woliveiras e @jaqueventurim posso mentorar se quiser... como faço p me tornar um mentor?

**Comment by woliveiras** [comment]
🙌 

Vem monstro!! 

Segue esse esquema aqui mano: https://github.com/training-center/mentoria#quero-ser-um-mentora

**Comment by woliveiras** [comment]
Está rolando o processo entre vocês, jovens @jaqueventurim e @ubirajarapelli?

**Comment by jaqueventurim** [comment]
Na verdade não ):
Eu pensei que ele teria que passar por um processo e acabei esperando ele me contatar rs, que lesada

**Comment by nandomoreirame** [comment]
Posso mentorar ela se o rapaz ali não puder, na vdd podemos trocar experiências sobre UX e Front-End 

Estou a disposição

**Comment by woliveiras** [comment]
Show de bola @nandomoreirame 

Caso o @ubirajarapelli não responda aqui hoje, você pode assumir. 😄

**Comment by ubirajarapelli** [comment]
Bom dia @woliveiras, @jaqueventurim  e @nandomoreirame, me desculpem a demora p responder, foi uma correria esse mês, né @woliveiras. Organizamos um evento aqui na região em que moramos (ABC Paulista), que tomou o nosso tempo.

Mas estou na pegada dessa mentoria!

**Comment by nandomoreirame** [comment]
Toca o barco @ubirajarapelli e sucesso! :+1:

**Comment by woliveiras** [comment]
Verdade @ubirajarapelli 

Então tacale pau mano!

Sucesso! 🙌

**Comment by jaqueventurim** [comment]
@ubirajarapelli podemos conversar por onde? Tô a disposição o/

**Comment by ubirajarapelli** [comment]
@jaqueventurim eu prefiro por email,

**Comment by jaqueventurim** [comment]
Fechou @ubirajarapelli ! jaqueventurim@gmail.com (se não puder colocar e-mail aqui me avise, pls D: hahaha)

**Comment by woliveiras** [comment]
Email pode @jaqueventurim 
Só não pode celular. :smile: 
Celular só troque por email com o seu mentor. Senão... Vish, vários trotes.

Assim que subirem seus perfis, eu vou fechar a issue. Taquem pau ae que é nozes!

Qualquer duvida é só chamar. :raised_hands:

**Comment by woliveiras** [comment]
@nandomoreirame 

A @jaqueventurim ainda precisa de ajuda, você ainda consegue um tempinho pra entrar em contato com ela?

**Comment by woliveiras** [comment]
@nandomoreirame e @jaqueventurim estão em contato?

**Comment by jaqueventurim** [comment]
@woliveiras não :(

**Comment by nandomoreirame** [comment]
@woliveiras eu posso mentorar ela sim, vc está no slack do CT @jaqueventurim? Se tiver ma chama lá pra eu te add no Grupo privado e te apresentar para meus pupilos ;)

**Comment by woliveiras** [comment]
\o/

Sucessoooo

**Comment by woliveiras** [comment]
Fala galera! 

Vou fechar a issue por já ter um tempo aberta e já estar tudo começando a caminhar.

Qualquer problema podemos reabrir.
