### ISSUE TITLE
Mentor em Javascript

### ISSUE THREAD

**Issue by JOAOSC17** [training-center/mentoria#1164]
Oi pessoal,
Meu nome é João e eu tenho 18 anos. Estou a um tempo aprendendo sobre programação web, mas estou a algum tempo empacado em javascript pq já faz alguns meses que estudo a linguagem e ainda não consegui começar a "pensar" em javascript e queria alguém que me ajudasse com isso.
Email: costav1402@gmail.com

**Comment by hmassareli** [comment]
https://www.linkedin.com/in/henrique-castilho-massareli-66a4a914b/
Manda mensagem, acho que posso te ajudar, consegui meu primeiro emprego como front-end depois de uns 10 meses de treino
