### ISSUE TITLE
Procuro um mentor JavaScript e carreira

### ISSUE THREAD

**Issue by alesalg** [training-center/mentoria#1165]
Boa noite a todos, 

Me chamo Alexandre, tenho 30 anos, sou formado em administração e pós graduado em Logistica 
Trabalhei na area de suprimentos durante 10 anos e hoje tenho o interesse em migrar para a carreira de desenvolvimento
Hoje estou cursando Engenharia da Computação 

Atualmente estou estudando Javascript/ HTML/ CSS ja vi um pouco de Python também, gostaria de um mentor que me auxilie nesta trilha de estudos, pois tem tanto conteudo gratuito na internet que acabo ficando um pouco perdido

Preciso de um Mentor que pudesse me  auxiliar nesta trilha em JavaScript e recolocação de carreira 

Meu contato: allesalg@gmail.com

**Comment by hmassareli** [comment]
Olá! ainda precisa de ajuda? Me chama no linkedin: 
https://www.linkedin.com/in/henrique-castilho-massareli-66a4a914b/
