### ISSUE TITLE
Preciso de mentoria com pré processadores e boas práticas de CSS

### ISSUE THREAD

**Issue by joselialcosta** [training-center/mentoria#118]
Hey! 
Sou a Josélia, estou envolvida com front-end desde o final de 2014.
Apesar de ter feito algumas formações específicas, eu sinto que sei um pouquinho do básico, um pouco de intermediário e um pouco de avançado. Nessa salada toda, as vezes fico muito perdida e pelo fato de não terem muitos desenvolvedores focados em front aqui no meu trampo atual, sinto dificuldades de melhorar meu código e de não ser refém de frameworks como o famigerado bootstrap.

email: joselialcosta@gmail.com

Tks!

**Comment by akfzambrana** [comment]
Opa! essa pupila aqui é minha :smile: 
Pode ser @woliveiras?

**Comment by woliveiras** [comment]
Opa! Tá lá então! 

Só subir o perfil que é sucesso!

**Comment by akfzambrana** [comment]
Top :tada:

**Comment by woliveiras** [comment]
Como já está tudo certinho, fechando a issue.

Qualquer coisa é só dar um toque. 😄
