### ISSUE TITLE
Quero ser mentor de CSS e HTML

### ISSUE THREAD

**Issue by akfzambrana** [training-center/mentoria#12]
*Nome:* Andréa Zambrana

*Mini descrição:* Desenvolvedora front-end desde 2007. Não tenho formação superior, sou 100% autodidata. Atualmente trabalho no time *Multicanal e mobile* na Amil. Meu foco é em desenvolvimento de HTML, semântico e acessível, e CSS pra grandes aplicações e que tem skins diferentes. Eu amo CSS :smile:. Tenho um blog mas que não tem muitos artigos técnicos. Faço parte da comunidade @front-ladies do ABC e atualmente estou dando um [curso básico gratuito de front-end para mulheres via Hangout](https://www.youtube.com/channel/UCpruvBgT4fET_h42IIxPDjA). Não tenho muita coisa no meu github e não tenho portfolio, mas fiz uma grande parte da base do CSS dos sites [Amil](http://www.amil.com.br/portal/web/institucional), [One Health](http://www.onehealth.com.br/portal/web/institucional), [Next Saúde](http://www.nextsaude.com.br/portal/web/institucional) e outros que ainda não estão em produção. Não tenho certeza de se posso ser uma mentora, mas se eu puder, nem que seja um pouco, agregar conteúdo e mudar vida de alguém para mim ja é suficiente. 

*Alguns links sobre mim:*
* Facebook: https://www.facebook.com/akfzambrana
* Twitter: https://twitter.com/akfzambrana
* LinkedIn: https://br.linkedin.com/in/akfzambrana
* Blog: http://andreazambrana.com.br/

**Comment by woliveiras** [comment]
Já pode add seu perfil direto @akfzambrana, só abrir um PR mesmo com o perfil que é nozes! :smile:
