### ISSUE TITLE
Preciso de um(a) mentor(a) de Front End

### ISSUE THREAD

**Issue by lorkithen** [training-center/mentoria#127]
Nome: Luccas Candido

Olá gente, tudo bem? Eu me apaixonei por desenvolvimento la pelos 14 anos e ficava brincando de criar site por conta própria. Eis que cresci e me dispersei totalmente da área. Agora estou cá voltando e tentando realizar esse desejo. Estou estudando por começo HTML e CSS por conta própria, mas mês que vem já vou investir um pouco mais do meu tempo e $$. A questão é que sinto necessidade de conhecer alguém dentro da área pra me exemplificar o lado profissional. Vim aqui após a conversa com o William no Twitter. Agradecido desde já. 
Nível de conhecimento atual: **Básico**

**Contatos:** luccasdebarros@gmail.com / TT - luccasdebarros

**Comment by woliveiras** [comment]
Sucesso @lorkithen!

Vamos ver se alguém do @training-center/mentors consegue te ajudar. :metal:

**Comment by akfzambrana** [comment]
Um dos meus pupilos não ta muito dedicado, então acho q da pra pegar mais alguem se vc tiver interesse @lorkithen

**Comment by lorkithen** [comment]
Com certeza @akfzambrana . Você me manda um e-mail pra gente organizar? =)

**Comment by woliveiras** [comment]
\o/

Só atualizarem os perfis e sucesso galera!

**Comment by akfzambrana** [comment]
eu vou atualizar pq ele n manja de git ainda

**Comment by woliveiras** [comment]
Opa, sucesso!

**Comment by akfzambrana** [comment]
ja pode fechar @woliveiras ja fez o merge do pr

**Comment by woliveiras** [comment]
Perfeito @akfzambrana 

Valeu!
