### ISSUE TITLE
Preciso de um Tutor para Lógica de Programação

### ISSUE THREAD

**Issue by Baco23** [training-center/mentoria#128]
Olá! Caros amigos,

Sou Antonio Marcos, formado em Direito, mas iniciando uma nova faculdade de Análise e Desenvolvimento de Sistemas. Já fiz alguns cursos online, mas não é a coisa mais fácil, tenho muita dificuldade de compreender os enunciados de programação e aplicá-los..

Por isso peço ajuda para que me seja indicado um Tutor.

Att,
Antonio Marcos
@23antoniomarcos
https://github.com/Baco23

**Comment by woliveiras** [comment]
Bem vindo @Baco23!

Alguém buscar Mentoria para assuntos de base, como lógica, é perfeito! Pois começa todo o caminho já com ajuda e aprende tudo da melhor maneira.

Excelente iniciativa!

Vamos ver se alguém dos @training-center/moderators consegue te ajudar.

**Comment by Baco23** [comment]
@William,

Primeiro, parabéns por essa iniciativa...espetacular o training-center!

Depois, agradeço pela atenção!

Abcss

Em 15 de set de 2016 07:23, "William Oliveira" <notifications@github.com>
escreveu:

**Comment by woliveiras** [comment]
Fico feliz por estarmos ajudando, @Baco23 

🙌

**Comment by akfzambrana** [comment]
Eu estou estudando logica por minha conta com um livrinho mágico q o mestre @woliveiras me emprestou, n consigo ser mentora, mas acho q podemos fazer um pair de estudos e ir nos ajudando. Caso não apareça nenhum mentor de verdade 😛

**Comment by Belline** [comment]
Ensinar lógica de programação é meu assunto preferido, adoraria te ajudar @Baco23 , e você também @akfzambrana se precisar de alguma coisa pode entrar em contato 😄 

@Baco23 você tem algum outro contato além de twitter? Pode ser skype, FB, google hangouts, qualquer coisa. Twitter eu não uso muito.

Abraços!

**Comment by Baco23** [comment]
Andréa, agradeço muito l!!!

Vamos sim... só me falar como contatar você.

Abraços e muito obrigado.

A.m.

Em 20 de set de 2016 14:51, "Andréa Zambrana" <notifications@github.com>
escreveu:

**Comment by Baco23** [comment]
@Belline tenho fb, skype(antoniomarcos_adv), hangout (antoniomarcosadv@gmail.com)
desculpe-me não responder antes, não vi sua msg. Vou te add no fb, hangout e skype

Abcss
antonio

**Comment by Belline** [comment]
Já estou em contato com o @Baco23 . Irei atualizar meu perfil de mentor e adicionar ele como pupilo 👍

**Comment by Baco23** [comment]
Obrigado @Lucas!

Em 26 de set de 2016 14:19, "Lucas Pinto" <notifications@github.com>
escreveu:

**Comment by Baco23** [comment]
Prezados, como eu add meu perfil por ser pupilo do @Lucas ?

Att

Em 26 de set de 2016 15:13, "Antonio Marcos" <antoniomarcosadv@gmail.com>
escreveu:

**Comment by lucas** [comment]
@Baco23 please stop tagging me in this

**Comment by woliveiras** [comment]
Sorry @Baco23.

The @Baco23 don't have very experience in GitHub.

We are training him.

**Comment by lucas** [comment]
thanks @woliveiras :)

**Comment by woliveiras** [comment]
Galera, estou fechando a issue por possuir mais de 10 dias.

Qualquer coisa podemos reabrir.
