### ISSUE TITLE
Preciso de um(a) mentor(a) de Desenvolvimento Web - Front-End/FullStack

### ISSUE THREAD

**Issue by VitorFerraz** [training-center/mentoria#129]
## Meu Nome

Vitor Ferraz Varela

## Qual meu sonho na carreira?

Quero me aperfeiçoar tecnicamente e seguir carreira como desenvolvedor web.
Estou em uma fase de transição da área de gerenciamento de projetos para a de desenvolvimento, e gostaria de orientação para poder me tornar um profissional completo baseado na experiencia de programadores mais experientes.

#Conhecimentos

Tenho conhecimento de algumas linguagens como Java, JavaEE e C# na parte de back-end e html5,css3,javascript (ES6) , jQuery, Bootstrap e React na parte do front. Já fiz alguns cursos de programação além de estudar muito por fora. 

Atualmente estou me focando em estudar temas de front-end como React e ES6.
Participo de um projeto do SENAI em parceria com a Endeavour para desenvolvimento de um case para uma Startup , estou atuando na parte de front-end.

Tenho muito interesse pela área de front-end mas acredito também no perfil de desenvolvedor full-stack.

Estou aberto para qualquer esclarecimento e duvidas.

## Alguns links para me conhecer melhor

[Meu Facebook](https://facebook.com/varelavf)<br/>
[Perfil do Codepen](http://codepen.io/Vitor_Ferraz/)<br/>
[Meu LinkedIn](https://br.linkedin.com/in/vitor-ferraz-ba143466)<br/>
[Meu GitHub](https://github.com/VitorFerraz)<br/>

**Comment by woliveiras** [comment]
Bem vindo @VitorFerraz 

Vamos ver se os @training-center/mentors conseguem te ajudar.

**Comment by wesleycoder** [comment]
Fala vitor, gostei do teu perfil, podemos bater um papo para ver se eu posso preencher suas expectativas  se você quiser.

**Comment by VitorFerraz** [comment]
Ae @wesleycoder tudo bom? podemos sim! skype? ou por aqui mesmo?

**Comment by woliveiras** [comment]
Sucesso!!

**Comment by woliveiras** [comment]
Fala galera!

Vou fechar a issue por já ter mais que 10 dias em "Work in progress"

Qualquer coisa podemos reabrir

**Comment by wesleycoder** [comment]
Ah, sim.
Está tudo feito em #136, #142 & #143.

**Comment by woliveiras** [comment]
\o/

Sucesssoooo!
