### ISSUE TITLE
Preciso de um(a) mentor(a) de Front-End.

### ISSUE THREAD

**Issue by williangd** [training-center/mentoria#131]
**Nome:** Willian Oliveira	

**Descrição:** Trabalho atualmente com suporte e testes, mas gostaria de trabalhar com front-end. Estou iniciando alguns cursos na Alura, tenho um pouco de conhecimento de HTML, CSS e quase nada de JS.

**Nível de conhecimento atual:** Nível básico

**Contatos:** 
*E-mail:* williangd@yahoo.com.br
*Facebook:* https://www.facebook.com/williangd

**Comment by woliveiras** [comment]
Bem vindo @williangd!

Vamos ver se alguém dos @training-center/mentors consegue te ajudar.

**Comment by Belline** [comment]
Fala @williangd, Beleza?

Te adicionei no Facebook, consigo te colocar como pupilo de boas 😄 

Abraços!

**Comment by williangd** [comment]
@Belline, tudo certo e com você?

Já te aceitei no Facebook. :D 

@woliveiras belo nome! haha

**Comment by woliveiras** [comment]
Perfeito @Belline!

Assim que subir o perfil do @williangd já fecho a issue. :smile:

**Comment by woliveiras** [comment]
Fala galera!

Vou fechar a issue por já ter mais que 10 dias em "Work in progress"

Qualquer coisa podemos reabrir
