### ISSUE TITLE
Quero ser mentor de Front-End (com um pé no UX)

### ISSUE THREAD

**Issue by ubirajarapelli** [training-center/mentoria#133]
## Ubirajara Pelli
Sou Desenvolvedor Front End há alguns anos, Organizador do [FEMUG-ABC](https://github.com/femug-abc), colaborador da comunidade [ABC-Dev](https://github.com/abc-dev), Professor do Ensino técnico e Universitário, que não curte a mesmice na hora de ensinar. 

## Perfil

Mentor para desenvolvedores Front End, e um pé lá no UX/ Design.

## Links

* [Site pessoal](http://ubirajarapelli.com.br) - Em descontrução
* [Facebook](https://www.facebook.com/ubirajara.pelli)
* [Twitter](https://twitter.com/ubirajarapelli)
* [LinkedIn](https://br.linkedin.com/in/ubirajara-pelli-60127956)

## Gostaria de retribuir a ajuda do Ubirajara?

Mande um salve para ubirajaracpelli@gmail.com ou nas redes sociais.

## Pupilos

**Comment by woliveiras** [comment]
@ubirajarapelli, pode criar seu perfil seguindo o esquema do [template](https://github.com/training-center/mentoria/blob/master/mentores/mentor_template.md)

Da uma lida no [código de responsabilidade do mentor](https://github.com/training-center/mentoria/blob/master/mentores/responsibility.md)

E tacale pau! 😄

**Comment by woliveiras** [comment]
Já pode mandar o PR fechando essa issue mesmo.

**Comment by woliveiras** [comment]
Bira, estou fechando a issue por ter mais que 10 dias em "work in progress"

Assim que possível sobe seu perfil no projeto. 😄
