### ISSUE TITLE
Preciso de um mentor de Back End

### ISSUE THREAD

**Issue by fernandoamvj** [training-center/mentoria#134]
## Nome: 
Fernando Martins

## Descrição: 

Moro em Belo Horizonte,curso Engenharia da Computação, e trabalho na área de Gestão e Governança de TI como estagiário. Só que tenho muito mais interesse na área de desenvolvimento. E no semestre passado cursei uma disciplina relacionada a Web e gostei bastante. Apesar de ter gostado da parte de front-end, eu achei mais interessante o back end

## Sonho de carreira: 

Meus sonhos atualmente é de me formar na faculdade e conseguir algum estágio/emprego na área de desenvolvimento.

## Nível de conhecimento atual:

Meu conhecimento em programação em geral é básico. Os projetos que fiz foram para trabalhos da faculdade. No back end eu aprendi um pouco de Node e estou estudando PHP pelo Alura.

## Contatos:

Facebook:  https://facebook.com/fernando.martins.3551
Email: fernandoamvj@gmail.com

Agradeço desde já .

**Comment by woliveiras** [comment]
Bem vindo @fernandoamvj!

Vamos ver se alguém dos @training-center/mentors consegue te ajudar! 😄

**Comment by dorianneto** [comment]
E ae @fernandoamvj !

Da uma olhada no meu [perfil](https://github.com/training-center/mentoria/blob/master/mentores/perfis/dorian_neto.md) e vê se te agrada ;)

Abraço!

**Comment by fernandoamvj** [comment]
Opa e ai @dorianneto 
Animo sim cara!
Valeu

**Comment by dorianneto** [comment]
Show!

@fernandoamvj prefere conversar por onde?

**Comment by woliveiras** [comment]
Assim que possível atualizem seus perfis aqui no repo e sucesso!

:smile:

**Comment by fernandoamvj** [comment]
@dorianneto pode ser pelo 
Facebook: https://facebook.com/fernando.martins.3551
Ou 
Skype:
 fernandoamvj@hotmail.com
Você que manda chefe!

**Comment by dorianneto** [comment]
@woliveiras nós já estamos conversando :D

Só aceitar o PR #149 e fechar a issue.

**Comment by woliveiras** [comment]
Perfeito @dorianneto
