### ISSUE TITLE
Preciso de um mentor de Front-end

### ISSUE THREAD

**Issue by laryro** [training-center/mentoria#135]
**Nome:** Laryssa Rocha

**Descrição:** Front-end dev de 22 anos, perdida no mundo.

**Nível de conhecimento atual:** Me considero pleno, mas ainda preciso aprender muita coisa pois sinto que estou estagnada, não manjo de nada desses frameworks e tenho a impressão de que a cada 5 minutos sai coisa nova e eu n tenho dado conta de acompanhar :(

**Contatos:** [GitHub](https://github.com/laryro) [Facebook](https://facebook.com/laryro) [LinkedIn](https://linkedin.com/in/laryro) 

Obrigada! :)

**Comment by woliveiras** [comment]
Bem vinda @laryro!

Vamos ver se alguém do @training-center/mentors consegue te ajudar.

Realmente, a cada 5 min alguém cria alguma tecnologia web nova que vai se tornar hype!

kkkk 😂  😂  😂

**Comment by akfzambrana** [comment]
Opa! a @laryro já foi minha trainee uns anos atras, posso pegar ela de pupila? (ela ja ta acostumada com minha personalidade amorosa 😈)

**Comment by woliveiras** [comment]
Poode! kkkk

**Comment by woliveiras** [comment]
Fala galera! Vou fechar a issue por já ter mais que 10 dias.

Qualquer coisa é só avisar que reabrimos. :smile:
