### ISSUE TITLE
Preciso de um mentor de Front-end e WordPress

### ISSUE THREAD

**Issue by ThalesIsaias** [training-center/mentoria#137]
Nome: Thales Isaias 
Descrição: Sou novo aqui e estou em busca de aprender, sou estudante e não tenho conhecimento de como começar a ser programador front end. 
Nível de conhecimento atual: Basico estou querendo começar a ser programador front end. 
Contatos: 
Email: thalesisaias13@gmail.com
Facebook: www.facebook.com/thales.isaias

**Comment by woliveiras** [comment]
Bem vindo @ThalesIsaias!

Vamos ver se alguém dos @training-center/mentors consegue te ajudar. 😄

**Comment by ThalesIsaias** [comment]
obg Woliveiras estou querendo muito aprender esta área de front-end.

**Comment by woliveiras** [comment]
Boa sorte cara!

E bons estudos. 😁

**Comment by woliveiras** [comment]
Algum dos novos @training-center/mentors consegue ajudar esse moço?

**Comment by woliveiras** [comment]
Estamos com todos os Mentores e Mentoras ocupados no momento, adicionei a label `wait for new mentors` para que os próximos busquem por essas issues primeiro.

**Comment by cleisoncarlos** [comment]
Fala @woliveiras , to disponível pra ajudar o @ThalesIsaias  (y) conforme o possível

**Comment by luizbills** [comment]
@ThalesIsaias se ainda estiver interessado posso te ajudar.

**Comment by ftonato** [comment]
Fala @ThalesIsaias, como está o andamento dessa _issue_?
- [ ] Encontrou o mentor?
- [ ] O mentor entrou em contato com você?

/cc @luizbills

**Comment by woliveiras** [comment]
@ThalesIsaias nosso processo mudou: https://medium.com/trainingcenter/e-o-mentoria-mudou-mais-uma-vez-5ad8725bc778

Peço, por favor, que responda esse formulário, se ainda fizer sentido, para que algum mentor ou mentora entre em contato contigo quando possível: http://bit.ly/preciso-de-mentoria

A issue será fechada para que não aconteçam desencontros de informação.
