### ISSUE TITLE
Preciso de um(a) mentor(a) de carreira Full-Stack

### ISSUE THREAD

**Issue by rgcavalcanti** [training-center/mentoria#138]
**Nome:** Rafael Gomes Cavalcanti
**Descrição:** Tenho um conhecimento básico sobre desenvolvimento web pois trabalho a mais ou menos 1 ano com webforms, porém sou entusiasta por novas tecnologias e atualmente o JS tem ganhado cada vez mais meu interesse. Quero mudar de carreira, mas principalmente quero criar meus próprios projetos e contribuir com a comunidade (quero muito mesmo hahaha).
**Nível de conhecimento atual:** HTML5, CSS3, ES6, JQuery, Bootstrap. ASP.NET WebForms, bancos relacionais, alguma coisa de bancos não relacionais.
**Contatos:**
email: rcavalcanti.ti@gmail.com  
facebook: https://www.facebook.com/rafael.g.cavalcanti

**Comment by woliveiras** [comment]
Bem vindo @rgcavalcanti!

Vamos ver se alguém dos @training-center/mentors consegue te ajudar. 😄

**Comment by Belline** [comment]
Fala @rgcavalcanti , beleza?

Adoraria lhe dar uma direção, entretanto não consegui lhe adicionar nem mandar mensagem no facebook, entra em contato comigo por algum meio de contato que você preferir (fb, linkedin, email, twitter), os links estão em http://lucaspinto.me e eu te dou uma força com o maior prazer.

Abração! 😄

**Comment by rgcavalcanti** [comment]
@Belline ficarei muiti grato em tê-lo como mentor!

**Comment by woliveiras** [comment]
Já vou atualizar as labels e, assim que subirem os perfis, podemos fechar a issue! ❤️

**Comment by rgcavalcanti** [comment]
@woliveiras já fiz o pull request do meu perfil!

**Comment by woliveiras** [comment]
Boa @rgcavalcanti

**Comment by woliveiras** [comment]
Fala galera! Vou fechar a issue por já ter mais que 10 dias.

Qualquer coisa é só avisar que reabrimos. :smile:
