### ISSUE TITLE
Preciso de um mentor em HTML e CSS

### ISSUE THREAD

**Issue by twobanks** [training-center/mentoria#14]
## Dados:   
**Nome:** Thiago Gonçalves
**Cidade:** Uberaba/MG

## Redes Sociais:
[Facebook](https://www.facebook.com/twobanks) | [Twitter](https://twitter.com/thbanks)

**Comment by woliveiras** [comment]
@training-center/moderators, se todos estiverem de acordo, vou ajudar o @twobanks

**Comment by twobanks** [comment]
**Eu**  estou de acordo, hahahaha

**Comment by danilovaz** [comment]
super de acord :smile:

**Comment by baltazarparra** [comment]
Da-lhe mano @woliveiras !

**Comment by woliveiras** [comment]
Show de bola
