### ISSUE TITLE
Preciso de um mentor Front End

### ISSUE THREAD

**Issue by TatyBarros** [training-center/mentoria#140]
Boa tarde! 
Me chamo Tatiana Barros, sou uma pessoa reticente e labiríntica, que bebe café quente em dias de sol, ambiciona escrever boas histórias e insiste em empreender.

Acredito na educação como arma poderosa de mudança e por isso criei a [Saga Pólen](www.sagapolen.com.br) que é uma startup de educação ambiental infantil com o propósito de tornar o aprendizado das crianças do fundamental 1, mais divertido e prazeroso.
É uma saga de flores e insetos que brigam pelo mesmo espaço dentro de um jardim mágico (quase que um GOT infantil), e desafiará as crianças a desenvolverem habilidades sócio emocionais, multidisciplinar e consciência ambiental. A nossa primeira jornada "As aventuras da Meg Margadinória no Reino das Formigas" é uma aventura dentro do mundo da matemática, programação e robótica com sucata. Ganhei prêmio do Google, Prefeitura de São Paulo e RME.

Sou designer gráfico de formação, passei por agência de publicidade como diretora de arte e direção de criação e até já fui mkt de uma fábrica de brinquedos. Tenho contato com wordpress (uma paixão), HTML5 e css. Como carreira ou o voo solo, ambiciono ser uma boa programadora Full stack  no máximo daqui até meio do ano que vem, independente da minha startup decolar.

Sonho em criar uma plataforma que ensine jovens escritores a compreenderem melhor a jornada do herói. AMO LITERATURA MAIS DO QUE CAFÉ.

Ainda esconderei a história da Alice no país das maravilhas (minha heroína) dentro de um código de um projeto qualquer.

Atualmente trabalho como coordenadora do Fablab livre SP da unidade Penha, e meu papel além de ministrar aulas de modelagem e impressão 3D, Eletrônica e Arduíno modo básico, é aproximar professores e alunos de escolas, principalmente públicas do universo maker.

Sou uma das organizadoras do Startup weekend de Educação ( ano passado e esse ano também) e do Startup Weekend de Mobilidade urbana desse ano aqui em SP.

Entrei em contato com o Fernando Moreira e pedi para ele ser meu mentor em Wordpress.
Como quero ser Full, deixo o convite para outros mentores e agradeço essa iniciativa linda <3

**Comment by woliveiras** [comment]
Bem vinda @TatyBarros!!

Vamos ver se alguém dos @training-center/mentors consegue te ajudar

**Comment by TatyBarros** [comment]
Obrigada @woliveiras

**Comment by nandomoreirame** [comment]
@woliveiras já estou encaminhando com a @TatyBarros a mentoria de Front-end e WordPress.

tea with me bro!

**Comment by woliveiras** [comment]
🙌 

Só atualizar seu perfil e a @TatyBarros criar o dela então e sucesso!

**Comment by woliveiras** [comment]
Fala galera! Vou fechar a issue por já ter mais que 10 dias.

Qualquer coisa é só avisar que reabrimos. :smile:

**Comment by nandomoreirame** [comment]
Pode manter fechada @woliveiras que já iniciamos a mentoria :+1:
