### ISSUE TITLE
Preciso de um(a) mentor(a) de Front End

### ISSUE THREAD

**Issue by anthonnygm** [training-center/mentoria#144]
**Nome:**
Anthonny Machado
**Descrição:**
Sou um desenvolvedor Back End, mas tenho um grande desejo de aprender melhor sobre a área de Front End, acho que sou como muitos desenvolvedores que ficam muito animados quando sai novas tecnologias para se aprender, os olhos começam a brilhar de alegria como se fosse uma criança com um brinquedo novo.
**Sonho de Carreira:**
Meu sonho de carreira é um dia trabalhar para uma empresa multinacional e se possível que trabalhe com home office.
**Nível de conhecimento atual:**
Tenho um bom conhecimento em PHP, HTML, CSS e Javascript.
Já fiz alguns cursos online e curso técnico de informática que me deu uma boa base sobre programação web.
**Contatos:**
Email:  [anthonny.gm@gmail.com](mailto:anthonny.gm@gmail.com)

**Comment by woliveiras** [comment]
Bem vindo @anthonnygm 

Vamos ver se alguém dos @training-center/mentors consegue te ajudar. 😄

**Comment by woliveiras** [comment]
Algum dos novos @training-center/mentors consegue ajudar esse jovem?

**Comment by anthonnygm** [comment]
Agradeço pela tentativa deixamos para um próximo momento.
