### ISSUE TITLE
Preciso de um(a) mentor(a) de Front End 

### ISSUE THREAD

**Issue by pedroGermano** [training-center/mentoria#147]
Nome:
Pedro Germano
Descrição:
Sou estudante do curso de analise e desenvolvimento de sistemas procuro me especializar na parte de front
Sonho de Carreira:
Espero um dia trabalhar para uma empresa com grandes projetos e se possível que trabalhe 
Nível de conhecimento atual:
Tenho um bom conhecimento em  HTML5, CSS3 e Javascript, 
Contatos:
Email: pedrogermano232@gmail.com
Facebook: https://www.facebook.com/pedrogermano232

**Comment by woliveiras** [comment]
Bem vindo @pedroGermano 

Vamos ver se algum dos @training-center/mentors consegue te ajudar.

**Comment by pedroGermano** [comment]
Obrigado @woliveiras

**Comment by abnersajr** [comment]
@pedroGermano Olá brother. Estou entrando em contato com você para ajustarmos e saber se você topa ser meu pupilo.

**Comment by pedroGermano** [comment]
opa topo sim

**Comment by abnersajr** [comment]
Fecho é nois, contato inicial no facebruik

**Comment by woliveiras** [comment]
Assim que estiver tudo acertado entre vocês, podem me avisar pra eu fechar a issue, por favor. :smile:

**Comment by pedroGermano** [comment]
já ta tudo certo @woliveiras

**Comment by woliveiras** [comment]
Booooooa @pedroGermano 

Sobe seu perfil pro projeto, então pra eu te add na org e, se possível, já entra no nosso Slack!

Tem mais informações aqui: https://github.com/training-center/mentoria#preciso-de-uma-mentora

**Comment by woliveiras** [comment]
Galera, estou fechando a issue por possuir mais de 10 dias.

Qualquer coisa podemos reabrir.
