### ISSUE TITLE
Preciso de um mentor para Fullstack (Front-end/Back-end/UX/Design) ou algum desses!

### ISSUE THREAD

**Issue by hhalmeida** [training-center/mentoria#148]
## Mentoria para FullStack [Front-end, Back-end]
_Qualquer_ linguagem to aceitando rsrs...

### Nome:
Hugo Almeida

### Descrição:
Bom, tenho um básico conhecimento em desenvolvimento web, voltado mais para front-end (especificamente AngularJS e Bootstrap) e UX.
Gostaria de ajuda para que eu possa ter um norte de como desenvolver outras habilidades, para ser um fullstack, Sou entusiasta a novas tecnologias e diversas linguagens, Quero alavancar meu profissional,  criar meus próprios projetos e contribuir com a comunidade (quero muito mesmo hu3hu3hu3), e ajudar outras pessoas que queiram melhorar sempre.

### Nível de conhecimento atual:
Tenho conhecimento de algumas linguagens como Java, Python, C++ [nível básico] no back-end e html5,css3,javascript (ES5) , jQuery, Bootstrap e Angular no front-end
Atualmente estou me focando em estudar Angular, Ionic, ES6 e testes(Sou muiito ruim para entender testes).
Faço parte de alguns projetos onde estou atuando na parte de front-end.

Tenho muito interesse em me tornar um desenvolvedor full-stack.

### Contatos: 
[GitHub - Hugo Almeida](http://github.com/hhalmeida)
[Email - hugohbalmeida@gmail.com](hugohbalmeida@gmail.com)

_Desde já, muiito obrigado pela disponibilidade!_

_Qualquer dúvida estou a disposição._

**Comment by woliveiras** [comment]
Ai é o verdadeiro Full Stack ein @hhalmeida 

Vamos ver se algum dos @training-center/mentors consegue te ajudar. 😄

**Comment by hhalmeida** [comment]
Tem que ser assim né! @woliveiras , rsrs...

Muiito obrigado, estou ansioso no aguardo.!, Valeu!

**Comment by danilovaz** [comment]
Boa @hhalmeida  go go go go! Evoluir, sempre. Tá no caminho certo :heart:

**Comment by danilovaz** [comment]
@woliveiras tava falando com o @hhalmeida e ele tá precisando de mentoria em Front e/ou Back. Eu me propus a ser mentor de Front pra ele, caso não haja nenhum FullStack pra mentorar. Aí eu ficaria à cargo da parte de Front e como o Hugo é meu conterrâneo e sempre aparece nos meetups aqui, fica fácil essa troca de conhecimento.

**Comment by woliveiras** [comment]
Opa! Que sucesso ein @danilovaz 

Já cria seu perfil pra ficar registrado. 😄

**Comment by woliveiras** [comment]
@hhalmeida estará em boas mãos!!!

**Comment by hhalmeida** [comment]
Obrigado @woliveiras, rsrs...
Agora em busca de um mentor de Back-end.! kkkkkk :+1:

**Comment by dorianneto** [comment]
Faaaaala negada, tudo tranquilo?

@hhalmeida da uma olhadinha no [meu perfil](https://github.com/training-center/mentoria/blob/master/mentores/perfis/dorian_neto.md) e vê se te agrada. Estou a disposição ;)

**Comment by woliveiras** [comment]
@hhalmeida, o @dorianneto tem bons conhecimentos para acrescentar junto ao @danilovaz ein. :smile:

**Comment by danilovaz** [comment]
require @hhalmeida

**Comment by hhalmeida** [comment]
Fala galera, desculpe a demora, fiquei um pouco OFF! rsrs...
Então eu gostei bastante do @dorianneto... ! 
@dorianneto , meus conhecimentos estão voltados a essas tecnologias :: Java,Node, álem do php vc conhece algumas outras..?
Muito muiiito obrigado pela atenção, qualquer dúvida estou a disposição.

**Comment by dorianneto** [comment]
@hhalmeida já trabalhei com um pouco e tudo, porém, há alguns anos utilizo bastante PHP

**Comment by woliveiras** [comment]
🙌 

Sucesso monstros!!! 

Assim que possível atualizem os perfis de vocês.

**Comment by hhalmeida** [comment]
Sim sim... espero que sim! kkkkkkk
Legal @dorianneto, estou muito animado pelo que está por vir...! rsrs..!
Bora lá ver o que acontece rsrs, o que você precisa para começarmos @dorianneto ??

Valeu galera... kkk tamo junto

**Comment by dorianneto** [comment]
@hhalmeida atualiza teu perfil e fala comigo lá no slack :D

**Comment by hhalmeida** [comment]
@woliveiras , bom dia, você poderia aceitar a PR do @danilovaz ? com o meu perfil, para que eu possa atualiza-lo..? Valeu, qualquer dúvida estou a disposição.

**Comment by woliveiras** [comment]
Fala @hhalmeida,

O PR do @danilovaz já foi.

[Aqui, o perfil](https://github.com/training-center/mentoria/blob/master/pupilos/perfis/hugo_almeida.md)

Agora é só atualizar. 😄

**Comment by woliveiras** [comment]
Galera, fechando a issue por já estar tudo OK.

Qualquer coisa podemos reabrir.

:metal:
