### ISSUE TITLE
Chamada aos pupilos para nosso Slack

### ISSUE THREAD

**Issue by woliveiras** [training-center/mentoria#150]
@training-center/pupils, estamos tentando melhorar nossa comunicação e para isso precisamos que vocês entrem no nosso Slack.

Basta adicionar seu email nesse site: https://ctgroups.herokuapp.com/

Lá existem alguns canais que podem servir como forum para ajuda e o seu mentor poderá ser encontrado facilmente, também.

Qualquer dúvida podemos discutir nessa issue.

**Comment by dorianneto** [comment]
@fernandoamvj @iagoqueiroz @AlexBarazal

**Comment by woliveiras** [comment]
Boa @dorianneto

**Comment by akfzambrana** [comment]
@laryro @joselialcosta @andreneto97 @lorkithen @ytalobessa

**Comment by woliveiras** [comment]
\o/

Valeu @akfzambrana
