### ISSUE TITLE
Chamada aos Mentores para o Slack

### ISSUE THREAD

**Issue by woliveiras** [training-center/mentoria#151]
@training-center/mentors, estamos tentando melhorar nossa comunicação e para isso precisamos que vocês entrem no nosso Slack.

Basta adicionar seu email nesse site: https://ctgroups.herokuapp.com/

Tentei contato por email com todos, porém nem todo mundo respondeu. Provavelmente cai no meio dos Spams! kkkk

Qualquer dúvida podemos discutir nessa issue.

**Comment by danilovaz** [comment]
Cara, eu acho o Slack pouco "produtivo" se comparado ao Gitter, ou eu não tô sabendo usar mesmo rs. Tipo, se eu tiver 5 grupos com canais do Slack, vou precisar ficar com 5 abas abertas, por ter 5 canais diferentes, correto?

O Gitter é muito melhor nisso. Só associo meu usuário Github, uso 1 aba só e todos os meus canais estão disponíveis ali.

Agora, se tem como fazer isso no Slack. Help me kkkkk tá foda

**Comment by wesleycoder** [comment]
No menu lateral, no nome do grupo você vai encontrar o menu da aplicação e
mais para baixo você encontrará o item "Sign in to another team" onde você
pode entrar em outro time.
À partir do momento em que você possui mais de um time você verá novas
opções como "Switch to NomeDoTime".
E então você poderá receber notificações de todos os times ao habilitar as
notificações no desktop mesmo não estando com a aba do time aberta mas
tendo ao menos  uma sessão do slack aberta.

> --
*Wésley Queiroz* (@wesleycoder)
Web Developer
(11) 96050-2935

**Comment by woliveiras** [comment]
Outra opção é usar o App do Slack, @danilovaz. Ai fica melhor ainda com os times do lado! 😬 

Ai só fica o  fato de precisar de uma conta pra cada time.

O ruim é que a galera não usa o Gitter por ser mais um app pra abrir, sendo que no Slack eles colocam tudo, tanto no App pra Desktop quanto de celular, ai o Gitter fica as traças. 😢 

Nosso Gitter está meio abandonado lá por isso.

**Comment by raymonsanches** [comment]
Slack :+1:

**Comment by danilovaz** [comment]
vou seguir a dica do @wesleycoder :smile:

**Comment by woliveiras** [comment]
Slack é vida galera!

kkk
