### ISSUE TITLE
Quero ser mentor back-end (foco em PHP)

### ISSUE THREAD

**Issue by raymonsanches** [training-center/mentoria#154]
Me chamo Ramon Sanches e sou desenvolvedor backend, mais especificamente PHP há quase 10 anos. Sou apaixonado por arquitetura, microserviços, métodos ágeis e inovação. Também sou host do DevNaEstrada, podcast focado em desenvolvimento.

Quero ser mentor pra ajudar principalmente quem está iniciando na carreira com PHP de todas as formas que conseguir, seja tecnicamente ou trocando idéia sobre carreira, oportunidades e motivação. Quero levar um pouco do espírito do nosso podcast pra essa mentoria, onde não falamos somente de assuntos técnicos.

+ Infos:

[@raymonsanches](https://twitter.com/raymonsanches)
[GitHub](https://github.com/raymonsanches)
[LinkedIn](https://br.linkedin.com/in/ramonfilipesanches)
[DevNaEstrada](http://devnaestrada.com.br/)

**Comment by woliveiras** [comment]
Fala @raymonsanches 

Cara, pode tacar pau em subir seu perfil e ver se já tem pupilo pra você ajudar!

Já entra no nosso Slack e me avisa `@woliveiras` pra eu te adicionar no canal onde discutimos assuntos relacionados a administração do projeto.

https://ctgroups.herokuapp.com/

**Comment by raymonsanches** [comment]
Aeeeeee, valeu! Logo menos mando o PR do perfil \o/

**Comment by woliveiras** [comment]
Sucesso! 😄
