### ISSUE TITLE
Quero ser mentor Front-End com foco em CSS e semântica

### ISSUE THREAD

**Issue by LFeh** [training-center/mentoria#155]
# Mentor

## Felipe Fialho

Sou Desenvolvedor Front End desde 2009, quando comecei a profissão não tinha nem nome e me chamavam de "menino do HTML". Sou um dos criadores e organizadores do [Meetup CSS](http://www.meetup.com/pt-BR/CSS-SP/) e participei da organização da primeira [Conferência CSS Brasil](http://www.conferenciacssbrasil.com.br/). Também sou um dos criadores e mantenedores da comunidade [Front-End Brasil - Github](https://github.com/frontendbr)

Tenho um monte de projetos e iniciativas na comunidade frontender brasileira. Entre elas, as que mais se destacam são:

- [Felipe Fialho - Blog](http://www.felipefialho.com/blog/)
- [CSS Components](http://www.felipefialho.com/css-components/)
- [Kratos Boilerplate](https://github.com/LFeh/kratos-boilerplate)
- [Coding Style](https://github.com/LFeh/coding-style)
- [Piano Keyboard](http://www.felipefialho.com/piano/)

Quem me conhece sabe que apesar de estar estudando JavaScript a todo vapor, sou apaixonado por CSS, modularização e semântica. Acredito que pode ser um bom ponto de partida para a mentoria.

## Perfil

Mentor para desenvolvedores Front-End, interessados em CSS.

## Links

* [Site pessoal](http://www.felipefialho.com/)
* [Facebook](https://www.facebook.com/LFehh)
* [Twitter](http://twitter.com/LFeh)
* [LinkedIn](https://www.linkedin.com/in/lfehfrontend)
* [Codepen](https://codepen.io/lfeh)
- [Medium](https://medium.com/@lfeh)

**Comment by LFeh** [comment]
Está ai @woliveiras :)

**Comment by drunksheep** [comment]
Esse é o tópico pra quem quer ser pupilo também ?

**Comment by nandomoreirame** [comment]
Olha o mestre ai manooo! 
No meu ponto de vista o @LFeh deveira cair direto em @training-center/mentors já hein @woliveiras, sem nem ter que abrir Issues :smile:

**Comment by Renatomsilva** [comment]
Eu gostaria de ter um mentor. Meu css é péssimo

**Comment by wesleycoder** [comment]
@drunksheep Se quiser ser pupilo você pode abrir uma [nova issue](https://github.com/training-center/mentoria/issues/new) seguindo o template no fim [desse arquivo](https://github.com/training-center/mentoria/blob/master/issue_template.md).

**Comment by woliveiras** [comment]
Claro que não @nandomoreirame...

Deve seguir o fluxo normalmente. Agora vamos fazer o comite pra ver se o @LFeh deve ser aprovado OU não.

**Comment by woliveiras** [comment]
Mentira!

Nós conhecemos o trampo do @LFeh!

Já pode tacar pau em subir seu perfil e ver se já tem pupilo pra você ajudar!

Também entra no nosso Slack e me avisa `@woliveiras` pra eu te adicionar no canal onde discutimos assuntos relacionados a administração do projeto.

https://ctgroups.herokuapp.com/

**Comment by woliveiras** [comment]
Podem abrir uma issue que, com certeza, aparece alguém pra ajudar vocês @Renatomsilva e @drunksheep

**Comment by LFeh** [comment]
hahaha, que exagero @nandomoreirame.

Valeu @woliveiras .

Vou subir.
