### ISSUE TITLE
Preciso de um(a) mentor(a) de Front-End!

### ISSUE THREAD

**Issue by YuriBrunetto** [training-center/mentoria#158]
## Informações pessoais
Yuri Brunetto
19 anos
Feliz (sim, esse é o nome da cidade) - Rio Grande do Sul

## Descrição
Olá! Trabalho na área de front-end e design de layouts há 4 anos, mas, apenas trabalhei em agências. Em ambos empregos, sempre usei HTML, CSS e JS (jQuery) puros, nada de NPM, pré-processadores ou algo do tipo. No começo desse ano, decidi mudar isso e começar a estudar isso por conta própria. Já desenvolvi vários projetinhos pessoais - que estão disponíveis no meu GitHub.

Eu gosto muito de aprender coisas novas e esse é um dos motivos pelo qual estou aqui pedindo por um(a) mentor(a) 😄 

Pretendo seguir carreira na área front-end, trabalhando em alguma start-up ou com produto (pra mim, chega de agência!!) e se alguém se interessar em me ajudar, serei eternamente grato. Em janeiro do ano que vem pretendo sair do meu emprego atual e tentar trabalhar remotamente, então até lá, eu quero estudar várias coisas legais e interessantes.

## Nível de conhecimento atual
Acredito que eu já me encaixe como desenvolvedor front-end *pleno*. Mas, pode ser que não também... Falar de si mesmo é sempre muito difícil auhahuaau

## Contatos
[Personal website](https://ybrntt.com.br)
[Twitter](https://twitter.com/yuribrunetto)
[GitHub](https://github.com/YuriBrunetto)
[Facebook](https://www.facebook.com/brunettoyuri)
[E-mail](mailto:brunettoyuri@gmail.com)
[LinkedIn](https://br.linkedin.com/in/yuri-brunetto-3b8625a6)
[Behance](https://behance.net/yuribrunetto)

**Comment by woliveiras** [comment]
Bem vindo @YuriBrunetto 

Vamos ver se alguém dos @training-center/mentors consegue te ajudar. :smile:

**Comment by YuriBrunetto** [comment]
Valeu @woliveiras 😄

**Comment by danilovaz** [comment]
Salve @YuriBrunetto beleza? Eu não sou nenhum sênior, menos ainda um especialista front-end. Mas acredito que eu possa te ajudar. Eu já trabalhei em agências digitais como dev. A pegada era full-stack mas eu sempre acabava indo mais pro front. Tanto que ainda continuo ligado à essa agência, só que hoje eu sou front-end em uma startup/produto deles. Por isso acho que posso te ajudar nessa transição de agência (N projetos, escopo maluco, N linguagens, N frameworks, N's N's N's e N's) para startup/produto. Se interessar vc, me procura em um dos contatos que estão [aqui](https://github.com/training-center/mentoria/blob/master/mentores/perfis/danilo_vaz.md) e podemos conversar melhor para ver se é o que vc precisa. Se não for, tem muita gente aqui ainda que pode te dar esse help. tamojunto :smile:

**Comment by YuriBrunetto** [comment]
@danilovaz pra mim já tá perfeito! logo entro em contato contigo o/

**Comment by woliveiras** [comment]
Show! 

Assim que estiver tudo OK me deem um toque pra fecharmos a issue. 😄

**Comment by YuriBrunetto** [comment]
@woliveiras já estamos conversando! acho que dá pra fechar a issue 👍

**Comment by woliveiras** [comment]
Perfeito cara! 

Não esqueçam de atualizar/criar o perfil de vocês aqui no repo. 🙌
