### ISSUE TITLE
Preciso de um(a) mentor(a) de Front-End

### ISSUE THREAD

**Issue by ingridrauany** [training-center/mentoria#159]
**Nome:** Ingrid Rauany 

**Descrição:** Tive meu contato com programação em 2012 no curso técnico, naquela época aprendi o básico de HTML e CSS fazendo coisinhas básicas, quando me formei no médio em 2013 optei por fazer Sistemas de Informação (faculdade na qual irei formar ano que vem se mais nenhuma greve/dp me impedir) porque simplesmente apaixonei pela área. Atualmente ainda estou na faculdade e decidi aprofundar meus conhecimentos na área para poder trabalhar com isso. Acaba que a vida de faculdade + estágio te deixa com pouco tempo de melhorar suas habilidades em coisas específicas. Na metade deste ano consegui estágio em uma empresa que trabalha com sites/ecommerce, é o que está me fazendo aprender mais coisas, mas sinto que ainda preciso crescer muito, para além de saber programar, programar da melhor forma possível.

**Nível de conhecimento atual:** Complicado definir, mas creio que consigo estruturar boas páginas com HTML e CSS, porém sinto que preciso melhorar bem mais meu CSS, sabe quando você em um projeto grande tem que usar um `!important` e fica sem saber porque? Então. Infelizmente JavaScript é meu ponto fraco, não sei porque tenho dificuldade em aprender.

**Contatos:**
[Github](https://github.com/ingridrauany)
[Personal Website](http://ingridrauany.github.io/)
[Facebook](https://www.facebook.com/ingrid.rauany)
[Twitter](https://twitter.com/ingridrauany)

**Comment by woliveiras** [comment]
Bem vinda @ingridrauany!

Vamos ver se alguém dos @training-center/mentors consegue te ajudar. :smile:

**Comment by nandomoreirame** [comment]
Pode deixar comigo @woliveiras , claro que a @ingridrauany quiser, estou disponível 😄

**Comment by woliveiras** [comment]
Shoow!

**Comment by ingridrauany** [comment]
Olá @nandomoreirame, claro que aceito ajuda (que aliás é sempre bem vinda) :wink:

**Comment by woliveiras** [comment]
🙌 

Assim que estiver tudo OK, atualizem/criem seus perfis, viu?

Muito sucesso!

**Comment by nandomoreirame** [comment]
Que bom @ingridrauany :+1: 

Entra no Slack do CT Group pra gente começar a mentoria :) >> https://ctgroups.herokuapp.com/

Te encontro lá

**Comment by woliveiras** [comment]
Galera, estou fechando a issue por possuir mais de 10 dias.

Qualquer coisa podemos reabrir.

:metal: :metal: :metal:
