### ISSUE TITLE
Preciso de um mentor de front-end

### ISSUE THREAD

**Issue by Stoque** [training-center/mentoria#16]
## Dados
**Nome:** Lucas Stoque
**Cidade:** Rio de Janeiro - RJ
**Redes Sociais:** [twitter](http://www.twitter.com/ostoque)

**Comment by jlamim** [comment]
Lucas, qual a sua area? Fale um piuco sobre suas habilidades para que os
mentores possam conhecer melhor e saberem se possuem o conhecimento para te
mentorar.

Em quarta-feira, 20 de abril de 2016, Lucas Stoque <notifications@github.com>
escreveu:

> Dados
>
> *Nome:* Lucas Stoque
> *Cidade:* Rio de Janeiro - RJ
> *Redes Sociais:* twitter <http://www.twitter.com/ostoque>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/training-center/mentoria/issues/16>
>


-- 

*Jonathan Lamim Antunes*


*Desenvolvedor Web/Mobile & Palestrante*
*Tel: *+55 27 3082-4437 | 27 995 125 164

www.jlamim.com.br
www.github.com/jlamim
www.facebook.com/jlamim.projetos

**Comment by Stoque** [comment]
Então, na empresa onde trabalho meu cargo é Técnico de Suporte :(, mas minha principal função atualmente é desenvolver o front end do novo site deles.
Acredito que tenho conhecimento intermediário em HTML e CSS, atualmente estou usando Stylus + Gulp no desenvolvimento, porém meu conhecimento em JavaScript é bem básico.
Minhas maiores dúvidas na área é organização e  componentização do CSS, JavaScript e também sobre carreira e mercado.

**Comment by jlamim** [comment]
Legal! Posso ser seu mentor.

Todo mundo de acordo?

Em quinta-feira, 21 de abril de 2016, Lucas Stoque <notifications@github.com>
escreveu:

> Então, na empresa onde trabalho meu cargo é Técnico de Suporte :(, mas
> minha principal função atualmente é desenvolver o front end do novo site
> deles.
> Acredito que tenho conhecimento intermediário em HTML e CSS, atualmente
> estou usando Stylus + Gulp no desenvolvimento, porém meu conhecimento em
> JavaScript é bem básico.
> Minhas maiores dúvidas na área é organização e componentização do CSS,
> JavaScript e também sobre carreira e mercado.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/training-center/mentoria/issues/16#issuecomment-212725930>
>


-- 

*Jonathan Lamim Antunes*


*Desenvolvedor Web/Mobile & Palestrante*
*Tel: *+55 27 3082-4437 | 27 995 125 164

www.jlamim.com.br
www.github.com/jlamim
www.facebook.com/jlamim.projetos

**Comment by woliveiras** [comment]
De acordo! \o/

**Comment by jlamim** [comment]
Sendo assim, @Stoque sou oficialmente o seu mentor.

Me envie um email (contato@jlamim.com.br) com seus contatos: skype, facebook, email para que eu possa te adicionar e comaçarmos o programa de mentoria.

P.S.: @woliveiras pode fechar a Issue.

**Comment by woliveiras** [comment]
Show de bola!
