### ISSUE TITLE
Quero ser mentor de Front-end

### ISSUE THREAD

**Issue by abnersajr** [training-center/mentoria#160]
# Mentor

## Abner Soares Alves Junior

Trabalho desde 2011 como desenvolvedor front-end. Graduado em Tecnologia em Sistemas para Internet. Foco maior em CSS, UI/UX e semântica trabalho sempre em busca daquele FPS que está faltando na animação pra bater o tão sonhado 60FPS. Moro num interior no meio do campo e com vacas na minha janela. No entanto procuro estar sempre participando de eventos e atento as novidades.

Atualmente estou fazendo Nanodegree da Udacity para elevar mais ainda meus conhecimentos ,estudando bastante Javascript e dando uma maior atenção a minhas páginas perdidas por ai na web, github e afins. Javascript não é muito meu forte. Mas com certeza estarei disposto a procurar e aprender junto com o Pupilo para auxiliar ele.

## Perfil

Mentor para Front-end com foco em UI/UX, CSS e semântica.

## Links

Nunca parei para criar um blog e nem um site megapower. Mas abaixo alguns dos meus projetos em que fiz para algumas agências que trabalhei.

- [My Page](https://abnersajr.net)
- [Beagle Ship](http://beagleship.com.br)
- [Postos Premium](http://postospremium.com.br)
- [Uninga SM](http://www.uningasm.com.br/)
- [Sou + Camobi](http://www.soumaiscamobi.com/)
- [Business & Dental](http://www.businessdental.com.br/)
- [Leandro Reichert](http://www.leandroreichert.com.br/)
- [Arroz Sepé](http://www.arrozsepe.com.br/)

**Comment by woliveiras** [comment]
Fala @abnersajr!

Rapaz, você está pronto pra enfrentar as mais variadas dúvidas e ajudar alguém a conquistar seus sonhos profissionais?

**Comment by abnersajr** [comment]
Estou pronto Capitão. Sei como o início é mais difícil e que com uma ajudinha a qual eu não tive tudo fica mais fácil, claro e os sonhos são realizados mais facilmente. E deixo por fim essa citação

> Ei Ei Estamos ai, pro que der e vier - Cidade Negra

**Comment by woliveiras** [comment]
Boooooooa!

Taca pau criar teu perfil então cara!

Também entra no nosso Slack e me avisa `@woliveiras` pra eu te adicionar no canal onde discutimos assuntos relacionados a administração do projeto.

https://ctgroups.herokuapp.com/

Depois é só ver os pupilos que estiverem precisando (com label `need a mentor`) e tentar entrar em contato. :smile:

**Comment by abnersajr** [comment]
Vlw pela oportunidade cara, estou ajeitando as parada e logo vou pegar candidatar a pegar um pupilo 👯

**Comment by woliveiras** [comment]
\o/

É nozes mano!

Taca pau e vamos melhorar o mundo!
