### ISSUE TITLE
Preciso de um(a) mentor(a) de carreira e desenvolvimento front end

### ISSUE THREAD

**Issue by guilhermeocosta** [training-center/mentoria#164]
Olá pessoal, tudo bem? :)

Conversei um pouquinho com o @woliveiras no inbox do Facebook, então ele me orientou a vir aqui abrir a issue, cá estou!

Me chamo Guilherme, tenho 24 anos, trabalho como desenvolvedor front end há cerca de 4 anos, atualmente atuo numa empresa pequena e uma das minhas maiores dificuldades está sendo com relação a crescer na minha carreira.

Sou formado em design gráfico e hoje curso análise e desenvolvimento de sistemas no IFSP, procuro me atualizar de tecnologias (na medida de possível) e estou sempre estudando algo novo. De uns tempos pra cá, senti minha carreira um pouco estagnada, e me sinto sem tempo/direcionamento para investir na minha carreira.

Gostaria muito de uma ajuda principalmente nisso, porque tenho vários caminhos que quero tomar, mas não sei realmente o que seria melhor pra mim e como avaliar isso.

Além do meu trabalho, da faculdade e dos estudos, procuro empreender, estou atuando com um amigo e ex-colega de trabalho numa "agência" de desenvolvimento web, tenho muita vontade que nosso projeto dê certo, mas também gostaria de estar mais seguro em minha carreira com um futuro mais certo à vista.

Obrigado por me lerem até aqui, se algo não ficou claro ou eu precise passar mais informações sobre mim/meus conhecimentos, não deixem de perguntar por favor!

Abraços! =D

--
**Informações de Contato:**

**Nome:** Guilherme de Oliveira Costa
**Descrição:** Desenvolvedor Front End e UX Designer
**Nível de conhecimento atual:** Pleno
**Contatos:** [Facebook](https://www.facebook.com/guilhermedeocosta), [guilhermedeocosta@gmail.com](mailto:guilhermedeocosta@gmail.com)

**Comment by woliveiras** [comment]
Vamos ver se alguém dos @training-center/mentors consegue te ajudar @guilhermeocosta!

**Comment by woliveiras** [comment]
Algum dos novos @training-center/mentors consegue ajudar esse jovem?

**Comment by WendellAdriel** [comment]
Olá @DaniloAgostinho, se quiser dar uma olhada em meu perfil de mentor para ver se gosta e se eu poderei te ajudar, ficarei feliz caso possa ajudar em algo.

No meu perfil não está falando, mas atualmente moro em Lisboa/Portugal, então meu horário é um pouco diferente do de vocês, mas mesmo assim posso ajudar bastante.

Podemos elaborar planos de estudo para você, vou acompanhar com atividades que irei passar, corrigir, etc. Tenho bastante experiência com processos seletivos também, até palestrei sobre carreira na LaraConf Brasil.

Como canais de comunicação, prefiro utilizar Slack/Telegram. Fico no aguardo. Abraços!

**Comment by guilhermeocosta** [comment]
Olá @WendellAdriel, acho que você marcou a pessoa errada então vou considerar que a mensagem foi para mim hahahah

Adoraria receber a sua ajuda, como podemos começar? Dos meios de comunicação que você citou, acho que é uma boa usarmos o Telegram, pode ser? Meu user name lá é **@guilhermedeocosta**

Quando estiver disponível, posso te falar um pouco mais sobre o momento que estou passando, é aquele momento que não se é mais júnior mas também ainda há muiiiito o que aprender pela frente haha

Grande abraço!

**Comment by guilhermeocosta** [comment]
E muito obrigado pelo follow, @woliveiras :)

**Comment by WendellAdriel** [comment]
@guilhermeocosta desculpa cara, foi erro de CTRL+C CTRL+V asusuhahusauhsa. Mas era pra você mesmo cara!!! Vou te mandar mensagem lá pra começarmos então!!!

Aproveita e já cria/atualiza seu perfil de pupilo aqui no repo. Qualquer dúvida eu ou outro @training-center/moderators  pode te ajudar!!!

Abraços!!! :wink:

**Comment by guilhermeocosta** [comment]
Perfeito, obrigado!

**Comment by thiagobvs** [comment]
noob

**Comment by woliveiras** [comment]
@thiagobvs, aqui nós não curtimos esse tipo de comentário.

**Comment by daniloagostinho** [comment]
@thiagobvs comentário desnecessário meu amigo.
