### ISSUE TITLE
Preciso de um mentor Full Stack

### ISSUE THREAD

**Issue by nikolasbrandao** [training-center/mentoria#165]
**Nome:** Nikolas Martins Brandão Oliveira
**Descrição:** Sou Maranhense, estudo de Sistemas de Informação no Instituto Federal de Ciência e Tecnologia do Maranhão, sou atualmente bolsista de um projeto de iniciação científica.
**Nível de conhecimento atual:** 
Possuo conhecimento basicos em C, Java, C#, HTML, CSS, JavaScript, PHP e MySQL.
**Pretendo:**
Adquirir e aprimorar conhecimentos na area de desenvolvimento Web, principalmente com tecnologias que utilizem JavaScript.
**Contatos:**
[Facebook](https://www.facebook.com/NikolasBrandao)
[Twitter](https://twitter.com/ofabricante)

**Comment by woliveiras** [comment]
Vamos ver se alguém dos @training-center/mentors consegue te ajudar @nikolasbrandao!

**Comment by WendellAdriel** [comment]
Olá @nikolasbrandao, se quiser dar uma olhada em meu perfil de mentor para ver se gosta e se eu poderei te ajudar, ficarei feliz caso possa ajudar em algo.

No meu perfil não está falando, mas atualmente moro em Lisboa/Portugal, então meu horário é um pouco diferente do de vocês, mas mesmo assim posso ajudar bastante.

Podemos elaborar planos de estudo para você, vou acompanhar com atividades que irei passar, corrigir, etc. Como canais de comunicação, prefiro utilizar Slack/Telegram. Fico no aguardo. Abraços!

**Comment by nikolasbrandao** [comment]
Olá @WendellAdriel , fiquei extremamente feliz com a proposta, ja tinha dado uma olhada no perfil dos tutores e o seu foi um dos que mais me chamou atenção, principalmente pelo CodeShare que eu já conhecia antes do mentoria.

Eu não tenho um problema muito grande com horarios, a faculdade é integral (tarde e noite) mas não é dificil pra mim flexibilizar horarios. podemos conversar no telegram, meu contato é o @Nikolasbrandao.

**Comment by WendellAdriel** [comment]
Opa @nikolasbrandao que top mano, fico feliz que já conhecia meu projeto antes. Então fechou, estou resolvendo umas paradas aqui no trabalho, mas vou dar um oi no Telegram pra já ficar com meu contato e vamos começar já a mentoria!!!

Enquanto isso você pode ler as [responsabilidades de um pupilo](https://github.com/training-center/mentoria/blob/master/pupilos/responsibility.md), usar esse [template](https://github.com/training-center/mentoria/blob/master/pupilos/pupilo_template.md) e criar o seu perfil de pupilo [aqui](https://github.com/training-center/mentoria/tree/master/pupilos/perfis). Caso tenha alguma dificuldade com o Git/Github por favor me avise que começamos a mentoria por aí.
Abraços!!!

**Comment by WendellAdriel** [comment]
@woliveiras pode fechar essa issue

**Comment by woliveiras** [comment]
Beleza mano!
