### ISSUE TITLE
Preciso de um(a) mentor(a) de Front-End/Full Stack (não aguento mais mandar currículo e não receber resposta)

### ISSUE THREAD

**Issue by freeboxd** [training-center/mentoria#166]
**Nome:** Guilherme Martins

**Descrição:**  Tenho 17 anos e estudo o conteúdo da área já tem uns anos. Acontece que aprendo tudo sozinho, então reconheço muitas falhas e matérias negligenciadas por minha parte. Estou saindo do ensino médio esse ano e preciso de um emprego no ano que vem. Um emprego como desenvolvedor jr. meio-período seria excelente; poderia me dedicar aos estudos e conseguir uma renda. Aliás, eu já devo ter mandado meu currículo pra umas 30 empresas esse ano. Das poucas que me responderam, precisavam com urgência e nem cheguei a ser entrevistado.

**Nível de conhecimento atual:**
- Pacote Adobe (Photoshop, Illustrator)
- HTML
- CSS
- Javascript
- jQuery
- Conhecimentos de pré-processadores CSS (LESS, Sass, Stylus) - não tenho prática com funções e coisas muito complexas
- Bootstrap
- Wordpress básico
- PHP básico
- Node.js básico
- Angular.js básico
- Bower
- Jeet
- Javascript Templating básico

Embora eu tenha conhecimento das matérias acima, por não trabalhar, de fato, na área, eu esqueço muito facilmente e preciso revisar sempre que vou fazer um novo projeto. Outra coisa também é que não aprofundei muito em algumas coisas e, justamente por não ter um chão, algum modelo a seguir, me sinto inseguro.

A minha maior necessidade é ser contratado por uma boa empresa (preferencialmente em regime CLT), mas cada vez mais parece impossível de entrar no mercado.

**Contatos:**
Não tenho costume de usar redes sociais. Mas mando se precisar.

**Comment by LFeh** [comment]
Poderia te ajudar na parte de Front-End.

Tem interesse [nesses assuntos](https://github.com/training-center/mentoria/blob/master/mentores/perfis/felipe_fialho.md)?

**Comment by woliveiras** [comment]
O @LFeh pode ajudar bastante na parte de Front ein @freeboxd

**Comment by woliveiras** [comment]
Vamos ver se mais alguém dos @training-center/mentors consegue ajudar em Back End

**Comment by freeboxd** [comment]
Com certeza, @LFeh. O mais importante agora é mais o Front-End mesmo.
O que faço agora?

**Comment by LFeh** [comment]
Não é meu foco.

Não sei dizer se é melhor ter alguém fullstack ou dois mentores.

O que pensa @woliveiras?

**Comment by woliveiras** [comment]
Podemos buscar alguém de Node enquanto ensina coisas de Front End, @LFeh

O que acham?

**Comment by LFeh** [comment]
Acho que vai mais do @freeboxd ver o que é melhor.

**Comment by wesleycoder** [comment]
Eu poderia trabalhar em conjunto com @LFeh para preencher a fome de conhecimento desse fera aí!
Meu foco é sempre o javascript nosso de cada dia, tenho uma boa bagagem em Node e alguma experiência em testes que vale a pena compartilhar.
O que acha disso Guilherme (@freeboxd)?

**Comment by woliveiras** [comment]
Olha lá que sucesso!

**Comment by freeboxd** [comment]
Demais, @wesleycoder e @LFeh! O foco de vocês deve me dar uma base boa pro que eu to buscando na área. Acho que vai ser sensacional.

**Comment by LFeh** [comment]
Okay @freeboxd, a mentoria vai ser separada. Me chama no Slack para te explicar como estou pensando em fazer com meus "pupilos" :)

**Comment by woliveiras** [comment]
SUCESSSSSOOO

**Comment by woliveiras** [comment]
Fala galera, vou fechar essa issue, pois ela já completou seus 10 dias! :smile: 

Qualquer problema podemos reabrir.
