### ISSUE TITLE
Mentoria FrontEnd Básico-intermediário

### ISSUE THREAD

**Issue by Edusar** [training-center/mentoria#167]
Olá, meu nome é Eduardo. Eu sou designer web e tenho noções básicas de front end. Eu gostaria de alguém que me ajude a aprender o html semântico, css com alguma metodologia e, se possível, JavaScript também. Estou procurando aprender front porque gosto muito de codificar os layouts que desenho e porque desejo ter mais autonomia para colocar projetos em prática. Além disso, gostaria de conseguir uma vaga nessa área em breve.

Contatos: 
eduardosdearaujo@gmail.com | https://fb.com/eduardo.s.de.araujo

Obrigado.

**Comment by woliveiras** [comment]
Bem vindo @Edusar 

Vamos ver se alguém dos @training-center/mentors consegue te ajudar!

**Comment by nandomoreirame** [comment]
@Edusar eu tenho vaga e gostaria de ser seu mentor, claro se você quiser ;)

**Comment by Edusar** [comment]
E aí Fernando, tudo bem?

Claro, vamos lá. 
Eu quero aprender o máximo possível de front!

**Comment by Edusar** [comment]
@nandomoreirame, vamos conversar por email ou como? Aguardo teu contato pra gente se organizar. Valeu!

**Comment by nandomoreirame** [comment]
Entra no slack do CT Group >> https://ctgroups.herokuapp.com/

Conversamos por lá :smile:

**Comment by woliveiras** [comment]
Sucesso!

Assim que possível subam/atualizem o perfil de vocês aqui no repo. 😄

**Comment by nandomoreirame** [comment]
Tranquilo @woliveiras \o/

**Comment by woliveiras** [comment]
Fala galera, vou fechar essa issue, pois ela já completou seus 10 dias! :smile: 

Qualquer problema podemos reabrir.
