### ISSUE TITLE
Preciso de um(a) mentor(a) de Front End

### ISSUE THREAD

**Issue by pedbernardo** [training-center/mentoria#168]
### Dados Pessoais

**Nome**: Pedro Bernardo
**Descrição**: Sou estudante do curso de Análise e Desenvolvimento de Sistemas (o que é, de certa forma, irrelevante para a área - minha opinião), já trabalho como "desenvolvedor front-end", mas como é uma empresa pequena (somente 2 desenvolvedores, contado comigo, haha) e focada em um nicho de tecnologia (automação de processos em BPMS) sempre tive vontade de adquirir experiência em como as coisas funcionam com equipes mais estruturadas, com processos e metodologias de desenvolvimento mais maduras.

**Nível de Conhecimento Atual**: Me considero um _"desenvolvedor pleno"_, pois tenho capacidade de iniciar e entregar um projeto de ponta-a-ponta, contando com todos os conhecimentos envolvidos nesse processo (html, css, js...). Ainda assim, acredito que tenho muito pra aprender e vi essa iniciativa como uma ótima oportunidade de aprendizado! :)

### Sonhos/Vontades
_(vi em uma Issue, achei legal a idéia!)_
 
Faço trabalho voluntário como chefe escoteiro (há 6 anos) e hoje tenho vontade de partir pra outra _"aventura"_, criando/participando um curso gratuito de desenvolvimento para pessoas de baixa renda.
Além disso, tenho como projeto pessoal imigrar para o Canadá (o principal motivo que faz com que eu permaneça na faculdade).

### Contatos

> **FB**: [facebook.com/pedrovbernardo](http://facebook.com/pedrovbernardo)
> **Twitter**: [twitter.com/pedbernardo](http://twitter.com/pedbernardo)
> **Codepen**: [codepen.io/pedbernardo/](http://codepen.io/pedbernardo)
> **Email**: pedrovbernardo@gmail.com

**Comment by woliveiras** [comment]
Bem vindo @pedbernardo 

Vamos ver se alguém dos @training-center/mentors consegue te ajudar! 

Boa sorte nos seus objetivos!

**Comment by pedbernardo** [comment]
@woliveiras
Obrigado, e parabéns pela iniciativa!

**Comment by woliveiras** [comment]
:raised_hands: :raised_hands: :raised_hands:

**Comment by woliveiras** [comment]
Algum dos novos @training-center/mentors consegue ajudar esse jovem?

**Comment by guilhermepontes** [comment]
Fala @pedbernardo, tudo baum?
Dá uma olhada no meu perfil e vê se encaixa com o que você está procurando, se sim dá um toque!

Abs

**Comment by pedbernardo** [comment]
@guilhermepontes com certeza 'se encaixa'!

Qual melhor canal pra trocarmos idéia?

Abraço!

**Comment by guilhermepontes** [comment]
@pedbernardo opa, adicionei você num grupo lá no Slack!

**Comment by pedbernardo** [comment]
@guilhermepontes fechou 👍

**Comment by guilhermepontes** [comment]
cc: @training-center/moderators #226 #227

**Comment by danilovaz** [comment]
Perfil do Mentor atualizado: #244 sucesso pessoal :tada:
