### ISSUE TITLE
 Preciso de um(a) mentor(a) de Mentores de Front End e UX/UI

### ISSUE THREAD

**Issue by maiconkcond** [training-center/mentoria#169]
**Nome:**Maicon Henrique
**Descrição:** Tenho 26 anos. Iniciei meus estudos na area de TI através de um curso técnico de informatica pela ETEC, que serviu como base para eu me apaixonar pela área. Logo após fiz superior em Analise e Desenvolvimento de Sistemas, cursando 1 ano na FATEC e o restante na Impacta, atualmente estou cursando uma especialização em Desenvolvimento Multi Plataforma (Web e Mobile) pelo SENAI.
Trabalhei na área por dois anos com desenvolvimento desktop, mais especificamente com VB.NET. Atualmente trabalho fora da area, com suporte técnico e  estou com dificuldades de arrumar meu primeiro emprego como Dev FrontEnd Jr. 

**Nível de conhecimento atual:**
-HTML5
-CSS5
-Javascript
-jQuery
-Frameworks css (bootstrap, materialize)
-PHP 
-CodeIgniter
-Ruby
-Rails
-Jekyll
-Git
-React

Lembrando que todo meu conhecimento é básico e totalmente acadêmico, treinando com materiais e projetos próprios.
Venho a um bom tempo me dedicando ao FrontEnd com cursos, livros e foruns e sinto que o que falta hoje e minha maior necessidade seria uma oportunidade de mostrar minha capacidade, ou seja um oportunidade de um trabalho como junior.
Já pensei em criar um portfolio e tentar alguns projetos como freelancer porém estou um pouco perdido quanto a isso.
**Contatos:**[LinkedIn](https://www.linkedin.com/in/maicon-henrique-raimundo-8441b368?trk=nav_responsive_tab_profile) [Facebook](https://www.facebook.com/maiconhenriquekcond)

**Comment by woliveiras** [comment]
Bem vindo @maiconkcond 

Vamos ver se alguém dos @training-center/mentors consegue te ajudar.

**Comment by woliveiras** [comment]
Algum dos novos @training-center/mentors consegue ajudar esse jovem?

**Comment by leandro-lima** [comment]
Eu posso ajudar com a parte de UX/UI =)

**Comment by maiconkcond** [comment]
A ajuda irá ser muito bem vinda :D, ainda mais se tratando dos temas UX/UI.
Obrigado pela iniciativa Leandro

**Comment by woliveiras** [comment]
\o/

Show de bola!

É só criar/atualizar os perfis de vocês e se comunicarem da melhor maneira que encontrarem. :heart:

**Comment by maiconkcond** [comment]
@woliveiras 

Está criado o perfil (Acredito que fiz tudo certo).
Obrigado =)

**Comment by woliveiras** [comment]
:metal: :metal: :metal: :metal:
