### ISSUE TITLE
 Preciso de um mentor sobre desenvolvimento backend em PHP

### ISSUE THREAD

**Issue by CaioFlavio** [training-center/mentoria#17]
Nome: Caio Flávio
Descrição: Preciso de um mentor na área de desenvolvimento PHP utilizando algum framework. No momento estou utilizando CAKEPHP para um projeto no trabalho, mas estou disposto a aprender outro caso necessário.
Nível de conhecimento atual: Intermediário
Contatos:
Facebook: https://www.facebook.com/kaiooflavio
Twitter: https://twitter.com/KaioFlavio123

**Comment by jlamim** [comment]
@CaioFlavio posso ser seu mentor. Trabalho com desenvolvimento usando PHP a mais de 10 anos, e com cereteza posso contribuir para o seu crescimento.

Todo mundo de acordo?

**Comment by woliveiras** [comment]
100% de acordo!

**Comment by jlamim** [comment]
@CaioFlavio A partir desse momento passo a ser seu mentor.

Me envie um email (contato@jlamim.com.br) com seus dados: skype, email, facebook para que possamos iniciar o processo de mentoria.

P.S.: @woliveiras pode fechar a issue.

**Comment by woliveiras** [comment]
Pra já! Não esquece de atualizar seu perfil e pedir pros manos atualizarem os deles @jlamim :D
