### ISSUE TITLE
Preciso de um(a) mentor(a) de Front-end com foco em Design/UX

### ISSUE THREAD

**Issue by rieliboldrini** [training-center/mentoria#171]
**Nome:** Rieli Boldrini

**Descrição:** Olá, pessoal! Beleza? Sou recém-formado em Design Gráfico e atualmente estou cursando o Nanodegree Front-End da Udacity. Decidi mergulhar de cabeça no mundo do Desenvolvimento Web, sendo que trabalhei como designer durante os últimos 5 anos em agências de publicidade do interior de SP.

**Nível de conhecimento atual:** HTML e CSS, intermediários.

**Contato:** rieliboldrini@gmail.com

**Comment by LFeh** [comment]
@rieliboldrini Veja se está de acordo -> https://github.com/training-center/mentoria/blob/master/mentores/perfis/felipe_fialho.md

Ps. Meus pais moram em Americana, estou sempre por ai, rs.

**Comment by rieliboldrini** [comment]
@LFeh Opa, totalmente de acordo. 💃
Como nos comunicaremos então?

**Comment by LFeh** [comment]
Me chama no Slack. Vou te colocar no grupo dos meus "pupilos". :)

**Comment by woliveiras** [comment]
Eita galera ligeira!!!

**Comment by woliveiras** [comment]
Fala galera, vou fechar essa issue, pois ela já completou seus 10 dias! :smile: 

Qualquer problema podemos reabrir.
