### ISSUE TITLE
Preciso de um(a) mentor(a) para Front-End :D

### ISSUE THREAD

**Issue by andre-mendes** [training-center/mentoria#172]
**Descrição**: Fala galera, tranquilo? :) Sou formado em Publicidade e Propaganda, mas decidi cair de cabeça no desenvolvimento que é o que realmente gosto <3 Sempre tive interesse no Front-End. Faz 1 ano que tive meu primeiro contato com códigos e hoje trabalho em uma agência como desenvolvedor :D Também hoje estou fazendo Pós Graduação em desenvolvimento WEB pra abrir minha mente :D
Obs. Sou extremamente apaixonado por CSS e semântica <3

Tenho 26 anos e moro em Umuarama, no interior do paraná :D

**Nome:** André Mendes
**Nível de conhecimento atual:** HTML, CSS e JS intermediario
**Contatos:** mendes.adc@gmail.com

vlw \o/

**Comment by woliveiras** [comment]
Fala @andre-mendes 

Vamos ver se alguém dos @training-center/mentors consegue te ajudar. 😄

**Comment by LFeh** [comment]
@andre-mendes Meu perfil é de acordo?

https://github.com/training-center/mentoria/blob/master/mentores/perfis/felipe_fialho.md

**Comment by andre-mendes** [comment]
ai @woliveiras os caras são ninjas! uhashuaHUShuaU

Pooo @LFeh nem vou abrir seu perfil pq ja conheço :D :D acompanho mto seu conteúdo, e sem saber vc ja é meu mentor hhahhaah por mim ta fechadaço! :D

**Comment by LFeh** [comment]
hahahaha, nóis então

Me chama no Slack, que te coloco no canal.

Meu grupo de três agora está fechado \o

**Comment by andre-mendes** [comment]
Demoro @LFeh :D :D 

Eu to na casa da minha mãe (feriado aqui :D :D), não estou conseguindo entrar no slack aqui :( Assim que chegar em casa ja te chamo la entao \o/

**Comment by woliveiras** [comment]
Fala @LFeh e @andre-mendes 

Tudo certo entre vocês?

Posso fechar a issue?
