### ISSUE TITLE
Preciso de um(a) mentor(a) de Front-End

### ISSUE THREAD

**Issue by luizgabriell** [training-center/mentoria#173]
**Nome:** Luiz Gabriel

**Descrição:** Olá! Me chamo Luiz Gabriel e faço faculdade de Sistemas de Informação (pretendo pedir transferência para Sistemas para Internet).

Sou completamente novato na área de desenvolvimento, seja ele Front-End ou Back-End, mas tenho sede de aprender.
A última vez que cheguei a criar sites de fato do zero, foi quando termos como "Front-End" e "Back-End" não eram separados, mas sim unificados através de uma profissão chamado "Web Designer".
Nesta época as pessoas ainda utilizavam tabelas em HTML para estruturar um site. Atitude que hoje faz qualquer desenvolvedor mais experiente se coçar de agonia. rs

Estou acompanhando algumas vídeo aulas  do site "Curso em Vídeo" sobre HTML5, CSS3 e Javascript e  para conseguir entrar nessa área tão bacana que acredito ser o desenvolvimento web.

Gostaria do auxílio de um(a) mentor(a) para poder me guiar logo no início e me direcionar para o caminho correto. Mais do que isso gostaria que o(a) mentor(a) me ensinasse a elaborar e desenvolver meus próprios projetos do zero e não somente ficar copiando conteúdos de vídeo-aulas.

**Nível de conhecimento atual:** Básico
**Contatos:** Possuo Facebook, mas tenho maior facilidade de acesso e acompanhamento via e-mail
E-mail: [lgabriell.araujo@gmail.com](mailto:lgabriell.araujo@gmail.com)

Desculpa se cometi alguma coisa errada. Assim como estou iniciando agora na área de desenvolvimento, é a primeira vez que utilizo o GitHub.

**Comment by woliveiras** [comment]
Bem vindo @luizgabriell 

Vamos ver se alguém dos @training-center/mentors consegue te ajudar. 😄

**Comment by wagnerssouza** [comment]
Oi @luizgabriell, esse é meu [Perfil](https://github.com/training-center/mentoria/blob/master/mentores/perfis/wagner_santos.md), veja se está de acordo, se sim, posso te ajudar ;D

**Comment by luizgabriell** [comment]
Olá @wagnerssouza, achei seu perfil muito completo e com  um conhecimento muito amplo e sólido. 

Se poder me ajudar neste novo começo, ficarei muito grato!

**Comment by wagnerssouza** [comment]
Show @luizgabriell  , cria um perfil [aqui](https://github.com/training-center/mentoria/tree/master/pupilos/perfis), já te mando um e-mail pra gente começar a conversar ;D

**Comment by woliveiras** [comment]
Show de bola!

**Comment by luizgabriell** [comment]
@wagnerssouza Desculpe minha ignorância, mas como faço para criar um perfil? 
Eu preciso subir um arquivo para o GitHub? Como faço isso?

**Comment by woliveiras** [comment]
Que isso @luizgabriell, sem problemas perguntar cara.

É isso mesmo.

Você cria o arquivo com seu nome de usuário do GitHub aqui:

https://github.com/training-center/mentoria/blob/master/pupilos/perfis

Seguindo esse template:

https://github.com/training-center/mentoria/blob/master/pupilos/pupilo_template.md

Depois é só atualizar essa lista colocando o link pro seu perfil: 

https://github.com/training-center/mentoria/blob/master/pupilos/README.md

E sucesso!

**Comment by woliveiras** [comment]
Fala galera, vou fechar essa issue, pois ela já completou seus 10 dias! :smile: 

Qualquer problema podemos reabrir.
