### ISSUE TITLE
Preciso de um(a) mentor(a) de Front-end

### ISSUE THREAD

**Issue by luizangelomedeiros** [training-center/mentoria#174]
# Preciso de um(a) mentor(a) de Front-end

**Nome:** Luiz Ângelo Tognon Medeiros

**Sobre mim:**
Olá galera, tudo certo?
Me chamo Luiz , tenho 22 anos e sou de Passo Fundo no Rio Grande do Sul.
Após encerrar o ensino médio realizei um técnico em informática de 2 anos, que foi minha base para aprender a programar. Com o termino do técnico iniciei uma graduação em Sistemas para Internet e no final de 2015 conclui a mesma.

**Nível de conhecimento atual:**
Trabalhei praticamente 4 anos e meio como Web Developer (para não dizer Full Stack HAHAHA ) em uma empresa de Passo Fundo mesmo. Realizava o desenvolvimento de Sites Imobiliários e também fazia implementação/manutenção em um sistema CRM. Nesta empresa eu trabalhava com PHP, Mysql, SOAP, JS, Jquery, Sass, Bootstrap, Css, Html, técnicas de otimização , SEO,  entre outros.

Além destes conhecimentos possuo conhecimento em REST, Java como JSP, JPA, Hibernate e em meu trabalho de conclusão de curso realizei um estudo sobre "Push" e desenvolvi um aplicativo Android para demonstrar esta comunicação.
Em projetos pessoais possuo conhecimento com versionamento (Git) , task runners (Gulp) e SPA com AngularJS. 
Acredito ser um desenvolvedor intermediário.

**Objetivos:**
Recentemente decidi pedir desligamento da empresa aonde trabalhava, para focar em estudos e buscar desafios maiores em novas cidades. Conforme já havia pedido a opinião da galera nessa [issue ](https://github.com/frontendbr/forum/issues/203 ) antigamente.
Preciso do apoio de um mentor, principalmente em Javascript com Angular (Nível Intermediário), Es6, testes ( Jasmine, Mocha ) e também Arquitetura Css (Smacss, bem).

**Contatos:**
Possuo um projeto parado de Blog, porém pretendo dar continuidade em breve, para ter meu portfólio e currículo online e também treinar o conhecimento adquirido recentemente. Por enquanto os contatos são estes:

E-mail: luizangelomedeiros@gmail.com
Linkedin: https://br.linkedin.com/in/luizangelomedeiros
Github: https://github.com/luizangelomedeiros

PS: Mals o textão AHAHA

**Comment by woliveiras** [comment]
Eae cara!

Vamos ver se alguém dos @training-center/mentors consegue te ajudar.

Boa sorte!

**Comment by woliveiras** [comment]
Algum dos novos @training-center/mentors consegue ajudar esse jovem?

**Comment by luizangelomedeiros** [comment]
Olá Pessoal,
andei olhando as issues abertas e vi que existem pessoas que estão iniciando sua jornada na programação. Eu não tenho tanto conhecimento como vocês mentores, porém acredito que já consigo me virar bem.
Por esse motivo, vou fechar esse pedido de mentoria, para que a prioridade fique com pessoas que realmente precisam de uma ajuda mais de perto. Acredito que para quem está começando, ter o suporte de alguém mais experiente faz toda a diferença.
Qualquer coisa eu vou incomodando vocês lá no slack mesmo HAHAHA

Enfim, parabéns pelo projeto e iniciativa de quem realmente está disposto a ajudar.

vamos nos falando 😃

**Comment by woliveiras** [comment]
Perfeito @luizangelomedeiros 

Qualquer coisa grita noes lá no Slack! :smile:
