### ISSUE TITLE
Preciso de um(a) mentor(a) de Desenvolvimento Front-end.

### ISSUE THREAD

**Issue by RodrigoDietriech** [training-center/mentoria#176]
Preciso de um(a) mentor(a) de Desenvolvimento Front-end.

Nome: Rodrigo Dietriech dos Passos.
Descrição: fiz um curso técnico em desenvolvimento de sistemas IFRS o que inclui WEB, mas este contéudo não fixei muito bem e gostaria de agora me aperfeiçoar na área para conseguir um emprego. relembrando o básico/intermediário de HTML, CSS, PHP e JavaScript e querendo melhorar em todos quesitos possíveis.

Nível de conhecimento atual:  básico/intermediário de HTML, CSS, PHP, JavaScript e mySQL querendo melhorar em todos quesitos possíveis. Ano passado fiz uma loja virtual completa de trabalho final da disciplina, porém já não me lembro muito bem e portanto estou relembrando inicialmente.
Contatos: 
https://www.facebook.com/rodrigodietriech;
E-mail: rodrigodietriech11@gmail.com.

**Comment by woliveiras** [comment]
Bem vindo @RodrigoDietriech 

Removi o número de telefone, pois pode gerar trotes, viu.

Compartilha só com quem for conversar contigo mesmo.
Attach files by dragging & dropping,  Choose Files selecting them, or pasting from the clipboard.

Vamos ver se alguém dos @training-center/mentors consegue te ajudar. :raised_hands: 

Boa sorte!

**Comment by wagnerssouza** [comment]
Olá @RodrigoDietriech, esse é meu [Perfil](https://github.com/training-center/mentoria/blob/master/mentores/perfis/wagner_santos.md), se estiver de acordo, posso te ajudar ;D

**Comment by RodrigoDietriech** [comment]
Olá @wagnerssouza, adoraria ser seu pupilo :D. Como fazemos para nos comunicar?

**Comment by wagnerssouza** [comment]
Show @RodrigoDietriech , cria um perfil [aqui](https://github.com/training-center/mentoria/tree/master/pupilos/perfis), já te mando um e-mail pra gente começar a conversar ;D

**Comment by woliveiras** [comment]
Suuuucesso! 😄

**Comment by woliveiras** [comment]
Fala galera, vou fechar essa issue, pois ela já completou seus 10 dias! :smile: 

Qualquer problema podemos reabrir.
