### ISSUE TITLE
Preciso de um mentor de front-end (foco em js e css)

### ISSUE THREAD

**Issue by douglas-castilho** [training-center/mentoria#179]
**Nome:**  douglas castilho 

**Sobre mim** 
Trabalho com front desde quando não existia esse nome, já rodei por agências, produtoras, produtos fechados (onde eu prefiro). Trabalhando com produtos acabei ficando desatualizado com muitas coisas de desenvolvimento. 
Na parte de css quero aprimorar as partes de otimizações, novas estruturas, reponsive, mobile... 
Com JS também, tenho bom conhecimento mas ainda tenho alguns problemas com testes e boas práticas, ES6 e por aí vai...

**contato**
twitter: [doug001](http://www.twitter.com/doug001)
email: douglas.castilho@gmail.com

**Comment by woliveiras** [comment]
Bem vindo @douglas-castilho 

Vamos ver se alguém dos @training-center/mentors consegue te ajudar. 😄
