### ISSUE TITLE
Preciso de um(a) mentor(a) de JavaScript/Carreira

### ISSUE THREAD

**Issue by pauloweb** [training-center/mentoria#182]
**Nome:**  Paulo Silveira

**Descrição:** 
 Trabalho há 4 anos como desenvolvedor back-end em Php, formado em Sistemas de Informação, atualmente trabalho em uma agência onde não há distinção de back-end e front-end.

**Nível de conhecimento atual:**
C, Java, JavaScript, Node.js, Angular 1, Mysql, Android, HTML, CSS,  PHP(Nível Intermediário).

**Pretensão:**
Adquirir conhecimentos na área e principalmente os relacionados à JavaScript, React, React-native, babel, pois vejo um cenário onde tudo esta centralizando na linguagem e a usando como base para muitas coisas.

**Contato:**
paulodesenvolvedorweb@gmail.com

**Comment by woliveiras** [comment]
Bem vindo @pauloweb 

Vamos ver se algum @training-center/mentors consegue te ajudar. :smile:

**Comment by pauloweb** [comment]
@woliveiras  Muito obrigado!! 
Fico ansiosamente aguardando.

**Comment by woliveiras** [comment]
Algum dos novos @training-center/mentors consegue ajudar esse jovem?

**Comment by woliveiras** [comment]
Fala pessoal dos @training-center/mentors conseguem nos ajudar nessa? :)

**Comment by woliveiras** [comment]
Estamos com todos os Mentores e Mentoras ocupados no momento, adicionei a label `wait for new mentors` para que os próximos busquem por essas issues primeiro.

**Comment by kivervinicius** [comment]
Opa, ainda está precisando de um mentor @pauloweb

**Comment by ftonato** [comment]
Fala @pauloweb, como está o andamento dessa _issue_?
- [ ] Encontrou o mentor?
- [ ] O mentor entrou em contato com você?

/cc @kivervinicius

**Comment by woliveiras** [comment]
@pauloweb nosso processo mudou: https://medium.com/trainingcenter/e-o-mentoria-mudou-mais-uma-vez-5ad8725bc778

Peço, por favor, que responda esse formulário, se ainda fizer sentido, para que algum mentor ou mentora entre em contato contigo quando possível: http://bit.ly/preciso-de-mentoria

A issue será fechada para que não aconteçam desencontros de informação.
