### ISSUE TITLE
Preciso de um(a) mentor(a) de Full Stack

### ISSUE THREAD

**Issue by itamarsilvacc** [training-center/mentoria#183]
**Nome:** Itamar Silva
**Descrição:** Bom, eu cursei Ciência da Computação até o 7º período, de 2010 à 2013, que me colocou em contato com os códigos e a tecnologia. Nesse período descobri o Desenvolvimento Web, e me apaixonei. Trabalho a quase 3 anos desenvolvendo, ou tentando rs, como freelancer. Porém, estudando de tudo um pouco, me sinto não sabendo o suficiente de nada. Desejo um mentor que me direcione para que eu realmente me torne um Full Stack Web Developer.
**Nível de conhecimento atual:** Sinceramente, não sei avaliar! Sei um pouco de HMTL, CSS, JavaScript, PHP, C(sabia pelo menos rs), SEO, SQL. Não sei usar o Github.
**Contatos:** 
contato@itamarsilva.com.br
https://www.facebook.com/itamarsilvacc

**Comment by woliveiras** [comment]
Bem vindo @itamarsilvacc 

Vamos ver se algum dos @training-center/mentors consegue te ajudar. :smile:

**Comment by itamarsilvacc** [comment]
Obrigado @woliveiras 
Estarei aguardando aqui por alguém. :dagger:

**Comment by WendellAdriel** [comment]
Olá @itamarsilvacc, se quiser dar uma olhada em meu perfil de mentor para ver se gosta e se eu poderei te ajudar, ficarei feliz caso possa ajudar em algo.

No meu perfil não está falando, mas atualmente moro em Lisboa/Portugal, então meu horário é um pouco diferente do de vocês, mas mesmo assim posso ajudar bastante.

Podemos elaborar planos de estudo para você, vou acompanhar com atividades que irei passar, corrigir, etc. Como canais de comunicação, prefiro utilizar Slack/Telegram. Fico no aguardo. Abraços!

**Comment by itamarsilvacc** [comment]
Olá @WendellAdriel , dei uma olhada aqui e gostei bastante do meu perfil, creio que você esteja totalmente apto a ser meu mentor, já que desejo seguir um caminho tendo como base justamente o PHP e JavaScript.
Quanto ao horário eu posso me adaptar aos horários que você tiver disponível, quando for o caso de nos falarmos instantaneamente.
Pra mim está ótimo você ser o meu mentor, como continuamos daqui em diante?

**Comment by WendellAdriel** [comment]
Qual canal de comunicação prefere pra gente se comunicar?
Telegram ou Slack?
Escolhendo um, podemos começar a mentoria já!!! :wink:

**Comment by woliveiras** [comment]
:metal: :metal: :metal: 

Não se esqueçam de atualizar/criar seus perfis. :smile:

**Comment by WendellAdriel** [comment]
@itamarsilvacc estou aguardando seu retorno

**Comment by woliveiras** [comment]
Rolou alguma conversa entre vocês @WendellAdriel?

**Comment by WendellAdriel** [comment]
@woliveiras não tive mais nenhum contato dele depois disso :cry:

**Comment by woliveiras** [comment]
@itamarsilvacc aparece meu jooovi

**Comment by itamarsilvacc** [comment]
@woliveiras e  @WendellAdriel , me desculpem a demora em responder, estive com uns problemas pessoais que não me cabe expor aqui e não estava acompanhando os emails e as issues. Ainda desejo receber a mentoria, ainda podemos iniciar @WendellAdriel ? Eu prefiro pelo Telegram, apesar de que começarei a usar pra falar com você. Não me dei muito bem com o Slack.

**Comment by woliveiras** [comment]
Sem problemas @itamarsilvacc 

Só combinarem o esquema, se der

O importante é continuar na pegada

**Comment by itamarsilvacc** [comment]
Está bem @woliveiras , vou aguardar a resposta do @WendellAdriel para darmos continuidade.

**Comment by woliveiras** [comment]
@itamarsilvacc, @WendellAdriel, tudo certo com vocês?

Não se esqueçam de atualizar/criar seus perfis ou avisar aqui se já o fizeram. :smile:

**Comment by woliveiras** [comment]
@itamarsilvacc, @WendellAdriel, tudo certo com vocês?

**Comment by WendellAdriel** [comment]
Vish man, nem vi essa issue aqui!!!

@woliveiras quando mandei a mensagem pra ele eu estava recrutando mais pupilos, como demorou muito eu peguei muitos pupilos e agora não posso pegar mais nenhum porque junta: meu trabalho fixo, as consultorias que dou, meus projetos pessoais e os pupilos que já tenho. Não vou ter tempo pra dar atenção necessária então prefiro não pegar mais nenhum pupilo.

**Comment by woliveiras** [comment]
Entendido @WendellAdriel 

Vamos ver se alguém consegue ajudar você @itamarsilvacc 

Se quiser, já pode seguir o novo fluxo: https://medium.com/trainingcenter/menos-burocracia-para-conseguir-um-mentor-ou-mentora-d571ed9cc3e0#.1p103u5hc

**Comment by ftonato** [comment]
Fala @itamarsilvacc, como está o andamento dessa _issue_?
- [ ] Encontrou o mentor?
- [ ] O mentor entrou em contato com você?

/cc @training-center/mentors

**Comment by itamarsilvacc** [comment]
Olá @ftonato, não encontrei, na época quando abri a issue, o mentor que tinha se disposto acabou não podendo mais, devido também e principalmente eu acho, à minha demora para responder o interesse dele. Continuo interessado em um mentor, caso você possa me ajudar.

**Comment by ftonato** [comment]
Entendo, bom vamos ver se algum dos mentores tem disponibilidade...

Ei @Ladeia, @giovannicruz97, @Belline, algum de vocês tem disponibilidade para o nosso amigo @itamarsilvacc?

**Comment by Ladeia** [comment]
Nops, meu foco infelizmente é backend e embarcados, posso ajudar pouquissimo com front :-(

**Comment by itamarsilvacc** [comment]
Está bem @ftonato , continuarei aguardando. E grato de qualquer forma @Ladeia :)

**Comment by woliveiras** [comment]
@itamarsilvacc nosso processo mudou: https://medium.com/trainingcenter/e-o-mentoria-mudou-mais-uma-vez-5ad8725bc778

Peço, por favor, que responda esse formulário, se ainda fizer sentido, para que algum mentor ou mentora entre em contato contigo quando possível: http://bit.ly/preciso-de-mentoria

A issue será fechada para que não aconteçam desencontros de informação.
