### ISSUE TITLE
Preciso de um mentor de Front End e UX/UI

### ISSUE THREAD

**Issue by diegosantoss** [training-center/mentoria#184]
Preciso de um mentor de Front End e UX/UI

Me formando agora em dezembro/2016 em Análise e Desenvolvimento de Sistemas, 

Nome: Diego Santos de Souza
Linkedin: https://www.linkedin.com/in/diegosantoss
Github: https://github.com/diegosantoss
Descrição: Procurando aprender sobre Gulp, Sass, Bootstrap e AngularJS
Nível de conhecimento atual: Web Developer Jr
Contato via e-mail: dsaantos1995@gmail.com

**Comment by woliveiras** [comment]
Bem indo @diegosantoss!!

Vamos ver se algum dos @training-center/mentors consegue te ajudar.

Enquanto isso leia o documento de [Responsabilidades do Pupilo](/pupilos/responsibility.md)!! :smile:

**Comment by wagnerssouza** [comment]
Oi @diegosantoss , da uma olhada no meu [Perfil](https://github.com/training-center/mentoria/blob/master/mentores/perfis/wagner_santos.md), se estiver de acordo, podemos seguir em frente. ;D

**Comment by diegosantoss** [comment]
ok Wagner, bom perfil creio que poderá me ajudar muito, podemos seguir em frente

**Comment by wagnerssouza** [comment]
Show @diegosantoss, cria um perfil [aqui](https://github.com/training-center/mentoria/tree/master/pupilos/perfis), já te mando um e-mail pra gente começar a conversar ;D

**Comment by woliveiras** [comment]
\o/

Caso não saiba como criar o perfil, nós podemos ajudar @diegosantoss

**Comment by woliveiras** [comment]
Fala @diegosantoss e @wagnerssouza 

Tudo rolando certinho entre vocês?

Posso fechar a issue?

**Comment by diegosantoss** [comment]
só preciso criar o perfil, nao consegui criar ainda mas hj ja vai estar pronto

**Comment by woliveiras** [comment]
Perfeito @diegosantoss

**Comment by woliveiras** [comment]
Fala pessoal, como a issue já passou de 10 dias, estou fechando ela. 

Qualquer problema é só avisar.

Abraços!
