### ISSUE TITLE
 Preciso de um(a) mentor(a) Front-End/Full Stack

### ISSUE THREAD

**Issue by agadev-bh** [training-center/mentoria#185]
**Nome:** 
Augusto Gonçalves Almeida

**Descrição:** 
Olá! Tenho 25 anos, trabalho com Business Intelligence e gostaria de recomeçar minha carreira na área de Desenvolvimento Web. Tenho interesse em Front-End, Full Stack e UX/UI.

**Nível de conhecimento atual:** 
HTML
CSS
Bootstrap
Jade (Que mudou pra pug)
SASS
Javascript (Intermediário)
jQuery (Intermediário)

Tenho noções de: .Net, PHP, Java

Tenho muito interesse em: ES6, Node, Express, Angular, React, Meteor, Backbone, Mongodb, PWA e outros assuntos que não me lembro nesse momento.

**Contatos:**
[Site pessoal](http://agadev.com.br)
[Linkedin](https://br.linkedin.com/in/agadev)
[GitHub](https://github.com/agadev-bh)
agadevbh@gmail.com

_Obrigado e parabéns a todos pela iniciativa!_

**Comment by danilovaz** [comment]
Bem vindo @agadev-bh

Vamos ver se algum dos @training-center/mentors consegue te ajudar.

Enquanto isso leia o documento de [Responsabilidades do Pupilo](/pupilos/responsibility.md)!! :smile:

**Comment by woliveiras** [comment]
Algum dos novos @training-center/mentors consegue ajudar esse jovem?

**Comment by wbruno** [comment]
opa! dá uma olhada:
https://github.com/training-center/mentoria/blob/master/mentores/perfis/william_bruno.md

se você achar que posso te ajudar, combinamos de nos falarmos pelo FacebookMessenger,hangout..ou algum outro IM ai.

**Comment by danilovaz** [comment]
Show! @agadev-bh Veja se o perfil do @wbruno é o que você procura.

**Comment by agadev-bh** [comment]
Excelente!
@wbruno , hoje à noite entro em contato pelo facebook.
Obrigado a todos.

**Comment by danilovaz** [comment]
Legal pessoal! Vão me atualizando à respeito do que forem decidindo e atualizem o perfil de vocês, assim que acertarem tudo e sucesso :tada:

**Comment by danilovaz** [comment]
@agadev-bh @wbruno alguma novidade?

**Comment by danilovaz** [comment]
Perfil de Pupilo adicionado: #300 e perfil do Mentor atualizado: #301
