### ISSUE TITLE
Quero ser mentor de desenvolvimento Full Stack.

### ISSUE THREAD

**Issue by diegoponciano** [training-center/mentoria#186]
Sou desenvolvedor há alguns anos, já tive a oportunidade de trabalhar com váááárias tecnologias (VB6, asp clássico, ~COBOL~, .NET, Java, Ruby e ultimamente quase só Python, pra nossa alegria :D).  
Minha experiência maior é com Python web, e back end. Manjo o suficiente de front-end pra montar uma página hahaha.

Contatos: [dgo.ponciano@gmail.com](mailto:dgo.ponciano@gmail.com) | [telegram.me/diegoponciano](telegram.me/diegoponciano)

**Comment by raymonsanches** [comment]
Olá @diegoponciano 

Você já leu as [Responsabilidades do Mentor]((/mentores/responsibility.md)) e está de acordo com a ideia do projeto?

:)

**Comment by diegoponciano** [comment]
Olá @raymonsanches, estou de acordo!

**Comment by raymonsanches** [comment]
Boa mano!

Bora criar teu perfil então. 
Aqui -> https://github.com/training-center/mentoria/blob/master/mentores/mentor_template.md <- tem um template pra você fazer PR do seu perfil.

Aproveita e entra lá no slack do CT -> https://ctgroups.herokuapp.com/

Assim que entrar lá no Slack me manda uma mensagem @raymonsanches que eu te chamo pro canal de mentores ;)

**Comment by woliveiras** [comment]
Fala pessoal, tudo Ok?

Posso fechar essa issue?

**Comment by diegoponciano** [comment]
@woliveiras Vou fechar, acabei de abrir a PR na lista de mentores.

**Comment by diegoponciano** [comment]
https://github.com/training-center/mentoria/pull/287

**Comment by woliveiras** [comment]
Perfeito @diegomalone 

Valeu cara
