### ISSUE TITLE
Preciso de um(a) mentor(a) Front-End/Full Stack

### ISSUE THREAD

**Issue by Josue23** [training-center/mentoria#187]
**Nome:** Josué C. Rodrigues
**Descrição:** Sou o Josué, trabalho como tester, faço faculdade de Sistemas de Informação e participo das comunidades de desenvolvimento daqui de Sampa.
**Nível de conhecimento atual:**
Linux
Git
Vim
HTML
CSS
JavaScript
PHP
Python
Selenium
**Contatos:**
<a href="https://github.com/Josue23">Github</a>
<a href="https://www.facebook.com/Josue.Rodrigues23">Facebook</a>
<a href="mailto:josuerodrigues@gmail.com">josuerodrigues@gmail.com</a>

**Comment by danilovaz** [comment]
Bem vindo @Josue23  

Vamos ver se algum dos @training-center/mentors consegue te ajudar.

Enquanto isso leia o documento de [Responsabilidades do Pupilo](https://github.com/training-center/mentoria/blob/master/pupilos/responsibility.md)!! :smile:

**Comment by Josue23** [comment]
:+1:

**Comment by woliveiras** [comment]
@Josue23 pretende focar em alguma linguagem específica?

**Comment by Josue23** [comment]
@woliveiras estou de coração aberto pra Python, JS ou PHP.

**Comment by danilovaz** [comment]
Algum dos novos @training-center/mentors consegue ajudar esse jovem?

**Comment by Josue23** [comment]
@woliveiras, @danilovaz 
O que eu posso fazer pra tornar o meu perfil no GitHub melhor?
Estou estudando bastante Django e JS
https://github.com/Josue23?tab=repositories

**Comment by danilovaz** [comment]
@Josue23 Melhor em que sentido? Se estiver perguntando para se tornar um dev melhor, foque em estudar o que você gosta e se identifica. Não importa se você commita todos os dias, isso é quase irrelevante. O importante é qualidade do que você faz. Estude, se dedique e aprenda com calma que já é metade do caminho :smile:

Algum @training-center/mentors que manja de JS e/ou Python para ajudar nosso amigo?

**Comment by Josue23** [comment]
Estou me dedicando @danilovaz, valeu pela dica. :)
É importante receber dicas como essa tua.

Abs!

**Comment by danilovaz** [comment]
@Josue23 Show, vi os commits que você fez de lógica JS e algoritmo. Maneiro, melhor forma de aprender é praticando mesmo. Sucesso aí :smile:

**Comment by Josue23** [comment]
Énois mano @danilovaz !!
Vou ficar bom nessa bagaça pra colaborar com a comunidade.

**Comment by woliveiras** [comment]
Estamos com todos os Mentores e Mentoras ocupados no momento, adicionei a label `wait for new mentors` para que os próximos busquem por essas issues primeiro.

**Comment by diegoponciano** [comment]
@Josue23 Eu trabalho com Django e manjo um pouco de javascript, posso ser seu mentor

**Comment by Josue23** [comment]
@diegoponciano eu aceito, o meu Telegram é @josue_rodrigues

**Comment by diegoponciano** [comment]
@Josue23 te mandei mensagem lá!

**Comment by danilovaz** [comment]
Olá pessoal!

Legal que estão se ajeitando nisso.

Não esqueçam de atualizar ou criar seus perfis no [repositório](https://github.com/training-center/mentoria/blob/master/helpers/README.md) e entrar no nosso [Slack](https://ctgroups.herokuapp.com/).

Assim que fizerem isso, me avisem aqui na issue para fechá-la.

**Comment by Josue23** [comment]
Bom dia @danilovaz e @diegoponciano, eu criei o meu perfil de pupilo,adicionei na lista de pupilos e fiz o PR do mesmo. :)

**Comment by danilovaz** [comment]
Perfil do pupilo criado em #331 e #332. Aguardando mentor @diegoponciano atualizar o seu perfil para fechar a issue. Sucesso pessoal :tada:

**Comment by Josue23** [comment]
Obrigado @danilovaz!
Vou me esforçar bastante :)

**Comment by woliveiras** [comment]
Fala galera, estou fechando a issue por tempo sem interação.
