### ISSUE TITLE
Preciso de um(a) mentor(a) Desenvolvimento Front-End/carreira

### ISSUE THREAD

**Issue by DaniloAgostinho** [training-center/mentoria#188]
Salve rapaziada!

Estou precisando de um norte sobre carreira Front-end, tenho 25 anos, trabalhei em uma agência apenas 45 Dias, agora estou estudando/praticando para me recolocar no Mercado, amo de mais desenvolvimento - preciso de um Mentor(a) - que possa me ajudar a criar um plano de estudos, estou perdido quando o assunto é entrevistas de emprego, dicas de vocês cairiam muito bem \o/.

Gostaria de aprender na pratica, a relacionar MYSQL, ou outra linguagem de banco de Dados com uma aplicação real. 

Jquery, Angular, ou React, - é sempre bem vindo....

Como citei, estou aberto a criar junto com o meu futuro mentor(a), um plano de estudo bacana p/ aperfeiçoamento das tecnologias. Preciso aprimorar meus conhecimentos nas tecnologias que já conheço, e também desejo aprender novas tecnologias para me recolocar nesta Área.
 
Aguardo ai, uma boa alma, kkk

**Nome:** Danilo Agostinho 
**Nível de conhecimento atual:** HTML, CSS e JS intermediário
**Contatos:** daniloagostinhosilva@gmail.com

**Comment by woliveiras** [comment]
Bem vindo @DaniloAgostinho 

Vamos ver se algum dos @training-center/mentors consegue te ajudar.

**Comment by DaniloAgostinho** [comment]
@woliveiras na espera \o/

:D

**Comment by WendellAdriel** [comment]
Olá @DaniloAgostinho, se quiser dar uma olhada em meu perfil de mentor para ver se gosta e se eu poderei te ajudar, ficarei feliz caso possa ajudar em algo.

No meu perfil não está falando, mas atualmente moro em Lisboa/Portugal, então meu horário é um pouco diferente do de vocês, mas mesmo assim posso ajudar bastante.

Podemos elaborar planos de estudo para você, vou acompanhar com atividades que irei passar, corrigir, etc. Tenho bastante experiência com processos seletivos também, até palestrei sobre carreira na LaraConf Brasil.  
  
Como canais de comunicação, prefiro utilizar Slack/Telegram. Fico no aguardo. Abraços!

**Comment by DaniloAgostinho** [comment]
Olá @WendellAdriel, eu aceito ser seu pupilo mesmo tendo diferença de fuso horário. Creio que vamos aprender bastante um com o outro. 

Os canais de comunicação são  adequados para mim, e irei me aprofundar ao máximo nas atividades que você me passar, com a intenção de aprimorar ainda mais o meu conhecimento. 

Assim que puder, me chame pelo Slack/Telegram para iniciarmos nosso estudo, vou deixar meu e-mail para contato: daniloagostinhosilva@gmail.com 

Fico no aguardo. Abraços!

**Comment by WendellAdriel** [comment]
@DaniloAgostinho combinado, irei te chamar no Slack então para iniciarmos uma conversa e começar a montar seu plano de estudos. Se não me engano agora o @DaniloAgostinho precisa criar/atualizar o perfil de pupilo dele e eu o meu de mentor correto @woliveiras???

**Comment by DaniloAgostinho** [comment]
@woliveiras eu que dou um close nessa issue, ou vcs dai? 

nois!

**Comment by woliveiras** [comment]
Isso mesmo @WendellAdriel 

Fechamos somente depois de atualizar tudo no repositório @DaniloAgostinho 😄

**Comment by DaniloAgostinho** [comment]
@woliveiras falta algo pra mim terminar?

**Comment by DaniloAgostinho** [comment]
@woliveiras atualizar!

**Comment by DaniloAgostinho** [comment]
@woliveiras estive analisando aqui e acho que não existe mais pendencias para atualizar. Você pode dar fechar a issue? 

To me precavendo pra não perder meu Mentor. 😄

**Comment by woliveiras** [comment]
KKKKKKK

Não perde mais não @DaniloAgostinho! :joy: :joy: :joy: 

Obrigado pelo alerta e qualquer coisa é só chamar no Slack.
