### ISSUE TITLE
Preciso de um(a) mentor(a) de desenvolvimento Fullstack (Front-end/Back-end)

### ISSUE THREAD

**Issue by igoralvess** [training-center/mentoria#189]
Ola,
Eu procuro um mentor que me ajude a estudar e produzir o necessário para trabalhar como freela daqui alguns meses. Caso algum mentor esteja empreendendo algum projeto ou ideia eu gostaria muito de participar também aumentando meu conhecimento e ajudando na medida do possível.

Estou cursando Ciência da Computação na UFG e atualmente trabalhando em uma empresa como estagiário. Não tenho profundidade em nenhum assunto, gosto de desenvolvimento em geral, o que toparem me orientar eu vou estudar!

Igor Alves
igoralvess@gmail.com

**Comment by woliveiras** [comment]
Bem vindo @igoralvess 

Vamos ver se algum dos @training-center/mentors consegue te ajudar.

**Comment by WendellAdriel** [comment]
Olá @igoralvess, se quiser dar uma olhada em meu [perfil de mentor](https://github.com/training-center/mentoria/blob/master/mentores/perfis/wendell_adriel.md) para ver se gosta e se eu poderei te ajudar, ficarei feliz caso possa ajudar em algo.  
  
No meu perfil não está falando, mas atualmente moro em Lisboa/Portugal, então meu horário é um pouco diferente do de vocês, mas mesmo assim posso ajudar bastante.  
  
Podemos elaborar planos de estudo para você, vou acompanhar com atividades que irei passar, corrigir, etc. Como canais de comunicação, prefiro utilizar Slack/Telegram. Fico no aguardo. Abraços!

**Comment by igoralvess** [comment]
@WendellAdriel, seria um prazer ter você como mentor!
Utilizo tanto telegram quanto slack, e acredito que a diferença de horário não irá atrapalhar nossas atividades!

**Comment by WendellAdriel** [comment]
@woliveiras pode fechar essa issue

**Comment by woliveiras** [comment]
Perfeito @WendellAdriel
