### ISSUE TITLE
Preciso de um Mentor para Desenvolvimento Web

### ISSUE THREAD

**Issue by AlexBarazal** [training-center/mentoria#19]
## Meu Nome

Alex Santana Barazal

## Qual meu sonho na carreira?

Quero me aperfeiçoar até estar apto como gerente de projetos mais no momento
busco oportunidade em desenvolvimento Web. É uma orientação quais linguagens 
deveria me dedicar mais para buscar produtividade e performance. 

## Conhecimentos
    Conheço diversas linguagem como Java, JavaEE, C#, PHP, Android, CSS, Javascrit, html5 entre outras mais meus conhecimentos acadêmicos estou fazendo diversos cursos aleatórios, mais busco desenvolver meus conhecimentos direcionando para web e mobile. 
     Atualmente estou desenvolvendo um projeto com outros alunos para desenvolver nossas habilidades como desenvolvedor mais a grande dificuldade e não conhecer o ambiente real de produção, gostaria através desse projeto orientação para me desenvolver profissionalmente e também partilhar esse conhecimento.
       Estou aberto para qualquer esclarecimento e duvidas.

## Alguns links para me conhecer melhor

[Facebook do Alex Santana Barazal](https://www.facebook.com/alex.santanabarazal)
[Twitter do Alex Santana Barazal](https://twitter.com/_LastResort)
[LinkedIn do Alex Santana Barazal](https://br.linkedin.com/in/alex-santana-barazal-0938a821)
[GitHub do Alex Santana Barazal](https://github.com/AlexBarazal)
```
------------------------------------------------------------
Parabéns pela Iniciativa do Centro de Treinamento.
Espero mais para frente esta ajudando como mentor.

**Comment by dorianneto** [comment]
Olá @AlexBarazal, gostaria de poder te ajudar nessa caminhada.

Da uma olhadinha no [meu resumo](https://github.com/training-center/mentoria/blob/master/mentores/perfis/dorian_neto.md) :)

**Comment by AlexBarazal** [comment]
Que ótimo resposta muito rápida.!
Gostei bastante.

Já tinha visto seu perfil e tinha me indentificado muito com objetivos que busco.
Obrigado por fazer parte do projeto essas iniciativas ajudam muito quem está començando,

Agora por onde começamos.?

**Comment by dorianneto** [comment]
Fico feliz por você ter se identificado comigo e pela sua clara vontade de crescer profissionalmente!

De acordo com a área que explica o [funcionamento da mentoria](https://github.com/training-center/mentoria#como-funciona), ela é feita através das issues, ou seja, podemos nos falar por aqui. 

Acho legal esse método pois fica registrado suas dúvidas, dificuldades etc para que alguém que se identifique com isso possa ter um caminho/resposta. Mas se você quiser algo mais reservado, podemos nos falar através de email, messenger etc. Fica a seu critério.

**Comment by AlexBarazal** [comment]
Acho bom ser por aqui que fica registrado para outras pessoas entenderem como funciona o projeto, mais vou adicionar Linkedin se não se importa, pois busco oportunidade de trabalho na aréa sou Gerente mais em outro ramo.

**Comment by dorianneto** [comment]
Massa!

Primeiro passo agora é você ler as responsabilidades de um pupilo e criar um PR para adicionar seu perfil na lista de pupilos. Tem tudo nesse [link](https://github.com/training-center/mentoria/blob/master/pupilos/responsibility.md) caso tenha dúvida.

Depois disso é só mandar ver!

obs: já te aceitei no linkedin ;)

**Comment by AlexBarazal** [comment]
Vou atualizar o perfil.

**Comment by AlexBarazal** [comment]
Já atualizei agora só aguardando o aceitarem a atualização.

**Comment by dorianneto** [comment]
Massa!

Vamos aguardar agora a aprovação pra que tudo fique documentado :)

**Comment by woliveiras** [comment]
Valeu @dorianneto. Bem vindo @AlexBarazal! :smile:

**Comment by AlexBarazal** [comment]
Obrigado.!

**Comment by dorianneto** [comment]
Pronto @AlexBarazal, agora estamos prontos para começar ;)

**Comment by AlexBarazal** [comment]
Pronto. 
No horário comercial não fico no computador acesso algumas coisas no celular mais fazer as tarefas e ver os conteúdos normalmente a noite na faculdade ou quando chego.
Mais pode ter certeza que vou me dedicar bastante.

**Comment by dorianneto** [comment]
Massa :)

Estou sempre de olho nas notificações do github e farei o possível pra sempre responder o mais rápido possível.

Atualmente ta cursando o que?

**Comment by AlexBarazal** [comment]
Analise de Sistemas, 4º Ciclo. Atualmente estou estudanda javascript, php, css, html 5 e tudo relacionado a web. Mais estou meio perdido estudando muito e não usando nada.

**Comment by dorianneto** [comment]
Massa.

No início é normal querer abraçar o mundo com as pernas e no final acabar não conseguindo fazer nada. De vez em quando eu ainda faço isso :P

Antes de comentar sobre estilos de estudo, grau de priorização etc, gostaria de fazer uma pergunta pra entender melhor seu perfil, expectativas, etc.

Vi que você pretende se qualificar para se tornar um bom gerente de projetos, porém, agora quer focar em desenvolvimento web. Gostaria que você explicasse melhor seu plano de carreira.

**Comment by AlexBarazal** [comment]
Gosto muito da parte administrar projeto, lidar com pessoas, buscar soluções novas metodos e coisas deste tipo. Porem estou tendo nuita dificuldade para comecar a trabalhar na area de TI. Então quero focar em web para caso nao consiga entrar em uma empresa que me ofereça algo do meu interresse posso ganhar experiencia em clientes menores(que eu mesmo posso conseguir) e assim evoluindo com negocio proprio.

**Comment by AlexBarazal** [comment]
Precisa saber mais algo.?

**Comment by dorianneto** [comment]
Entendi.

Trabalhar com desenvolvimento web é uma ótima forma de se inserir no mercado de TI. Vagas tem de sobra, as possibilidades de trabalho são inúmeras e é ótimo pelo fato de que você vai adquirir um ótimo conhecimento na área para no futuro gerenciar esses profissionais. Isso é muito massa e fico feliz em ver que você, de certa forma, possui essa preocupação de começar pela áera pois nada melhor do que um gerente de projetos que entenda todo o processo de trabalho e dia a dia de quem ele vai gerenciar.

Mas de agora em diante, vamos focar no desenvolvimento web.

Você falou que está com algumas dificuldades nos estudos, acredito que seja pelo fato de não ter um rumo bem definido na sua cabeça do que precisa estudar para entrar no mercado de trabalho.

Primeiro quero falar um pouco sobre metodologias de estudo. Como você estuda?

Há uns 2 anos atrás, conheci um brother que mandava muuuuito no frontend, e o cara tinha uma metodologia bastante interessante de estudar. Toda tecnologia nova que ele ia aprender, ele criava um guia/tutorial sobre o que ele estava estudando. Primeiro ele separava os tópicos que iria estudar em um documento word no drive, depois ele criava desafios para fazer dentro de cada tópico e só depois ele começava a estudar. Durante o estudo ele fazia anotações em cada tópico e realiza seus respectivos desafios, como se estivesse escrevendo um tutorial para ensinar alguém.

Acho sensacional a forma que ele encontrou de aprender. Cada um utiliza métodos que melhor se adequa ao estilo de aprendizado que foi aprendido no decorrer da vida, mas nada nos impede de tentar outros estilos. Lembre-se de sempre estar com a cabeça aberta pra tudo e seja humilde, pois como disse Shunryu Suzuki:

> “Há muitas possibilidades na mente do principiante, mas poucas na do perito.”

E por fim, vi que você está envolvido em alguns projetos com seus colegas da faculdade. Se não se importa, o que vocês estão desenvolvendo? Quais as tecnologias? Qual seu papel no projeto? O grupo visa apenas estudo ou estão criando um produto?

**Comment by AlexBarazal** [comment]
Como estudo?
R. Primeiro busco conhecer o que é, para que serve, onde é usado, quem está usando se acho valido estudar busco cursos online, que vou acompanhado fazendo os exemplos.
Mais gostei da metodologia do seu amigo.
Na verdade eu queria aprender muita coisa e rápido para saber o que eu realmente queria praticando um pouco então meu estudo foi um tanto quanto aleatório. Mais me identifiquei muito com web e ultimamente estou mais focado.

Meu projeto, a ideia é uma aprender praticando criar projetos sociais que ajudem o dia a dia da comunidade e aprendendo a trabalhar. Ou seja aprender fazendo e ganhar experiencia em troca ou criar uma plataforma de conhecimento continuo passando para novos membros. Ajudando o próximo e adquirindo conhecimento.
Eu sou 'presidente' pois a ideia foi minha e alguns amigos compartilham do meu ideal estão ajudando mais está no começo.

**Comment by AlexBarazal** [comment]
Estamos desenvolvendo a pagina com HTML, CSS, Bootstrap, PHP, javascript mais ou menos isso.

**Comment by AlexBarazal** [comment]
E como funciona o processo de treinamento? 
E como se fosse estagiário em uma empresa.?

**Comment by dorianneto** [comment]
Muito bom saber que você possui critérios para iniciar os estudos em algo e principalmente que você está focado, acho que isso é o essencial para se iniciar em qualquer área. Quando estiver um pouco perdido com relação a quais tecnologias estudar, me fala que a gente tenta encontrar um caminho :)

Com relação ao seu projeto, gostei bastante da ideia. A forma mais rápida de se aprender é passando conteúdo para os outros, e vejo que você já faz isso. Conhecimento não se deve ser guardado e sim compartilhado!

Quando você fala do processo de treinamento você quer saber de uma forma geral ou de algum em específico?

**Comment by AlexBarazal** [comment]
Assim como vejo diversos profissionais disponibilizando seu tempo material para que eu possa aprender, também acredito que devo manter esse padrão e o incrivel que quando vc pensa que esta ensinando algo aprende outras milhares de outras coisas.
Esse projeto e centro de treinamento, você e meu mentor. Gostaria de saber como será esse treinamento você mais me passar alguma tarefa e vou te mandando ou eu estudo por conta e você vai me orientando. ???

Ou e como se fosse estagio você me passa a tarefa e vou desenvolvendo e tirando as duvidas. ???
O se for de outra forma gostari de saber.

**Comment by dorianneto** [comment]
Nesse link você pode ler sobre o que é o [centro de treinamento](https://github.com/training-center/sobre).

Dentre as diversas iniciativas do projeto, essa que estamos desenvolvendo pouco a pouco é a de mentoria. Meu foco principal é te orientar passando meus conhecimentos de vida, adquiridos nesses anos de trabalho e de vida, para que você possa enfrentar as adversidades com mais naturalidade e conquiste uma carreira de sucesso naquilo que você escolheu.

Caso sua dúvida seja mais urgente e técnica, temos também um [grupo de estudos](https://github.com/training-center/study-groups) onde tem uma galera bem bacana que pode te ajudar com mais rapidez!

Lembrando que não estou dizendo que não podemos falar sobre assuntos técnicos, porém, abordaremos os temas com uma forma mais crítica do que técnica.

**Comment by AlexBarazal** [comment]
Tinha entendido de uma forma diferente, mais o que me sugere para desenvolver o que ja aprendi?
O como devo me preparar para entrar no mercado de trabalho.?

**Comment by dorianneto** [comment]
Sei que nessa hora todo mundo procura por respostas rápidas e que solucionem o problema, mas vamos por partes :)

Primeiramente, é de total importância que você faça uma analise profunda a respeito de que tipo de desenvolvedor você quer se tornar (back-end, front-end ou full stack). Sei que não é uma decisão fácil, principalmente no começo da carreira, e também pode ter certeza de que essa não será a decisão definitiva. Conheço vários desenvolvedores que começaram como front-end e hoje em dia são apaixonados por back-end. Acho super importante você refletir sobre isso nesse início pois dessa forma você conseguirá manter o foco em uma área.

Após essa reflexão, vamos conversar um pouco mais sobre as tecnologias e alguns métodos que possam melhorar seu crescimento profissional e o aprendizado.

**Comment by AlexBarazal** [comment]
Eu quero se tornar um desenvolvedor full stack, acredito que é uma linha mais complexa, mais procuro ser um profissional completo e dessa forma no futuro irá me ajudar como gerente.
Você usa SLACK ?
Se sim poderiamos criar um time para conversamos para ter um feed back mais rápido o que você acha.?

**Comment by dorianneto** [comment]
Alex, o que você acha de conversarmos através do messenger do Facebook? Acho que a comunicação ficaria ainda mais rápida :)

**Comment by dorianneto** [comment]
@woliveiras pode encerrar a issue, estamos nos falando pelo messenger ;)

**Comment by woliveiras** [comment]
Opa! Show de bola @dorianneto

**Comment by CarlosHenrique2** [comment]
como faço para participar?
