### ISSUE TITLE
Quero ser mentor de desenvolvimento Full Stack.

### ISSUE THREAD

**Issue by alexjunior012** [training-center/mentoria#191]
## Nome:
Alex Junior

## Perfil:
Meu nome é Alex Junior, trabalho atualmente como Analista Programador PHP, mas na verdade atuo como full stack.
Possuo 4 anos de experiencia com desenvolvimento, mesclando front-end com back-end. Estou cursando 7º semestre de Ciência da Computação e gostaria de ser mentor  para poder retribuir o conhecimento que adquiri nas minhas experiencias e com outras pessoas, também por que ao ensinar você acaba aprendendo, bom é isso.

## Contatos:
* [Facebook](https://www.facebook.com/alexjunior012)
* [Twitter](https://twitter.com/alexjunior012)
* [Google+](https://plus.google.com/+AlexJunior012)
* [Linkedin](https://br.linkedin.com/in/alexjunior012)
* alexjunior.web@gmail.com

**Comment by woliveiras** [comment]
Faaala @alexjunior012

Você já leu as [Responsabilidades do Mentor]((/mentores/responsibility.md)) e está de acordo com a ideia do projeto?

**Comment by alexjunior012** [comment]
Eae @woliveiras  já li sim e estou de acordo com a ideia do projeto.

**Comment by woliveiras** [comment]
\o/

Perfeito cara! Então é só esperar o pessoal dos @training-center/mentors responderem.

**Comment by alexjunior012** [comment]
Ok, valeu!

**Comment by woliveiras** [comment]
Fala @alexjunior012 

Pode criar seu perfil cara.

Alguma dúvida sobre o processo de criação do perfil?

**Comment by alexjunior012** [comment]
Fala @woliveiras, é só criar meu perfil na lista de de mentores full-stack, certo?

**Comment by woliveiras** [comment]
Isso mesmo @alexjunior012 

E depois atualizar na lista principal do /mentores

**Comment by alexjunior012** [comment]
Ta feito @woliveiras, obrigado.
