### ISSUE TITLE
Preciso de um(a) mentor(a) de Desenvolvimento Front-end/Python

### ISSUE THREAD

**Issue by danlaurent** [training-center/mentoria#192]
Olá, me chamo Daniel e preciso de um mentor de Desenvolvimento Front-end/Python.

Sou formado em Design, possuo experiência de 4 anos na área, passando por diversas funções, desde criação de layouts e diagramação até desenvolvimento de produtos.

Sempre tive interesse pela área de programação/desenvolvimento, e após me formar em Design, comecei a estudar para poder "migrar" para a área de desenvolvimento mesclando meus conhecimentos em Design.

Estou trabalhando como Desenvolvedor Front-end faz 3 meses, porém estou estudando desde o começo do ano, investí em alguns cursos presenciais (HTML5, CSS3 e JS) e fiz diversos cursos online, e nesses cursos me interessei muito por Python.

A empresa onde eu trabalho é muito focada em PHP, e muito serviço em back-end, então estou sentindo que estou me desenvolvento muito lentamente na área de front. Portanto gostaria de uma mentoria que me desse um norte para conseguir me desenvolver profissionalmente.

Conhecimentos: HTML5, CSS3 e JS intermediários, Python e Django básicos, PHP básico.
Frameworks: Bootstrap, PureCSS, AngularJS básico, React básico, Laravel intermediário.

Contatos:

E-mail: daniel.s.laurent@gmail.com
Twitter: https://twitter.com/_Dlaurent
Behance: https://www.behance.net/danlaurent

**Comment by danilovaz** [comment]
Bem vindo @danlaurent !

Vamos ver se algum dos @training-center/mentors consegue te ajudar.

Só para ficar mais claro, você pretende focar mais no Front e aprender mais sobre Python, correto?

Enquanto isso leia o documento de [Responsabilidades do Pupilo](https://github.com/training-center/mentoria/blob/master/pupilos/responsibility.md)!! :smile:

**Comment by danlaurent** [comment]
Obrigado @danilovaz !

Sim, isso mesmo, preciso focar no Front e desejo aprender mais sobre Python, com foco em web também! 

:)

**Comment by danilovaz** [comment]
@danlaurent Legal! Vamos aguardar para ver se algum mentor pode te ajudar nisso :smiley: :tada:

**Comment by raymonsanches** [comment]
@training-center/mentors alguém? 

=)

**Comment by woliveiras** [comment]
Estamos com todos os Mentores e Mentoras ocupados no momento, adicionei a label `wait for new mentors` para que os próximos busquem por essas issues primeiro.

**Comment by ftonato** [comment]
Fala @danlaurent, como está o andamento dessa _issue_?
- [ ] Encontrou o mentor?
- [ ] O mentor entrou em contato com você?

/cc @training-center/mentors

**Comment by woliveiras** [comment]
@danlaurent nosso processo mudou: https://medium.com/trainingcenter/e-o-mentoria-mudou-mais-uma-vez-5ad8725bc778

Peço, por favor, que responda esse formulário, se ainda fizer sentido, para que algum mentor ou mentora entre em contato contigo quando possível: http://bit.ly/preciso-de-mentoria

A issue será fechada para que não aconteçam desencontros de informação.
