### ISSUE TITLE
Preciso de um(a) mentor(a) sobre desenvolvimento Front-end

### ISSUE THREAD

**Issue by marcosabb** [training-center/mentoria#193]
Oe :)

Me chamo Marcos, tenho 18 anos e preciso de um(a) mentor(a) que me ajude a evoluir no frontend.

Eu sei HTML, CSS e JS. Tenho um conhecimento básico em Angular, Stylus e Gulp.

O que eu gostaria de saber hoje: Angular (estudando), ES6.

O que eu gostaria de saber no futuro: Ruby e Node.js.

Bom, eu sinto que ainda não tenho um conhecimento sólido na parte de frontend. Muitas vezes me pego desistindo de pequenos projetos no meio do caminho, pois tem uma hora que trava, não consigo progredir, acho que tenho que aprender mais... Meu "sonho" é um dia, conseguir desenvolver um site completo, do início ao fim, mesmo que só a parte de frontend.

Gostaria de um mentor para me dizer onde tenho que melhorar, o que devo aprender.

Estou aberto a aprender novas coisas.

Contato:

[Facebook] (https://www.facebook.com/Marcos.abb10)
[Email] (mailto:marcos.abb52@gmail.com)
[Github] (https://github.com/marcosabb)
[Codepen] (http://codepen.io/marcosabb/)

Obrigado! :smile:

**Comment by danilovaz** [comment]
Bem vindo @marcosabb !

Vamos ver se algum dos @training-center/mentors consegue te ajudar.

Enquanto isso leia o documento de [Responsabilidades do Pupilo](https://github.com/training-center/mentoria/blob/master/pupilos/responsibility.md)!! :smile:

**Comment by marcosabb** [comment]
@danilovaz Esperarei! :smile:

**Comment by guilhermepontes** [comment]
@marcosabb tudo bem jovem?
Nós temos uma diferença de time-zone de 4h, mas consigo te ajudar. Me avise se te interessar! :)

**Comment by danilovaz** [comment]
@marcosabb Pô, que legal! O @guilhermepontes tem uma experiência bem foda, veja se o perfil dele condiz com o que você precisa e sucesso :tada:

**Comment by marcosabb** [comment]
@guilhermepontes Tenho MUITO interesse! :smile:

**Comment by guilhermepontes** [comment]
@marcosabb beleza, já coloquei você num grupo privado lá no Slack. 👍

**Comment by guilhermepontes** [comment]
cc: @training-center/moderators #229

**Comment by danilovaz** [comment]
Agora é só atualizar o perfil do mentor @guilhermepontes para fecharmos essa issue e partir para o abraço :heart: :tada: :beers:

**Comment by danilovaz** [comment]
Perfil do Mentor atualizado: #244 sucesso pessoal :tada:
