### ISSUE TITLE
Preciso de um(a) mentor(a) de desenvolvimento Fullstack (Front-end/Back-end)

### ISSUE THREAD

**Issue by teteusix** [training-center/mentoria#194]
**Nome:** Matheus Ramos

**Descrição:** Sou desenvolvedor frontend desde de 2011 e nos ultimos 3 anos com foco em e-commerce.
Estou indo em breve para a Alemanha tentar a vida, buscando trabalhar na area e queria deixar de ser frontend apenas e ser um bixão, vulgo Fullstack. Queria aprender mais de frontend e entrar mais a fundo no backend.

**Objetivo:** Foco em criar aplicações e jogos. Também com foco em trabalhos sociais.

**Nível de conhecimento atual:**
- Intermediário
  > Css/ Css3, Html/ Html5, Javascript, Semantica, Seo, Ui/Ux, Git, Jquery, Less, Sass
- Basico
  > Php e Python 

**Contatos:**
- Facebook: [teteusix](https://www.facebook.com/teteusix)
- Twitter: [@teteusix](https://twitter.com/teteusix)
- Github: [@teteusix](https://github.com/teteusix)
- LinkedIn: [matheusramos](https://br.linkedin.com/in/matheusramos)
- Skype: [matheus.hf.ramos](skype:matheus.hf.ramos?call)
- E-mail: [matheus.hf.ramos@gmail.com](mailto:matheus.hf.ramos@gmail.com)

**Comment by danilovaz** [comment]
Bem vindo @teteusix  !

Vamos ver se algum dos @training-center/mentors consegue te ajudar.

Enquanto isso leia o documento de [Responsabilidades do Pupilo](https://github.com/training-center/mentoria/blob/master/pupilos/responsibility.md)!! :smile:

**Comment by matmarsiglio** [comment]
@teteusix tu é de Marechal Candido Randon, a terra do Wilmutt!!!!!!! Cacete, que coisa incrível! hahaha

Eu estou bem envolvido com o mundo de Full Stack e tenho bom conhecimento em programação que poderiamos fazer uns estudos massas! [Eis meu perfil](https://github.com/training-center/mentoria/blob/master/mentores/perfis/matheus_marsiglio.md). Se achar que me enquadro no que procura, me disponho! 💃

**Comment by danilovaz** [comment]
Aí sim ein!

O @matmarsiglio tem uma bagagem de conhecimento muito foda e é uma excelente pessoa, veja se o perfil dele bate com seus objetivos, @teteusix !

Ps: Acredito que não haja problema se não for palavrão de forma exagerada ou ofendendo alguém. Só usar com moderação :laughing:

**Comment by woliveiras** [comment]
Só não pode ofender o peão, @matmarsiglio, de resto... kkk 😂

**Comment by teteusix** [comment]
@matmarsiglio acredito que seu perfil se enquadra nos meus objetivos sim! :)

Willmutt Tas Tores Tos Praceres era daqui sim, que pena que se foi :/

**Comment by danilovaz** [comment]
Legal, pessoal! :smile: 

Assim que estiverem conversados e alinhados, subam/atualizem os perfis de vocês e avisem nessa issue para fechá-la e sucesso :tada:

**Comment by matmarsiglio** [comment]
@teteusix show, cara! Crie seu perfil e abra o PR pra galera aí, eu ja ja atualizo meu perfil te colocando lá e aí fechamos essa issue! Abs!

**Comment by danilovaz** [comment]
@teteusix @matmarsiglio Alguma novidade sobre isso, galera? Se precisarem de algo, é só falar.

**Comment by teteusix** [comment]
Desculpem a demora, estava na correria da viagem e cheguei recentemente em Berlim. Até amanhã a noite daqui (umas 18h daí) faço as solicitações pedidas. Estou correndo atras de apartamento e etc...

Mais uma vez, desculpe a demora!

**Comment by danilovaz** [comment]
Tranquilo, @teteusix ! Era só para saber como está o andamento. Sucesso :tada:

**Comment by danilovaz** [comment]
Pessoal, como já passou mais de 12 dias, estou fechando essa issue. Qualquer coisa, me avisem.
