### ISSUE TITLE
Preciso de um(a) mentor(a) de desenvolvimento Back-end(PHP)

### ISSUE THREAD

**Issue by rpaggi** [training-center/mentoria#195]
**Nome:**

Ronaldo Paggi

**Descrição:**

Quero aprimorar meus conhecimentos com PHP para elevar meu nível de 0,5 a mais de 9000!!! 
Atualmente ganho o pão como desenvolvedor Cobol, mas já uso PHP desde 2009, mas nunca usei profissionalmente, na maioria das vezes sempre mexendo com sistemas de fórum(Invision Power Board e PHPBB), uma unica vez com Drupal e uma unica vez com Magento. Fiz o site do meu casamento(preciso achar o fonte dele) em PHP, com lista de confirmação de convidados e banco de dados MYSQL.
Então a minha idéia é saber quais caminhos devo seguir para aos poucos migrar de área e conseguir quem sabe um trampo remoto(meu sonho)

**Nível de conhecimento atual:**

Estagiário Pleno

**Contatos:**

[Twitter](https://twitter.com/rpaggi)

**Comment by woliveiras** [comment]
Bem vindo @rpaggi 

Estagiário Pleno é lokura! :joy: :joy: :joy: 

Vamos ver se alguém dos @training-center/mentors consegue te ajudar a estudar esse PHP ai.

Enquanto isso leia o documento de [Responsabilidades do Pupilo](https://github.com/training-center/mentoria/blob/master/pupilos/responsibility.md)

**Comment by raymonsanches** [comment]
Olá @rpaggi posso seu mentor, com grande prazer.

Dá uma checada no meu perfil lá ;) - https://github.com/training-center/mentoria/blob/master/mentores/perfis/raymonsanches.md

**Comment by rpaggi** [comment]
Oi @raymonsanches vamos prosseguir.

**Comment by woliveiras** [comment]
:raised_hands: :raised_hands: 

Assim que possível é só subir/atualizar os perfis de vocês.

**Comment by woliveiras** [comment]
Fala pessoal, como a issue já passou de 10 dias, estou fechando ela. 

Qualquer problema é só avisar.

Abraços!
