### ISSUE TITLE
Preciso de um mentor em back-end em Python, Node.Js, Ruby.

### ISSUE THREAD

**Issue by felipepatricio** [training-center/mentoria#196]
Felipe Alves Patricio
Graduando em Analise e Desenvolvimento de Sistemas
Iniciante
alvespatriciofelipe@gmail.com 
https://www.linkedin.com/in/felipe-patricio-748968112

**Comment by woliveiras** [comment]
Bem vindo @felipepatricio!

Você gostaria de aprender alguma dessas tecnologias em específico?

**Comment by woliveiras** [comment]
Como a issue não teve mais atualização, está sendo fechada.

Qualquer coisa basta nos avisar que reabrimos.
