### ISSUE TITLE
Preciso de um(a) mentor(a) de desenvolvimento Back-End

### ISSUE THREAD

**Issue by marcoweb** [training-center/mentoria#198]
**Nome:** Marco Antônio Gusmão Carvalho
**Descrição:** Sou professor de programação (php e asp.net) e atuei em pequenos projetos como freelancer nas linguagens citadas, entretanto busco entrar no mercado de desenvolvimento, sendo que Java tem se demonstrado a mais promissora na região em que atuo, entretanto estudo diversas tecnologias como Python, Javascript e Typescript.
**Nível de conhecimento atual:** Tenho maior conhecimento em desenvolvimento web utilizando PHP e ASP.Net e, sendo amante de Linux, me empolguei bastante com o ASP.Net Core, visto que já tenho experiência no desenvolvimento na plataforma da Microsoft, mas tenho estudado bastante de JSP, JSF e Python.
Contatos: marcocarvalho.web@gmail.com

**Comment by danilovaz** [comment]
Bem vindo @marcoweb !

Vamos ver se algum dos @training-center/mentors consegue te ajudar.

Você citou conhecimentos em PHP e ASP.net, interesse por JAVA e que está estudando Python. Para ficar mais claro, um mentor ideal para você deve ter conhecimentos em quais dessas linguagens?

Enquanto isso leia o documento de [Responsabilidades do Pupilo](https://github.com/training-center/mentoria/blob/master/pupilos/responsibility.md)!! :smile:

**Comment by marcoweb** [comment]
Meu principal interesse no momento é JEE.

**Comment by danilovaz** [comment]
@marcoweb Legal, vamos aguardar para ver se algum Mentor consegue te ajudar :smile:

**Comment by danilovaz** [comment]
Cadê os Javeiros, para ajudar nosso amigo? @training-center/mentors

**Comment by woliveiras** [comment]
@marcoweb compartilhe essa issue nas comunidades de Java e informe que estamos precisando de Mentores com experiência na linguagem. 

Talvez já ache alguém pra te ajudar e já aumenta a quantidade de Mentores auxiliando o projeto. :smile:

**Comment by woliveiras** [comment]
@marcoweb compartilhou nas comunidades Java? :)

**Comment by woliveiras** [comment]
Estamos com todos os Mentores e Mentoras ocupados no momento, adicionei a label `wait for new mentors` para que os próximos busquem por essas issues primeiro.
