### ISSUE TITLE
Quantidade de pessoas por mentor

### ISSUE THREAD

**Issue by woliveiras** [training-center/mentoria#2]
Issue para definir a quantidade de pupilos por Mentor.

cc: @baltazarparra @danilovaz @LFeh @JGcarv @willycamargo @icaromh @sanderweb @augustoabreu @robsonbittencourt

**Comment by woliveiras** [comment]
Aquele esquema que o @danilovaz comentou de 10 por pessoa é maneiro.

**Comment by augustoabreu** [comment]
Se o mentor julgar 10 pessoas uma quantidade muito grande para a atual condição dele, ele poderá diminuir o número de pessoas?

**Comment by woliveiras** [comment]
Seria bom mano, assim não atrapalha o cara na vida fora dos projetos Open.

Poderia ser aberto pro cara decidir quantos ele pode atender, mas com um default de 10. Que tal?

**Comment by jlamim** [comment]
Muitas pessoas ligadas a um único mentor pode gerar sobrecarga nele. Deixando aberto pra que o próprio mentor defina a quantidade acho que pode dar mais certo.

**Comment by danilovaz** [comment]
Concordo, acho que o default deve ser o que o mentor achar que pode dar conta sem prejudicar nem as pessoas que contam com ele e nem ele mesmo. Porém, acredito que deva existir um limite, de no máximo até 10 pessoas por mentor. Mais do que isso, acredito ser praticamente impossível alguém dar conta de algo que não gera renda a ele e por consequência devemos imaginar que sempre será uma das ultimas prioridades nas diversas tarefas que uma pessoa possuí no dia-a-dia.

**Comment by LFeh** [comment]
De 5 a 10 pessoas, considero o ideal.

**Comment by baltazarparra** [comment]
A gente pode deixar com o mínimo de 5 dev's por mentor, sendo que o próprio poderá aumentar isso pra até 10. Ai seria criado um gitter entre os envolvidos, e quando surgir algum tipo de discussão interessante, os mesmo podem levar isso para uma issue pública.

**Comment by woliveiras** [comment]
Da pra usar o Slack do CT também mano. Já tem tudo no esquema. :)

**Comment by baltazarparra** [comment]
Perfeito. Acho que precisamos pensar em algumas "regras" também, tipo, alguns limites, porque estamos lidando com algo muito delicado, no caso, a carreira/vida de outras pessoas, por exemplo, temos um mentor que é fanático pela ferramenta X, por conta disso, corremos o risco de perder a imparcialidade, fugindo do que é melhor para o interessado.

**Comment by woliveiras** [comment]
Booooa cara! Essa ae entra na #1 ein!

**Comment by woliveiras** [comment]
Enfatizei a quantidade em 5 e 10 pessoas [aqui](https://github.com/training-center/mentoria#quero-ser-um-mentor).

Se tudo estiver OK, podemos fechar a issue.

**Comment by danilovaz** [comment]
@woliveiras acho que essa também está OK para ser fechada.

**Comment by woliveiras** [comment]
Show mano!
