### ISSUE TITLE
Quero ser mentor de desenvolvimento back-end

### ISSUE THREAD

**Issue by vyper** [training-center/mentoria#202]
## Nome

Leonardo Saraiva

## Descrição

Tenho mais de 10 anos de experiência em desenvolvimento web; mexi profissionalmente com PHP, Java, Ruby, Python, Scala, Go, C# e as várias tecnologias e framework correlatos as linguagens anteriormente listadas.
Atualmente atuo a maior parte do tempo com desenvolvendo em Ruby, mas tenho um _background_ muito grande em integração (usando SOA e WSO2). 
Sou o mantenedor do [GURU-PR](http://gurupr.org) e o principal organizador dos eventos do grupo, além de um dos mantenedores do site.
Gostaria de retribuir um pouco a comunidade com o conhecimento que consegui adquirir e aprender nesses vários anos.

## Contatos

- [twitter](https://twitter.com/vyper)
- [facebook](https://www.facebook.com/leonardo.saraiva.169)
- [e-mail](vyper@maneh.org)

**Comment by woliveiras** [comment]
Bem vindo @vyper 

Você já leu as [Responsabilidades do Mentor]((/mentores/responsibility.md)) e está de acordo com a ideia do projeto?

**Comment by vyper** [comment]
Sim @woliveiras (:

**Comment by woliveiras** [comment]
Perfeito cara! 

Os @training-center/mentors irão avaliar seu perfil e logo te daremos uma resposta.

Valeu pelo interesse em ajudar!

**Comment by woliveiras** [comment]
@vyper pode criar seu perfil!

Assim que tiver seu perfil OK, vai receber um convite para participar da org e para entrar no canal dos Mentores no Slack.
