### ISSUE TITLE
Preciso de um(a) mentor(a) sobre Desenvolvimento Front End.

### ISSUE THREAD

**Issue by lukao98** [training-center/mentoria#204]
Olá, me chamo Lucas, tenho 18 anos.  Iniciei meus estudos web há umas semanas e gostaria de um mentor para auxílio em temas para aprofundamento, acompanhamento de progresso e para sanar dúvidas.
Conheço um pouco de HTML, CSS e comecei meus estudos em JS.

Contato:
[Facebook](https://www.facebook.com/luckagabriel)

Aguardo contato

**Comment by woliveiras** [comment]
Bem vindo(a) @lukao98 

Vamos ver se algum dos @training-center/mentors consegue te ajudar! :)

Enquanto isso leia o documento de [Responsabilidades do Pupilo](https://github.com/training-center/mentoria/blob/master/pupilos/responsibility.md).

Só cuidado com o ponto de tirar dúvidas para não criar expectativas sobre seu(sua) Mentor(a), pois ela(a) não pode ser seu Google pessoal. Ele(a) quem ajuda a aprender o que se deve procurar no Google. :smile:

**Comment by WendellAdriel** [comment]
Olá @lukao98, se quiser dar uma olhada em meu perfil de mentor para ver se gosta e se eu poderei te ajudar, ficarei feliz caso possa ajudar em algo.

No meu perfil não está falando, mas atualmente moro em Lisboa/Portugal, então meu horário é um pouco diferente do de vocês, mas mesmo assim posso ajudar bastante.

Podemos elaborar planos de estudo para você, vou acompanhar com atividades que irei passar, corrigir, etc.

Como canais de comunicação, prefiro utilizar Slack/Telegram. Fico no aguardo. Abraços!

**Comment by lukao98** [comment]
Olá, @WendellAdriel. Aceito sem dúvidas!
Sobre o horário: minha namorada atualmente está em Portugal, estou acostumado com o fuso.

Vamos acertar como e quando começar agora.
Obrigado.

**Comment by WendellAdriel** [comment]
@lukao98 ficarei feliz em ajudar. Estou indo almoçar agora, mas enquanto vou lá veja algumas coisas:
- Já está no Slack do Training Center?
- Já tem seu perfil de pupilo aqui no repo?

Se não tiver algum dos itens por favor os faça. Enquanto estou no almoço o mano @woliveiras ou outro @training-center/moderators pode te ajudar com isso. Assim que chegar te chamo no Slack para começarmos!!!

Abraços!!! :wink:

**Comment by lukao98** [comment]
Ja estou no slack, preciso arrumar o perfil de pupilo.

Poderia me ajudar, @woliveiras?

**Comment by WendellAdriel** [comment]
@lukao98 qual seu user no Slack?

Você deve fazer um fork desse repo, seguir o modelo [desse arquivo](https://github.com/training-center/mentoria/blob/master/pupilos/pupilo_template.md) e criar um perfil para você [aqui](https://github.com/training-center/mentoria/tree/master/pupilos/perfis).

Qualquer dúvida estou à disposição.

**Comment by lukao98** [comment]
Obrigado. Meu user no stack esta como lukao98 também

**Comment by WendellAdriel** [comment]
@woliveiras pode fechar essa issue

**Comment by woliveiras** [comment]
Pra já!
