### ISSUE TITLE
Quero ser mentor fullstack

### ISSUE THREAD

**Issue by luketevl** [training-center/mentoria#206]
**Nome:** Lucas Henrique
**Apelido:** Lukete
**Tempo de experiência:** 7 anos
**Linkedin:** https://br.linkedin.com/in/lucashenriqueps93
**Facebook:** https://www.facebook.com/luketevl2
**E-mail:** luketevl@gmail.com

Fiz o técnico em informática COTEMIG (concluído em 2010), logo em seguida fiz faculdade de Sistema de Informação também no COTEMIG (concluído em 2014).

**Comment by danilovaz** [comment]
Bem vindo @luketevl 

Você já leu as [Responsabilidades do Mentor](https://github.com/training-center/mentoria/blob/master/mentores/responsibility.md) e está de acordo com a ideia do projeto?

**Comment by luketevl** [comment]
Já sim, estou de acordo !

**Comment by danilovaz** [comment]
Show :smile: 

Os @training-center/mentors irão avaliar seu perfil e logo te daremos uma resposta.

Valeu pelo interesse em ajudar!

**Comment by danilovaz** [comment]
@luketevl Seu perfil foi aprovado :tada: 

Bora criar seu perfil então? Aqui tem um template para você fazer o PR do seu perfil, no padrão: https://github.com/training-center/mentoria/blob/master/mentores/mentor_template.md

Aproveita e entra lá no Slack do CT -> https://ctgroups.herokuapp.com/

Assim que subir seu perfil e entrar lá no Slack me manda uma mensagem @danilovaz lá no Slack, que eu te coloco no canal de mentores ;)

Depois é só caçar nas issues um pupilo que você possa ajudar e sucesso :beers:

**Comment by luketevl** [comment]
Muito obrigado, vou criar e fazer um pull !
Eh nois 💪🏻
