### ISSUE TITLE
Preciso de um(a) mentor(a) sobre Desenvolvimento Front-End em JS

### ISSUE THREAD

**Issue by gabrielferreiraa** [training-center/mentoria#207]
Nome: Gabriel Ferreira
Descrição: Oi pra alguém, estou em busca de um mentor para me auxiliar na minha carreira Front-End em JavaScript, trabalho como Junior atualmente na fábrica de software de uma empresa de São Paulo. Conheci o Mentoria através do podcast Devnaestrada, e busco cada vez mais fazer parte da comunidade.

Nível de conhecimento atual: Mediano, programador orientado a plugins jQuery 

Facebook: https://www.facebook.com/gabrielferreira.sap
LinkedIn: https://br.linkedin.com/in/gabrielferreira
Email: gabrielferreira.95@hotmail.com

Abraço a todos!

**Comment by danilovaz** [comment]
Bem vindo @gabrielferreiraa !

Vamos ver se algum dos @training-center/mentors consegue te ajudar a sair da orientação à plugins jQuery :smile: e que legal que você descobriu o Mentoria através do DevNaEstrada :tada: 

Enquanto isso leia o documento de [Responsabilidades do Pupilo](https://github.com/training-center/mentoria/blob/master/pupilos/responsibility.md)!! :smile:

**Comment by gabrielferreiraa** [comment]
Opa @danilovaz obrigado pelo retorno! Fico no aguardo do meu querido mentor :)

**Comment by gabrielferreiraa** [comment]
Bom dia @danilovaz , alguma novidade sobre o mentor?

**Comment by danilovaz** [comment]
Bom dia @gabrielferreiraa , agora temos que aguardar para ver se algum dos @training-center/mentors consegue te ajudar.

**Comment by wbruno** [comment]
opa! tá aqui o meu perfil:
https://github.com/training-center/mentoria/blob/master/mentores/perfis/william_bruno.md

Podemos ir nos falando via facebook messenger, hangout ou algum outro IM ai.. 
=)

**Comment by gabrielferreiraa** [comment]
Boa noite @wbruno gostei bastante do seu perfil, e acho você o cara ideal pra me ajudar nessa caminhada front-end! Qual o próximo passo? :)

PS: Te adicionei no facebook

**Comment by danilovaz** [comment]
Show!

Assim que se acertarem, atualizem seus perfis e avisem aqui na issue para finalizarmos.

Sucesso :tada:

**Comment by danilovaz** [comment]
Perfil do mentor atualizado #284 

Aguardando Pupilo atualizar seu perfil para fechar a issue: #281

**Comment by gabrielferreiraa** [comment]
Já criei meu perfil ! Finalizo a issue @danilovaz  ?

**Comment by danilovaz** [comment]
@gabrielferreiraa Não, ainda não. Você precisa atualizar o seu PR, está faltando incluir seu nome na lista de pupilos -> https://github.com/training-center/mentoria/pull/281

**Comment by gabrielferreiraa** [comment]
@danilovaz mandei novamente, tem como ver se deu certo?

**Comment by danilovaz** [comment]
@gabrielferreiraa ainda consta somente 1 commit no seu PR: #281

**Comment by gabrielferreiraa** [comment]
@danilovaz https://github.com/training-center/mentoria/pull/309

Confirma?

**Comment by danilovaz** [comment]
@gabrielferreiraa Não precisava fazer outro PR, era só atualizar o #281. De qualquer forma, a lista de pupilos não está em ordem alfabética, o correto é:
* Gabriel Brito
* Gabriel Ferreira
* Gabrielle Dias

E não:
* Gabriel Brito
* Gabrielle Dias
* Gabriel Ferreira

Consegue atualizar somente isso? Não precisa enviar outro PR, é só ir no seu repositório e commitar essa modificação da ordem alfabética. Vou fechar o PR #281, beleza? Qualquer dificuldade, me informe.

**Comment by danilovaz** [comment]
@gabrielferreiraa Opa, de boas? Consegue atualizar a listagem? Só falta isso :heart:

**Comment by gabrielferreiraa** [comment]
Opa @danilovaz, desculpe toda essa demora, eu nunca criei Pull Request, e estou com uma certa dificuldade. Acabei de commitar a ordenação correta, tem como confirmar? Valeu
https://github.com/training-center/mentoria/pull/309/commits/4fc1c3f451ebff5c135a701da4ee5d07597f93ed

**Comment by danilovaz** [comment]
@gabrielferreiraa Relaxa, normal. Peça ajuda ao seu mentor sobre essas dúvidas e dê uma olhada nesse curso foda do @willianjusten: http://willianjusten.teachable.com/p/git-e-github-para-iniciantes

Perfil do pupilo atualizado em #309 !
