### ISSUE TITLE
Preciso de um(a) mentor(a) sobre Desenvolvimento Front-End e JS

### ISSUE THREAD

**Issue by atreyucore** [training-center/mentoria#208]
Olá,

Me chamo Maicon, tenho 30 anos e gostaria de um mentor pra me auxiliar na minha caminhada pelo mundo Front End. O que preciso é basicamente de alguém que me diga o que estudar, que se possível estabeleça metas e me incentive. Tenho algum conhecimento ja em HTML, Javascript, CSS (bem básico) e Angular.
Atualmente moro no Rio de Janeiro e faço um estágio numa empresa, mas vou me mudar pra São Paulo no início de novembro e ja quero buscar uma vaga de júnior.

Contatos:
https://www.facebook.com/atreyu.maicon
https://www.linkedin.com/in/mrgomes86

**Comment by danilovaz** [comment]
Bem vindo @atreyucore  !

Vamos ver se algum dos @training-center/mentors consegue te ajudar.

Enquanto isso leia o documento de [Responsabilidades do Pupilo](https://github.com/training-center/mentoria/blob/master/pupilos/responsibility.md)!! :smile:

**Comment by atreyucore** [comment]
Opaa, foi a primeira coisa que eu fiz :)
to no aguardo

**Comment by atreyucore** [comment]
@danilovaz pode adicionar o label Javascript? Tenho interesse tb, e se for o caso altero o título da issue

**Comment by danilovaz** [comment]
@atreyucore pronto, feito 😆

**Comment by guilhermepontes** [comment]
@atreyucore tudo bem? 
Dá uma olhada no meu [perfil](https://github.com/training-center/mentoria/blob/master/mentores/perfis/guilhermepontes.md) e me dá um toque se te interessa.

Abs.

**Comment by danilovaz** [comment]
@atreyucore Pô, que legal! O @guilhermepontes tem uma experiência bem foda, veja se o perfil dele condiz com o que você precisa e sucesso :tada:

**Comment by atreyucore** [comment]
Ohhhh loko, com certeza @guilhermepontes!!!!! Mentor sinistro *.*

**Comment by danilovaz** [comment]
@atreyucore @guilhermepontes Legal, pessoal!

Não esqueçam de atualizar ou criar seus perfis no [repositório](/helpers/README.md) e entrar no nosso [Slack](https://ctgroups.herokuapp.com/) (se ainda não estiverem lá).

**Comment by guilhermepontes** [comment]
@atreyucore ótimo! Me manda uma mensagem quando entrar no Slack. Me usuário é `guilherme`.

**Comment by danilovaz** [comment]
Perfil do Pupilo, atualizado: #236 #237 agora é só atualizar o perfil do Mentor :smile: :tada:

**Comment by danilovaz** [comment]
Perfil do Mentor atualizado: #244 sucesso pessoal :tada:

**Comment by danilovaz** [comment]
Perfil do Mentor atualizado: #244 sucesso pessoal :tada:
