### ISSUE TITLE
Preciso de um(a) mentor(a) sobre Desenvolvimento Front-End em JS e Ionic

### ISSUE THREAD

**Issue by marcoaure** [training-center/mentoria#209]
**Nome:** Marco Aurélio Moreira (mau)
**Descrição:** Olá, eu gostaria de uma pessoa pra me guiar nos próximos passos da minha carreira, como front-end. Sou programador front-end pleno em uma empresa bem conhecida e quero me tornar sênior o mais rápido possível. Estou na área de desenvolvimento web a mais de 5 anos... mas fiquei muito tempo no PHP e estou me dedicando 100% ao front-end agora... aprendendo sobre gulp, grunt etc...estou um pouco atrasado... 
Quero tirar a certificação da Microsoft, desenvolver projetos open source que beneficiem a sociedade brasileira de alguma maneira e embarcar em projetos fechados promissores.
**Contatos:** marcoaure47@gmail.com

**Comment by danilovaz** [comment]
Bem vindo @marcoaure !

Vamos ver se algum dos @training-center/mentors consegue te ajudar.

Só para ficar mais claro, você quer solidificar os seus conhecimentos em Front-End e desenvolver conhecimento com Ionic, correto?

Enquanto isso leia o documento de [Responsabilidades do Pupilo](https://github.com/training-center/mentoria/blob/master/pupilos/responsibility.md)!! :smile:

**Comment by woliveiras** [comment]
Galera dos @training-center/mentors consegue ajudar?

**Comment by woliveiras** [comment]
Estamos com todos os Mentores e Mentoras ocupados no momento, adicionei a label `wait for new mentors` para que os próximos busquem por essas issues primeiro.

**Comment by woliveiras** [comment]
@marcoaure nosso processo mudou: https://medium.com/trainingcenter/e-o-mentoria-mudou-mais-uma-vez-5ad8725bc778

Peço, por favor, que responda esse formulário, se ainda fizer sentido, para que algum mentor ou mentora entre em contato contigo quando possível: http://bit.ly/preciso-de-mentoria

A issue será fechada para que não aconteçam desencontros de informação.
