### ISSUE TITLE
Quero ser um mentor de desenvolvimento FullStack

### ISSUE THREAD

**Issue by guilhermepontes** [training-center/mentoria#214]
Olá!

Meu nome é Guilherme, tenho 24 anos e trabalho com desenvolvimento web profissionalmente há 7 anos, mas já estou vagando no mundo de desenvolvimento há uns 12 anos. Já passei por várias empresas, pequenas e grandes, essas foram as últimas: Gauge, Embraer, R7, Emprego Ligado e The Next Web (TwitterCounter).

Já trabalhei com todo tipo de tecnologia possível, mas tenho especialidade em JavaScript (vanilla + jQuery, Backbonejs, React + Redux), CSS (SASS, BEM), Ruby (Rails), Linux (AWS, Linux Servers) entre mais algumas coisas por aí.

Sou natural de São José dos Campos. Morei 3-4 anos em São Paulo antes de me mudar para Amsterdam - Países Baixos, onde eu trabalho e moro hoje!

Quero ajudar esse tipo de pupilo (sendo em inglês ou não  — preferência para pessoas que querem fazer isso em inglês):
- Quero aprender mais sobre FrontEnd
- Quero aprender mais sobre JavaScript
- Quero aprender mais DevOps
- Quero aprender mais Ruby on Rails
- Quero dicas de carreira (Internacional ou não)

E sim...estou de acordo com o código de conduta.

**Twitter:** http://twitter.com/guiiipontes
**Linkedin:** http://linkedin.com/in/guilhermepontes

**Comment by danilovaz** [comment]
Olá @guilhermepontes seja bem-vindo conterrâneo :smile: 

Pelo que vi, você já leu as [Responsabilidades do Mentor]((/mentores/responsibility.md)) e está de acordo com a ideia do projeto, certo?

Os @training-center/mentors irão avaliar seu perfil e logo te daremos uma resposta.

**Comment by danilovaz** [comment]
@guilhermepontes Ah, você poderia mudar o título da sua issue para PT-BR, mesmo? Temos pupilos com vários níveis de conhecimento (alguns sabem inglês e outros não), então seria legal manter em portuga mesmo :smile: bele?

**Comment by danilovaz** [comment]
Olá @guilhermepontes 

Seu perfil foi aprovado pelos outros mentores.

Bem vindo ao time!

Agora você precisa criar seu perfi no [repositório](/helpers/README.md) e entrar no nosso [Slack](https://ctgroups.herokuapp.com/). Quando entrar no Slack, me mande mensagem -> @danilovaz que coloco você no canal de mentores. 

Depois é só pegar algum pupilo através dessas [issues](https://github.com/training-center/mentoria/issues?q=is%3Aissue+is%3Aopen+sort%3Acreated-asc+label%3A%22need+a+mentor%22).

OBS: busque das issues mais antigas primeiro. :)

**Comment by danilovaz** [comment]
Mentor adicionado #219

**Comment by woliveiras** [comment]
🤘
