### ISSUE TITLE
Preciso de um(a) mentor(a) de SEO 

### ISSUE THREAD

**Issue by santosluiz** [training-center/mentoria#215]
**Nome**: Luiz Santos

**Descrição:** Tenho 19, irei começar a graduação em Sistema da Informação este mês e trabalho como front há 1 ano, principalmente criando sites para WordPress e campanhas de e-mail marketing. Gosto muito da área de SEO, otimização, análises e até mesmo marketing digital de forma geral. Gostaria de ter um mentor na área de SEO.

**Nível de conhecimento atual:** HTML5, CSS3, JavaScript, jQuery, SEO, WordPress.

**Contatos**: 
                E-mail: 97luizsantos@gmail.com
                Facebook: https://www.facebook.com/eu.santosluiz
                Linkedin: https://www.linkedin.com/in/santosluizz

**Comment by danilovaz** [comment]
Bem vindo @santosluiz !

Vamos ver se algum dos @training-center/mentors consegue te ajudar.

Enquanto isso leia o documento de [Responsabilidades do Pupilo](https://github.com/training-center/mentoria/blob/master/pupilos/responsibility.md)!! :smile:

**Comment by woliveiras** [comment]
@training-center/mentors alguém disponível?

**Comment by woliveiras** [comment]
Estamos com todos os Mentores e Mentoras ocupados no momento, adicionei a label `wait for new mentors` para que os próximos busquem por essas issues primeiro.

**Comment by woliveiras** [comment]
@santosluiz nosso processo mudou: https://medium.com/trainingcenter/e-o-mentoria-mudou-mais-uma-vez-5ad8725bc778

Peço, por favor, que responda esse formulário, se ainda fizer sentido, para que algum mentor ou mentora entre em contato contigo quando possível: http://bit.ly/preciso-de-mentoria

A issue será fechada para que não aconteçam desencontros de informação.
