### ISSUE TITLE
Preciso de um(a) mentor(a) de Front-End e UX/UI.

### ISSUE THREAD

**Issue by Zanelatti** [training-center/mentoria#217]
Nome: Diego Zanelatti

Descrição: Olá! Tenho 26 anos, trabalho como designer gráfico há quase 10 anos e recentemente comecei a me interessar bastante por desenvolvimento front-end, UX e UI. Estudo basicamente com conteúdo que encontro no Youtube e no W3Schools. Tenho um conhecimento bem básico de HTML e CSS e estou com um pouco de dificuldade para aplicar e desenvolver esse conhecimento.
Fiquei sabendo da mentoria através da entrevista com o Felipe Fialho, no Dev na Estrada e me empolguei bastante com a iniciativa, pois acredito que com a ajuda de um mentor eu consiga encontrar um rumo, desenvolver e aplicar meus conhecimentos de forma efetiva e quem sabe, conseguir um emprego na área.

Nível de conhecimento atual: HTML e CSS bem basicão.

E-mail: diegozanelatti@hotmail.com
Facebook: www.facebook.com/diego.zanelatti
Linkedin: https://www.linkedin.com/in/diego-zanelatti-21501a100?trk=nav_responsive_tab_profile

**Comment by woliveiras** [comment]
Bem vindo @Zanelatti 

Vamos ver se algum dos @training-center/mentors consegue te ajudar.

Enquanto isso leia o documento de [Responsabilidades do Pupilo](https://github.com/training-center/mentoria/blob/master/pupilos/responsibility.md)!! :smile:

**Comment by leandro-lima** [comment]
Posso ajudar com UI / UX! =)

**Comment by Zanelatti** [comment]
Aceito toda a ajuda que puder me dar, Leandro. 
Valeu mesmo :D

Quando podemos começar?

**Comment by woliveiras** [comment]
Shoooow!

Não se esqueçam de atualizar/criar seus perfis. \o/

**Comment by Zanelatti** [comment]
@woliveiras pode me ajudar com o perfil? Estou apanhando um pouco aqui...

**Comment by danilovaz** [comment]
@Zanelatti Veja se esse link te ajuda: https://github.com/training-center/mentoria/blob/master/helpers/CREATE_PUPIL_PROFILE.md

**Comment by Zanelatti** [comment]
Feito!
Obrigado pela ajuda, @danilovaz e @woliveiras :D

**Comment by leandro-lima** [comment]
Oi Zanelatti,

Criei meu perfiu lá. Estou no Slack, Facebook, Email... hahaha! Só entrar em contato para começarmos! =)

**Comment by woliveiras** [comment]
Tudo certo entre vocês @leandro-lima e @Zanelatti?

Posso fechar essa issue?
