### ISSUE TITLE
Quero ser mentor de UX / UI design.

### ISSUE THREAD

**Issue by leandro-lima** [training-center/mentoria#218]
Nome: Leandro Lima

Descrição: Gosto de UX, Gosto de Internet e gosto de resolver problemas usando essas duas ferramentas! =) Trabalho com design e internet há 9 anos. Há 6 anus comecei a PopUp Design junto com a Dani Guerrato e desde o início deste ano (2016) trabalho como UX Designer na Booking.com

Contatos:
Facebook: https://www.facebook.com/leandro.goes.lima
Linkedin: https://www.linkedin.com/in/leandrogoeslima
Dribbble: https://dribbble.com/leandro-lima

**Comment by woliveiras** [comment]
Bem vindo @leandro-lima!

Com certeza você já leu as [Responsabilidades do Mentor]((/mentores/responsibility.md)) e está de acordo com a ideia do projeto, né? 😁 

Vou conversar com o pessoal dos @training-center/mentors sobre seu perfil!

**Comment by leandro-lima** [comment]
Opa cara!

Li sim! Achei a iniciativa sensacional! =)

**Comment by woliveiras** [comment]
Suuucesso!

**Comment by woliveiras** [comment]
Merged #224
