### ISSUE TITLE
Preciso de um(a) mentor(a) sobre Desenvolvimento Front-End

### ISSUE THREAD

**Issue by G18siqueira** [training-center/mentoria#220]
Olá, boa tarde!!

Sou o Gustavo, 26 anos, atualmente cursando Ciências da Computação, porém com planos para mudar para Análise e Desenvolvimento de Sistemas.. Em resumo peguei uma DP em programação web no segundo semestre de 2015 e em Junho deste ano em meio aos estudos acabei viciado em tudo que eu estava vendo, desde então tenho buscado de forma até equivocada tudo que eu posso para me tornar um desenvolvedor, porém acabo me frustando pois não acho o caminho certo para os estudos, ouvi o DNE 75 com o Felipe Fialho que além de inspirar mostrando que o começo realmente é complicado me animou demais com esse projeto de mentoria!!! 
E venho aqui a procura de um mentor que possa me auxiliar a trilhar esse caminho, tenho conhecimentos em HTML, CSS( Sass), JavaScript/Jquery (ambos bem básico) e estou extremamente disposto a aprender e seguir todas as dicas que me forem passadas!!
Moro em São Paulo e desde já agradeço  a atenção e esse projeto!!

Contatos:
 [Facebook](https://www.facebook.com/GuhhSiqueira)
 [Twitter](https://twitter.com/Guhh_Siqueira)
 gustavo18siqueira@gmail.com

**Comment by danilovaz** [comment]
Bem vindo @G18siqueira !

Pô, legal que conheceu o projeto pelo DNE :tada: 

Vamos ver se algum dos @training-center/mentors consegue te ajudar.

Enquanto isso leia o documento de [Responsabilidades do Pupilo](https://github.com/training-center/mentoria/blob/master/pupilos/responsibility.md)!! :smile:

**Comment by G18siqueira** [comment]
Muito Obrigado @danilovaz !!!

**Comment by G18siqueira** [comment]
E aee @luketevl !!!

Muito obrigado pela oportunidade, como fazemos para começar então? haha!

**Comment by woliveiras** [comment]
Fala galera! Agora é só atualizar/criar os perfis de vocês.

Qualquer dúvida da pra seguir por [aqui](https://github.com/training-center/mentoria/blob/master/helpers/CREATE_PUPIL_PROFILE.md), @G18siqueira :grin:

**Comment by G18siqueira** [comment]
Maravilha então, vou criar agora!! Brigadão @woliveiras

**Comment by G18siqueira** [comment]
@woliveiras você pode verificar se fiz tudo certo por favor??

**Comment by woliveiras** [comment]
Pode mandar o PR @G18siqueira 

Se precisar de ajuda é só chamar nozes :smile:

**Comment by G18siqueira** [comment]
@woliveiras então, acho que a ultima etapa do tutorial não deu muito certo no caso haha, foi mal!

**Comment by G18siqueira** [comment]
Consegui finalizar certinho!

**Comment by danilovaz** [comment]
Perfil do Pupilo atualizado em: #251 e #252 

Agora só falta o Mentor @luketevl atualizar seu perfil e fechamos essa issue. Sucesso :tada:

**Comment by G18siqueira** [comment]
@danilovaz Vlww!! aguardando ansioso!

**Comment by G18siqueira** [comment]
@danilovaz @woliveiras vocês tem alguma noticia do @luketevl ? foi mal perguntar.

**Comment by danilovaz** [comment]
@G18siqueira Não, ainda não. Tentando invocar o menino @luketevl :ghost:

**Comment by G18siqueira** [comment]
@danilovaz blz, brigadão!! :(

**Comment by luketevl** [comment]
Desculpa ai @G18siqueira tive uns contra tempos foda, vo mandar um PR te colocando como pupilo, mas pode me chamar nos meus contatos que estão lá no perfil, até mesmo no proprio slack que te respondo mais fácil do que na issue !

Abraços e booora !

**Comment by luketevl** [comment]
#298 enviado !

**Comment by G18siqueira** [comment]
@luketevl Rlxxx cara!! vou te chamar la então!! 

abraços e vlww!

**Comment by danilovaz** [comment]
Show pessoal! Perfil do Mentor e Pupilo atualizados, fechando essa issue. Sucesso aí :tada:
