### ISSUE TITLE
Preciso de um(a) mentor(a) sobre Desenvolvimento Front-end

### ISSUE THREAD

**Issue by leonantvrs** [training-center/mentoria#223]
**Nome:** Leonan Machado

**Descrição:** atualmente estudande autodidata na alura, comecei a estudar front-end depois de desistir do java :D Agora o foco é HTML, CSS, JavaScript, tbm mas pra frente estudar um pouco back-end (php, ruby, talvez java de novo), tenho acompanhado esse excelente projeto e quero agradecer a iniciativa, certeza que está e vai continuar ajudando muitas pessoas. Tenho visto que não estou progredindo, talvez por não praticar em projetos de verdade, por isso estou aqui a procura de um mentor(a) que possa me auxiliar no caminho para ser um dev front-end e conseguir um trampo. Desde já meu muito obrigado.

**Nível de conhecimento atual:** Básico
- HTML
- JavaScript
- CSS
- Bootstrap
- Jquery
- Git
- Web Design Responsivo

**Contatos:**

Twitter: [leonantvrs](https://twitter.com/leonantvrs)
Email: leonantvrs@gmail.com

**Comment by woliveiras** [comment]
Bem vindo @leonantvrs!

Java nããããão! uhHAUHUHAU - Zoera

Vamos ver se o pessoal dos @training-center/mentors consegue te ajudar. :)

**Comment by leonantvrs** [comment]
Obrigado @woliveiras

**Comment by leonantvrs** [comment]
Olá @luketevl 

sera bem vinda sim a sua ajuda. podemos começar quando e por onde ?

**Comment by woliveiras** [comment]
Fala pessoal, não se esqueçam de criar/atualizar seus perfis. :smile:

**Comment by leonantvrs** [comment]
@woliveiras o @luketevl sumiu. haha

**Comment by woliveiras** [comment]
Eita lasqueira! Apareça @luketevl :ghost:

**Comment by leonantvrs** [comment]
procura-se o @luketevl 
tem noticias @woliveiras  ?
kkk

**Comment by woliveiras** [comment]
Ainda não @leonantvrs 

Vamos aguardar, pode ser algum problema pessoal, pois ele deu uma sumida.

**Comment by luketevl** [comment]
uhuhuhu essas issues me deixam perdido !!!

Pode me chamar no slack no CT que respondo bem mais rapido hahahahahah!!

Desculpa por desaparecer 🏎  !

Seria um prazer te ajudar bora atualizar o perfil e boooooooora !!!!

**Comment by woliveiras** [comment]
Galera, tudo certo entre vocês?

Não se esqueçam de atualizar/criar seus perfis ou avisar aqui se já o fizeram. :smile:

**Comment by luketevl** [comment]
Orientando/aguardando pupilo criar perfil

**Comment by leonantvrs** [comment]
perfil criado, espero que esteja tudo correto.

**Comment by woliveiras** [comment]
Fala @leonantvrs, valeu!

#341 feito.

Agora é só o @luketevl atualizar o perfil dele. \o/

**Comment by woliveiras** [comment]
Fala galera, fechando a issue por inatividade.

Qualquer problema é só avisar.
