### ISSUE TITLE
Preciso de um(a) mentor(a) Full Stack

### ISSUE THREAD

**Issue by romarioccoimbra** [training-center/mentoria#233]
**Nome:**
Romário Coimbra
**Descrição:**
Eae galera! 
Cursei Ciência da Computação e atualmente estou estudando autodidata no Alura e pelos Googles da vida. Mas até agora nada da carreira deslanchar. xD
Preciso de ajuda para adquirir e aprimorar meus conhecimentos em desenvolvimento web. Um guia na área. :)
Alguém que possa, principalmente, me ajudar a direcionar meus estudos em um cenário mais profissional. 
Seriam muito bem vindas dicas de como é trabalhar na prática com desenvolvimento, ou se possível até deixar que eu participe de alguma forma em um projeto real. :)

**Nível de conhecimento atual:**
Como nunca trabalhei em um projeto real, não sei muito bem como me avaliar.
Conheço um pouco de HTML, CSS, JavaScript, PHP, SQL. Mas ainda não sei usar o Github. :/ 

**Contatos:**
<a href= "https://www.facebook.com/romarioccoimbra">Facebook</a>

**Comment by woliveiras** [comment]
Bem vindo @romarioccoimbra 

Com certeza aqui você pode mandar seus primeiros commits!

Vamos ver se algum dos @training-center/mentors consegue te ajudar.

Enquanto isso já da uma lida no documento de [responsabilidades do pupilo](https://github.com/training-center/mentoria/blob/master/pupilos/responsibility.md)!! :smile:

**Comment by romarioccoimbra** [comment]
Muito obrigado! :))

**Comment by alexjunior012** [comment]
@romarioccoimbra posso te ajudar nos estudos, pode olhar meu perfil e se tiver interesse podemos dar continuidade.

**Comment by romarioccoimbra** [comment]
Olá @alexjunior012 !
Fico muito grato pela ajuda! Como podemos continuar?

**Comment by alexjunior012** [comment]
@romarioccoimbra pode me chamar pelo Telegram ou pelo face, como você achar melhor.
Meu telegram é @alexjunior012

**Comment by woliveiras** [comment]
Não se esqueçam de criar/atualizar seus perfis. :smile:

**Comment by woliveiras** [comment]
Fala galera! Essa issue já passou de 12 dias sem atualização. Posso fechar?

**Comment by alexjunior012** [comment]
@woliveiras desculpa a demora, vou atualizar os perfis.

**Comment by woliveiras** [comment]
Show de bola! 😄

**Comment by woliveiras** [comment]
Galera, tudo certo entre vocês, posso fechar a issue?

**Comment by woliveiras** [comment]
@romarioccoimbra e @alexjunior012 está rolando tudo bem com vocês?

**Comment by woliveiras** [comment]
Fala galera, fechando a issue por inatividade.

Qualquer problema é só avisar.
