### ISSUE TITLE
Quero ser mentor de desenvolvimento Back - End (PHP)

### ISSUE THREAD

**Issue by giovannicruz97** [training-center/mentoria#235]
## Nome
Giovanni Cruz
## Descrição
Trabalho com desenvolvimento Back End focado em PHP na ACS Desenvolvimento, há um ano. Amante de APIs RESTful, Docker, padrão MVC e fã do DevNaEstrada . Participante assíduo na comunidade virtual de PHP Brasil no Telegram. Atualmente focado em projetos construídos com CodeIgniter 3 e Slim, porém com enfoque no aprendizado em outros Frameworks como Laravel e Lumen.

## Contatos
Facebook: https://www.facebook.com/giovanni.cruz.1485
Twitter: https://twitter.com/giovanni_cruz97
LinkedIn: https://br.linkedin.com/in/giovanni-cruz-1011a6104
Email: giovanni.cruz97@hotmail.com

_**Space, the final frontier!**_

**Comment by danilovaz** [comment]
Olá @giovannicruz97 seja bem-vindo :smile: 

Você já leu as [Responsabilidades do Mentor]((/mentores/responsibility.md)) e está de acordo com a ideia do projeto?

Os @training-center/mentors irão avaliar seu perfil e logo te daremos uma resposta.

**Comment by giovannicruz97** [comment]
@danilovaz Li sim! Estou totalmente de acordo!

**Comment by danilovaz** [comment]
Olá @giovannicruz97

Seu perfil foi aprovado pelos outros mentores.

Bem vindo ao time!

Agora você precisa criar seu perfi no [repositório](/helpers/README.md) e entrar no nosso [Slack](https://ctgroups.herokuapp.com/). Depois que criar sua conta no Slack, me chama lá, meu user é @danilovaz e eu incluo você no canal de Mentores.

Depois é só pegar algum pupilo através dessas [issues](https://github.com/training-center/mentoria/issues?q=is%3Aissue+is%3Aopen+sort%3Acreated-asc+label%3A%22need+a+mentor%22).

OBS: busque das issues mais antigas primeiro :)

**Comment by raymonsanches** [comment]
`fã do DevNaEstrada` - muito amor <3

**Comment by giovannicruz97** [comment]
@raymonsanches vc representa a resistência do PHP ahahahah

**Comment by danilovaz** [comment]
Perfil do Mentor criado/atualizado: #261
