### ISSUE TITLE
Preciso de um(a) mentor(a) de Front-end  HTML5 CSS3 JS & UX/UI Design

### ISSUE THREAD

**Issue by Nedango** [training-center/mentoria#239]
Olá pessoal, me chamo Daniel tenho um conhecimento conhcimento bem básico de HTML CSS, gostaria de um mentor pra me ajudar nessa jornada front, estou empenhado em a práticar com muita vontade as orientações do meu futuro mentor.
abraço,
Daniel
dansigner@gmail.com

**Comment by danilovaz** [comment]
Bem vindo @Nedango !

Eu vi que você criou 2 Pull Requests #238 #241 para incluir seu nome na lista de pupilos. Eu vou fechar esses dois Pull Requests, ok? 

Vamos ver se algum dos @training-center/mentors consegue te ajudar. E então partimos para a parte de criar e atualizar os perfis, tudo bem?

Enquanto isso leia o documento de [Responsabilidades do Pupilo](https://github.com/training-center/mentoria/blob/master/pupilos/responsibility.md)!! :smile:

**Comment by leandro-lima** [comment]
Eu não posso ajudar com Javascript, mas com UI / UX, tamo ae... =)

**Comment by danilovaz** [comment]
Olha, que legal @Nedango !  O @leandro-lima é um cara sensacional, veja o perfil dele [aqui](https://github.com/training-center/mentoria/blob/master/mentores/perfis/leandro_lima.md) e veja se bate com o que você precisa.

**Comment by Nedango** [comment]
Olá @danilovaz  e @leandro-lima  sou muito grato , por esta oportunidade .

**Comment by danilovaz** [comment]
@Nedango e @leandro-lima vão me informando à respeito do andamento, assim que estiverem alinhados criem/atualizem o perfil de vocês e sucesso :tada:

**Comment by danilovaz** [comment]
@Nedango @leandro-lima Alguma atualização sobre isso, pessoal?

**Comment by danilovaz** [comment]
Estou fechando essa issue por falta de atualização. Qualquer novidade, me contatem.
