### ISSUE TITLE
Quero ser mentor de Front End

### ISSUE THREAD

**Issue by felipeuliana** [training-center/mentoria#240]
**Nome:**
Felipe Uliana
**Descrição:**
Designer e Desenvolvedor Web.
Interessado em compartilhar conhecimentos e experiências de pouco mais de 4 anos de trabalho na área.
**Contatos:**
[GitHub](https://github.com/felipeuliana)
[LinkedIn](https://www.linkedin.com/in/felipe-uliana-461520107/)

**Comment by cantoniazzi** [comment]
Felipe, o link do seu perfil no Linkedin não está abrindo. 
Abs,

**Comment by danilovaz** [comment]
Olá @felipeuliana seja bem-vindo :smile: 

Você já leu as [Responsabilidades do Mentor]((/mentores/responsibility.md)) e está de acordo com a ideia do projeto?

Os @training-center/mentors irão avaliar seu perfil e logo te daremos uma resposta.

**Comment by felipeuliana** [comment]
Olá @danilovaz!
Já li sim as _Responsabilidades do Mentor_, assim como os demais documentos do projeto, e estou de acordo.
Já corrigi o link para o perfil do _Linkedin_ também.

Fico no aguardo da resposta, abraço!

**Comment by danilovaz** [comment]
Olá @felipeuliana 

Seu perfil foi aprovado pelos outros mentores.

Bem vindo ao time!

Agora você precisa criar seu perfi no [repositório](/helpers/README.md) e entrar no nosso [Slack](https://ctgroups.herokuapp.com/). Depois que criar sua conta no Slack, me chama lá, meu user é @danilovaz e eu incluo você no canal de Mentores.

Depois é só pegar algum pupilo através dessas [issues](https://github.com/training-center/mentoria/issues?q=is%3Aissue+is%3Aopen+sort%3Acreated-asc+label%3A%22need+a+mentor%22).

OBS: busque das issues mais antigas primeiro :)

**Comment by danilovaz** [comment]
Salve @felipeuliana alguma novidade sobre o perfil? Precisa de algo?

**Comment by felipeuliana** [comment]
Dia @danilovaz! Que bom que me lembrou, na verdade não consegui acessar o link acima pra criar o perfil `https://github.com/helpers/README.md`...

**Comment by danilovaz** [comment]
@felipeuliana É verdade. Estranho, o link relativo não estava funcionando. Editei, é esse [aqui](https://github.com/training-center/mentoria/tree/master/helpers)

Qualquer coisa, é só chamar.

**Comment by felipeuliana** [comment]
@danilovaz a página _Como criar o perfil de Mentor_ está sem informações, mas se entendi bem, criei meu perfil de acordo com o _template_ que encontrei e fiz o _pull request_. Caso tenha feito errado me avise. Abraço!

**Comment by danilovaz** [comment]
@felipeuliana Tá certo sim Felipe. Já aceitei o PR. O link correto é [esse](https://github.com/training-center/mentoria/blob/master/mentores/mentor_template.md) my bad :disappointed: 

Agora é só ir vendo quem precisa de mentor [aqui](https://github.com/training-center/mentoria/issues?q=is%3Aissue+is%3Aopen+sort%3Acreated-asc+label%3A%22need+a+mentor%22)

:tada:
