### ISSUE TITLE
Quero ser mentor de Android

### ISSUE THREAD

**Issue by diegomalone** [training-center/mentoria#242]
## Nome

Diego Malone Seixas Dantas

## Perfil

Mentor para desenvolvimento nativo Android

## Descrição

Sou formado em Ciência da Computação pela PUC Rio e trabalho com desenvolvimento a 7 anos. Participei de algumas startups desde o começo e trabalhei em empresas de médio e grande porte, como a B2W. Tive experiência com desenvolvimento web com PHP, mas também fazendo um pouco de tudo, típico de startups. Hoje me identifico muito mais no desenvolvimento de aplicativos nativos Android. Também sou o responsável pela equipe de desenvolvimento na startup que trabalho atualmente. Apesar de não ter um conhecimento específico muito grande, acredito que possa ajudar bastante alguém na minha área.

## Links

* [Telegram](http://telegram.me/diegomalone)
* [Twitter](https://twitter.com/diegomalone)
* [Linkedin](https://www.linkedin.com/in/diegomalone)
* [GitHub](https://github.com/diegomalone)

**Comment by danilovaz** [comment]
Olá @diegomalone seja bem-vindo :smile: 

Você já leu as [Responsabilidades do Mentor]((/mentores/responsibility.md)) e está de acordo com a ideia do projeto?

Os @training-center/mentors irão avaliar seu perfil e logo te daremos uma resposta.

**Comment by diegomalone** [comment]
Opa @danilovaz, li sim e estou de acordo 😉

**Comment by danilovaz** [comment]
Olá @diegomalone

Seu perfil foi aprovado pelos outros mentores.

Bem vindo ao time!

Agora você precisa criar seu perfi no [repositório](/helpers/README.md) e entrar no nosso [Slack](https://ctgroups.herokuapp.com/). Depois que criar sua conta no Slack, me chama lá, meu user é @danilovaz e eu incluo você no canal de Mentores.

Depois é só pegar algum pupilo através dessas [issues](https://github.com/training-center/mentoria/issues?q=is%3Aissue+is%3Aopen+sort%3Acreated-asc+label%3A%22need+a+mentor%22).

OBS: busque das issues mais antigas primeiro :)
