### ISSUE TITLE
Preciso de um(a) mentor(a) de JavaScript

### ISSUE THREAD

**Issue by felipeacelino** [training-center/mentoria#249]
**Nome:** Felipe Acelino

**Descrição:** Tenho 23 anos, cursei ADS e atualmente estou trabalhando em uma agência como programador BackEnd (PHP). Apesar de trabalhar com PHP, sou apaixonado por Front também e estudo bastante diversos assuntos dessa área. Porém um dos meus maiores problemas é com o tão amado e odiado **javascript**. Confesso que por estar começando, fiquei meio assustado com os trilhões de frameworks e bibliotecas. Preciso de um mentor que possa me ajudar a direcionar meus estudos e aprimorar meus conhecimentos em desenvolvimento web.

**Nível de conhecimento atual:**
- PHP (s2)
- Java
- SQL
- CSS
- JS (Básicozinho)
- Jquery (Esse cara é legal)
- Android

**Contatos:**

[Facebook](https://www.facebook.com/felipesilva10)
[Twitter](https://twitter.com/felipe_acelino)
[LinkedIn](https://www.linkedin.com/in/felipeacelino)

**Comment by woliveiras** [comment]
Bem vindo @felipeacelino 

Vamos ver se algum dos @training-center/mentors consegue te ajudar com esse JS ae! :smile: 

Realmente, JS é um eterno amor e ódio por minha parte viu.

Enquanto isso leia o documento de [Responsabilidades do Pupilo](https://github.com/training-center/mentoria/blob/master/pupilos/responsibility.md)!

**Comment by felipeacelino** [comment]
@woliveiras Pelo visto o pessoal ta com medo de JS por aqui hahaha... Nenhum mentor badass de JS?

**Comment by wbruno** [comment]
Dá uma olhada no meu perfil
https://github.com/training-center/mentoria/blob/master/mentores/perfis/william_bruno.md

Se você curtir podemos falar por algum IM.

**Comment by felipeacelino** [comment]
@wbruno cara te conheço lá do iMasters haha! Você já me ajudou bastante, vai ser uma honra telo como mentor =)

**Comment by woliveiras** [comment]
Assim que estiverem em contato, não esqueçam de criar/atualizar seus perfis. Sucessssso!

**Comment by felipeacelino** [comment]
@woliveiras criei meu perfil de acordo com esse [helper](https://github.com/training-center/mentoria/blob/master/helpers/CREATE_PUPIL_PROFILE.md), falta algo mais?

**Comment by woliveiras** [comment]
Chegou a mandar o PR @felipeacelino?

**Comment by felipeacelino** [comment]
Sim @woliveiras =)

**Comment by woliveiras** [comment]
Achei!!!

Perfeito cara!

Fiz o Merge. Agora o @wbruno consegue atualizar o perfil dele. :metal:

**Comment by wbruno** [comment]
https://github.com/training-center/mentoria/pull/299

**Comment by woliveiras** [comment]
Perfeito! \o/

Boa sorte pra vocês.
