### ISSUE TITLE
Preciso de um(a) mentor(a) sobre back-end

### ISSUE THREAD

**Issue by osmar-vil** [training-center/mentoria#250]
**Nome:**
_Osmar Villalba_

**Descrição:**
_Atualmente trabalho como web design - graphic design, mas gostaria de focar meus estudos para a área de desenvolvedores, já trabalhei bastante com web design, e gosto de mexer no javascript, mas também já fiz algumas soluções em PHP e também gostei, gostaria de aprender muito mais de PHP e outras linguagens e me tornar un Back End pleno_

**Nível de conhecimento atual:**
_**HTML:** (Intermediário - me defendo bem embora não tenha noções de boas práticas)
**CSS:** (Intermedio/Avanzado: consigo fazer bastante coisa com o CSS, embora só mexa no css puro, e um pouco de Bootstrap)
**Javascript:** (Intermédio: ainda aprendendo mas já consigo fazer bastante coisa, tenho conhecimento en librerías tais como Jquery, Bootstrap, e algumas outras para Formulários, carroceis e slideshow).
**PHP:** (Básico/Intermédio: ainda em treinamento, tenho noções de POO, trabalho com classes, mas até hoje ainda nao fiz um CMS do ZERO com PHP)_

**Contatos:**
_**[Facebook](https://www.facebook.com/osmar.luc), [Twitter](https://twitter.com/osmar_luc)**_

**Comment by woliveiras** [comment]
Bem vindo @osmar-vil 

Vamos ver se algum dos @training-center/mentors consegue te ajudar com esse PHPzaum ae!

Enquanto isso leia o documento de [Responsabilidades do Pupilo](https://github.com/training-center/mentoria/blob/master/pupilos/responsibility.md)!! :smile:

**Comment by osmar-vil** [comment]
Valew @woliveiras , já esto ansioso para ver qual seram os desafios  :)

**Comment by woliveiras** [comment]
@training-center/mentors alguém disponível?

**Comment by giovannicruz97** [comment]
Boa noite @osmar-vil , posso ser seu mentor :)
Dê uma olhada no meu [perfil](https://github.com/training-center/mentoria/blob/master/mentores/perfis/giovannicruz97.md)
Até mais!

**Comment by osmar-vil** [comment]
Oi @giovannicruz97, pode sim, como comenzamos?

**Comment by woliveiras** [comment]
:metal: :metal: :metal: :metal: 

Já podem criar/atualizar seus perfis aqui no repositório então, galera. :raised_hands: 

Boa sorte!

**Comment by woliveiras** [comment]
Fala @osmar-vil e @giovannicruz97, está tudo certo com vocês?

Já criaram seus perfis?

**Comment by woliveiras** [comment]
Galera, fechando a issue por conta do tempo aberto e falta de interação aqui.

Qualquer coisa podemos reabrir.

Boa sorte! :metal: :metal: :metal:

**Comment by osmar-vil** [comment]
já consegui um mentor, valew!!
