### ISSUE TITLE
Preciso de um(a) mentor(a) de Back End (PHP)

### ISSUE THREAD

**Issue by vikt07** [training-center/mentoria#255]
**Nome:**

Victor Maciel

**Descrição:**

Tenho 23 anos, faço Sistemas para internet e trabalho atualmente com suporte/infra, já fiz alguns projetos bem simples com JS e pretendo migrar de área assim que possível.
Aprendi o básico do PHP na faculdade estou fazendo um projeto e pretendo me aprofundar na tecnologia.

**Nível de conhecimento atual:**

Estagiário jr.

Fale comigo em:

facebook.com/vmaciell07
twitter.com/vmaciel7

**Comment by ogilvieira** [comment]
Bem vindo @vikt07 

Vamos encontrar algum dos @training-center/mentors para te ajudar com pi-8-pi :)

Enquanto aguarda, leia nosso documento sobre as **[Responsabilidades do Pupilo](https://github.com/training-center/mentoria/blob/master/pupilos/responsibility.md)**

**Comment by giovannicruz97** [comment]
Olá @vikt07, posso ser seu mentor :)
Dá uma olhada no meu perfil -> https://github.com/training-center/mentoria/blob/master/mentores/perfis/giovannicruz97.md

**Comment by ogilvieira** [comment]
Acho que encontrou @vikt07 

Não se esqueça de atualizar/criar seu perfil ✌️

**Comment by vikt07** [comment]
Tranquilo @giovannicruz97 ?
Vamos lá ! Como faço meu perfil ?

**Comment by ogilvieira** [comment]
@vikt07 vi que já criou seu perfil, mas no seu PR faltou adicionar seu nome com link para perfil a lista de pupilos. Mandei este feedback lá no seu PR #259

**Comment by giovannicruz97** [comment]
@vikt07 Opa! Será um prazer :)

**Comment by ogilvieira** [comment]
Olá @vikt07 e @giovannicruz97 

Não esqueçam de atualizar seus perfis no [repositório](/helpers/README.md) e entrar no nosso [Slack](https://ctgroups.herokuapp.com/).
