### ISSUE TITLE
Preciso de um(a) mentor(a) de desenvolvimento Android

### ISSUE THREAD

**Issue by lucascapistrano** [training-center/mentoria#256]
Olá, meu nome é Lucas Capistrano, tenho 24 anos e sou recém formado em sistemas de informação. Tenho uma boa base em Java, pois estudei durante 4 anos na minha graduação. Por ter essa base em Java, consegui aprender com mais facilidade Android. Fiz um curso de desenvolvimento Android, oferecido pelo Porto Digital de Pernambuco, no qual desenvolvi um APP de vendas que armazenava o local que foi efetuado a venda. Mas gostaria de um mentor para me auxiliar a desenvolver um APP mais complexo, e assim, ganhar mais conhecimento.

**Comment by ogilvieira** [comment]
Seja muito bem vindo @lucascapistrano 
Vamos encontrar algum dos @training-center/mentors para te ajudar com Android sim!
Enquanto isso, pode ler nosso documento sobre as **[Responsabilidades do Pupilo](https://github.com/training-center/mentoria/blob/master/pupilos/responsibility.md)** e seguir algumas das instruções lá!?

**Comment by danilovaz** [comment]
@diegomalone Acha que consegue ajudar, nosso amigo?

**Comment by diegomalone** [comment]
Opa @lucascapistrano!

Dá uma olhada no [meu perfil](https://github.com/training-center/mentoria/blob/master/mentores/perfis/diegomalone.md) e se interessar, vamos juntos ;)

**Comment by lucascapistrano** [comment]
Olá @diegomalone ,

como falei no issue, não tenho muita experiência, e observei que você tem de sobra. Estou atualmente trabalhando, mas por enquanto, não comecei minha pós graduação, por isso tenho tempo livre a noite. A noite posso estudar e desenvolver projeto ou até ajudar na manutenção de algum que já está em produção. Enfim, não sei qual primeiro passo podemos dar, tem algo em mente? Só sei que quero desenvolver mais meus conhecimentos em Android trabalhando em algo que se aproxima dos APP's que estão hoje no mercado.

**Comment by diegomalone** [comment]
Bacana @lucascapistrano! Me chama lá no telegram, que ta no meu perfil, ou em algum outro contato lá que a gente já bate um papo melhor.

**Comment by ogilvieira** [comment]
Olá pessoal!

Não esqueçam de atualizar ou criar seus perfis no [repositório](/helpers/README.md) e entrar no nosso [Slack](https://ctgroups.herokuapp.com/).

**Comment by ogilvieira** [comment]
@lucascapistrano preciso que crie seu [perfil de pupilo](https://github.com/training-center/mentoria/tree/master/pupilos/perfis) por favor e adicione também a [lista](https://github.com/training-center/mentoria/tree/master/pupilos)
