### ISSUE TITLE
Preciso de um(a) mentor(a) de Desenvolvimento Front-End

### ISSUE THREAD

**Issue by johnyramos** [training-center/mentoria#257]
**Nome:** Johny Ramos
**Descrição:** Já trabalho com desenvolvimento de sistemas, porém estou querendo migrar pra desenvolvimento web e não sei exatamente por onde começar. Já mexi um pouco com HTML e JS, mas sempre interrompo por não conseguir pensar em projetos para executar como treinamento.
**Nível de conhecimento atual:** Básico

**Contatos:**
- [Twitter](https://twitter.com/JoeeyRamos)
- [Facebook](https://www.facebook.com/johnyeramos)
- Skype - nuts_joe@hotmail.com
- E-mail - johny.eramos@gmail.com

Obrigado Galere!

**Comment by ogilvieira** [comment]
Bem vindo @johnyramoa

Vamos ver se algum dos @training-center/mentors consegue te ajudar.

Enquanto isso leia o documento de [Responsabilidades do Pupilo](https://github.com/training-center/mentoria/blob/master/pupilos/responsibility.md)!! :smile:

**Comment by ogilvieira** [comment]
@cezarlz está disponível para ser mentor do @johnyramos ?

**Comment by cezarlz** [comment]
@ogilvieira claro! Podemos conversar por email, é mais fácil e prático para mim. cezarluiz.c@gmail.com

@johnyramos pode mandar um email com suas dúvidas, o que você já fez, etc. Estarei esperando ansiosamente ;)

**Comment by johnyramos** [comment]
Opa! Obrigado @cezarlz e @ogilvieira  pela atenção!! 

@cezarlz estarei enviando o email pra ti!

Abraços!

**Comment by ogilvieira** [comment]
@johnyramos você já criou seu perfil e adicinou seu nome a lista de pupilos? Esse [helper](https://github.com/training-center/mentoria/blob/master/helpers/CREATE_PUPIL_PROFILE.md) vai te guiar.
Se precisar de ajuda pode contar comigo.

**Comment by woliveiras** [comment]
#285 mergeado!

Seu perfil já está OK @cezarlz? :)

**Comment by woliveiras** [comment]
Galera, tudo certo, podemos fechar a issue?

**Comment by cezarlz** [comment]
@woliveiras está ok sim ;)

**Comment by woliveiras** [comment]
Shoow
