### ISSUE TITLE
Quero ser mentor na área de Frontend e com VIM

### ISSUE THREAD

**Issue by matmarsiglio** [training-center/mentoria#26]
Nome: Matheus Marsiglio

Sou Desenvolvedor Front End há 5 anos, co-organizador do [FrontUX](http://www.frontux.com), colaborador ativo da comunidade de VIM de São Paulo [vim-sp](https://github.com/vim-sp/vim-sp), descobri que queria programar durante o técnico de mecatrônica, desisti da faculdade por desgosto e apoio aos estudos autodidatas e de compartilhamento de conhecimento em comunidades, estou começando a falar com mais frequência em eventos da comunidade de desenvolvimento; trabalhando em escrever meu primeiro livro; estudo de forma autodidata campos da ciência da computação, arquitetura de softwares, matemática e física; trabalho há 3 anos em ambientes de start ups com softwares de larga escala ou em processo de escala, com foco em Javascript e padrão de folhas de estilos.

[Site pessoal](http://heymathe.us)
[Twitter](https://twitter.com/matmarsiglio)
[LinkedIn](https://br.linkedin.com/in/matmarsiglio)

**Comment by woliveiras** [comment]
@training-center/moderators, o @matmarsiglio é conhecido dos grupos e eventos aqui em SP. :)

Por mim é mais Mentor um para ajudar muito!

**Comment by baltazarparra** [comment]
Ótimo =D

**Comment by danilovaz** [comment]
show!

**Comment by woliveiras** [comment]
@matmarsiglio, já pode criar seu perfil de mentor e mandar o PR cara! 

:smile:

**Comment by matmarsiglio** [comment]
@woliveiras vou ver isso já já, cara! Amanha é FrontUX, aí um dia antes e no dia é correria, mas já tiro um tempo pra fazer isso com calma! 😸

**Comment by woliveiras** [comment]
KKKK

Sem problemas cara, aguardamos o PR sem pressa 😄

**Comment by woliveiras** [comment]
Perfil adicionado
