### ISSUE TITLE
Preciso de um(a) mentor(a) Full Stack

### ISSUE THREAD

**Issue by renesoaresse** [training-center/mentoria#263]
**Nome:**
Renê Soares
**Descrição:**
E ai mentores, blz?
Já programo PHP a algum tempo e estudo nas horas vagas, estou procurando um mentor para poder guiar os meus estudos tanto no PHP quanto em HTML, CSS, JS e outras coisas da profissão. Ficarei grato a quem puder me ajudar. Estou aberto a estudar coisas novas, mas antes aprender a base. :D

**Nível de conhecimento atual:**
PHP - Junior quase pleno :P
HTML - Junior mais pra baby :P
CSS - Junior mais pra baby :P
JS - Baby :P
Git -  Junior quase pleno :P
Postgresql -  Junior quase pleno :P

**Contatos:**
[FB](https://www.facebook.com/rene.soares.946)

**Comment by ogilvieira** [comment]
Bem vindo(a) @renesoaresse 

Vamos ver se algum dos @training-center/mentors consegue te ajudar.
Enquanto isso leia o documento de [Responsabilidades do Pupilo](https://github.com/training-center/mentoria/blob/master/pupilos/responsibility.md)!! :smile:

**Comment by ogilvieira** [comment]
Opa, mais uma coisa! é necessário criar um perfil de pupilo [desta forma aqui](https://github.com/training-center/mentoria/blob/master/helpers/CREATE_PUPIL_PROFILE.md).

Até mais :)

**Comment by ogilvieira** [comment]
@wbruno consegue ajudar nosso amigo @renesoaresse?

**Comment by wbruno** [comment]
opa! dá uma olhada no meu perfil:
https://github.com/training-center/mentoria/blob/master/mentores/perfis/william_bruno.md

**Comment by renesoaresse** [comment]
@wbruno seria uma honra você como mentor. Seu blog já me salvou algumas vezes, principalmente no JS. :P

**Comment by renesoaresse** [comment]
@wbruno como seria esse contato?

**Comment by wbruno** [comment]
hangout wbrunom@gmail.com
ou via facebook https://www.facebook.com/wbruno.moraes

**Comment by ogilvieira** [comment]
@renesoaresse 

Não esqueçam de atualizar ou criar seus perfis no [repositório](/helpers/README.md) e entrar no nosso [Slack](https://ctgroups.herokuapp.com/).

**Comment by wbruno** [comment]
feito
https://github.com/training-center/mentoria/blob/master/mentores/perfis/william_bruno.md
