### ISSUE TITLE
Preciso de um mentor em PHP

### ISSUE THREAD

**Issue by LuizGlatz** [training-center/mentoria#264]
**Nome:**
Luiz Glatz

**Descrição:**
Sou estudante de Análise e Desenvolvimento de Sistema. Estou iniciando minha jornada no mundo de TI e gostaria de aprofundar meus conhecimentos sobre back-end, principalmente em PHP.

**Nível de conhecimento atual:**
*HTML:* básico/intermediário (conheço o suficiente para criação de HTML não muito complexos)
*CSS:* básico (conhecimento muito superficial, suficiente apenas para criações muito simples)
*PHP:* básico/intermediário (consigo fazer o CRUD sem muitas dificuldades, porém não sei quase nada de POO)

**Observação:**
Fora do GitHub o @giovannicruz97 é meu mentor, então eu gostaria que ele fosse oficialmente meu mentor, aqui.

**Contatos:**
[Facebook](https://www.facebook.com/luiz.glatz.9) | [Linkedin](www.linkedin.com/in/luiz-glatz)

**Comment by ogilvieira** [comment]
Bem vindo(a) @LuizGlatz 

Vamos ver se algum dos @training-center/mentors consegue te ajudar.

Enquanto isso leia o documento de [Responsabilidades do Pupilo](https://github.com/training-center/mentoria/blob/master/pupilos/responsibility.md)!! :smile:

Não esqueça de criar seu perfil assim como descrito neste [helper](https://github.com/training-center/mentoria/blob/master/helpers/CREATE_PUPIL_PROFILE.md).

**Comment by giovannicruz97** [comment]
@LuizGlatz  vamos continuar nossos estudos juntos! Será um prazer :)

**Comment by ogilvieira** [comment]
Fechado! que bom que já estão resolvidos :D

**Comment by ogilvieira** [comment]
@LuizGlatz preciso que adicione seu nome na lista de [perfis de pupilos](https://github.com/training-center/mentoria/tree/master/pupilos) seguindo a ordem alfabética por favor :)

**Comment by LuizGlatz** [comment]
Está adicionado

2016-10-26 11:55 GMT-02:00 Gil Vieira <notifications@github.com>:
