### ISSUE TITLE
Preciso de um mentor para a área de criação e SEO de páginas web

### ISSUE THREAD

**Issue by rafaDfaria** [training-center/mentoria#27]
# **Rafael Alves  Duarte**

### **Breve descrição sobre mim e minha rotina**
Tenho 26 anos, moro em Guarulhos - SP, e curso no período noturno o curso de ciências da computação na Universidade de Guarulhos.
Sempre tive muita facilidade em aprender e entender a lógica por trás do funcionamento de programas e afins, já realizei a criação de alguns sites, mas sempre utlizando de templates já prontos, copiando e colando pedaços de códigos para montar meus franksteins funcionais, jamais criei um site totalmente do 0.

Meu objetivo com esse mentorado é primeiramente obter conhecimento para melhor meu site pessoal, conseguir colocá-lo em uma ótima posição nas buscas pelo google e posteriormente trabalhar como freela na área durante a minha graduação, meu objetivo futuro é me dedicar a área da programação de softwares, mas como sei que não vou conseguir me manter financeiramente durante a graduação com os valores oferecidos nos estágios vou me dedicar aos freelas também para ajudar na renda.

Sou prestador de serviços durante o dia e faço faculdade durante a noite, chego em casa por volta das 21:50 22:00, durante o dia meu horário é completamente inconstante, fico dias sem conseguir passar em casa antes de ir para a faculdade e há dias que fico em casa sem fazer nada.

### **Nível de conhecimento atual:**

Estou realizando um curso online, o CS50, o curso vai me proporcionar conhecimentos em C, Java, C++, HTML,CSS e PHP.
Atualmente consigo me virar com HTML, CSS, mas preciso aprender a fundo os conhecimentos e técnicas e aprender também PHP e Javascript.

### **Contatos**
[Facebook](https://www.facebook.com/rafael.duarte.129)
[Linkedin](https://www.linkedin.com/in/rafael-alves-duarte-619589a8?trk=hp-identity-name)

Os três últimos sites que fiz. (utilizando templates de terceiros)
www.maridoaqui.com.br (Site que utilizo para divulgar meu trabalho como prestador de serviços)
www.zabritech.com.br
www.megacabling.com.br

E desde já dou os parabéns a todos pela iniciativa, o conhecimento deve ser sempre compartilhado!

**Comment by woliveiras** [comment]
Opa, conheço alguém que conhece alguém... Vou tentar te ajudar @rafaDfaria

**Comment by rafaDfaria** [comment]
@woliveiras Perfeito, no aguardo.

**Comment by woliveiras** [comment]
Ae mano, agora a @fabiolafaria pode te ajudar! :smile: 

Só decidirem qual o melhor canal de comunicação entre vocês e adicionar seu perfil de pupilo, conforme o [guia](https://github.com/training-center/mentoria#preciso-de-uma-mentora), @rafaDfaria

**Comment by woliveiras** [comment]
Ainda precisando de ajuda ou conseguiu por fora @rafaDfaria?

**Comment by woliveiras** [comment]
Alguém consegue ajudar essa alma, jovens @training-center/mentors?

**Comment by wesleycoder** [comment]
@fabiolafaria não está com esse pupilo então?
Eu talvez possa ajudar.
@rafaDfaria será que podemos combinar algum dia pra bater um papo e ver se o que eu tenho à oferecer vai se encaixar com suas expectativas no projeto?

**Comment by woliveiras** [comment]
Não está, @wesleycoder.

Pode tacar lenha ajudando esse jovem! :raised_hands:  :raised_hands:  :raised_hands:

**Comment by rafaDfaria** [comment]
@wesleycoder perfeito, conversaremos pelo discord e alinharemos as ideias, muito obrigado e não decepcionarei ;D

@woliveiras  obrigado pelo apoio.

Vamos que vamos!

**Comment by woliveiras** [comment]
Booooooa! 

Quando possível atualizem os perfis de vocês e sucesso!!! :raised_hands:

**Comment by woliveiras** [comment]
Tudo dando certo entre vocês @rafaDfaria e @wesleycoder?

**Comment by wesleycoder** [comment]
Sim, tudo indo bem.
O @rafaDfaria inclusive já enviou o [perfil](https://github.com/training-center/mentoria/blob/master/pupilos/perfis/rafadfaria.md) dele.
Pode fechar essa issue já @woliveiras.

**Comment by woliveiras** [comment]
Perfeito @wesleycoder ! :smile: 

Verdade
