### ISSUE TITLE
[Quero ser mentor] de backend e/ou php.

### ISSUE THREAD

**Issue by mrprompt** [training-center/mentoria#280]
**Nome:** Thiago Paes
**Descrição:** Desenvolvedor PHP e Javascript, Full stack e ZCPE
**Contatos:** mrprompt@gmail.com (hangout), @mrprompt (skype)

**Comment by woliveiras** [comment]
Faaaala @mrprompt 

Você já leu as [Responsabilidades do Mentor]((/mentores/responsibility.md)) e está de acordo com a ideia do projeto?

**Comment by mrprompt** [comment]
@woliveiras li sim ;)

**Comment by woliveiras** [comment]
Sucesso cara!

O pessoal dos @training-center/mentors vai avaliar seu perfil e logo te daremos uma resposta.

Valeu pelo interesse em nos ajudar.

**Comment by Gabrielbarretobr** [comment]
Se quiser ser meu mentor com Javascript fique a vontade! hahaha.

**Comment by mrprompt** [comment]
Aceito com o maior prazer Gabriel, mas aviso que minha especialidade é PHP, apesar de trabalhar a mais de um ano com JS. Acredito que pela minha experiência na área de desenvolvimento, consigo te ajudar sim.

**Comment by woliveiras** [comment]
Fala @Gabrielbarretobr 

O que acha da ajuda do @mrprompt?

**Comment by woliveiras** [comment]
@mrprompt, você chegou a criar seu perfil?

Eu acabei esquecendo dessa issue! Mil perdões, cara.

**Comment by mrprompt** [comment]
@woliveiras desculpe, que perfil?

**Comment by woliveiras** [comment]
Da uma olhada mano: https://github.com/training-center/mentoria#quero-ser-um-mentora

O item 4 no resumo. :)

Pode criar seu perfil e eu vou te adicionar a organização.

**Comment by mrprompt** [comment]
ah beleza, pensei que já tinha feito: https://github.com/training-center/mentoria/pull/320

**Comment by woliveiras** [comment]
Perfeito!
