### ISSUE TITLE
Preciso de um(a) mentor(a) de Front-end & UI/UX

### ISSUE THREAD

**Issue by ivosoares** [training-center/mentoria#286]
**Nome:** Ivonaldo Soares

**Descrição:** Atualmente estudante do segundo ano de sistemas de informação, acabei de terminar um estagio de 1 ano como desenvolvedor de sistemas web (PHP/Mysql), e agora to trabalhando em uma agencia de publicidade como desenvolvedor a uma semana. To a cerca de uns 6 meses participando das comunidades de Front e UX  no qual são as  áreas que pretendo me especializar.

**Nível de conhecimento atual:** Iniciante

**Contatos:** 
Email - ivonaldojrsoares@gmail.com
Slack(CT) - @ivonaldosoares
Twitter - @grilonaldo
Telegram - @ivonaldosoares

**Comment by danilovaz** [comment]
Bem vindo @ivosoares  !

Alterei o título da sua issue para seguir o padrão, beleza?

Vamos ver se algum dos @training-center/mentors consegue te ajudar.

Enquanto isso leia o documento de [Responsabilidades do Pupilo](https://github.com/training-center/mentoria/blob/master/pupilos/responsibility.md)!! :smile:

**Comment by woliveiras** [comment]
Estamos com todos os Mentores e Mentoras ocupados no momento, adicionei a label `wait for new mentors` para que os próximos busquem por essas issues primeiro.

**Comment by LFeh** [comment]
@ivosoares Qual o tempo semanal que você teria disponivel para participar desse projeto?

**Comment by ivosoares** [comment]
@LFeh  Acredito que todo dia de manhã e a tarde, porque aqui no trabalho dão bastante liberdade pra estudar e tal, então sempre to no slack. A noite fica um poco puxado por causa da faculdade.
