### ISSUE TITLE
Preciso de um(a) mentor(a) de JavaScript

### ISSUE THREAD

**Issue by Gabrielbarretobr** [training-center/mentoria#288]
Meu nome é Gabriel, sou desenvolvedor front end jr  e estou no projeto no site da Oi, utilizamos react no projeto, porém tenho pouco contato de js e gostaria de um mentor para me ajudar, se possível = )

**Comment by danilovaz** [comment]
Bem vindo @Gabrielbarretobr  !

Eu atualizei o título da issue para seguir o padrão das demais, ok?

Para entender melhor, você quer aprofundar seus conhecimentos em JavaScript ou aprofundar em JS E React?

Vamos  aguardar e ver se algum dos @training-center/mentors consegue te ajudar.

Enquanto isso, se ainda não leu, leia o documento de [Responsabilidades do Pupilo](https://github.com/training-center/mentoria/blob/master/pupilos/responsibility.md)!! :smile:

**Comment by Gabrielbarretobr** [comment]
Bom dia,
Obrigado por ter mudado.
Respondendo sua pergunta.. Javascript e depois react.

Valeu pela atenção.

**Comment by woliveiras** [comment]
Estamos com todos os Mentores e Mentoras ocupados no momento, adicionei a label `wait for new mentors` para que os próximos busquem por essas issues primeiro.

**Comment by mrprompt** [comment]
@Gabrielbarretobr salve, posso ser teu mentor de js, porém não manjo nada de React, então, podemos estudar juntos isso ;)

**Comment by danilovaz** [comment]
Olá pessoal!

@Gabrielbarretobr Veja se o perfil do @mrprompt condiz com o que você precisa.

E se tudo estiver OK, não esqueçam de atualizar ou criar seus perfis no [repositório](https://github.com/training-center/mentoria/blob/master/helpers/README.md) e entrar no nosso [Slack](https://ctgroups.herokuapp.com/).

Assim que fizerem isso, me avisem aqui na issue para fechá-la.

**Comment by woliveiras** [comment]
Fala galera, estou fechando a issue por tempo sem interação.
