### ISSUE TITLE
Preciso de um(a) mentor(a) de Front-end [INICIANTE]

### ISSUE THREAD

**Issue by deltasoneca** [training-center/mentoria#289]
Meu nome é Rodrigo Pontes ([LinkedIn](https://br.linkedin.com/in/rodrigohgpontes), [Twitter](twitter.com/sousoneca)), tenho 37 anos, de SP, e decidi fazer uma mudança drástica (e tardia) de carreira e me tornar desenvolvedor.

Posso explicar melhor minha história e contexto a quem se interessar, mas um resumo é que sou formado em Economia, passei uns 8 anos como gestor de projetos sociais (em ONGs), depois uns 4 anos no mundo de startups (como founder non-tech e marketing) e agora tomei essa decisão que quero investir numa mudança de carreira e me tornar desenvolvedor.

Minha atual necessidade é ter um(a) mentor(a) que me ajude a responder algumas dúvidas sobre uma meta que estou me propondo: **Partir do zero e em 4 meses ser empregável como desenvolvedor junior.**
Isso é possível? Como é possível? O que faço para chegar lá? Por onde começo?

Qual tipo de desenvolvedor também é algo que está parcialmente respondido apenas. Sei que não quero ser puro back-end ou SysOp. E provavelmente também não especialista iOS ou Android developer. Agora dentre Front-End, Front-End+UX/UI, Full-stack web, também está aberto (apesar de ter a sensação que essa é uma decisão de especialização a ser tomada um pouco mais para frente).

Tenho certa facilidade e familiaridade com programação e pensamento lógico, mas meu conhecimento é praticamente zero. Diria 0,1. Por exemplo, consigo pegar um template de site estático pronto e ficar mexendo no HTML+CSS até ficar do jeito que eu quero. Vide o meu site de casamento que eu fiz inteiro baseado em um template que baixei. Peguei [isso](http://hssoluciones.com/MyTemplates/tpl/evento-free-music-event-template/) e transformei [nisso](http://www.mariero.com.br/). Mas JS (e todo o resto) eu teria que começar do zero.

Enfim, quem pode me ajudar? :)
Pode me contatar pelo rodrigohgpontes@gmail.com
Mesmo que não queira/possa me mentorar, pode enviar um email se quiser saber mais dessa minha decisão ou qualquer outra coisa.

Obrigado!

PS: Adorei a iniciativa aliás! Foi dica do Matheus Marsiglio vir aqui.

**Comment by danilovaz** [comment]
Bem vindo @deltasoneca  !

Alterei o título da sua issue para seguir o padrão, beleza?

Se o @matmarsiglio do FrontUX te trouxe até aqui, é sucesso :beers: 

Muito legal sua decisão de tentar algo novo na vida profissional. Desejo todo sucesso à você nessa jornada. E mesmo sabendo 0.1 de programação, parabéns pelo site do seu casamento.

**Partir do zero e em 4 meses ser empregável como desenvolvedor junior:** Vamos ver se algum dos @training-center/mentors consegue te ajudar nisso e iniciar sua carreira.

Enquanto isso, se ainda não leu, leia o documento de [Responsabilidades do Pupilo](https://github.com/training-center/mentoria/blob/master/pupilos/responsibility.md)!! :smile:

**Comment by woliveiras** [comment]
ADORO ESSE TIPO DE REVIRAVOLTA DE CARREIRA!!!! 

Visto que trabalhei como Analista de Suporte, virei SysAdmin, fui trabalhar com Segurança da Informação e de repente era Front End! :joy: 

Da uma olhada no [meu perfil](https://github.com/training-center/mentoria/blob/master/mentores/perfis/william_oliveira.md) e veja se é interessante, cara. :metal: :metal: :metal:

**Comment by danilovaz** [comment]
Pô, maneiro @deltasoneca ! Veja se o perfil do @woliveiras bate com o que você precisa. Já aviso que o cara é firmeza :heart:

**Comment by Josue23** [comment]
@deltasoneca, eu gostei da tua objetividade e já estou copiando a tua meta por que me identifiquei com o teu resumo.
Abraços mano :)

**Comment by deltasoneca** [comment]
animal, @woliveiras! Como começamos? Você me manda um email no rodrigohgpontes@gmail.com e a gente combina um papo??

**Comment by danilovaz** [comment]
Show! Vão me avisando do andamento disso :tada:

**Comment by woliveiras** [comment]
Perfeito @deltasoneca e @danilovaz

**Comment by danilovaz** [comment]
Oi pessoal, alguma novidade?

**Comment by woliveiras** [comment]
MENINO DO CÉU

Está rolando a conversa e esquecemos de atualizar os perfis.

Sobe ae pra noes @deltasoneca

**Comment by woliveiras** [comment]
Atualizamos tudo @danilovaz
