### ISSUE TITLE
Quero ser mentora de SEO e Digital Analytics

### ISSUE THREAD

**Issue by fabifaria** [training-center/mentoria#29]
Breve apresentação: Oi Pessoal, meu nome é Fabíola tenho 30 anos, sou formada em Sistemas de Informação, mestranda em Eng. Software na USP, atualmente monitora do curso de Métricas e Digital Analytics na ESPM, adoro estar informada sobre novas tecnologias, ferramentas para Web Analytics, SEO, etc.

-----
​*Empresa que trabalha: VivaReal - VivaDecora
​*Cidade/UF:*​ São Paulo/SP
​*Função: Especialista SEO
​*Redes sociais: Linkedin: https://www.linkedin.com/in/fabiolafaria
Facebook: https://www.facebook.com/fabiola.faria
Twitter: @fabiola_faria

**Comment by woliveiras** [comment]
@training-center/moderators a @fahbiuzinha trabalha comigo! Manja e é muito gente fina. Por mim já está aprovada. :D

**Comment by dorianneto** [comment]
Por incrível que pareça, eu estava pensando em abrir uma issue para perguntar se o projeto aceitava profissionais do marketing digital ou apenas da área de desenvolvimento, pois conheço uma galera do marketing digital e também muita gente que busca conhecimento na área.

Sensacional!

**Comment by woliveiras** [comment]
Chama eles mano @dorianneto! 

Se tiver relação com Web, acho que todo mundo pode ajudar.

**Comment by woliveiras** [comment]
@fahbiuzinha, pode criar seu perfil de mentor seguindo o [fluxo](https://github.com/training-center/mentoria#quero-ser-um-mentora) que lhe informei.

**Comment by danilovaz** [comment]
@woliveiras @fahbiuzinha muito massa! :+1:

**Comment by fabiolafaria** [comment]
@woliveiras me add com esse perfil aqui, recuperei a senha :)

**Comment by woliveiras** [comment]
Ooopa, show de bola!

**Comment by woliveiras** [comment]
Adicionado o [perfil](https://github.com/training-center/mentoria/tree/master/mentores#mentores-de-seo).
