### ISSUE TITLE
Preciso de um(a) mentor(a) Javascript

### ISSUE THREAD

**Issue by frrrnd** [training-center/mentoria#290]
**Nome:** Fernando Soares
**Descrição:** Trabalho com UX/UI. Basicamente penso na interface, desenho ela, e implemento em HTML e CSS. Faço poucas coisas em JS, bem o basicão mesmo. Quero aprender bem pra pelo menos fazer um Front completo sem a necessidade de outra pessoa.
**Nível de conhecimento atual:** HTML (jade/pug), CSS (Sass, Less), Semantica, Worpdress,  jQuery, Git
**Contatos:** [Twitter](https://twitter.com/frrrnd), [E-mail](mailto:dotfernando@gmail.com)

**Comment by danilovaz** [comment]
Bem vindo @frrrnd !

Vamos ver se algum dos @training-center/mentors consegue te ajudar com nosso amado JS.

Enquanto isso, se ainda não leu, leia o documento de [Responsabilidades do Pupilo](https://github.com/training-center/mentoria/blob/master/pupilos/responsibility.md)!! :smile:

**Comment by woliveiras** [comment]
Estamos com todos os Mentores e Mentoras ocupados no momento, adicionei a label `wait for new mentors` para que os próximos busquem por essas issues primeiro.

**Comment by mrprompt** [comment]
@danilovaz posso ser seu mentor de js se você aceitar brother.

**Comment by danilovaz** [comment]
Olá pessoal! @mrprompt Na verdade quem está precisando de mentor é nosso amigo @frrrnd :smile: 

@frrrnd Veja se o perfil do @mrprompt condiz com o que você precisa.

E se tudo estiver OK, não esqueçam de atualizar ou criar seus perfis no repositório e entrar no nosso Slack.

Assim que fizerem isso, me avisem aqui na issue para fechá-la.

**Comment by mrprompt** [comment]
hahaha, blz, foi mal a confusão

**Comment by wagnerssouza** [comment]
Oi, aqui já foi resolvido? Caso não tenha, @frrrnd, posso te ajudar 😃

**Comment by woliveiras** [comment]
Fala galera, estou fechando a issue por tempo sem interação.
