### ISSUE TITLE
Preciso de um(a) mentor(a) em HTML e CSS

### ISSUE THREAD

**Issue by AlexAvila** [training-center/mentoria#291]
Olá, meu nome é Alex Ávila.

Minha formação é Ciência da Computação, e trabalho com infraestrutura de redes com foco em Linux há MUITOS anos, mesmo. Há 1 ano venho estudando para mudar de carreira e, depois de pesquisar muito, comecei a estudar por conta própria front-end, com foco em design e interação. 

Já estudei bastante sobre html, css, javascript, jQuery, Bootstrap, lógica de programação, métodos ágeis, etc. 

De todo o escopo que envolve Front-end o que mais gosto de fazer é estilo e interação.

Minha meta é me tornar empregável o mais breve possível, ou poder trabalhar como freelancer, para que possa largar de vez os apt-gets, nslookups e afins. 

Tecnicamente posso me virar bem, o que preciso é orientações para saber se estou estudando as coisas certas,  carreira e dicas de mercado e formas de tornar um bom candidato para uma vaga 

Resumindo, quero mudar de carreira, e achei no Front-end o que eu nem sabia que queria fazer. Acho que consigo aprender a programar sozinho, sou melhor do que eu pensava nisso, mas  tem coisas que só o dia-a-dia pode me dar. Tenho 43 anos, não tenho tempo a perder, mas preciso de ajuda naquilo que não se acha no Youtube, cursos em vídeo e documentação oficial, experiência de campo.

Valeu

*_Nome: Alex Santos de Ávila
*_Nível de conhecimento atual: Básico
**Contatos: oalexavila@gmail.com, twitter.com/alexavila, facebook.com/deavila.info

**Comment by danilovaz** [comment]
Bem vindo @AlexAvila   

Muito legal sua iniciativa de mudar de área, independente da idade, temos que buscar trabalhar com o que nos dá mais felicidade. E algumas vezes, é como você falou: nem sabemos o que queríamos de fato fazer.

Desejo sucesso na sua jornada e vamos ver se algum dos @training-center/mentors consegue te ajudar.

Enquanto isso, se ainda não leu, leia o documento de [Responsabilidades do Pupilo](https://github.com/training-center/mentoria/blob/master/pupilos/responsibility.md)!! :smile:

**Comment by luketevl** [comment]
Fala @AlexAvila dá um olhada no meu [perfil](https://github.com/training-center/mentoria/blob/master/mentores/perfis/lucas_henrique.md) e se te interessar estou a disposição. 
Nunca é tarde pra aprender ! booooora

**Comment by AlexAvila** [comment]
Opa! Me interesso sim @luketevl, valeu pelo interesse. Qual o próximo passo agora?

**Comment by danilovaz** [comment]
Agora é vocês conversarem e se acertarem à respeito da mentoria, feito isso, o @AlexAvila precisa criar seu perfil de pupilo --> https://github.com/training-center/mentoria/blob/master/helpers/CREATE_PUPIL_PROFILE.md e o @luketevl precisa atualizar a lista de pupilos dele.

Após atualizarem, me avisem nessa issue para eu fechar.

**Comment by AlexAvila** [comment]
@danilovaz, eu criei o perfil de pupilo, mas não tenho certeza se fiz certo, tu poderia dar uma olhada?

**Comment by danilovaz** [comment]
@AlexAvila você chegou a enviar o Pull Request?

**Comment by AlexAvila** [comment]
@danilovaz, acho que tinha feito a coisa certa no lugar errado, foi mal.

Mas creio que agora acertei.

Obrigado

**Comment by danilovaz** [comment]
@AlexAvila Ainda não chegou seu PR, veja aqui: https://github.com/training-center/mentoria/pulls

Como você está fazendo? Você pode fazer o fork do repositório Mentoria, clonar na sua máquina, fazer a inclusão do seu nome na listagem de pupilos e criar seu perfil, commitar e então enviar o PR para que possamos realizar o merge.

Se não conseguir com os passos acima, sem problemas. Tente seguir esse guia aqui: https://github.com/training-center/mentoria/blob/master/helpers/CREATE_PUPIL_PROFILE.md

Se ainda assim não conseguir enviar. Pode me chamar no Slack quando eu estiver online ou chamar seu mentor, que ajudamos nisso.

**Comment by danilovaz** [comment]
Perfil do pupilo criado: #304 e #305 . Aguardando o mentor @luketevl atualizar seu perfil para fecharmos essa issue.

**Comment by luketevl** [comment]
PR #313 feito !

**Comment by danilovaz** [comment]
Show! Estou fechando essa issue, agora é seguirem a mentoria e sucesso para vocês :tada:
