### ISSUE TITLE
Preciso de um(a) mentor(a) de Desenvolvimento Back-end/Python/PHP

### ISSUE THREAD

**Issue by gusttavoaguiarr** [training-center/mentoria#296]
E ae, beleza?. Me chamo Gustavo, tenho 24 anos, moro em Umuarama no interior do Paraná, estou prestes a me formar em Sistemas de Informação faltando apenas a apresentação do TCC :D irru \o/ e atualmente venho fazendo Pós Graduação em desenvolvimento WEB.

já trabalho na área já faz 2 anos e 10 meses :D, comecei focado no front-end mas com o decorrer do tempo começei a mexer com o back-end também e hoje em dia eu só tenho trabalhado com o back-end. 

No desenvolvimento back-end utilizo o PHP, já trabalhei com 3 frameworks, Lumine :D, Zend Framework 1/2 e atualmente trabalho com Laravel.

Sobre a mentoria, eu gostaria de um foco em Python é algo que venho tendo muito interesse e precisava de um mentor que me desse um caminho :D, mas também gostaria de melhorar o meu desenvolvimento no PHP. Hoje eu sinto muito a falta de desafios, atualmente consigo resolver todos os problemas da empresa mas eu gostaria de estar apto para conseguir resolver grandes problemas :D.

Desde já agradeço

**Nível de conhecimento atual:** HTML5, CSS3 e JS/Jquery (Intermediário), PHP (Intermediário) e PYTHON ( Sem conhecimento ainda )

**Contatos:** gusttavoaguiarr@gmail.com

**Comment by danilovaz** [comment]
Bem vindo @gusttavoaguiarr   !

Vamos ver se algum dos @training-center/mentors consegue te ajudar com Back-End, Python e PHP :smile: 

Enquanto isso, se ainda não leu, leia o documento de [Responsabilidades do Pupilo](https://github.com/training-center/mentoria/blob/master/pupilos/responsibility.md)!! :smile:

**Comment by gusttavoaguiarr** [comment]
Massa :D, valeu @danilovaz, fico no aguardo

**Comment by woliveiras** [comment]
Estamos com todos os Mentores e Mentoras ocupados no momento, adicionei a label `wait for new mentors` para que os próximos busquem por essas issues primeiro.

**Comment by mrprompt** [comment]
Tudo bom @gusttavoaguiarr ? Manjo pouco de Python, mas posso ser seu mentor no back-end/php se você desejar.

**Comment by gusttavoaguiarr** [comment]
Tudo certo Thiago, por mim fechooo :D :D

**Comment by danilovaz** [comment]
Olá pessoal!

Legal que estão se ajeitando nisso.

Não esqueçam de atualizar ou criar seus perfis no [repositório](https://github.com/training-center/mentoria/blob/master/helpers/README.md) e entrar no nosso [Slack](https://ctgroups.herokuapp.com/).

Assim que fizerem isso, me avisem aqui na issue para fechá-la.

**Comment by gusttavoaguiarr** [comment]
@danilovaz feito! :D

**Comment by mrprompt** [comment]
Eu e o @gusttavoaguiarr já estamos trocando uma idéia no Slack, acho que este card está ok.

**Comment by danilovaz** [comment]
@mrprompt  O seu PR #334 está OK. Mas o @gusttavoaguiarr precisa atualizar o PR da lista de pupilos em ordem alfabética, conforme eu citei em #322 . Aí sim, podemos fechar e sucesso :tada: :smile:

**Comment by gusttavoaguiarr** [comment]
@danilovaz perdão mano :D, ta feito :D valeeeu

**Comment by danilovaz** [comment]
Perfil do pupilo atualizado em #322 e #335 Sucesso :tada:
