### ISSUE TITLE
Preciso de um mentor para desenvolvimento WordPress

### ISSUE THREAD

**Issue by santosluiz** [training-center/mentoria#297]
Nome: Luiz Santos

Descrição: Tenho 19, faço Sistema da Informação e trabalho como front há 1 ano, principalmente criando sites para WordPress. Já tenho desenvolvo temas e gostaria de uma mentoria em relaçao a boas práticas e também desenvolvimento de plugins.

Nível de conhecimento atual: HTML5, CSS3, JavaScript, jQuery, SEO, WordPress.

Contatos:
E-mail: 97luizsantos@gmail.com
Facebook: https://www.facebook.com/eu.santosluiz
Linkedin: https://www.linkedin.com/in/santosluizz

**Comment by danilovaz** [comment]
Bem vindo @santosluiz  !

Vamos ver se algum dos @training-center/mentors consegue te ajudar com o Wordpress!

Enquanto isso, se ainda não leu, leia o documento de [Responsabilidades do Pupilo](https://github.com/training-center/mentoria/blob/master/pupilos/responsibility.md)!! :smile:

**Comment by santosluiz** [comment]
Obrigado pela força @danilovaz! Já li sim!

**Comment by woliveiras** [comment]
Estamos com todos os Mentores e Mentoras ocupados no momento, adicionei a label `wait for new mentors` para que os próximos busquem por essas issues primeiro.

**Comment by luizbills** [comment]
@santosluiz sou mentor de wordpress. Bora?

**Comment by santosluiz** [comment]
@luizbills Vamos ou bora?  😎😎

Te enviei uma mensagem no facebook!

**Comment by luizbills** [comment]
@woliveiras pode fechar essa issue. Esse pupilo está comigo já

**Comment by woliveiras** [comment]
Pra já @luizbills 

Valeu!
