### ISSUE TITLE
Doação, sim ou não, eis a questão?

### ISSUE THREAD

**Issue by woliveiras** [training-center/mentoria#3]
Issue para tratarmos sobre as doações para os Mentores.

cc: @baltazarparra @danilovaz @LFeh @JGcarv @willycamargo @icaromh @sanderweb @augustoabreu @robsonbittencourt

**Comment by woliveiras** [comment]
Doação opcional, acho maneiro.

Poderia ser até tratado entre o pupilo direto com o Mentor. Se o pupilo quiser doar pro cara, pede a conta dele ou coisa do tipo. O que acham?

**Comment by danilovaz** [comment]
Acho doação opcional válida. Quem puder e quiser, doa. Quem não puder ou não quiser, não tem essa obrigação.

Dependendo de como serão organizadas as apresentações dos mentores, pode ser que um link para doações no estilo do pag seguro seja uma boa. Assim ele pode não só receber doações de seus pupilos, como de outros mentores e até outras pessoas da comunidade que acreditem no potencial de transformação da mentoria.

**Comment by jlamim** [comment]
A doação opcional para o mentor é interessante, é uma forma dele se motivar ainda mais pelo trabalho realizado, independente do valor.

A colocação do @danilovaz é perfeita sobre isso.

**Comment by woliveiras** [comment]
@danilovaz, cara perfeito!

**Comment by LFeh** [comment]
Doação opcional, sem dúvidas :)

**Comment by baltazarparra** [comment]
Doações opcionais decidido. Agora precisamos polir o formato da doação pra evitar ruídos.

**Comment by JGcarv** [comment]
Acho importante arrumar o forma de deixar claro que é opcional, e serve apenas como agradecimento/reconhecimento, inclusive pelos mentores. A mentoria deve sempre ser feita com o espírito de "give back" e não com uma motivação monetária.

Hoje, por exemplo, 10% de para garçom é opcional, mas o sistema está estruturado de tal forma que parece obrigação, o que eu acho que não cria um clima legal...

**Comment by woliveiras** [comment]
Verdade @JGcarv.

O esquema de deixar um link no perfil do Mentor pra um PayPal da vida é sucesso!

Da pra deixarmos arquivos com o nome do Mentor, os skills dele e em qual área ele se propõe a ajudar (Back, Front, Mobile, etc).

**Comment by woliveiras** [comment]
Já vou criar um folder para os perfis e um template

Carmae...

**Comment by woliveiras** [comment]
Tá lá! Só opinarem sobre o template de perfil galera. :)

**Comment by woliveiras** [comment]
Informei sobre a ajuda ao Mentor [aqui](https://github.com/training-center/mentoria#quero-retribuir-a-ajuda-do-meu-mentor-ou-colaborar-com-os-que-est%C3%A3o-ajudando).

Se tudo estiver OK, podemos fechar a issue.

**Comment by danilovaz** [comment]
@woliveiras acho que pode ser fechada sim, até para nos organizarmos melhor

**Comment by woliveiras** [comment]
Maravilha.
