### ISSUE TITLE
Preciso de um mentor para Android 

### ISSUE THREAD

**Issue by gabrielsouzaa** [training-center/mentoria#306]
Nome: Gabriel Souza

Descrição: Tenho 19, faço Análise e Desenvolvimento de Sistemas e trabalho como DevMobile há 8 meses, desenvolvendo aplicativos para uma empresa nacional.  Já tenho um breve conhecimento com apps básicos e comunicação com webservice. Gostaria de uma mentoria em relação a boas práticas e também tópicos um pouco mais avançados. Atualmente estou cursando Android Basics na Udacity. 

Nível de conhecimento atual: Java (Formado no curso "Academia JAVA" pela empresa GlobalCode e estudando para a certificação). PHP e C básico.

Contatos:
E-mail: contato@gabrielsouzaa.com
Linkedin: https://br.linkedin.com/in/gabriel-souza-48735b82

**Comment by diegomalone** [comment]
Opa @gabrielsouzaa 

Bacana esse seu interesse em desenvolvimento nativo Android. Dá uma olhada no [meu perfil](https://github.com/training-center/mentoria/blob/master/mentores/perfis/diegomalone.md) e se achar bacana, pode contar comigo. 😉

**Comment by woliveiras** [comment]
Já vai entrar direto no Work In Progress!

QUE SUCESSO.

Você leu as [Responsabilidades do Pupilo](https://github.com/training-center/mentoria/blob/master/pupilos/responsibility.md), @gabrielsouzaa?

**Comment by gabrielsouzaa** [comment]
Opa, bacana!
Já sim @woliveiras !

**Comment by woliveiras** [comment]
\o/

Isso mesmo @gabrielsouzaa.

Depois o @diegomalone atualiza o dele e é só sucesso!

**Comment by giovannicruz97** [comment]
Boa Garoto! @gabrielsouzaa

**Comment by woliveiras** [comment]
Perfeito!
