### ISSUE TITLE
Preciso de um mentor de JavaScript

### ISSUE THREAD

**Issue by pamelasouza** [training-center/mentoria#307]
**Nome:** Pâmela Pereira de Souza

**Descrição:** Atualmente trabalho como designer gráfico, mas meu objetivo é desenvolver e atuar como front-end. 

**Nível de conhecimento atual:** Junior - HTML5, CSS e LESS.

**Contatos:** 
Facebook - https://www.facebook.com/pamdora10
Portfólio - www.pamelasouza.com

**Comment by matmarsiglio** [comment]
@training-center/moderators essa eu trouxe, eu pego a responsa! Trabalha aqui na Evino e vou auxiliar nos estudos com Javascript :)

**Comment by matmarsiglio** [comment]
E fechando aqui!

**Comment by woliveiras** [comment]
Show de bola @matmarsiglio 

Não se esqueçam de criar/atualizar os perfis pra ficar registrado aqui no repo. :smile:

**Comment by matmarsiglio** [comment]
@woliveiras tá tudo feito já! ;)

**Comment by woliveiras** [comment]
🤘 🤘 🤘 🤘
