### ISSUE TITLE
Preciso de um(a) mentor(a) para desenvolvimento Back End em Python.

### ISSUE THREAD

**Issue by ffabiorj** [training-center/mentoria#31]
## Nome: 
Fábio Macêdo Oliveira

## Descrição: 
Sou iniciante em programação, tenho conhecimentos em python de iniciante para intermediário, sei o básico de html/css. Gostaria de uma mentoria para desenvolvimento de um app web do inicio ao fim, feito em Django ou Flask.

## Nível de conhecimento atual: 
Iniciante para intermediário em programação.

## Contatos: 
https://twitter.com/ffabiorj

**Comment by woliveiras** [comment]
Vou compartilhar essa issue nos grupos de Python pra trazer mais Mentores da linguagem @ffabiorj.

Valeu pelo interesse.

**Comment by davinirjr** [comment]
E aí, Fábio, em que podemos ajudá-lo?

**Comment by woliveiras** [comment]
Veeeem monstro! 

Segue [esse fluxo](https://github.com/training-center/mentoria#quero-ser-um-mentora) pra criar seu perfil de Mentor mano @davinirjr 

\o/

Valeu cara!

**Comment by ffabiorj** [comment]
@woliveiras Vem mostro foi foda. huauauhhuahuahua

@davinirjr Cara, queria um help para criar app web. Qual melhor jeito de começa? Eu vejo que muita gente começca pelo back e depois faz o front.

Obs: Sou muito ruim em css. Rsrsrs Não sei se é falta de pratica ou talento...uahuahuahua

**Comment by ishyevandro** [comment]
@ffabiorj, não sou mentor e ando precisando de um também, porém fikdik: da uma olhada nos frames de CSS (utilizo bastantes o bootstrap e acho simples), eles simplificam a vida e você só trabalha no que realmente precisa de um toque "personalizado"

**Comment by luanfonceca** [comment]
Como que noix resolve isso ai mestre?

Tu quer criar uma do zero ou aprender fazendo uma? Qualquer coisa cola com noix no http://github.com/luanfonceca/speakerfight pra fechar umas issue cmg

**Comment by woliveiras** [comment]
Que da hora esse negócio de Speakerfight ein @luanfonceca kkkkkkkkk

**Comment by MaximusXXX** [comment]
ae galera tô fazendo um merge sort em python tava precisando de uma ajuda

**Comment by davinirjr** [comment]
Voti, quantas mensagens pelamordedeus !!! :)

@woliveiras: também te amo !!! :*

Galera, eu não tenho disponibilidade durante o expediente, e procuro
atender por email.

@ffabiorj, o importante é a "dor do usuário" (o problema que você está se
propondo a resolver). Front é com o @woliveiras, backend (e Python/Django,
Java, etc) pode ser comigo - porque não manjo bosta nenhuma de front. :)

Mas melhor separar as threads senão vai virar uma micareta isso aqui - uma
coisa é desenvolvimento web, outra é merge sort.


Abraço.

**Comment by woliveiras** [comment]
@ffabiorj, uma dúvida: Essa sua necessidade é para um projeto específico ou para agregar a sua carreira?

Acabei deixando passar.

Se for para um projeto somente, use o [Grupo de estudos](https://github.com/training-center/study-groups).

O Mentoria é para agregar a sua carreira, ter uma pessoa mais experiente te ajudando para crescer profissionalmente.

:)

**Comment by woliveiras** [comment]
@MaximusXXX, uma dúvida dessa deve ser postada em um forum. 

Se precisar de ajuda em real time da até pra chamar a galera aqui no [Slack da Python Brasil](http://slack-pythonbrasil.herokuapp.com/). :)

**Comment by MaximusXXX** [comment]
saquei então vou chamar no forum

**Comment by woliveiras** [comment]
Valeu mano :D

**Comment by woliveiras** [comment]
@ffabiorj, vou fechar a issue, mas podemos reabrir depois, se precisar.
