### ISSUE TITLE
Preciso de um(a) mentor(a) de Full Stack

### ISSUE THREAD

**Issue by vanialadev** [training-center/mentoria#312]
**Nome:**
Vânia Almeida.

**Descrição e Nível de conhecimento atual:**
Oi, pessoal. 
Tô querendo um mentor em full stack, comecei a estudar um pouco de HTML, CSS, JS e Rails e gostei bastante, mas como no estágiando tô vendo mobile parei um pouco, mas tô querendo me aprofundar no Full Stack mesmo. 
Queria um mentor em qualquer linguagem, framework. Tô disposta a tudo e sempre buscando aprender algo a mais :dancer: 

Meu nível de conhecimento nessa área não é muito grande, como só estudava pra faculdade passei um bom tempo só em java. Aí decidi me matricular na Alura e descobri esse mundo novo por lá :) Fiz uns cursos nessas áreas de Ruby on Rails e Html e CSS, JavaScript que foi uma base bem legal, mas como não tenho muita ideia do que fazer depois não tô praticando e por isso decidi vir pra cá, enfim...  
Tô buscando aprender e continuar descobrindo esse novo mundo;D

**Contatos:**
<a href='https://www.facebook.com/vanialalmeida'>Facebook</a>
<a href='https://twitter.com/vanialalm'>Twitter</a>

**Comment by woliveiras** [comment]
Bem vinda @vanialadev!

Vamos ver se algum dos @training-center/mentors consegue te ajudar.

Enquanto isso leia o documento de [Responsabilidades do Pupilo](https://github.com/training-center/mentoria/blob/master/pupilos/responsibility.md)!! :smile:

**Comment by mrprompt** [comment]
Tudo bom @vanialadev , se você quiser, posso ser seu mentor.

**Comment by vanialadev** [comment]
Oi @mrprompt, eu quero, mas eu não sei nada de php, tinha pensado em python ou rails pra back. Pode ser?

**Comment by mrprompt** [comment]
@vanialadev eu sei muito pouco de Python, utilizo somente para coisas muito específicas - nenhuma relacionada a web - e Rails realmente não manjo nada.

**Comment by guilhermepontes** [comment]
Oi @vanialadev, tudo bem?

Estamos planejando desenvolver um web-app que vai ter como base uma API em Ruby on Rails. Mas nosso time só tem desenvolvedores front-end no momento (no qual vamos usar React + Redux), estamos precisando de uma pessoa para nos ajudar. :)

Te interessa?
Dá uma olhada no meu perfil [aqui](https://github.com/training-center/mentoria/blob/master/mentores/perfis/guilhermepontes.md)!

**Comment by vanialadev** [comment]
Oi @guilhermepontes, me interesso sim :D
Por mim, tô dentro!

**Comment by guilhermepontes** [comment]
@vanialadev, faz o cadastro no [Slack](https://ctgroups.herokuapp.com/) pra gente conversar. :)

**Comment by vaniala** [comment]
Oi, já tô no slack. Vou falar contigo lá.

**Comment by ftonato** [comment]
Fala @vaniala, como está o andamento dessa _issue_?
- [X] Encontrou o mentor?
- [ ] O mentor entrou em contato com você?

/cc @guilhermepontes
