### ISSUE TITLE
Preciso de um(a) mentor(a) de Frontend/Web.

### ISSUE THREAD

**Issue by diegoroso** [training-center/mentoria#314]
Nome: **Diego Roso da Silva**

Objetivo: Descobrir como posso usar e ampliar meu conhecimento da melhor forma possível. 
Interesses: Front-end para websites. (angular, vue.js e demais que possam me auxiliar)

Nível de conhecimento atual:

- PHP
- JavaScript
- HTML
- CSS
- Alguns Frameworks e CMS's PHP
- Grunt/Gulp
- Git
- NPM/Bower

Contatos: 

- Email: silva95diego@hotmail.com
- Slack: @diegoroso
- Linkedin: https://www.linkedin.com/in/diegoroso

**Comment by ogilvieira** [comment]
Bem vinda @diegoroso!
Vamos ver se algum dos @training-center/mentors consegue te ajudar.
Enquanto isso leia o documento de [Responsabilidades do Pupilo](https://github.com/training-center/mentoria/blob/master/pupilos/responsibility.md)!! 😄

**Comment by ogilvieira** [comment]
@diegoroso Só mais uma coisa, pode ser mais especifico quanto a área em que quer atuar?
Seus conhecimentos são abrangentes em tecnologias web e isso é muito bom, talvez o que esteja procurando é em que parte do desenvolvimento quer atuar (Front-end ou Back-end) e em qual mercado (websites e produtos).

O que você curte mais fazer?

**Comment by diegoroso** [comment]
@ogilvieira Obrigado. 

Coloquei um tópico de "interesses" no post, assim fica mais fácil de saberem.

**Comment by wagnerssouza** [comment]
Oi @diegoroso, se seu foco é front (html, css e js), posso te ajudar 😃

**Comment by diegoroso** [comment]
oi @wagnerssouza, sua ajuda será muito bem vinda 👍

**Comment by wagnerssouza** [comment]
Legal, Vamos trocar uma ideia, me manda um email: wagneersantos@gmail.com

**Comment by wagnerssouza** [comment]
@diegoroso ,bora começar a brincadeira?

**Comment by ftonato** [comment]
Fala @diegoroso, como está o andamento dessa _issue_?
- [X] Encontrou o mentor?
- [ ] O mentor entrou em contato com você?

/cc @wagnerssouza

**Comment by woliveiras** [comment]
Pessoal nosso processo mudou: https://medium.com/trainingcenter/e-o-mentoria-mudou-mais-uma-vez-5ad8725bc778

Peço, por favor, que responda esse formulário, caso ainda faça sentido, para que algum mentor ou mentora entre em contato contigo quando possível: http://bit.ly/preciso-de-mentoria

A issue será fechada para que não aconteçam desencontros de informação.
