### ISSUE TITLE
Preciso de um(a) mentor(a) de PHP (Laravel) com uma pegada full-stack.

### ISSUE THREAD

**Issue by xfilipe** [training-center/mentoria#315]
**Nome:**

Filipe Teixeira Amaral

**Descrição:**

E ai galera, sou desenvolvedor Full-Stack em inicio de carreira, quase terminando Ciência da Computação. Acabei de voltar de um intercambio de 3 meses na Eslováquia (sim, Eslováquia =P) onde trabalhava como front-end utilizando AngularJS 1.x e também já trabalhei como bolsista na faculdade fazendo back-end com Flask (Python) e front-end (html, css e jquery). Atualmente estou começando uma agencia com dois amigos e nosso foco atual é utilizar Wordpress no que puder e nos projetos mais complexos utilizar Laravel. Procuro algum mentor de PHP que possa me ajudar a subir de nível como programador.

**Nível de conhecimento atual:**

Acredito que de básico a intermediário em full-stack.

**Contatos:** 

- [facebook](https://www.facebook.com/filipetamaral)
- [StackOverflow](http://stackoverflow.com/users/4338325/xfilipe?tab=profile)
- filipetamaral@gmail.com

**Comment by woliveiras** [comment]
Bem vindo @xfilipe 

Vamos ver se algum dos @training-center/mentors consegue te ajudar.

Enquanto isso leia o documento de [responsabilidades do pupilo](https://github.com/training-center/mentoria/blob/master/pupilos/responsibility.md)!! :smile:

**Comment by erikfig** [comment]
Bom dia @xfilipe 

Eu posso te ajudar, da uma olhada no meu perfil e se topar já marcamos um dia pra conversarmos.

**Comment by ftonato** [comment]
Fala @xfilipe, como está o andamento dessa _issue_?
- [X] Encontrou o mentor?
- [ ] O mentor entrou em contato com você?

/cc @erikfig

**Comment by xfilipe** [comment]
sim, entrei em contato com mais de um mentor alias e tirei as duvidas que queria. Obrigado :smile:

**Comment by ftonato** [comment]
Legal, @xfilipe podemos encerrar a _issue_?
