### ISSUE TITLE
Preciso de um mentor Back End em Ruby

### ISSUE THREAD

**Issue by marceloluizleite** [training-center/mentoria#316]
# **Nome:** 
Marcelo Luiz Leite

# **Descrição:** 
Olá, bom dia! Conheci o projeto a pouco e gostaria de auxilio de um mentor que pudesse me auxiliar com o desenvolvimento de minha carreira visando me tornar desenvolvedor. Hoje trabalho como suporte técnico e gostaria de migrar de área.

# **Nível de conhecimento atual:** 
Venho estudando a alguns meses e já tenho experiência em nível básico de Ruby.

# **Contatos:** 
[https://br.linkedin.com/in/marceloluizleite](url)
[https://www.facebook.com/marcelo.luiz.1426](url)

**Comment by marceloluizleite** [comment]
Pessoal, já conheço o @vyper e conversamos pelo fb. Criei a issue para seguir o fluxo normal do processo. Ele me disse que no momento está em viagem e voltando (previsão Dezembro/16) estaremos iniciando.

**Comment by vyper** [comment]
Isso aí, acertamos uma agenda para o início de dezembro que ficou ok para ambos... Agora é só esperar o @training-center/moderators darem as orientações do processo @marceloluizleite. (:

**Comment by marceloluizleite** [comment]
ok Leonardo ( @vyper ) desde já agradeço pela atenção.!

=D

**Comment by woliveiras** [comment]
Perfeito @marceloluizleite e @vyper 

Marcelo, agora é só criar o seu perfil aqui no [repositório](https://github.com/training-center/mentoria/blob/master/helpers/README.md).

Assim que você terminar o Leonardo atualiza o perfil dele e já era! Sucesso.

**Comment by woliveiras** [comment]
Galera, tudo certo entre vocês?

Não se esqueçam de atualizar/criar seus perfis ou avisar aqui se já o fizeram. :smile:

**Comment by woliveiras** [comment]
Fala galera, fechando a issue por inatividade.

Qualquer problema é só avisar.
