### ISSUE TITLE
Preciso de um mentor para Java, HTML e CSS

### ISSUE THREAD

**Issue by DPabloR** [training-center/mentoria#317]
**Nome:**

Dario Pablo Ribeiro

**Descrição:**

Estou me graduando em Análise e Desenvolvimento de Sistemas e preciso de um mentor em Java, HTML e CSS. Pretendo me aprofundar nessas linguagens para conseguir um trabalho ou estágio, em qualquer empresa séria. Gostaria de ser apresentado à linguagem SAP também.

**Nível de conhecimento atual:**

Não possuo conhecimento, estou treinando algoritmos e iniciando Java e HTML.

**Contatos:**

[Facebook](https://www.facebook.com/dario.pabloribeiro)
[Twitter](https://twitter.com/DarioPRibeiro)
[LinkeIn](https://br.linkedin.com/in/dario-pablo-ribeiro-345625130)

**Comment by woliveiras** [comment]
Bem vindo @DPabloR 

Alterei o título da issue pra não ficar parecendo que você precisa especificamente de um professor de ADS.

Vamos ver se algum dos @training-center/mentors consegue te ajudar.

Enquanto isso da uma olhada no documento de [responsabilidades do pupilo](https://github.com/training-center/mentoria/blob/master/pupilos/responsibility.md). :smile:

**Comment by lflimeira** [comment]
Boa tarde @DPabloR, tudo bem?

**Comment by woliveiras** [comment]
@DPabloR nosso processo mudou: https://medium.com/trainingcenter/e-o-mentoria-mudou-mais-uma-vez-5ad8725bc778

Peço, por favor, que responda esse formulário para que algum mentor ou mentora entre em contato contigo quando possível: http://bit.ly/preciso-de-mentoria

A issue será fechada para que não aconteçam desencontros de informação.
