### ISSUE TITLE
Preciso de um mentor para um iniciante em Front-end

### ISSUE THREAD

**Issue by TiagoFuelber** [training-center/mentoria#318]
Buenas.

Comecei meus estudos há 3 meses mais ou menos e há 1 mês estou seguindo o currículo do FreeCodeCamp. Comecei do zero mesmo, antes disso eu não sabia nada, nem o que era front e back, mas queria aprender. 
Tô muito focado, eu estudo uma média de 5~6 horas por dia (na tentativa de estudar 8, mas as vezes não dá), tenho até uma planilha de controle.

Possuo conhecimentos básicos em HTML, CSS, JS, Jquery, 

Meu objetivo a curto prazo é conseguir um trampo Jr  pra pegar um xp legal. (não to na faculdade, não posso pegar estágio).

No médio e longo prazo quero trabalhar pra alguma empresa gringa (aproveitar que meu inglês é bom), remoto ou presencial.

No FreeCodeCamp vou aprender JS e frameworks, MongoDB e NodeJS. Quero seguir essa linha meanstack.

Meus links.

[codepen.io/tfuelber](codepen.io/tfuelber)
[br.linkedin.com/in/tiagofuelber](br.linkedin.com/in/tiagofuelber)
[freecodecamp.com/tiagofuelber](freecodecamp.com/tiagofuelber)
[facebook.com/tiago.fuelber](facebook.com/tiago.fuelber)
[@TiagoSaft](https://twitter.com/TiagoSaft)

Abraço!

**Comment by woliveiras** [comment]
@TiagoFuelber, atualizei a descrição pra ficar mais curta e mais focada e adicionei os links para os seus perfis. :)

Muito bom você já estar preparado para as vagas gringas cara! Inglês é a base! Espero que consiga algo pra fora logo. São excelentes oportunidades.

Vamos ver se alguém dos @training-center/mentors consegue te ajudar.

Enquanto isso, da uma olhada nas [responsabilidades do pupilo]((https://github.com/training-center/mentoria/blob/master/pupilos/responsibility.md)).

**Comment by jessuircleydson** [comment]
Opa @TiagoFuelber  tamo ai :D da um hello no telegram @jessuircleydson ou no facebook(preferencia telegram hehe) pra gente vê se da certo flw /o/

**Comment by jessuircleydson** [comment]
@TiagoFuelber Vi que você ta no slack, da um hello lá que também da certo :D

**Comment by danilovaz** [comment]
Pessoal, fecharam essa issue mas a conversa da mentoria rolou, pelo que eu vi nos PR's: #323 #324 e #325 certo?

Estou reabrindo essa issue e peço, por favor, que façam a atualização do andamento da conversa de vocês aqui. Se o @TiagoFuelber aceitou o @jessuircleydson como mentor, avisa a gente aqui que o @woliveiras explica o fluxo pra vocês, assim nos ajuda a manter mais organizado, beleza?

Valeu :heart:

**Comment by jessuircleydson** [comment]
Opa @danilovaz ta rolando sim man.
Fui procurar a issue e tinha sumido, ai a cabeça deduzio: ta resolviso. Rsrs

Vlw ai :)

**Comment by woliveiras** [comment]
:raised_hands: :raised_hands: :raised_hands: 

Então, agora sim, podemos fechar. kkk
