### ISSUE TITLE
Preciso de um(a) mentor(a) de Desenvolvimento C#/C++

### ISSUE THREAD

**Issue by chungrob** [training-center/mentoria#319]
Nome: Robson Oliveira
Idade:19 anos

Descrição

Nunca trabalhei com programação porem faço ADS e tenho conhecimento básico em ambas linguagens (mais conhecimento acadêmico), gostaria de encontrar orientação para me ajudar aprender a programar de verdade (minha maior dificuldade é sair do básico) e por fim me dar um norte para entrar no mercado de trabalho.

Contatos:

1. Email: oliveira.robs@outlook.com
1. Facebook: https://www.facebook.com/robson.oliveira.10297701

**Comment by woliveiras** [comment]
Bem vindo @chungrob!!

Muito bom você estar na faculdade e já procurar um direcionamento de alguém que esteja no mercado de trabalho. Vai ajudar muuuuuuito!

Vamos ver se algum dos @training-center/mentors consegue te ajudar.

Enquanto isso leia o documento de [Responsabilidades do Pupilo](https://github.com/training-center/mentoria/blob/master/pupilos/responsibility.md)!! :smile:

**Comment by chungrob** [comment]
Muito obrigado,fico no aguado 
consegui ler tudo já

**Comment by woliveiras** [comment]
Se quiser pode criar sim cara.

Nós recomendamos depois que tiver o Mentor só pra não ter dois trabalhos (criar e depois atualizar), pois pode acabar esquecendo. 😂

**Comment by chungrob** [comment]
Rapaz fui o unico que sobrou hahhahahhaha

**Comment by alexsmonte** [comment]
Não sou um expert em C/C++  mas podemos aprender juntos.

**Comment by chungrob** [comment]
Então bora,você tem algum livro especifico que quer usar ou método para começar?(tenho uma boa notação básica de logica de programação)

**Comment by alexsmonte** [comment]
vc ja consegue fazer o basicao em C ?

**Comment by chungrob** [comment]
Sim,eu consigo em C e C++.

**Comment by alexsmonte** [comment]
https://learnxinyminutes.com/docs/pt-br/c-pt/

https://learnxinyminutes.com/docs/pt-br/c++-pt/


da uma lida nisso sempre tem algo q agente nao sabe ainda ou nao entende...

**Comment by chungrob** [comment]
vou dar um lida melhor nisso,é preciso criar um perfil aqui?

**Comment by alexsmonte** [comment]
vamos na boa... 

depois q tu ler e entender melhor agente pode decidir o q fazer... e mta coisa vamos ter q ir atras pq tem pouco material na internet... e eh dificil achar... 

quando acha... acha pronto.. tipo eu tava procurando como varrer as portas UBS achei uma lib isso eu nao queria. :D

**Comment by chungrob** [comment]
Eu concordo ,material na internet para essa linguem são bem poucas mesmo,vou começar a ler o que mandou.

**Comment by woliveiras** [comment]
Shooow de bola ein.

Vou fechar a issue por vocês já estarem acertados de estudar juntos.

Falando nisso, vocês podem até criar um grupo de estudos e chamar a galera no Slack, que tal?

**Comment by chungrob** [comment]
Pelo que eu vi aqui,estou com mais dificuldade em funções(essa ideia do grupo é legal).

**Comment by woliveiras** [comment]
Chama a galera lá no Slack, @chungrob 

Pode criar um canal, caso não exista, depois avisa no canal `general` que quer formar esse grupo. 

Aqui tem algumas dicas: https://github.com/training-center/study-groups

Não tem regras sobre como fazer, como estudar ou coisa do tipo. É tudo livre! ;D

**Comment by alexsmonte** [comment]
@chungrob  como assim funcoes ???

**Comment by chungrob** [comment]
@alexsmonte foi mal demora para responder(tive uns problemas com a internet e a semana de provas)mas no caso das minha dificuldade são conseguir achar funções(bibliotecas) que seja ultiu para usar em alguma parte do programa(no caso ler elas para entender com o se usa).

**Comment by chungrob** [comment]
@woliveiras  achei bacana,vou começar a ver isso,quem sabe amanha já não crie.

**Comment by alexsmonte** [comment]
@chungrob eh realmente dificil encontrar qualquer coisa... 

esse mundo do C e C++ tem mto mais ego do q se imagina :D então o povo se orgulha em geral de nao usar bibliotecas etals... apesar de existirem eu mesmo encontrei uma q verificava as portas UBS

Mas isso era o q eu nao queria huahu huahuahu :D 

queri justamente conseguir fazer as libs

**Comment by chungrob** [comment]
Isso que é foda,por isso que estava pensando em realmente migra para o C# já que as libs dele são muito grande.Mas o foda que eu não consigo ler as libs mesmo encontrando(ler no sentido de entender e usar ela da forma que quero).

**Comment by chungrob** [comment]
tenho muito que aprender.
