### ISSUE TITLE
Preciso de um(a) mentor(a) Full Stack Python e Ruby

### ISSUE THREAD

**Issue by beatrizuezu** [training-center/mentoria#328]
Beatriz Harumi Uezu
22 anos

Sou formada em ADS e atualmente trabalho com Desenvolvimento Web Python faz pouco tempo e estou em busca de melhorar meus conhecimentos em Front-End, Python/Django e também em Ruby on Rails. Já estagiei em Front-End, mas sai da área de web e fui para desenvolvimento em VB.Net e SQL. Participo de um grupo de mulheres que ensinam programação em Python.
Busco um(a) mentor(a) para me ajudar com recomendações, boas práticas e melhores formas de se programar.

email: beatriz.uezu@gmail.com
telegram: @beatrizuezu
facebook: https://www.facebook.com/beatrizuezu

**Comment by danilovaz** [comment]
Seja muito bem vinda @beatrizuezu ! :smile: 

Vamos ver se algum dos @training-center/mentors consegue te ajudar com Front, Python/Django e Ruby on Rails :rocket: :tada: 

Enquanto isso, se ainda não leu, leia o documento de [Responsabilidades do Pupilo](https://github.com/training-center/mentoria/blob/master/pupilos/responsibility.md)!! :smile:

**Comment by diegoponciano** [comment]
Olá @beatrizuezu, você quer mentoria web ou programação em geral?  
Eu trabalho com Python/Django e já brinquei com Ruby, mas já tive que trabalhar em projetos VB.NET e stored procedures também.

**Comment by guilhermepontes** [comment]
Oi @beatrizuezu, tudo bem?

Estamos planejando desenvolver um web-app que vai ter como base uma API em Ruby on Rails. Mas nosso time só tem desenvolvedores front-end no momento (no qual vamos usar React + Redux), estamos precisando de uma pessoa para nos ajudar. :)

Te interessa?
Dá uma olhada no meu perfil [aqui!](https://github.com/training-center/mentoria/blob/master/mentores/perfis/guilhermepontes.md)
<br><br>
@diegomalone foi mal ae! hahahah tâmo precisando de mão de obra aqui! huahuahuaahhua

**Comment by beatrizuezu** [comment]
Olá @diegoponciano, procuro mentoria em web...
Ultimamente o meu foco está sendo em front-end e django!

**Comment by diegoponciano** [comment]
@beatrizuezu legal, web é mais minha praia :D   
Vou te mandar mensagem no telegram.

**Comment by danilovaz** [comment]
Olá pessoal! 

Legal que estão se ajeitando nisso. :tada: 

Não esqueçam de atualizar ou criar seus perfis no [repositório](https://github.com/training-center/mentoria/blob/master/helpers/README.md) e entrar no nosso [Slack](https://ctgroups.herokuapp.com/).

Assim que fizerem isso, me avisem aqui na issue para fechá-la.

**Comment by woliveiras** [comment]
Fala pessoal, falta somente um ajuste no PR da @beatrizuezu: #368
