### ISSUE TITLE
Preciso de um Mentor pra Front

### ISSUE THREAD

**Issue by fgleyson** [training-center/mentoria#329]
**Nome:** Francisco Gleyson Ferreira dos Santos

**Descrição:** Tenho 30 anos, gosto muito da área de Tecnologia, e gostaria muito de um mentor pra me       ajuda e ensinar a programar com ótima qualidade pra mim ter um ótimo emprego em que gosto

**Nível de conhecimento atual:** Muito básico, somente assistindo algumas vídeo aulas no YouTube e vendo           algumas tag's de HTML. 

**Contatos:** FaceBook: https://www.facebook.com/fgleyson
                      E-Mail: gleyson_78@hotmail.com

**Comment by danilovaz** [comment]
Seja muito bem vindo @fgleyson ! :smile: 

Eu removi seu telefone dos comentários, evite colocar seu telefone em páginas publicas. Você pode ter muita dor de cabeça com isso: ligações indesejadas, mensagens, trotes, etc. Também arrumei as tags do Markdown :smiley: 

Vamos ver se algum dos @training-center/mentors consegue te ajudar com o básico de programação. 

Enquanto isso, se ainda não leu, leia o documento de [Responsabilidades do Pupilo](https://github.com/training-center/mentoria/blob/master/pupilos/responsibility.md)!! :smile:

**Comment by fgleyson** [comment]
Obrigado!, sou novo e não sabia mexer direito. bom dia

________________________________
De: Danilo Vaz <notifications@github.com>
Enviado: terça-feira, 22 de novembro de 2016 02:56:34
Para: training-center/mentoria
Cc: Gleyson Santos; Mention
Assunto: Re: [training-center/mentoria] Preciso de um Mentor pra Front (#329)


Seja muito bem vindo @fgleyson<https://github.com/fgleyson> ! ??

Eu removi seu telefone dos comentários, evite colocar seu telefone em páginas publicas. Você pode ter muita dor de cabeça com isso: ligações indesejadas, mensagens, trotes, etc. Também arrumei as tags do Markdown ??

Vamos ver se algum dos @training-center/mentors<https://github.com/orgs/training-center/teams/mentors> consegue te ajudar com o básico de programação.

Enquanto isso, se ainda não leu, leia o documento de Responsabilidades do Pupilo<https://github.com/training-center/mentoria/blob/master/pupilos/responsibility.md>!! ??

-

**Comment by lflimeira** [comment]
Boa tarde  @fgleyson, tudo bem? Você já encontrou algum mentor?

**Comment by fgleyson** [comment]
Boa noite, tudo bem, e não eu ainda não tenho nenhum mentor e quero muito ser um ótimo programador.

________________________________
De: Luiz Felipe de Oliva Limeira <notifications@github.com>
Enviado: terça-feira, 2 de maio de 2017 16:18:51
Para: training-center/mentoria
Cc: Gleyson Santos; Mention
Assunto: Re: [training-center/mentoria] Preciso de um Mentor pra Front (#329)


Boa tarde @fgleyson<https://github.com/fgleyson>, tudo bem? Você já encontrou algum mentor?

**Comment by lflimeira** [comment]
@fgleyson da uma olhada no meu perfil e se topar já marcamos um dia pra conversarmos.

**Comment by fgleyson** [comment]
Boa noite, gostei, topo sim, quero muito ser um desenvolvedor, como vai ser?
________________________________
De: Luiz Felipe de Oliva Limeira <notifications@github.com>
Enviado: quarta-feira, 3 de maio de 2017 08:01:00
Para: training-center/mentoria
Cc: Gleyson Santos; Mention
Assunto: Re: [training-center/mentoria] Preciso de um Mentor pra Front (#329)


@fgleyson<https://github.com/fgleyson> da uma olhada no meu perfil e se topar já marcamos um dia pra conversarmos.

**Comment by lflimeira** [comment]
@fgleyson vc tem Telegram? Se tiver me chama lá @lflimeira, e eu ti passo os detalhes.

**Comment by fgleyson** [comment]
ok
________________________________
De: Luiz Felipe de Oliva Limeira <notifications@github.com>
Enviado: quinta-feira, 4 de maio de 2017 09:27:19
Para: training-center/mentoria
Cc: Gleyson Santos; Mention
Assunto: Re: [training-center/mentoria] Preciso de um Mentor pra Front (#329)


@fgleyson<https://github.com/fgleyson> vc tem Telegram? Se tiver me chama lá @lflimeira<https://github.com/lflimeira>, e eu ti passo os detalhes.

**Comment by fgleyson** [comment]
boa noite eu não encontrei seu telegram, esta ai o meu @fgleyson

________________________________
De: Luiz Felipe de Oliva Limeira <notifications@github.com>
Enviado: quinta-feira, 4 de maio de 2017 09:27:19
Para: training-center/mentoria
Cc: Gleyson Santos; Mention
Assunto: Re: [training-center/mentoria] Preciso de um Mentor pra Front (#329)


@fgleyson<https://github.com/fgleyson> vc tem Telegram? Se tiver me chama lá @lflimeira<https://github.com/lflimeira>, e eu ti passo os detalhes.

**Comment by woliveiras** [comment]
@fgleyson nosso processo mudou: https://medium.com/trainingcenter/e-o-mentoria-mudou-mais-uma-vez-5ad8725bc778

Peço, por favor, que responda esse formulário caso faça sentido para que algum mentor ou mentora entre em contato contigo quando possível: http://bit.ly/preciso-de-mentoria

A issue será fechada para que não aconteçam desencontros de informação.
