### ISSUE TITLE
[Quero ser mentor] de WordPress e WooCommerce

### ISSUE THREAD

**Issue by luizbills** [training-center/mentoria#336]
**Nome:** Luiz Paulo
**Descrição:** Sou desenvolvedor front-end e back-end (usando wordpress) há uns 2 anos. Gosto de "fuçar" muito, criar soluções e ler bastante código para saber como as coisas funcionam por trás das cortinas. Não sou expertizão no wordpress, mas já aprendi umas maldades e creio que posso ajudar umas pessoas.
**Contatos:** [Facebook](https://www.facebook.com/luizpbfs)

**Comment by woliveiras** [comment]
Bem vindo @luizbills!!

Você já leu as [responsabilidades do mentor]((/mentores/responsibility.md)) e está de acordo com a ideia do projeto?

Creio que seu conhecimento em WordPress já vai contribuir com algumas pessoas: https://github.com/training-center/mentoria/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20wordpress

;D

Caso esteja de acordo com nossa "política" de Mentoria, vou compartilhar seu perfil com os outros mentores para analisarem.

**Comment by luizbills** [comment]
- [x] eu li e concordo :smile:

**Comment by woliveiras** [comment]
@luizbills pode criar seu perfil! 

Entendeu como funciona?

**Comment by woliveiras** [comment]
@luizbills,

Agora você pode seguir o novo fluxo: https://medium.com/@woliveiras/menos-burocracia-para-conseguir-um-mentor-ou-mentora-d571ed9cc3e0#.8sysjowyx

Pode criar o seu perfil seguindo o esquema: https://github.com/training-center/mentoria#quero-ser-mentora

Caso tenha alguma dúvida ou o tutorial não esteja claro, me de um toque.

Assim que subir seu perfil, aconselho que pegue as issues abertas para tentar encontrar um pupilo antes de seguir o novo fluxo, pois precisamos ajudar quem já estava seguindo o fluxo antigo.

**Comment by woliveiras** [comment]
@luizbills 

Você já está no nosso Slack?

**Comment by woliveiras** [comment]
O perfil foi adicionado a org.

Agora já pode seguir o fluxo informado aqui: https://github.com/training-center/mentoria/issues/336#issuecomment-263437358

Preciso somente do seu usuário no Slack para adicionar ao canal dos mentores. :)

**Comment by luizbills** [comment]
@woliveiras meu usuário é o **luizpf**. Essa semana está bem apertado, mas final de semana regularizo tudo que está faltando e já procuro um pupilo.

**Comment by woliveiras** [comment]
\o/

Perfeito @luizbills
