### ISSUE TITLE
Preciso de um(a) mentor(a) Full Stack PHP

### ISSUE THREAD

**Issue by Fredrumond** [training-center/mentoria#339]
**Nome:** Frederico Drumond
**Descrição:** Sou recém formado em Sistemas de Informação pela PUC-MG e ao decorrer do curso fui percebendo que a área de desenvolvimento web me chamava muita atenção e agora eu resolvi dar uma dedicação total nessa área. Sempre que eu começo estudar acabo perdendo o rumo e quando vou ver já estou estudando muitas coisas ao mesmo tempo e acaba que não pega o que tem que pegar de cada conteúdo que esta estudando. E meu objetivo um dia é ser mentor/professor e ensinar para as pessoas que estão iniciando que não é um monstro de 7 cabeças so precisa de uma boa orientação e determinação para chegar longe. E procuro um mentor para que possa me dar uma luz do caminho a ser seguido para não acabar me perdendo e conseguir uma experiencia em trabalhos pequenos para conseguir agregar meu currículo e me inserir no mercado de trabalho.
**Nível de conhecimento atual:**
HTML - intermediário
CSS- intermediário
JS - básico
PHP - intermediário
**Contatos:** 
[Facebook](https://www.facebook.com/frederico.drumond.33)
[Github](https://github.com/Fredrumond)

**Comment by danilovaz** [comment]
Seja muito bem vindo @Fredrumond  ! :smile: 

Vamos ver se algum dos @training-center/mentors consegue te ajudar! Alterei o título da sua issue para condizer melhor com o que você precisa.

Enquanto isso, se ainda não leu, leia o documento de [Responsabilidades do Pupilo](https://github.com/training-center/mentoria/blob/master/pupilos/responsibility.md)!! :smile:

**Comment by mrprompt** [comment]
@Fredrumond se quiser posso ser seu mentor brother.

**Comment by Fredrumond** [comment]
@mrprompt se tiver tudo certo pra você eu animo d+. To dentro

**Comment by danilovaz** [comment]
Olá pessoal! 

Legal que estão se ajeitando nisso. :tada: 

Não esqueçam de atualizar ou criar seus perfis no [repositório](https://github.com/training-center/mentoria/blob/master/helpers/README.md) e entrar no nosso [Slack](https://ctgroups.herokuapp.com/).

Assim que fizerem isso, me avisem aqui na issue para fechá-la.

**Comment by mrprompt** [comment]
@Fredrumond fechou brother, só falar comigo no slack então e mandar bala nos procedimentos necessários.

**Comment by Fredrumond** [comment]
Ja criei meu perfil e coloquei na lista de pupilos.  Ja esta tudo certo

**Comment by danilovaz** [comment]
Show @Fredrumond  não esqueça de entrar no nosso [Slack](https://ctgroups.herokuapp.com/).

Perfil do pupilo atualizado em #345 e #346 . Aguardando o mentor @mrprompt atualizar o seu perfil para fecharmos essa issue. :smile: :tada:

**Comment by mrprompt** [comment]
o meu já tá engatilhado, já mando o PR.. já estou conversando com o @Fredrumond também

**Comment by danilovaz** [comment]
Perfil do mentor atualizado em #351 ! Sucesso pessoal :tada:
