### ISSUE TITLE
Preciso de um mentor de Ruby on Rails, API e desenvolvimento mobile hibrido

### ISSUE THREAD

**Issue by diogowernik** [training-center/mentoria#34]
Preciso de um(a) Mentor para aprender a trabalhar com ruby on rails, API e desenvolvimento mobile hibrido.

**Nome:**

Diogo Wernik

**Descrição: **

Tenho interesse em aprender e me aprofundar no estudo de ruby on rails para desenvolvimento web de backend e frontend. Assim como criação de API e aplicativos mobile que se comuniquem com estes...

Sou uma pessoa criativa e estou sempre criando e tendo novas idéias, quero muito aprender programação para conseguir colocar minhas ideias mirabolantes em prática, rsrsrs...

meu github tem algumas coisas que tenho investigado...

https://github.com/

**Nível de conhecimento atual: basico/intermediário**
**Contatos: face: diogowernik , email: diogowernik@gmail.com**

**Comment by woliveiras** [comment]
Fala @diogowernik, tomei a liberdade de atualizar sua descrição na issue viu.

Uma dúvida: É somente para um projeto em específico ou algo para agregar a sua carreira?

O Mentor, no caso, deve ser uma pessoa que vai te acompanhar por um tempo para tirar suas dúvidas sobre carreira, não somente para um projeto específico.

Mas, se for para um projeto somente, temos os [Grupos de estudos](https://github.com/training-center/study-groups) cheio de gente querendo praticar! Poderia chamar o pessoal por lá, pois tem bastante gente que curte ajudar. :smile:

**Comment by diogowernik** [comment]
Opa, valeu @woliverias, na verdade é para me aprofundar e melhorar na carreira... vou atualizar o escopo do projeto :)

**Comment by diogowernik** [comment]
Ainda não entendi o sistema de label, é possíve acrescentar uma laber "desenvolvimento mobile"?

**Comment by woliveiras** [comment]
Boa cara! Valeu ein. :D

**Comment by woliveiras** [comment]
Está difícil achar uma pessoa de Ruby, compartilha nos grupos pra ajudar também. Vai queee... :smile:

**Comment by diogowernik** [comment]
Valeu woliveiras, rsrsrs

**Comment by woliveiras** [comment]
Ainda está precisando de ajuda ou conseguiu por fora @diogowernik?

**Comment by diogowernik** [comment]
Então, tenho conseguido algumas orientações por fora e feito alguns cursos, mas continuo tendo interesse na tutoria, caso exista, rsrs!

Valeu por perguntar!

**Comment by woliveiras** [comment]
Show de bola cara. Vamos continuar compartilhando. :)

**Comment by jessuircleydson** [comment]
@diogowernik não sei como está seu nível sobre apps híbridos, já fiz algumas coisas nessa questão(nada milaborante srsr), mas posso lhe mostrar um START utilizando Ionic que por sua vez usa Angular como estrutura do Front e Cordova como CORE. Não saco de ruby mas posso dar uma idéia de como consumir uma API REST no Ionic.

**OBS: Mas se achar melhor pode esperar alguém que manje bem mais disso, que vai aparecer, pra ter dar o caminho completo :D**

**Comment by woliveiras** [comment]
\o/

Ai sim ein

**Comment by diogowernik** [comment]
Super topo a tutoria, tenho muita vontade de aprender ionic!

**Comment by diogowernik** [comment]
Quando podemos começar, como seria o esquema :)

**Comment by woliveiras** [comment]
\o/

Boooa! Certeza que o @jessuircleydson tem coisa boa pra te passar, cara.

**Comment by jessuircleydson** [comment]
Opa @diogowernik me add no [Facebook](https://www.facebook.com/jessuir.cleydson) que agente pode ver como fica melhor pros dois.

**Comment by diogowernik** [comment]
Maneirissimo, vou te add lá! Valeu :+1:

**Comment by woliveiras** [comment]
Tudo correndo certinho com vocês @jessuircleydson e @diogowernik?

Se estiver tudo OK, é só atualizar o perfil de vocês aqui no projeto e podemos fechar a issue. 😄

**Comment by woliveiras** [comment]
Fala @jessuircleydson e @diogowernik. Atualizem esses perfis aeee. ;P

**Comment by diogowernik** [comment]
Fala @woliveiras , a tutoria acabou não funcionando... Eu até tentei atualizar quando achei que funcionaria, mas parece que o @jessuircleydson está muito atarefado e não pode me oferecer o suporte!

Acho que vou acabar saindo do sistema, mas super agradeço as ajudas oferecidas ;)

**Comment by woliveiras** [comment]
Entendi @diogowernik 

Entra no nosso slack pra trocar ideia por lá também, então.

https://ctgroups.herokuapp.com/

Vou fechar a issue por já ter mais que 10 dias em "Work in progress"

Qualquer coisa podemos reabrir
