### ISSUE TITLE
Preciso de um(a) mentor(a) Full Stack PHP Javascript

### ISSUE THREAD

**Issue by jalawz** [training-center/mentoria#340]
**Nome:** Paulo Roberto Menezes

**Descrição:** Sou biomédico formado e atuei por 8 anos na área, porém nunca foi o que realmente gostei, iniciei a alguns anos na área de programação e desde então tenho me esforçado para entrar
de vez nesse mundo. Estou cursando faculdade de ADS na FATEC e antes disso já tenho alguns cursos na área em PHP, HTML5, CSS3, JavaScript entre outros. Acredito que apesar disso ainda não tenho o conhecimento necessário para desenvolver sozinho. Gostaria de alguém que pudesse me guiar em desenvolvimento de aplicações web tanto no front quanto no back. Desde já agradeço!

**Nível de conhecimento atual:** Conhecimentos em HTML5 (intermediário para avançado), CSS3 (intermediário), JavaScript(básico para intermediário), PHP(intermediário), Laravel(básico), AngularJS(básico)

**Contatos:**
[Gmail](paulomenezes.web@gmail.com)
[Facebook](https://www.facebook.com/pauloroberto.menezes.5)
[Github](https://github.com/jalawz)

**Comment by danilovaz** [comment]
Seja muito bem vindo @jalawz  ! :smile: 

Alterei o título da sua issue para melhor condizer com o que você está procurando.

Vamos ver se algum dos @training-center/mentors consegue te ajudar. Pô, legal sua decisão de ter optado por fazer o que gosta. :tada: 

Enquanto isso, se ainda não leu, leia o documento de [Responsabilidades do Pupilo](https://github.com/training-center/mentoria/blob/master/pupilos/responsibility.md)!! :smile:

**Comment by mrprompt** [comment]
@jalawz se quiseres, posso ajudar.

**Comment by danilovaz** [comment]
@jalawz Veja se o perfil do @mrprompt condiz com o que você precisa.

**Comment by jalawz** [comment]
Boa noite @danilovaz muito obrigado pela oportunidade. 
O perfil do @mrprompt com certeza condiz e será um prazer e uma honra poder te-lo como mentor.
Como podemos proceder??

**Comment by mrprompt** [comment]
Show, agora é só seguir os procedimentos descritos nas tarefas do pupilo e me chamar no slack :)

**Comment by danilovaz** [comment]
Olá @jalawz agora é só atualizar/criar seus perfis no [repositório](https://github.com/training-center/mentoria/blob/master/helpers/README.md) e entrar no nosso [Slack](https://ctgroups.herokuapp.com/).

**Comment by danilovaz** [comment]
@jalawz Vi que você enviou um PR para atualizar a lista de pupilos, preciso que você crie o seu perfil de pupilo também. [Nesse link](https://github.com/training-center/mentoria/blob/master/helpers/CREATE_PUPIL_PROFILE.md) tem uma explicação, qualquer dúvida só falar.

**Comment by jalawz** [comment]
@danilovaz acredito que agora consegui fazer o commit. Qualquer coisa também me avisa. Muito obrigado!

**Comment by danilovaz** [comment]
Perfil do pupilo atualizado em #350 #352 agora é só o @mrprompt atualizar seu perfil e fechamos essa issue :tada:

**Comment by jalawz** [comment]
Muito obrigado @danilovaz! Entrei em contato com o @mrprompt pelo slack! É tudo muito novo pra mim, mas tenho certeza que tudo vai avançar! Mais uma vez obrigado!

**Comment by mrprompt** [comment]
ja to mandando o PR :D

**Comment by woliveiras** [comment]
Fala galera, estou fechando a issue por tempo sem interação.
