### ISSUE TITLE
Preciso de um(a) mentor(a) de Front End e UX/UI

### ISSUE THREAD

**Issue by simoneas02** [training-center/mentoria#342]
Alô humanos, eu sou a Simone, estou pendente do TCC para conclusão do curso de Sistemas de Informações 👎  e atualmente trabalho com suporte de sistemas legados 👎   bhaaaa("é o que tem pra janta por enquanto")...

Então, no corre corre do dia a dia tendo que conciliar em ser dona de casa, mãe de três filhos, trabalhar, estudar, ser mulher... acabou que não consegui aprender a programar de fato na faculdade e estou buscando aqui com vocês uma oportunidade de quebrar essa barreira 👍 .

Meu conhecimento é a nível bem iniciante, porém estou disposta aprender e começar a manjar dos paranaôes da área de front end pra iniciar uns freelas <3

Sem mais é só isso, aguardo urgentemente uma alma paciente e piedosa que aceite a iniciar essa trilha comigo ;)

## Contatos:
[Facebook](https://www.facebook.com/simone.amorim.33)
[Twitter](https://twitter.com/samorim02)
[LinkedIn](https://www.linkedin.com/in/simone-amorim-311a3a87?trk=nav_responsive_tab_profile_pic)

<3

**Comment by simoneas02** [comment]
Ajustando o título.

**Comment by danilovaz** [comment]
Seja muito bem vinda @simoneas02  ! :smile: 

Vamos ver se algum dos @training-center/mentors consegue te ajudar a evoluir em Front e quem sabe começar a pegar uns freelas :smile: :tada:

Enquanto isso, se ainda não leu, leia o documento de [Responsabilidades do Pupilo](https://github.com/training-center/mentoria/blob/master/pupilos/responsibility.md)!! :smile:

**Comment by LFeh** [comment]
@danilovaz Convenceu com a @simoneas02 e ela vai entrar como minha pupila.

Valeu!

**Comment by danilovaz** [comment]
@LFeh maneiro, mano! Só para manter atualizado e o histórico, você poderia atualizar seu perfil e a @simoneas02 criar o perfil dela?

Valeu pessoal e sucesso aí :tada:

**Comment by woliveiras** [comment]
@DaniloAgostinho, feito o merge do perfil da @simoneas02: #354

**Comment by LFeh** [comment]
Só atualizando, como disse outro dia no Slack, estou aguardando a @simoneas02 para iniciar.

**Comment by DaniloAgostinho** [comment]
@woliveiras acho que fui marcado no lugar errado. :dancer:

**Comment by woliveiras** [comment]
Eita lasqueira @DaniloAgostinho, foi mal. :D

**Comment by woliveiras** [comment]
Fala @LFeh, a @simoneas02 sumiu? :scream:

**Comment by LFeh** [comment]
Apareceu rs

**Comment by woliveiras** [comment]
🙌
