### ISSUE TITLE
Quero ser mentor de Front-end (Design/HTML/CSS/Javascript, Frameworks JS)

### ISSUE THREAD

**Issue by wilsoncampoz** [training-center/mentoria#343]
Nome: Wilson Campos
Profissão: Interface designer e desenvolvedor web FullStack
Experiência: 7 anos

Sobre: Comecei minha carreira como web designer, focado 90% no design e fazendo o que sabia para transformar o PSD em HTML/CSS. Passei por agências de publicidade de pequeno e médio porte, uma empresa de games onde criei e desenvolvi muitos hotsites de jogos.

Cheguei na CVC Viagens ainda muito inexperiente, sabendo muito bem HTML/CSS mas nada de desenvolvimento, nessa empresa encontrei grandes profissionais que me ensinaram muita coisa.

Hoje atuo na equipe de arquitetura definindo os rumos, e melhores práticas a seguir nos projetos.

Como tive grandes mentores, gostaria de me tornar um também. Sei como é importante ter alguém para tirar dúvidas sobre projetos ou mesmo qual caminho seguir.

Contatos:

[GitHub](https://github.com/wilsoncampoz)
[LinkedIn](https://www.linkedin.com/in/wilsoncamposgomes)
[Behance/Portfólio](https://www.behance.net/wilsoncampos)
[Facebook](https://www.facebook.com/Wilsoncamposgomess)
Email: wilsoncampoz@outlook.com

**Comment by danilovaz** [comment]
Olá @wilsoncampoz tranquilo? Pô, legal o seu perfil. Já vi que tem muita experiência pra passar aos pupilos.

Você já leu as [responsabilidades do mentor](https://github.com/training-center/mentoria/blob/master/mentores/responsibility.md) e está de acordo com a ideia do projeto?

Eu assisti uma palestra do pessoal da CVC no AWS Summit SP 2016, ouvi na palestra que estavam usando para Ember  :heart: :smile: :tada:

**Comment by wilsoncampoz** [comment]
Olá @danilovaz , já li as responsabilidades sim.
Poxa, nem eu sabia que alguém da CVC deu palestra no AWS Summit. rs

Estamos refazendo toda a aplicação, online e lojas com Ember.
Ember é bem bacana, mas um pouco de Angular nele faz falta.

**Comment by danilovaz** [comment]
@wilsoncampoz Não lembro qual era a palestra hauuahua, não tinha nada a ver com Ember. Mas foi citado. Estou refazendo uma aplicação em Ember também, estou gostando muito. :smile: 

Agora os @training-center/mentors vão avaliar seu perfil e logo te daremos uma resposta.

Obrigado pelo seu interesse em colaborar com a carreira de outras pessoas de maneira gratuita e sem pretensões.

**Comment by danilovaz** [comment]
Olá @wilsoncampoz !

Seu perfil foi aprovado pelos outros mentores :tada: 

Bem vindo ao time! :facepunch: 

Agora você precisa criar seu perfi no [repositório](https://github.com/training-center/mentoria/tree/master/helpers) e entrar no nosso [Slack](https://ctgroups.herokuapp.com/).

Depois é só pegar algum pupilo através dessas [issues](https://github.com/training-center/mentoria/issues?q=is%3Aissue+is%3Aopen+sort%3Acreated-asc+label%3A%22need+a+mentor%22).

OBS: busque das issues mais antigas primeiro, valeu :smile:

**Comment by woliveiras** [comment]
Tá lá galera! 😄
