### ISSUE TITLE
Quero ser mentor de Desenvolvimento Web em geral

### ISSUE THREAD

**Issue by erikfig** [training-center/mentoria#347]
Olá, Sou Erik Figueiredo, trabalho com desenvolvimento web (front-end (CSS, SASS, HTML, Javascript, AngularJS, Angular 2 e Vue), back-end (PHP, Laravel, CakePHP, Slim Framework, Zend Framework, Node.js e Express) e alguns bancos de dados, como MySql, Postgres e Mongo, mas DB não é muito minha área). Já trabalhei com design, mas também não é meu forte.

Trabalho na área desde os 18 anos (atualmente estou com 31, sou de 1985), tenho alguns cursos na internet, mas minha ideia é realmente ajudar a comunidade, então espero ser apto para estar aqui com vocês.

Minhas redes sociais: https://www.facebook.com/erikfigueiredods, https://twitter.com/erikfig

Obs.: Excelente iniciativa!

Att. Erik

**Comment by fgleyson** [comment]
quero um mentor

**Comment by woliveiras** [comment]
Fala @erikfig, o esquema que lhe informei sobre as mudanças no CT já aconteceram!

Agora você pode seguir o novo fluxo: https://medium.com/@woliveiras/menos-burocracia-para-conseguir-um-mentor-ou-mentora-d571ed9cc3e0#.8sysjowyx

Pode criar o seu perfil seguindo o esquema: https://github.com/training-center/mentoria#quero-ser-mentora

Caso tenha alguma dúvida ou o tutorial não esteja claro, me de um toque.

Assim que subir seu perfil, aconselho que pegue as issues abertas para tentar encontrar um pupilo antes de seguir o novo fluxo, pois precisamos ajudar quem já estava seguindo o fluxo antigo.

**Comment by woliveiras** [comment]
@fgleyson é necessário que a pessoa seja Mentor e esteja na lista antes de você buscar ajuda, viu.

Senão pode acontecer de você ser respondido por alguém que não foi aprovado pelo nosso grupo.

O @erikfig é amigo da casa, mas poderia ser alguém sem tanto compromisso com a comunidade. Por isso é tão importante seguir as regras.

**Comment by woliveiras** [comment]
Já foi aprovado @erikfig: https://github.com/training-center/mentoria/issues/347#issuecomment-263436748

kkkkkk 😂

**Comment by erikfig** [comment]
Eita... acho que passei direto esse comentário... kk...

**Comment by woliveiras** [comment]
😂 😂 😂 😂

**Comment by fgleyson** [comment]
Opa estou aguardando.

________________________________
De: William Oliveira <notifications@github.com>
Enviado: terça-feira, 29 de novembro de 2016 12:46:19
Para: training-center/mentoria
Cc: Gleyson Santos; Mention
Assunto: Re: [training-center/mentoria] Quero ser mentor de Desenvolvimento Web em geral (#347)


?? ?? ?? ??

-

**Comment by erikfig** [comment]
Bora lá... Acho que você precisa mandar um pull request na lista de pupilos da uma olhada no readme.md

Me manda um email pra gente marcar um bate papo essa semana.

**Comment by woliveiras** [comment]
É isso mesmo @erikfig 

Só seguir [aqui](https://github.com/training-center/mentoria#preciso-de-uma-mentora), @fgleyson 

Muito sucesso pra vocês.

Vou fechar essa issue por que ela é referente ao perfil de mentor do Erick e já foi adicionado a organização, mas se precisarem podem continuar conversando por aqui até se acertarem.

**Comment by fgleyson** [comment]
eu fiz, mas não sei o que ouve que não estar na lista de pupilos :/

________________________________
De: William Oliveira <notifications@github.com>
Enviado: terça-feira, 29 de novembro de 2016 20:39:45
Para: training-center/mentoria
Cc: Gleyson Santos; Mention
Assunto: Re: [training-center/mentoria] Quero ser mentor de Desenvolvimento Web em geral (#347)


É isso mesmo @erikfig<https://github.com/erikfig>

Só seguir aqui<https://github.com/training-center/mentoria#preciso-de-uma-mentora>, @fgleyson<https://github.com/fgleyson>

Muito sucesso pra vocês.

Vou fechar essa issue por que ela é referente ao perfil de mentor do Erick e já foi adicionado a organização, mas se precisarem podem continuar conversando por aqui até se acertarem.

-

**Comment by erikfig** [comment]
O que, me manda o email que este então será nossa primeiro passo...

**Comment by fgleyson** [comment]
e-mail: gleyson_78@hotmail.com

Whatsaap: 85 985959107

FaceBook: https://www.facebook.com/fgleyson

________________________________
De: Erik Figueiredo <notifications@github.com>
Enviado: quarta-feira, 30 de novembro de 2016 09:41:43
Para: training-center/mentoria
Cc: Gleyson Santos; Mention
Assunto: Re: [training-center/mentoria] Quero ser mentor de Desenvolvimento Web em geral (#347)


O que, me manda o email que este ent?o ser? nossa primeiro passo...

-
