### ISSUE TITLE
Preciso de um mentor de UX Design

### ISSUE THREAD

**Issue by urameshibr** [training-center/mentoria#349]
**Nome:** Lucas Rodrigues
**Descrição:** Dev backend PHP
**Contatos:** facebook.com/lucas.rodrigues.urameshi

Olá, tenho muita dificuldade em fazer algo bonito no frontend, não sei nada de design, em javascript tenho conhecimentos básicos mas sou um grande fuçador também.
Gostaria muito de ter um mentor que me mostrasse o "caminho das pedras" para eu não precisar mais ficar usando template pronto do themeforest hahaha.

**Comment by juliomoreira666** [comment]
Posso ser seu mentor se quiser ;)

**Comment by williambeto** [comment]
acho que posso ajudar, trabalho com Front-End há mais de 6 anos.
esse é o meu portfólio recente : http://josewillams.com/

se precisar de ajuda, me avise.
terei o mair prazer em ajudar um profissional da área.

**Comment by woliveiras** [comment]
Fala @juliomoreira666 e @williambeto para auxiliar alguém no projeto é importante que tenha um perfil aqui no repositório: https://github.com/training-center/mentoria#quero-ser-mentora

Assim garantimos comunicação com vocês e com os pupilos e integridade de ambos.

Até mesmo por isso que aconselhamos que ninguém aceite mentoria de alguém não cadastrado no nosso repo: https://github.com/training-center/mentoria#preciso-de-uma-mentora

Se entrarem agora vai ser até melhor, pois já pegam o novo fluxo! https://medium.com/@woliveiras/menos-burocracia-para-conseguir-um-mentor-ou-mentora-d571ed9cc3e0#.8sysjowyx 

Muito melhor! :grimacing: :grimacing: :grimacing:

**Comment by woliveiras** [comment]
@urameshibr você pretende aprender UX Design **E** Desenvolvimento Front End ou só as bases de Design e mais código HTML/CSS/JS?

**Comment by urameshibr** [comment]
@woliveiras Primeira opção, mais UX Design e frotnend, menos código, quero ver se consigo despertar o Michelangelo que há dentro de mim haha.

**Comment by woliveiras** [comment]
Shoooow cara,

Dei uma atualizada no titulo pra ficar mais simples. :)

Vamos ver se alguém dos @training-center/mentors consegue ajudar.

**Comment by woliveiras** [comment]
@urameshibr nosso processo mudou: https://medium.com/trainingcenter/e-o-mentoria-mudou-mais-uma-vez-5ad8725bc778

Peço, por favor, que responda esse formulário para que algum mentor ou mentora entre em contato contigo quando possível: http://bit.ly/preciso-de-mentoria

A issue será fechada para que não aconteçam desencontros de informação.
