### ISSUE TITLE
Preciso de um mentor para desenvolvimento JavaScript

### ISSUE THREAD

**Issue by RenanSMoura** [training-center/mentoria#35]
# Meu nome

Renan Silva Moura

# Qual meu sonho de carreira?
No atual momento, terminar meu curso de graduação (Último ano já) e ficar bom  em JavaScript.
Após a faculdade, virar um ninja em desenvolvimento Full-Stack e fazer parte da comunidade de desenvolvimento brasileira.

# Conhecimentos

Tenho conhecimentos acadêmicos em desenvolvimento Java e alguns de seus Frameworks, como JPA e JSF. Conhecimento bem básico em PHP, Android, Swift e Objective-C. Na parte de Front, conheço Html5, css3, JavaScript e na api Jquery. 

# Alguns links para me conhecer melhor
[Facebook](https://www.facebook.com/renan.silva.moura)
[Linkedin](https://br.linkedin.com/in/renansmoura)
[GitHub](https://github.com/RenanSMoura)

**Comment by woliveiras** [comment]
Seria JS com NodeJS ou para Front End @RenanSMoura?

**Comment by RenanSMoura** [comment]
Seria para front mesmo @woliveiras

**Comment by woliveiras** [comment]
Show de bola cara! Vamos esperar um pouco pra ver se aparece algum monstro dos @training-center/moderators

**Comment by woliveiras** [comment]
Caso ninguém se importe, eu gostaria de ajudar. :D

**Comment by woliveiras** [comment]
@RenanSMoura, vou te ajudar. Amanhã te chamo no Facebook para conversarmos mais.

**Comment by woliveiras** [comment]
Pode adicionar seu perfil de pupilo nesse local: https://github.com/training-center/mentoria/tree/master/pupilos

Seguindo o template: https://github.com/training-center/mentoria/blob/master/pupilos/pupilo_template.md

**Comment by RenanSMoura** [comment]
@woliveiras  Beleza cara. Muito obrigado!

**Comment by woliveiras** [comment]
[Perfil adicionado!](https://github.com/training-center/mentoria/blob/master/pupilos/perfis/RenanMoura.md)
