### ISSUE TITLE
Preciso de um(a) mentor(a) de Front End/JavaScript

### ISSUE THREAD

**Issue by JulianoPadilha** [training-center/mentoria#355]
**Nome:** Juliano Padilha Marques da Silva

**Descrição:** Olá, Mentores! Gostaria de alguém para me ajudar no planejamento e desenvolvimento da minha carreira como Desenvolver Front-end. Dissertarei um pouco sobre mim para ajudar vocês a entenderem meus objetivos. :)

Eu tenho 24 anos e há aproximadamente 1 ano trabalhando com algo na área de desenvolvimento (não exclusivamente com front). Atualmente eu moro em SP, mas antes disso eu morava em Belém/PA. Me mudei para SP faz pouco mais de um mês. Eu tomei a decisão de vir pra cá logo após me formar em Sistemas de Informação. Eu sou muito ambicioso e sempre soube que Belém não seria capaz de me propiciar as oportunidades de crescimento que eu sempre procurei, então, juntamente com a possibilidade de um futuro mestrado, fez eu me mudar na cara e na coragem. :D 

Apesar de eu ser da área da computação, eu acabei durante a faculdade focando meus estudos mais para a área de gestão, empreendedorismo, liderança, etc.. Não que isso seja ruim, só que acabei com isso deixando de lado os estudos na área desenvolvimento, área que sou super apaixonado (mesmo achando que não levo muito jeito. Haha :P)

Desde que me formei passei então a direcionar meus esforços para o estudo diário de tudo que deixei de lado até o momento. No começo foi incrível, eu conseguia ver claramente o meu desenvolvimento e esforço em sempre saber mais. Porém, com o passar do tempo eu comecei a me sentir perdido em meio a tantas possibilidades, e isso acabou afetando meu foco, empenho e compromisso. 

No meio de tudo isso, tive a sorte em conseguir um emprego com meu ex-professor de faculdade. Ele possui uma empresa de desenvolvimento de software web e mobile. Inicialmente entrei na empresa trabalhando na área de testes, depois tomei algumas responsabilidades gerenciais, como coleta de requisitos e gerência de projetos (coisas que também tenho muito prazer em fazer).. Depois de um tempo passei a atuar como desenvolvedor Back-end trabalhando com PHP (não sou bom mas conseguia fazer as coisas acontecerem. Haha). Enfim.. atualmente eu continuo trabalhando remoto para essa empresa, mas preciso urgentemente de uma nova colocação no mercado por dois principais motivos: não ganho o suficiente para me manter em SP; sinto que não estou no caminho certo dentro da empresa (mesmo gostando muito de trabalhar nela) e que preciso aproveitar as tais oportunidades que vim atrás aqui em SP. 

Para tal, preciso muito rever os conhecimentos e planejar uma rotina de estudos que me faça progredir novamente e assim começar a alcançar meus objetivos. Sou esforçado, disso não tenho dúvidas. O que falta é o apoio de alguém para fazer com que eu me mantenha no rumo certo e me ajude a não desistir quando sentir que as coisas não estão dando certo. É por isso que estou atrás de um mentor. 

Vou começar em breve a trabalhar com Ionic e Angular em um projeto da empresa, então procuro muito reforçar e progredir meus conhecimento em JavaScript, e com isso ganhar mais conhecimento de novos frameworks, boas práticas de desenvolvimento e tudo mais. 

Agradeço desde já um possível contato. Será um prazer poder compartilhar mais sobre meus objetivos e conhecimentos.  

**Nível de conhecimento atual:** HTML e CSS - Intermediário | JavaScript - Básico

**Contatos:** 
[Facebook](https://www.facebook.com/JulianoPadilha)
[LinkedIn](https://br.linkedin.com/in/julianopadilha)
E-mail: sistemas.padilha@gmail.com

**Comment by woliveiras** [comment]
@JulianoPadilha atualizei o título só para ficar mais simples, pois o mentor ou mentora irá te ajudar com as bases de JS, mas também com coisas avançadas. :smile: 

Você já leu as [responsabilidades de pupilo](https://github.com/training-center/mentoria/blob/master/pupilos/responsibility.md) e está de acordo?

**Comment by JulianoPadilha** [comment]
Opa, obrigado @woliveiras. :)

Sim, sim. Já li as responsabilidades e estou de pleno acordo.

**Comment by woliveiras** [comment]
Perfeito @JulianoPadilha 

Vamos ver se alguém dos @training-center/mentors consegue te ajudar. :)

**Comment by vinicius73** [comment]
Fala ae @JulianoPadilha 
Posso ser seu mentor :)

**Comment by JulianoPadilha** [comment]
Opa!! Vamos lá @vinicius73. \o/
 
Vou ler novamente as regras para ver como proceder agora. :D

Valeu!

**Comment by JulianoPadilha** [comment]
@vinicius73 @woliveiras Já mandei o PR com meu perfil de pupilo. rs

**Comment by woliveiras** [comment]
Feito! #371 

Perfeito @JulianoPadilha 

:)

**Comment by vinicius73** [comment]
@JulianoPadilha entra no slack ou telegram para podermos organizar as coisas :)
