### ISSUE TITLE
Preciso de um(a) mentor(a) para Desenvolvimento Front-End em JS

### ISSUE THREAD

**Issue by allangrds** [training-center/mentoria#356]
**Nome:** Allan Gabriel Ramos da Silva
**Descrição:** Olá, tudo bem ? Sou Allan Ramos, tenho 23 anos e atualmente trabalho como Front-end na CARGOBR. Trabalho como desenvolvedor web há 2 anos,  trabalhando com tecnologias como Python, PHP(Codeigniter e Laravel), mas atualmente quero ter como foco o front-end. Acabei de terminar minha faculdade, e quero dar um boost em meus estudos de Javascript, pois essa é minha maior deficiência. Quero melhorar minha habilidade nisso para focar depois em coisas como NPM, ES6, Browserfy, Gulp e algum framework.

**Nível de conhecimento atual:** HTML5, CSS3, Javascript e Git.
**Contatos:**
[Linkedin](https://br.linkedin.com/in/allangabrielrds)
[Facebook](https://www.facebook.com/allangabrielrds)

**Comment by woliveiras** [comment]
Faaala @allangrds, você já leu as [responsabilidades de pupilo](https://github.com/training-center/mentoria/blob/master/pupilos/responsibility.md) e está de acordo?

**Comment by allangrds** [comment]
@woliveiras Já sim. Estou 100% de acordo.

**Comment by woliveiras** [comment]
Perfeito @allangrds. 

Vamos ver se alguém dos @training-center/mentors consegue te ajudar. :)

**Comment by wilsoncampoz** [comment]
@allangrds com certeza.

**Comment by allangrds** [comment]
Fechado @wilsoncampoz :). Muito obrigado.
@woliveiras acabei de criar um PR pra adicionar meu perfil na lista de pupilos.

**Comment by woliveiras** [comment]
Show de bola @allangrds
