### ISSUE TITLE
Preciso de um mentor para Front-End Engineer com foco em VueJS, ES6, TDD, Programação Funcional, NodeJS, CSS Patterns.

### ISSUE THREAD

**Issue by simaodeveloper** [training-center/mentoria#357]
**Nome:** Daniel Simão da Silva

**Descrição:** Olá, sou Front-End Developer há mais de 3 anos, trabalho em uma agência que presta serviço para agências, tudo fica muito em torno do jQuery, normalmente são muitos projetos, fica muito difícil implementar um código limpo, organizado, manutenível e escalável, estou aqui porque preciso de um mentor que saiba como é trabalhar com produto, quero aprender a construir um código limpo, performático, testável e escalável, creio que com isso vou realizar meus sonhos, sendo um deles viajar para a Irlanda e ficar la um tempo rs, bom é isso e estou com fome de conhecimento.

Atualmente estou tentando estudar por fora sobre SPAs, NodeJS, ReactJS, TDD, ES6 e tudo mais para construir um projeto completo, mas é muito complicado ter um direcionamento, pensar em projetos para construir e se desenvolver, fica difícil não aplicar no dia-a-dia, mas a gente tenta, fico no aguardo de um mentor. o/

**Interesses**: Se o mentor se identificar gosto de Trash Metal e Death Metal, Cerveja Artesanal, estudo sobre Abelhas Nativas Sem Ferrão, como cuidar da Barba kkk e claro Tecnologia, Ciência e afins. 

**Nível de conhecimento atual:**   Intermediário

- Javascript (OOP, Facade e Adapter Patterns, AJAX, Lib jQuery, TweenMax);
- CSS3 (Keyframes, Responsive, Framework, Grid System);
- HTML5 (Rich Snippets, Semântica, Nunjucks Template Engine, LESS pre-processor);
- Tools (Trello para Scrum, Git, Gulp, Básico de Bash);
- O básico de API de facebook, twitter, google, youtube;
- Curriculo: https://github.com/simaodeveloper/curriculo

**Contatos:**
- Website : http://danielsimao.com.br
- E-mail: simaodeveloper@gmail.com
- facebook: https://www.facebook.com/simao.dev
- Twitter: https://twitter.com/simaodeveloper

**Comment by vinicius73** [comment]
Bastante coisa.
Mas posso ajudar com Node, ES6, FP e CSS Patterns :)

**Comment by simaodeveloper** [comment]
Ótimo, com certeza será de grande ajuda, @woliveiras como devemos proceder a partir daqui, o @vinicius73 já é um mentor aprovado?

**Comment by simaodeveloper** [comment]
@vinicius73 esse awesome-br é irado em, não conhecida, to fuçando seu GH hehe.

**Comment by vinicius73** [comment]
hahaha obrigado @simaodeveloper :yum:

**Comment by simaodeveloper** [comment]
Será que eu posso fazer meu PR de púpilo ou tem que realizar alguma aprovação @vinicius73 ?

**Comment by woliveiras** [comment]
Opa, desculpem a demora em responder.

Estava focado na [mudança de fluxo do projeto](https://medium.com/trainingcenter/menos-burocracia-para-conseguir-um-mentor-ou-mentora-d571ed9cc3e0#.tk1g0gppj) e acabei ficando sem tempo pra aparecer! ;D

@vinicius73 antes do @simaodeveloper se tornar seu pupilo, é importante que siga esse fluxo: https://github.com/training-center/mentoria#quero-ser-mentora

Tenho certeza que ninguém irá impedir seu ingresso no projeto, pois já devem te conhecer pelas interwebs. :grin: 
Porém é importante que todos sigam o processo.

Assim que tiver seu perfil o @simaodeveloper pode criar o perfil dele também. Isso é importante para mantermos o controle de quem está participando do projeto e a comunicação com ambos.

Depois disso é só alegria. Poderão tocar o barco como acharem melhor via Slack, Face ou algum canal de comunicação que curtirem. :)

**Comment by woliveiras** [comment]
Adicionei a label Work in progress, pois acho que o @vinicius73 vai conseguir te ajudar @simaodeveloper

**Comment by vinicius73** [comment]
Feito @simaodeveloper :)
#361

**Comment by simaodeveloper** [comment]
Beleza , logo faço meu PR de pupilo.

**Comment by woliveiras** [comment]
Show  bola!

#370 

Agora é só o @vinicius73 atualizar o perfil dele e muito sucesso pra vocês.

**Comment by woliveiras** [comment]
Fala galera, estou fechando a issue por tempo sem interação.
