### ISSUE TITLE
Preciso de um(a) mentor(a) sobre Desenvolvimento Front-End e UX/UI

### ISSUE THREAD

**Issue by sofiabareta** [training-center/mentoria#358]
Nome: Sofia Bareta

Descrição: Boa tarde, mentores! Procuro um(a) mentor(a) que possa me atualizar em relação à Front-End, me dar uma forcinha com Angular 2 e um empurraozinho com design/UX :)

Sou formada em análise e desenvolvimento de sistemas, e há três anos, comecei trabalhando na área como estagiária de desenvolvimento web (aprendia um pouquinho de front-end, um pouquinho de back-end). Dois anos pra cá, foquei apenas em desenvolvimento front-end. Problema é que, durante esse tempo, eu tive pouquíssimo contato com profissionais mais experientes. Ou seja, a maior parte do que aprendi foi fazendo, e geralmente, com prazos bem curtos. Acabei ficando muito pra trás em termos de novas tecnologias. Sass talvez tenha sido uma das pouquíssimas coisas """"novas"""" que aprendi e coloquei em prática. E, apesar de ser razoavelmente familiarizada com HTML/CSS, ainda apanho de flexbox :P

Atualmente, na empresa em que trabalho, estamos utilizando Angular 2, que para mim, é não somente uma nova ferramenta, mas também, uma nova forma de pensar para codificar, que ainda tenho muita dificuldade.

Não bastando, recentemente comecei uma pós-graduação em UX, e estou um pouco perdida com Design.

Agradeço desde já quem quiser me ajudar nessa, e espero que meu pouco conhecimento possa contribuir também :)

Nível de conhecimento atual: 
HTML, CSS, Javascript, JQuery - intermediário
Angular 2 - básico
Design/UX - básico

Contatos:
<a href="https://www.linkedin.com/in/sofiabareta">LinkedIn</a>
sofibareta@gmail.com

**Comment by woliveiras** [comment]
Fala @sofiabareta 

Acho que todo mundo ainda apanha um pouco pra Flexbox! kkkkk

Você já leu as [responsabilidades de pupilo](https://github.com/training-center/mentoria/blob/master/pupilos/responsibility.md) e está de acordo?

**Comment by sofiabareta** [comment]
Sim, estou de acordo :)

**Comment by woliveiras** [comment]
Vamos ver se alguém dos @training-center/mentors consegue te ajudar. :)

**Comment by sofiabareta** [comment]
Obrigada, @woliveiras :)

**Comment by abnersajr** [comment]
@sofiabareta Eu não trabalho com Angular 2 mas posso te dar uma força com UX/UI em front-end em geral.
Nunca tive a oportunidade de trabalhar com Angular 2 e não está sendo meu foco nos estudos no momento.

Se você quiser ser minha pupila talk to me e agente se entende.

**Comment by sofiabareta** [comment]
Opa, @abnersajr 
topo sim!! :)

obrigada!

**Comment by abnersajr** [comment]
@sofiabareta estarei entrando em contato com você no domingo a noite. Qualquer coisa se não nos encontrarmos não se assuste. Estou meio ocupado esse find, mas eu vou organizar uma parada pois tenho outro pupilo também que estou trabalhando. Domingo mais no fim da tarde, para a noite ;) Até logo.

**Comment by sofiabareta** [comment]
Tranquilo, @abnersajr! :)

**Comment by abnersajr** [comment]
@sofiabareta não encontrei seu perfil foi criado?

**Comment by sofiabareta** [comment]
@abnersajr Tentei criar alterando o template de pupilos e alterando o nome do arquivo... Git também não é meu forte, não sei se tava certo :T

**Comment by woliveiras** [comment]
Oi @sofiabareta, desculpa a demora. 

Está rolando interação entre vocês?

**Comment by sofiabareta** [comment]
oi, @woliveiras !
Tá rolando a interação sim, mas agora vi que meu perfil ainda não foi cadastrado, né :/

**Comment by woliveiras** [comment]
😂 😂 😂 

Exato, @sofiabareta.

Precisamos fazer isso, posso te ajudar de alguma maneira?

**Comment by sofiabareta** [comment]
@woliveiras, o @abnersajr já me deu o primeiro grande caminho que foi aprender o git/github. 
Acho que agora essa ficha sai :)
