### ISSUE TITLE
Melhorar descrição dos processos de novo Mentor e novo Pupilo

### ISSUE THREAD

**Issue by woliveiras** [training-center/mentoria#36]
Adicionar descrição de como é criado o perfil de Mentor e o perfil de Pupilo, conforme os templates, locais onde devem ficar os arquivos e lista.

**Comment by leportella** [comment]
Sugiro colocar o tipo de conhecimento esperam dos mentores. Eu tenho condições de ajudar alguém iniciante em python, mas não me sinto completamente segura de virar uma mentora da área... gostaria de entender melhor a proposta dos mentores. No mais, adorei o projeto e já divulguei :D

**Comment by woliveiras** [comment]
Oi @leportella. Valeu por divulgar ein! \o/

Então, a ideia é o mentor ajudar até onde pode. Mesmo que não possuamos 20 anos de carreira, por exemplo, mas se se sentir confortável em ajudar alguém a seguir ou criar um plano de carreira pode pegar uma pessoa e ajudar.

As vezes a pessoa só precisa de um direcionamento sobre o que estudar, como praticar... A gente pode traçar uma lista de coisas pra pessoa estudar com base no que ela já sabe e incentivar essa pessoa a pegar os Open Sources pra praticarem, etc.

Basicamente você ensina até onde consegue, se sentir, na descrição do pupilo, que não consegue ajudar a pessoa, talvez por falta de experiência, pode ensinar o básico e depois outra pessoa continua também.

O importante é ter alguém pra ajudar o iniciante naquela hora de desespero que passamos de: não sei o que estou fazendo, não sei se gosto do que faço, acho que não sirvo pra isso, acho que sou burro, etc. KKKKKK

Todo mundo já passou ou passa por isso.

Um mentor também serve pra ajudar a pessoa a ver se curte mesmo uma área de atuação falando como é seu dia-a-dia, por exemplo. 😄 

Você diz colocar o que esperamos no README principal mesmo, né?

**Comment by woliveiras** [comment]
@leportella, vai rolar um PR então com seu perfil pra Mentora? :grin:

**Comment by leportella** [comment]
Pretendo fazer um em breve, mas se condições de pegar 5 pupilos no momento... :/ 

Preciso terminar o mestrado primeiro...

**Comment by woliveiras** [comment]
Aeee, show de bola!

**Comment by leportella** [comment]
Aliás... não seria uma boa diminuir o número? 5 é um número alto e muita gente que eu conheço não quis pegar porque era mta coisa... Eu sei que a ajuda não é tanta assim, mas sabe como é... 1000 projetos pessoais hehehehe

**Comment by dorianneto** [comment]
@leportella acho que o range de pupilos por mentor serve apenas para manter um padrão no projeto, cada um deve pegar a quantidade que suportar. Isso até já foi discutido na #2 :)

@woliveiras pelo que vi a descrição de novos mentores e novos pupilos já estão bem encaminhadas! Encontrei alguns trechos que com algumas poucas alterações ficarão mais fácil de entender. Vou mandar um PR, blz?

Outra coisa é com relação aos links para a página dos [moderadores](https://github.com/orgs/training-center/teams/moderators). Todos os links para a mesma estão dando 404. Você pretende criá-la ou o links está errado mesmo?

**Comment by woliveiras** [comment]
1000 Projetos paralelos + Serviço! kkkkkk
Verdade @leportella.

Então é bem o que o @dorianneto falou, a quantidade ser 5 é mais um limite do que um número base, mas a pessoa pode ficar somente com um. Eu mesmo só atendo [dois rapazes](https://github.com/training-center/mentoria/blob/master/mentores/perfis/william_oliveira_souza.md#pupilos) e acho que só vou aceitar mais algum quando acabar minha faculdade.

Porém é bem livre. A pessoa pode se auto gerenciar e responder quantas pessoas ela conseguir. :)

**Comment by woliveiras** [comment]
Beleza @dorianneto \o/

Eita, quais links você diz rapaz? :scream: 

Testei aqui e está certinho.

**Comment by dorianneto** [comment]
@woliveiras esse aqui https://github.com/orgs/training-center/teams/moderators pra mim vai para uma página 404 do Github.

**Comment by dorianneto** [comment]
Estranho...

**Comment by woliveiras** [comment]
LO U CU RA

Clica nesse link: @training-center/moderators

**Comment by dorianneto** [comment]
Página 404 :/

**Comment by woliveiras** [comment]
Eita! 😱 

Da pra mais alguém do @training-center/moderators?

**Comment by JGcarv** [comment]
Cara, pra mim aparece normal, sem nenhum problema.

**Comment by akfzambrana** [comment]
Pra mim aparece 404 tb, sera que não é uma questão de "privacidade" do grupo? tipo vcs conseguem ver pq são parte do grupo

**Comment by dorianneto** [comment]
Provavelmente seja o que a @akfzambrana falou.

**Comment by woliveiras** [comment]
Putz! Que vacilo!

Vou conversar com o estagiário sobre isso galera... Isso deveria ter sido mais testado. :-1: 

Vou corrigir!

**Comment by woliveiras** [comment]
Atualizado!

Se tudo estiver OK com as descrições, vou fechar essa issue e abrir outra para sugestões de melhorias. Que tal, galera?
