### ISSUE TITLE
Preciso de um mentor(a) para JavaScript

### ISSUE THREAD

**Issue by devigor** [training-center/mentoria#360]
Preciso de um mentor para me ajudar com o JavaScript!!

Eu tenho um pouco de dificuldade em relação a como começar a estudar essa tecnologia, devido a imensa quantidade de cursos, artigos, etc, fico perdido em como começar. Meu objetivo e estudar o JS e depois partir para o ReactJs e para NodeJs.

Agradeço a todos!

Contatos: https://twitter.com/Litll3
                https://www.facebook.com/Littl33

**Comment by woliveiras** [comment]
Fala @littl3 

Realmente tem muita coisa de JavaScript!!! Vish.

Você já leu as [responsabilidades de pupilo](https://github.com/training-center/mentoria/blob/master/pupilos/responsibility.md) e está de acordo?

**Comment by littl3** [comment]
Opa @woliveiras 
Já li sim e estou de acordo com tudo

**Comment by woliveiras** [comment]
Show de bola @littl3 

O seu processo continua o antigo, pois você abriu a issue antes de mudarmos, mas conheça o novo formato de conseguir um mentor: 

https://medium.com/trainingcenter/menos-burocracia-para-conseguir-um-mentor-ou-mentora-d571ed9cc3e0#.km0dm7u76

**Comment by littl3** [comment]
Eu preciso mudar alguma coisa ou agora é só aguardar?

**Comment by woliveiras** [comment]
É só aguardar @littl3 

Mas, se quiser, fica de olho nos twitts dessa conta: https://twitter.com/ct_org

Lá eu posto quando um mentor está livre, ai você pode tentar entrar em contato direto com eles. :)

**Comment by littl3** [comment]
Obrigado pela atenção @woliveiras

**Comment by woliveiras** [comment]
É nozes @littl3

**Comment by littl3** [comment]
@wilcorrea o Erik Figueredo aceitou ser meu mentor. Tem como vc aceitar meu PR com meus dados??

**Comment by wilcorrea** [comment]
@littl3 eu sou pupilo ainda, haha. Quem recebeu o meu foi o @woliveiras ; )

**Comment by littl3** [comment]
Rapaz.... Marquei a pessoa errada hahahahaha Foi mal @wilcorrea

**Comment by woliveiras** [comment]
Feito! 😄

**Comment by renanoliver** [comment]
E aí @devigor! Pronto pra ser meu pupilo?

**Comment by ftonato** [comment]
Fala @devigor, como está o andamento dessa _issue_?
- [X] Encontrou o mentor?
- [ ] O mentor entrou em contato com você?

/cc @wilcorrea

**Comment by wilcorrea** [comment]
@ftonato sou eu mesmo que era para ser marcado ou o meu xará @woliveiras ?

**Comment by ftonato** [comment]
@wilcorrea que _issue_ confusa hahaha
Era para ter marcado o _PUPILO_ e o _MENTOR_ que ele tinha interesse...

**Comment by lflimeira** [comment]
Boa tarde, tudo bem? 
Já conseguiu achar um mentor?

**Comment by woliveiras** [comment]
@devigor nosso processo mudou: https://medium.com/trainingcenter/e-o-mentoria-mudou-mais-uma-vez-5ad8725bc778

Peço, por favor, que responda esse formulário para que algum mentor ou mentora entre em contato contigo quando possível: http://bit.ly/preciso-de-mentoria

A issue será fechada para que não aconteçam desencontros de informação.
