### ISSUE TITLE
Quero ser mentor de PHP, Laravel e JavaScript

### ISSUE THREAD

**Issue by vinicius73** [training-center/mentoria#361]
**Nome:** Vinicius Reis

**Descrição:** 
Sou desenvolvedor WEB. Trabalhei com PHP e Laravel atualmente tranalho na @decision6, onde trabalho exclusivamente com JavaScript, usando node e ferramentas como Vue.js
Também escrevo para os seguintes sites:
http://www.vuejs-brasil.com.br/
https://blog.codecasts.com.br/
https://medium.com/by-vinicius-reis

**Comment by woliveiras** [comment]
Fala @vinicius73 

Já passei a informação para os outros mentores. Já pode criar seu perfil! \o/

Você já vai seguir o novo fluxo: https://medium.com/trainingcenter/menos-burocracia-para-conseguir-um-mentor-ou-mentora-d571ed9cc3e0#.njr3fvrtf

Mas recomendo que de uma olhada nas issues mais antigas pra tentarmos ajudar quem já estava esperando.

**Comment by woliveiras** [comment]
Opa, nem tinha visto o PR!

Fechado!
