### ISSUE TITLE
Preciso de um Mentor para Desenvolvimento Full-Stack em JavaScript

### ISSUE THREAD

**Issue by emanuelgsouza** [training-center/mentoria#362]
Olá, sou Emanuel, tenho conhecimentos inicias em Front-End - HTML5, CSS3, e Back-End - PHP, sem nenhum Framework ainda. Estou em busca de um mentor que possa me auxiliar no Desenvolvimento Full-Stack com JavaScript.

Já tenho conhecimentos com JavaScript, mas pretendo aprofundá-los utilizando Frameworks como Vue.js, Node js, React, e começar a entender SPAs, Web Components, Web Apps, e afins.

Já participo de comunidades e escrevo no [Medium](https://medium.com/emanuelg-blog) e no momento estou estudando a fundo POO em PHP visando o desenvolvimento de uma API para um projeto de um Sistema para Desktop, utilizando o próprio PHP e o Vue js. Porem, não sei por onde começo. Já tenho conhecimentos básicos, mas preciso evoluí-los.

Desde já agradeço.

**Comment by woliveiras** [comment]
Olá @emanuelgsouza, o fluxo de buscar um(a) mentor(a) mudou, agora seguimos esse esquema: https://medium.com/trainingcenter/menos-burocracia-para-conseguir-um-mentor-ou-mentora-d571ed9cc3e0#.1p103u5hc

https://github.com/training-center/mentoria#preciso-de-uma-mentora
