### ISSUE TITLE
Mentoria VueJS, Componentes Web e performance de front

### ISSUE THREAD

**Issue by wilcorrea** [training-center/mentoria#365]
Oi pessoal, tenho uma pegada mais backend, mas tenho boas noções de front.
Atualmente tenho procurada reciclar meus conhecimento em Javascript e gostaria de me aprofundar em VueJS, Componentes Web e performance de front end.

Entrei em contato via Telegram com o @vinicius73 que está marcado como disponível na fila e espero que ele ou outro mentor possam me ajudar nessa jornada ; )

**Comment by vinicius73** [comment]
Tá sussa @wilcorrea manda PR com seus dados de pupilo :)

**Comment by woliveiras** [comment]
Perfeito meus queridos!

Feito o Merge.

Agora é só o @vinicius73 atualizar o perfil dele e muito sucesso pra vocês!
