### ISSUE TITLE
Preciso de um(a) mentor(a) de Front-End: HTML/CSS/JavaScript

### ISSUE THREAD

**Issue by adeonir** [training-center/mentoria#376]
**Nome:** Adeonir Kohl
**Descrição:** Opa. Sou Adeonir e trabalhei desde cedo como designer gráfico, depois passando a web designer. Faço freelas como desenvolver web há 3 anos, trabalhando com básico de HTML/CSS e também básico de PHP. Quero seguir na carreira de Front-End e para isso preciso de orientação para aprender Javascript, Node, React e afins. Além de aprimorar meu CSS com desenvolvimento de componentes e estruturação.
**Contatos:** 
[Facebook](https://www.facebook.com/adeonir)
[Linkedin](https://br.linkedin.com/in/adeonir-kohl-85599420)

**Comment by woliveiras** [comment]
Fala @adeonir 

Não precisa mais abrir issue para buscar um(a) mentor(a).

Da uma olhada aqui: https://medium.com/trainingcenter/menos-burocracia-para-conseguir-um-mentor-ou-mentora-d571ed9cc3e0#.4an727c5p

😄

**Comment by adeonir** [comment]
Ae @woliveiras 

Já combinei com o @wilsoncampoz, me aceitou como pupilo.
Criei o perfil e fiz o PR.

**Comment by woliveiras** [comment]
Perfeito! \o/
