### ISSUE TITLE
[Quero ser mentor] de CakePHP

### ISSUE THREAD

**Issue by DiegoFSFlor** [training-center/mentoria#378]
**Nome:** Diego Fernando dos Santos
**Descrição:** Adoro programação MVC e me identifiquei bem com o CakePHP, hoje consigo fazer quase tudo no cake, em questão de programação, isto facilita por ser em "php". Não tenho um conhecimento Vasto, mas tudo oque eu sei posso ensinar os que necessitam. 
**Contatos:** email: diegofernando@geniusweb.eti.br

**Comment by woliveiras** [comment]
Faaaala @DiegoFSFlor 

Você já leu as [responsabilidades do mentor]((/mentores/responsibility.md)) e está de acordo com a ideia do projeto?

**Comment by DiegoFSFlor** [comment]
Bom dia William, estou de acordo e disposto a ensinar com tudo oque será
necessário

2016-12-01 7:45 GMT-02:00 William Oliveira <notifications@github.com>:

**Comment by woliveiras** [comment]
Show de bola @DiegoFSFlor 

Os @training-center/mentors irão avaliar seu perfil e logo te daremos uma resposta.

Obrigado pelo seu interesse em colaborar com a carreira de outras pessoas de maneira gratuita e sem pretensões! \o/

**Comment by DiegoFSFlor** [comment]
Estou há ordens, quero ensinar oque sei para aprender também, é mais rápido
o desenvolvimento nas dificuldades que encontram.

Em 1 de dezembro de 2016 11:07, William Oliveira <notifications@github.com>
escreveu:

**Comment by woliveiras** [comment]
Fala @DiegoFSFlor, pode criar seu perfil. :)

Bem vindo ao time!

Você receberá por email um convite a participar da org no GitHub. Entre no nosso Slack, também, para entrar no nosso canal de Mentores.
