### ISSUE TITLE
Preciso de um mentor para Desenvolvimento Front-end

### ISSUE THREAD

**Issue by idlua** [training-center/mentoria#39]
# Luan Vicente

Tenho 23 anos, sou de São Paulo, mas moro atualmente em Caruaru, cidade do agreste pernambucano. Sou autodidata (no início, por falta de opção, hoje, por ter alcançado bons resultados e me virar melhor assim).

## Carreira e Objetivos

Comecei a me interessar por desenvolvimento em 2012. Procurei por instituições de ensino pra começar a estudar mas não encontrei muitas opções onde moro; fiz apenas um curso profissionalizante em Web Design. Trabalhei algum tempo com pequenos projetos desenvolvendo Front e Back-end, mas ignoro esse tempo, pois foi o *tempo da 'gambiarra'*.

Atualmente tenho estudado a maior parte do tempo, e criei alguma experiência teórica em desenvolvimento com boas práticas em Front-end. Tentei aprender o máximo do HTML, CSS e JS puros antes de partir pra ferramentas como ***task runners***, ***pré-processadores CSS***, ***arquitetura***, ***modularização*** e etc.

---

Meu objetivo é um pouco arriscado, porém bem decidido. Basicamente pretendo continuar estudando muito, juntar uma grana e voltar pra São Paulo. Conseguir começar a trabalhar na área e fazer o que gosto. Por isso minha busca por um mentor: não tomar caminhos errados nos estudos e seguir os passos de pessoas experientes.
Contudo, como dito no readme da iniciativa, não pretendo ter um *Google pessoal via e-mail*. Já tenho uma ideia do que estudar, busco soluções pros problemas que surgem.. mas é bom ter alguém para ajudar a nortear o futuro. :D

## Alguns links
[idlua.me](http://idlua.me)
[Twitter](http://twitter.com/idlua)
[Facebook](http://facebook.com/idluaOn)
luanfrvicente@gmail.com

---

São por causa de pessoas incríveis e voltadas a compartilhar o que sabem que a Web é tão foda dessa forma que é! Então, obrigado!

**Comment by woliveiras** [comment]
Fala @idlua! Só aguardar a galera @training-center/moderators responder

**Comment by woliveiras** [comment]
Valeu pela participação cara! :smile: 

Espero que possamos ajudar nessa sua caminhada cara. Curti.

**Comment by idlua** [comment]
Vlw @woliveiras! Demorei um pouco pra criar uma issue mas saiu! xD

**Comment by woliveiras** [comment]
kkkkk

Isso ae mano

**Comment by matmarsiglio** [comment]
@idlua acho que consigo te ajudar, cara! Eu tenho bastante foco em aplicações grandes, consigo te dar um bom _overview_ das coisas do mercado de Front, fora se quiser se arriscar no VIM e GIT, estamos ai! 

Eis meu perfil por aqui: 
https://github.com/training-center/mentoria/blob/master/mentores/perfis/matheus_marsiglio.md

😸

**Comment by woliveiras** [comment]
Por mim é sucesso, ein! 😄 

@idlua estará em boas mãos. \o/

Se quiserem prosseguir, é só o @idlua criar o perfil de pupilo e atrelar ao @matmarsiglio

**Comment by idlua** [comment]
@matmarsiglio aê!! Já te sigo no Twitter há um tempo e não tenho dúvida de que estarei em boas mãos, @woliveiras! haha

No Git já tô me aventurando, no VIM ainda não, mas vamo nessa! Eu sempre opto por fazer tudo que puder pelo terminal mesmo..

Vou criar o perfil e mandar então!

**Comment by matmarsiglio** [comment]
Então vamos lá! @idlua tu é **#TeamTelegram** ou **#TeamWhatsapp**? E uso bastante o Telegram por causa da facilidade de migrar entre mobile e desktop e até por ele aceitar formatação markdown nas mensagens. 

Praticamente não uso o Facebook durante o dia a dia, mas sempre respondo por lá (com algum delay). Me diga o que achar interessante e partiu bater uns papos aí!

**Comment by idlua** [comment]
@matmarsiglio atualmente tenho fugido do Whatsapp e daqueles grupos de família, já tô instalando o Telegram! Haha Mesmo username daqui: @idlua

**Comment by woliveiras** [comment]
Boa! 

Se forem se falando por fora dessa issue, a gente pode fechar viu galera (fica mais fácil pra gente cuidar das outras kkkk)

**Comment by matmarsiglio** [comment]
@woliveiras ia te falar isso já! Pode fechar, estamos falando por Telegram 😄

**Comment by woliveiras** [comment]
Pra já! 😄
