### ISSUE TITLE
Quero ser mentor de Back-end/DevOps (Java, Groovy, AWS) usando Spring MVC e Grails 

### ISSUE THREAD

**Issue by vtinguan** [training-center/mentoria#392]
Nome: Vinicius Tinguan
Profissão: Desenvolvedor Backend
Experiência: 3 anos

Sobre: Comecei a minha carreria trabalhando na boo-box fazendo um estágio na parte de devops, lá aprendi muitas coisas sobre Linux/Arquitetura POSIX e basicamente todo o fluxo de deployment e automação de uma aplicação de alta escalabilidade. <br />
Fiquei lá por 1 ano até começar a trabalhar na E.Life, onde fiquei aproximadamente 4 meses estagiando no desenolvimento de aplicações em Rails. Lá tive o meu primeiro contato com TDD e desenvolvimento back-end. <br />
Porém, no meio desse período, fui chamado para trabalhar no Guiabolso (época em que ele ainda estava começando, tinha aproximadamente 20 pessoas lá), que é onde estou até hoje como backend developer. <br />
Desde quando ingressei, sempre fui desafiado a desenvolver diversas API's complexas, com requirements de segurança bem exigentes, além de uma bela base de TDD e clean architecture. <br />
Apesar de ter apenas 3 anos de experiência, acredito que tenho um bom conhecimento para passar pras pessoas que tem interesse de ir um pouco mais a fundo no desenvolvimento de API's complexas e performaticas. 
<br />
<br />
Como portifólio: Tenho um app que consome uma API que faz extrações de notas e faltas do sistema da FATEC-SP. Hoje conta com mais de 1000 usuários. <br />
-[Sigatec](https://play.google.com/store/apps/details?id=me.razorblade.sigatec&hl=pt_BR) <br />
-[API CODE](https://github.com/vtinguan/siga_api)<br />
No meu github também tem outros exemplos de API's bem estruturadas sendo usadas para resolução de problemas de programação, como a elevator manager api <br />
-[Elevator Manager API](https://github.com/vtinguan/elevator_manager_api)
<br />
Contato:
-[About.me](https://about.me/vinicius_tinguan) <br />
-[LinkedIn](https://br.linkedin.com/in/vinicius-tinguan-a1712648) <br />
-[Github](https://github.com/vtinguan) <br />
-Email: vinicius.tinguan@gmail.com

**Comment by woliveiras** [comment]
Bem vindo @vtinguan 

Que experiência boa em pouco tempo cara! Muito bom.

Você já leu as [responsabilidades do mentor](https://github.com/training-center/mentoria/blob/master/mentores/responsibility.md) e está de acordo com a ideia do projeto?

**Comment by vtinguan** [comment]
Li, sim! Estou de acordo :)

**Comment by woliveiras** [comment]
Perfeito!

É só aguardar então que logo te respondemos sobre seu perfil.

**Comment by woliveiras** [comment]
Fala @vtinguan, pode criar seu perfil. :)

Bem vindo ao time!

Você receberá por email um convite a participar da org no GitHub. Entre no nosso Slack, também, para entrar no nosso canal de Mentores.
