### ISSUE TITLE
Preciso de um mentor para Front-end com foco em VueJS, ES6, Nodejs. 

### ISSUE THREAD

**Issue by wharley** [training-center/mentoria#397]
Nome: Wharley Ornelas da Rocha

Descrição: Olá, O pouco de conhecimento  que tenho foi correndo atras, lendo na Internet e pessoas de comunidades. Tenho 14 anos de experiência com erp usando linguagem como Delphi e Cobol. E no início de 2016 foi amor a primeira Vista com javascript onde tive a oportunidade de fazer parte com nodejs e angularjs na construcao de um Erp. Atualmente estou em uma empresa onde estou tendo uma liberdade em escolher quais frameworks e libs. Com isso estou tentando estudar  sobre SPAs, NodeJS, VueJS, ES6 e tudo mais para construir um projeto completo, por ter muitos artigos,  estou com dificuldades em focar os estudos para poder ter um conhecimento bacana, fico no aguardo de um mentor.

**Comment by woliveiras** [comment]
Fala @wharley!

Agora não precisa mais abrir issue.

Da uma olhada nesse artigo que explicamos o novo fluxo: https://medium.com/trainingcenter/menos-burocracia-para-conseguir-um-mentor-ou-mentora-d571ed9cc3e0

:smile:

**Comment by wharley** [comment]
Opa @woliveiras,

Valeu, irei dar uma lida.

**Comment by woliveiras** [comment]
🤘 🤘 

Boa sorte, cara

**Comment by wharley** [comment]
@woliveiras, desculpe pertubar voce.

Preciso cadastrar como pupilo né ? Porque dando uma olhada vi que tem o perfis do pupilo, só que observei que todos estao com mentor. Entao veio a dúvida

**Comment by woliveiras** [comment]
Fala @wharley 

Que isso, cara? Tem problema não.

Então, é só entrar em contato com os mentores disponíveis mesmo. Quando conseguir, ai cria seu perfil.

Antes disso é só aguardar mesmo e ficar de olho no nosso Twitter: `@ct_org` (https://twitter.com/ct_org)

Lá nós compartilhamos quando tem mentor disponível 😄
