### ISSUE TITLE
Feedback dos pupilos

### ISSUE THREAD

**Issue by woliveiras** [training-center/mentoria#4]
Issue para tratarmos sobre os feedbacks dos pupilos

cc: @baltazarparra @danilovaz @LFeh @JGcarv @willycamargo @icaromh @sanderweb @augustoabreu @robsonbittencourt

**Comment by woliveiras** [comment]
Ponto importante que o @danilovaz citou!

Poderíamos ter uma bancada que iria receber os feedbacks dos pupilos pra garantir que todo mundo esteja curtindo, sendo bem recebido, etc.

**Comment by augustoabreu** [comment]
Acho importante um feedback pois pode servir como uma forma de avaliação e seleção de mentores.

**Comment by woliveiras** [comment]
Sim mano e já protege a galera de possíveis tretas! Vai quee...

**Comment by danilovaz** [comment]
Seria interessante se fosse definido algo do tipo: todo mês no dia tal, será enviada uma pesquisa (sugiro o Typeform) para os pupilos de cada mentor. Após todos responderem, cada resposta será analisada por um grupo de pessoas comprometida com esse feedback. Caso hajam situações críticas, esse grupo de pessoas intervém com o mentor para analisar as duas versões e chegar a um consenso bom para todos os envolvidos.

Após esse trâmite, seria interessante disponibilizar o final do relatório de cada mentor. Assim, temos total transparência da avaliação e estimula os mentores. O próprio Typeform nos dá uma opção de compartilhar via URL o resultado da pesquisa em porcentagens e não exibe perguntas opinativas que essas sim, devem se manter anônimas.

**Comment by rafaDfaria** [comment]
Olá a todos, se eu participar, com certeza será como pupilo, ainda não tenho know how para ensinar sobre desenvolvimento, minha dúvida é... 
O foco será somente front-end?
 Estou cursando a faculdade de Ciências da Computação e paralelamente estou fazendo um curso online de Harvard, o CS50, acredito que vai ser meio puxado alguns aspectos desse curso online, logo de cara já vai ter algo em C, C#, Java, Javascript não sei o nível de dificuldade que enfrentarei.

Tenho muita coisa para aprender, mas meu foco inicial é back-end.

Será que eu conseguiria algum mentor para mim?

**Comment by rafaDfaria** [comment]
E já adiantando, parabéns a todos vocês!
Sem demagogias, sério! Se todo mundo tivesse a boa vontade de passar o conhecimento adiante, viveríamos em um mundo muito mais evoluído e melhor.

**Comment by danilovaz** [comment]
@rafaDfaria Isso ainda não foi discutido até onde eu sei. Mas eu presumo que seja mentoria em desenvolvimento geral. Dessa forma, será possível encontrar mentores para C, Java, Arduino, JavaScript, Angular, Ember, React, IoT, AI e o que mais as pessoas da comunidade puderem oferecer.

**Comment by rafaDfaria** [comment]
@danilovaz  vou ficar de olho aberto por aqui então, estou com a intenção de criar um projeto de Arduino dentro de alguns meses, vou focar inicialmente nesse curso online que estou fazendo e logo em seguida quero brincar um pouco com o Arduino.

**Comment by woliveiras** [comment]
Estou compartilhando com todas as comunidades, sem restrições. O próprio CT é geral, então seria legal a mentoria ser geral também. :)
Inicialmente foi pensado no Front por que começou a discussão lá no Forum do Front End Brasil, mas, tendo gente interessada e gente disposta a ajudar, da pra ir ao infinito e além! :D

**Comment by danilovaz** [comment]
@rafaDfaria Lega, caral! Clique em "Watch" no repositório, assim você recebe as atualizações a respeito do projeto e não perde nenhuma novidade. E se puder, clique em "Star" no repositório. Quanto mais visibilidade o repositório tiver; mais pessoas são impactadas, o que gera mais mentores e mais pupilos :smile:

**Comment by Marcelosilva10** [comment]
Como ira Funcionar por aqui?

**Comment by woliveiras** [comment]
Fala @Marcelosilva10, estamos definindo como tudo vai funcionar. Acompanha aqui nas issues como o @danilovaz falou ali em cima e ajude a opinar sobre como tudo vai ser. :D

**Comment by woliveiras** [comment]
Ressaltei a importância do Feedback dos pupilos [aqui](https://github.com/training-center/mentoria#preciso-de-um-mentor).

Se tudo estiver OK, podemos fechar a issue.

**Comment by danilovaz** [comment]
Legal @woliveiras ficou muito bom! Por hoje talvez eu não acompanhe ou responda as issues, mas amanhã estamos aí :smile: e vamos que vamos, está ficando massa!

**Comment by Marcelosilva10** [comment]
Podeixar vou ver @woliveiras

**Comment by woliveiras** [comment]
Galera, é legal deixar como regra que o pupilo envie um feedback mensal para os membros da org (via um Typeform que podemos criar)?

**Comment by danilovaz** [comment]
@woliveiras acho legal fazer isso sim. com isso nós podemos ter uma leve noção dos pupilos que estão engajados, já que demanda um tempinho da pessoa pra responder sobre um compilado do seu mês

**Comment by woliveiras** [comment]
\o/

**Comment by baltazarparra** [comment]
Caras, não entendi esse ponto.

Tipo, como já conversamos em outra issue, o foco não vai ser tão técnico, estamos de acordo nisso?

Alinhado esse ponto, acho que o feedback não tem tanto impacto, pois vai ser um lance quase pessoal. 

O que espero do mentor, no caso, seria tipo...
Uma visão ampla das vertentes do desenvolvimento, e um caminho legal pra seguir essas vertentes quando houver interesse.
Uma posição sobre o mercado também, tipo, tal vertente tem um mercado forte, essa outra tem menos.

E de forma leve, uma posição sobre tecnologias, tipo...
- Quero estudar X, o que você acha?
- X tem mercado pra isso e isso, mas Y atende melhor essa vertente por isso e isso.

Acho que a grosso modo, seria um slack onde teríamos um mentor disponível com um grupo limitado de desenvolvedores, conversando sobre esses tópicos, sendo que quando entrassem em uma discussão interessante, poderiam estender isso pra fora do slack, abrindo discussões.

**Comment by woliveiras** [comment]
É isso mesmo mano, mas sem Slack. Algo mais pessoal. O pupilo e o mentor devem ficar em contato entre eles. 
Se colocar num Slack, tem gente (pupilo) que não expõe a opinião por ter mais gente olhando. Então era melhor ter um espaço pra cada um. Como o email do Mentor. 

Algo menos público, se torna um contato mais pessoal e menos travado.

Tem gente que tem facilidade em aprender uma coisa e dificuldade em outras, se o mentor falar pra estudar determinado assunto no Slack pra todo mundo, essa pessoa pode ter dificuldades e não vai se expor por vergonha dos outros.

Mentoria não da pra tratar como os grupos de estudos que é mais parecido com sala de aula, sabe?

Nesse caso, o Feedback do pupilo é se ele está sendo bem tratado, se o mentor não é arrogante com ele, se ele está se sentindo bem com a ajuda do Grupo, se ele curte a forma como a organização está se portando, essas coisas.

O Feedback que estamos falando aqui é sobre o Projeto (nós) e sobre o Mentor. Como o Pupilo e Mentor conversam, pode ser escolhido por eles durante uma conversa, depois que o Mentor escolher esse pupilo nas issues.

😄

**Comment by baltazarparra** [comment]
@woliveiras saquei mano, perfeito.

A gente pode aconselhar os pupilos a mandar de forma anonima sempre que sentirem a necessidade, um feedback pro CT, saca?

**Comment by woliveiras** [comment]
No caso sem ser mensalmente mano?

Nesse ponto de usar Slack, Gitter e outras coisas que são em grupo pra coisa privada eu ainda acho ruim. É bom que o mentor e o pupilo escolham como se comunicar.

Como é uma conversa pessoal, sobre carreira, o melhor seria o email do mentor ou um contato que os dois acharem melhor.

Sem prender eles a org depois do contato via issue.

A org fica só para:

* Manter um cadastro dos mentores aqui no repo
* Manter uma base de quem quer ser pupilo para os mentores cadastrados entrarem em contato com eles
* Receber feedback e manter o cadastro de mentores com pessoas que estão fazendo algo bom, removendo quem descumprir o código de conduta

Senão fica parecendo escola mano, com diretoria e talz... kkkkk

**Comment by JGcarv** [comment]
Concordo @woliveiras 

Temos que partir to principio que todo mundo aqui é maduro e pode tentar resolver seus problemas sozinho, sem uma "mãe" protetora.

Acho que o feedback dos pupilos deve ter um caráter mais de avaliação pessoal e do processo: no final de determinado período, ele reponde perguntas de como foi seu aprendizado, se ele acha que o contato com o mentor ajudou de alguma forma, se ele está mais próximos do seus objetivos, etc. Assim como quais técnicas que o mentor utilizou que mais o ajudou, essas coisas.

Acho que o papel do feedback é entender o que está e o que não está funcionando, apenas para otimizar o processo de aprendizagem...

**Comment by woliveiras** [comment]
Exatamente @JGcarv.

Só ligamos quem precisa com quem está disposto a ajudar e o resto vai da autonomia de ambos. \o/

Bem pessoal, bem específico, sem muito processo pra não tornar engessado sabe.

**Comment by augustoabreu** [comment]
Acho que a org só precisa saber se o Mentor segue o código de conduta e nada mais. Mas não descarto um form com algumas perguntas para gerar dados estatísticos e informativos, como o  @JGcarv disse.

**Comment by Marcelosilva10** [comment]
Certo e @woliveiras e qual assunto inicial sera abordado aqui?

**Comment by woliveiras** [comment]
@training-center/moderators, com base no que definimos, deixei o relato ao feedback na descrição do projeto e vamos tacar lenha nesse negócio. 

Qualquer problema podemos reabrir a issue.

**Comment by woliveiras** [comment]
@Marcelosilva10, esse projeto aqui é o do Mentoria, talvez você confundiu com os grupos de estudos.

Senão, é só abrir uma issue seguindo o template que aparece lá que vamos começar a fazer o Mentoria rodar. :D

**Comment by Marcelosilva10** [comment]
@woliveiras otimo, vou ver lá também
