### ISSUE TITLE
Preciso de um mentor para Desenvolvimento Front End.

### ISSUE THREAD

**Issue by randhson** [training-center/mentoria#40]
**# Randson Nunes**
Tenho 26 anos, sou de Paulo Afonso-Bahia, mas moro em Aracaju-Sergipe. Estou cursando Sistemas de informação, no 5º período.

**## Carreia e Objetivos**
Comecei no mundo da web, com um curso online de HTML e CSS lá em 2005. Já na faculdade comecei a estudar e procurar por estágios.

**- Tenho** conhecimento básico em java, c#, html, css e js.

**- Meu objetivo** é adquirir conhecimento teórico e prático, para ser um _Engenheiro Front End_.
Quero apreender a usar com maestria tecnologias como:
 - Task runner                        - Package Manager             - Frameworks

- Dependency Manager        - Modularização                   - UI / UX
 

**## Onde me Encontrar**
[https://branded.me/randsonnunes](url)
[https://github.com/randhson](url)
[https://twitter.com/@randhson](url)
[https://telegram.me/Randhson](url)

**Comment by woliveiras** [comment]
Fala @randhson! Só aguardar a galera dos @training-center/moderators retornarem o contato aqui viu. :smile:

**Comment by woliveiras** [comment]
@matmarsiglio, bora ajudar o mano @randhson?

Eu gostaria ajudar, mas como ele tem interesse em UI/UX lasca, por que ai eu não manjo! kkkkk

**Comment by matmarsiglio** [comment]
@woliveiras vamaê! 

@randhson onde tu costuma estar para conversa? Eu uso bastante o Telegram e como ele permite escrever em Markdown, tem app pra desktop e mobile, eu super recomendo usarmos 😄

**Comment by randhson** [comment]
e aí blz @matmarsiglio  ?
Eu costumo usar muito o telegram e o slack.
http://telegram.me/Randhson

**Comment by matmarsiglio** [comment]
Te mandei uma msg la! @woliveiras Issue digna de ser fechada, vamos continuar o papo pelo Slack 😸

**Comment by woliveiras** [comment]
Show de bola! Pra já. kkk

**Comment by woliveiras** [comment]
@matmarsiglio, não esquece de colocar os pupilos no seu perfil. kkkk
