### ISSUE TITLE
Preciso de um mentor para Full Stack Node + Front-End

### ISSUE THREAD

**Issue by isaacguerreir** [training-center/mentoria#400]
Boa tarde,

Meu nome é Isaac Guerreiro, atualmente eu sou jornalista. Eu estou estudando programação a uns 6 meses. Já me envolvi bastante com a minha comunidade de programação na minha cidade (Manaus), mas de uns tempos pra cá eu tenho sentido a necessidade de ter alguém que possa me mentorar na área de programação.

Eu atualmente já faço alguns pequenos projetos em Node.js, HTML + CSS e comecei a estudar mais sobre Typescript, Angular 2 e React. Eu estou procurando alguém que possa me ajudar nessas tecnologias, mas também me ajude no sentido de adquirir experiência real para o mercado de trabalho, principalmente que meu principal objetivo em 2017 é mudar de carreira e conseguir meu primeiro emprego na área.

Eu li o código de conduta, estou ciente e aceito.

Contato: isaacguerreicom@gmail.com
https://www.facebook.com/isaac.guerreiro

**Comment by woliveiras** [comment]
Fala @isaacguerreir 

O processo de procura por mentor mudou, da uma olhada aqui: https://medium.com/trainingcenter/menos-burocracia-para-conseguir-um-mentor-ou-mentora-d571ed9cc3e0

E aqui: https://github.com/training-center/mentoria#preciso-de-uma-mentora

Agora está mais simples. 😄
