### ISSUE TITLE
Mentoria sobre contribuição em projetos open-source

### ISSUE THREAD

**Issue by joffilyfe** [training-center/mentoria#419]
**Nome**: Joffily Ferreira

**Perfil**: Sou um estudante da área de T.I e tenho um conhecimento relativamente básico nas áreas de front-end, back-end, banco de dados relacionais, sistemas operacionais e processos de engenharia de software.

**Área de atuação**: Desenvolvimento Web e Mobile.

**Confortável com as seguintes tecnologias**: Linux, Unix, SQL, C, Python, Ruby, Golang, Java, Git, HTML, CSS2/3.
**Gostaria de melhorar nas seguintes áreas**: Javascript, Construção de APIs, SEO, UX, **Deployment**.

**Aspiração**: Gostaria de conhecer um mentor(a) que pudesse me ajudar a encontrar projetos interessantes para contribuir e consequentemente evoluir como desenvolvedor.

**Comment by woliveiras** [comment]
Fala @joffilyfe! 

O processo de conseguir um(a) mentor(a) mudou, agora é só seguir isso aqui: https://github.com/training-center/mentoria#preciso-de-uma-mentora
