### ISSUE TITLE
Quero ser mentor de Front End

### ISSUE THREAD

**Issue by renanoliver** [training-center/mentoria#423]
**Nome:** Renan Oliveira
**Descrição:** Com 3 anos de experiência em front end, hoje atuo como front end engineer na @thomsonreuters, atualmente trabalho com AngularJS mas posso ajudar com qualquer coisa relacionada a front end, procuro sempre me manter bem por dentro das novidades.
**Contatos:** renansdeoliveira@gmail.com e https://linkedin.com/in/renanoliver

![bitmoji](https://render.bitstrips.com/v2/cpanel/10134094-214077190_1-s4-v1.png?transparent=1&width=246)

**Comment by woliveiras** [comment]
Fala @renanoliver!

Você já leu as [responsabilidades do mentor](https://github.com/training-center/mentoria/blob/master/mentores/responsibility.md) e está de acordo com a ideia do projeto?

**Comment by renanoliver** [comment]
@woliveiras: Sim, li e estou de acordo :+1:

**Comment by woliveiras** [comment]
\o/

Sucesso @renanoliver.

Você pode [criar seu perfil](https://github.com/training-center/mentoria#quero-ser-mentora)!

Não esquece de entrar no nosso [Slack](https://ctgroups.herokuapp.com/) e me avisar pra eu te adicionar no canal de Mentores. :smile: 

Assim que tiver seu perfil criado, seria interessante entrar em contato com as pessoas que buscaram ajuda nas issues mais antigas, [aqui](https://github.com/training-center/mentoria/issues?q=is%3Aissue+is%3Aopen+sort%3Acreated-asc).

Assim que tiver seu perfil no repositório nós fechamos essa issue aqui.

**Comment by renanoliver** [comment]
Tudo certo, @woliveiras! 

Só fechar a issue e ir em busca dos pupilos :rocket:
