### ISSUE TITLE
Preciso de um Mentor para FullStack

### ISSUE THREAD

**Issue by phillip18** [training-center/mentoria#433]
Procuro mentor baseado em Ruby on Rails e Javascript e seus frameworks, tenho conhecimento nas duas linguagens e quero aprender e subir o nivel do meu código e conhecimento. Aceito qualquer coisa que possa me ajudar a crescer como um Dev, como trabalhar em projetos e tudo mais...

Dê uma olhada no meu repo e veja minha experiência.

Obrigado!

**Comment by woliveiras** [comment]
Fala @phillip18!

O processo para conseguir um Mentor(a) mudou, agora não se abre mais issues para isso.

Da uma olhada aqui: https://github.com/training-center/mentoria#preciso-de-uma-mentora
