### ISSUE TITLE
Gostaria de receber mentoria de Desenvolvimento Web (Full stack)

### ISSUE THREAD

**Issue by jucylene** [training-center/mentoria#453]
Meu nome é Jucylene, sou uma pessoa apaixonada pelo fato de desenvolver algo novo e aceitar novos desafios. Gostaria de me tornar uma desenvolvedora completa, desde o Back-end até o Front. Estou finalizando a gradução (restando um TCC para entregar que no momento já está em andamento, \0/ ).

Sobre minhas experiências, já desenvolvi um sistema utilizando Java, mas tenho interesse e curiosade de aprender Ruby e Python, além de desenvolver skills na parte de Front-end: JavaScript/ES6, HTML, CSS. 

Atualmente estou estudando o Ionic2 com o Angular2 e explorando o Firebase em um projeto pessoal e visando desenvolver um outro app social.

Gostaria também de estudar Padrões de Projeto, Testes automatizados, Integação Contínua, entre outros assuntos relevantes.

Podem me encontrar aqui:
[Facebook](https://www.facebook.com/jucylenehelismara)
[GitHub](https://github.com/jucylene)
[Linkedin](https://br.linkedin.com/in/jucylene-melo-610423b6) 

Desde já agradeço! ;)

**Comment by woliveiras** [comment]
Oi @jucylene! 

Hoje em dia o processo para conseguir um mentor ou mentora mudou. Não precisa mais abrir issue.

Da uma olhada aqui: https://github.com/training-center/mentoria/#preciso-de-uma-mentora

E aqui: https://medium.com/trainingcenter/menos-burocracia-para-conseguir-um-mentor-ou-mentora-d571ed9cc3e0

Somente as issues antigas e que não conseguimos ajudar, ainda, que ficam abertas. :smile:
