### ISSUE TITLE
Preciso de um mentor(a) para WooCommerce

### ISSUE THREAD

**Issue by theandersonn** [training-center/mentoria#456]
Olá |o| 
Acabei de ver pelo Twitter que tem mentor disponível para WooCommerce, gostaria muito de trocar ideias sobre Woo e aprender mais sobre a estrutura e montar lojas do zero.

Já tenho certo conhecimento de WordPress e um nível muito básico de Woo, apenas de configuração. 

Meus contatos:
Twitter: https://twitter.com/theandersonn
GitHub: https://github.com/theandersonn

Acabei de ler o termo de responsabilidades
https://github.com/training-center/mentoria/blob/master/pupilos/responsibility.md

**Comment by woliveiras** [comment]
Faaala @theandersonn!

Não precisa mais abrir issue mano, agora é só mandar email pra o Mentor. Da uma olhada: https://github.com/training-center/mentoria#preciso-de-uma-mentora

https://medium.com/trainingcenter/menos-burocracia-para-conseguir-um-mentor-ou-mentora-d571ed9cc3e0

**Comment by theandersonn** [comment]
@woliveiras Valeu! Tá falado :facepunch:
