### ISSUE TITLE
[Quero ser mentor] de Frontend (Javascript e AngularJS)

### ISSUE THREAD

**Issue by gustavogodoi** [training-center/mentoria#458]
**Nome**: Gustavo Godoi
**Descrição**: Com mais de 7 anos de experiência em front e back end, tendo trabalhado principalmente com PHP, MySQL e WebServices. Atualmente mais focado em frontend, com Angular(1x) e Javascript vanila.

**Contatos**: gugodoi@gmail.com e https://ie.linkedin.com/in/gugodoi

**Comment by woliveiras** [comment]
Fala @gustavogodoi!!

Você já leu as responsabilidades de mentor e a proposta do projeto e está de acordo com tudo?

**Comment by gustavogodoi** [comment]
Hey @woliveiras ,

Sim, li e concordo! :)

**Comment by woliveiras** [comment]
Show de bola, cara! 

Os @training-center/mentors irão avaliar seu perfil e logo te daremos uma resposta.

**Comment by woliveiras** [comment]
Fala @gustavogodoi, pode criar seu perfil e adicionar seu nome na lista deixando em aberto sua disponibilidade.

Assim que finalizar isso, seria legal dar uma olhada nas issues antigas e ver se consegue atender alguma dessas pessoas. :smile: 

Valeu pela vontade de contribuir com a comunidade.

**Comment by woliveiras** [comment]
Merged #465
