### ISSUE TITLE
Preciso de um mentor(a) para UX/UI

### ISSUE THREAD

**Issue by devigor** [training-center/mentoria#461]
Estou necessitando de um mentor(a) em UX/UI, estou sentindo a necessidade de melhorar os meus layouts e deixar eles mais usáveis.

OBS: Criei essa issue para quando um mentor estiver disponível possa ver quem está precisando de um mentor.

**Comment by woliveiras** [comment]
Fala @devigor,

O processo de Mentoria mudou. Eles só olham as issues antigas, mas as novas são fechadas para seguir o novo fluxo:

https://github.com/training-center/mentoria#preciso-de-uma-mentora

**Comment by LFeh** [comment]
@woliveiras Está comigo :)

**Comment by woliveiras** [comment]
Shooow mano
