### ISSUE TITLE
Preciso de mentoria em TDD, Agile etc.

### ISSUE THREAD

**Issue by odnamrataizem** [training-center/mentoria#464]
Olá, pessoas! Sou um programador de 33 anos chamado Armando Meziat *bastante* obcecado desde tenra idade por desenvolvimento Web, principalmente na área *front-end* (o que não me impede de também gostar do resto do *stack*, muito pelo contrário - se é Web, tô dentro!).

Muito embora eu seja normalmente autodidata nestas searas, algumas coisas acabam escapando à minha compreensão, até porque nunca precisei ou tive a chance de colocá-las em prática. É o caso de TDD e siglas relacionadas, possuo várias dúvidas a respeito. Até consigo bolar testes simples para coisas simples como, por exemplo, um *parser*, mas perguntem se consigo compreender as nuances de testes de interface (leia-se: *front-end*), PhantomJS, essas coisas um pouco mais elaboradas. Metodologias ágeis mesma coisa, é algo que simplesmente não entra na cabeça por mais que eu leia trocentos artigos a respeito.

Isso é muito importante para mim, já que vejo um número crescente de vagas de emprego exigindo precisamente estas duas coisinhas.

Para encerrar, declaro que li tudo o que tinha pra ser lido neste repositório, olhei *issue* por *issue* e cá estou. E devo dizer que achar esta organização foi um *godsend*.

P.S.: 日本語ができるメンターもあるんだろうか。僕はあまり上手じゃないけど、そんな人があれば超嬉しい😃

**Comment by woliveiras** [comment]
Fala @odnamrataizem!

Fico feliz por você ter curtido a ideia. 

Hoje não ficam mais abertas issues novas sobre busca por Mentor(a). Agora é só olhar na lista de mentores se tem alguém disponível e mandar email direto pra pessoa. - Ficou mais rápido. :smile: 

https://medium.com/trainingcenter/menos-burocracia-para-conseguir-um-mentor-ou-mentora-d571ed9cc3e0
