### ISSUE TITLE
Preciso de um Mentor

### ISSUE THREAD

**Issue by wgtoliveira** [training-center/mentoria#468]
Olá rapaziada!

Estou precisando de um norte sobre ao que me dedicar para iniciar minha carreira de programador. Tenho lido muito sobre angular2 e gostaria muito de encontrar um Mentor(a) que pudesse criar um plano de estudos com um projeto prático usando o mesmo. Preciso de uma luz geral sobre as tendẽncias dos projetos para a desktop e mobile.
Gostaria de aprender na prática, relacionar BD com as aplicações modernas e o uso de jquery,  Angular2 e React.

Como citei, estou aberto a criar junto com o meu futuro mentor(a) um plano de estudos para aperfeiçoamento das tecnologias. Preciso aprimorar meus conhecimentos
nas tecnologias que já conheço e também desejo aprender novas tecnologias para o meu avanço com programador.
Por favor me ajudem! É muita informação e estou perdido

Nome: Washington Oliveira
Nível de Conhecimento: HTML, CSS e JS intermediário
contato: tonoliveira743@gmail.com

**Comment by woliveiras** [comment]
Fala @wgtoliveira!

Hoje em dia não precisa mais abrir issues para conseguir um mentor. Basta entrar em contato com os mentores que estão disponíveis.

Da uma olhada aqui: https://medium.com/trainingcenter/menos-burocracia-para-conseguir-um-mentor-ou-mentora-d571ed9cc3e0

As issues abertas sobre isso são fechadas, mas não impede de você entrar em contato com eles, viu.

Bem vindo!

**Comment by wgtoliveira** [comment]
Bom dia, William

Valeu!
Já entrei em contato. Estou aguardando.

*         Washington Oliveira *
*        Consultor Google Adwords - Marketing Digital*
*75 99226 - 6025  - Skype: wgtshop*
*      Chronos - Seu Negócio na Web Agora *
*                            Website <http://chronosads.com/> *



Em 29 de janeiro de 2017 07:16, William Oliveira <notifications@github.com>
escreveu:
