### ISSUE TITLE
Preciso de um mentor para Javascript/Angular

### ISSUE THREAD

**Issue by denisibanez** [training-center/mentoria#48]
Denis Ibanez Rodrigues vieira
Gostaria de um mentor para aprender JS, trabalho com front end mas tenho grandes dificuldades com JS.
Conhecimento: Iniciante.

https://www.linkedin.com/profile/view?id=AAIAABTkJh0BYN3bKm2ku2XHK7i21_EBr5p-on4&trk=nav_responsive_tab_profile

**Comment by woliveiras** [comment]
Bem vindo @denisibanez!

Vamos ver se alguém pode te ajudar. 😄 

cc: @training-center/moderators

**Comment by woliveiras** [comment]
Alguém do @training-center/moderators pra ajudar esse jovem? 😄

**Comment by akfzambrana** [comment]
Como ele é iniciante, se não tiver nenhum outro(a) mentor(a) melhor qualificado(a) eu poderia ajudar a trilhar o caminho inicial até chegar num nível mais avançado e que precise de conhecimentos melhores.

**Comment by woliveiras** [comment]
Acho O TE MO

**Comment by denisibanez** [comment]
Tem um cara que mandou email, si responder ele?
Acho O TE MO

---

**Comment by woliveiras** [comment]
Qual o nome dele, @denisibanez?

**Comment by woliveiras** [comment]
@denisibanez, como não rolou mais conversa aqui, vou fechar a issue.

Caso queira continuar o processo é só dar um toque que eu reabro.
