### ISSUE TITLE
Preciso de um(a) mentor(a) em UX/UI e Cloud Computing

### ISSUE THREAD

**Issue by danilosoarescardoso** [training-center/mentoria#481]
Galera, 

Trabalhei recentemente em um _Cloud Broker_ brasileiro, tendo muita interação com Linux, scripts de automação e grandes _players_ de _Cloud Computing_. Por isso queria saber se alguém aqui tem interesse nessa área, a fim de desenvolver projetos e estudos em Cloud.

Adicionalmente, recentemente terminei meu TCC na área de Usabilidade e UX, e caso haja alguém que me ajudasse a dar mais passos nessa área, seria muito legal! Quero encontrar um caminho dentro de UX ou cloud para me desenvolver, e um mentor me ajudaria bastante nisso. Fico no aguardo do auxílio de vocês, muito obrigado!

**Comment by luizbills** [comment]
Eai @danilosoarescardoso 

Você já leu as [responsabilidades de pupilo](https://github.com/training-center/mentoria/blob/master/pupilos/responsibility.md) e está de acordo?

**Comment by danilosoarescardoso** [comment]
Já, e estou de acordo!

**Comment by luizbills** [comment]
Só aguardar agora, que algum dos nossos @training-center/mentors irá entrar em contato com você. Você também é livre para entrar em contato com qualquer um dos mentores.

**Comment by woliveiras** [comment]
Fala galera! O processo de conseguir um Mentor ou Mentora mudou. 

Agora é só entrar em contato direto com quem estiver disponível na lista de mentores.

Da uma olhada [aqui](https://medium.com/trainingcenter/menos-burocracia-para-conseguir-um-mentor-ou-mentora-d571ed9cc3e0).

As issues antigas continuam abertas, porém as novas são fechadas pra não confundir. :smile:

**Comment by luizbills** [comment]
@woliveiras eu cheguei a ler sobre o novo processo antes, mas tinha esquecido completamente kkkkkk desculpa, foi erro meu.

**Comment by danilosoarescardoso** [comment]
Aaaaah, ok! Falarei com eles, muito obrigado ;)

**Comment by danilosoarescardoso** [comment]
sem problemas @luizbills , você ajudou! haha, obrigado cara!
