### ISSUE TITLE
Quero ser mentor de Backend

### ISSUE THREAD

**Issue by paulodiniz** [training-center/mentoria#482]
**Nome:**

Paulo Diniz

**Descrição:**

Sou formado em Ciência da Computação na USP São Carlos e trabalho na área há quase 10 anos. Comecei a trabalhar com o falecido J2ME e de lá já passei por J2EE, Spring, Hibernate e outras.  Saí do Java para investir em Ruby e Python. 

Hoje trabalho principalmente com Ruby e Elixir, mas já trabalhei usando Python para processamento de dados estatísticos e aplicando modelos matemáticos até design de APIs em Ruby on Rails.

Sou um forte adepto de TDD e programação funcional. Não acho que são as melhores ferramentas do mundo, mas mudaram completamente a minha perspectiva com relação ao processo de desenvolvimento.
 
**Contatos:**

https://twitter.com/paulodiniz
https://github.com/paulodiniz/

**Comment by woliveiras** [comment]
:raised_hands: #elixir!!! Sucesso!

Bem vindo @paulodiniz,

Você já leu as [responsabilidades do mentor](https://github.com/training-center/mentoria/blob/master/mentores/responsibility.md) e está de acordo com a ideia do projeto?

**Comment by paulodiniz** [comment]
@woliveiras Sim e sim ;)

**Comment by woliveiras** [comment]
Show de bola, cara!

Os @training-center/mentors irão analisar seu perfil e logo te damos a resposta. 

Valeu pela vontade de contribuir.

**Comment by woliveiras** [comment]
@paulodiniz, seu perfil foi aprovado pelos outros mentores.

Bem vindo ao time, cara!

Agora você precisa criar seu perfi no [repositório](https://github.com/training-center/mentoria/blob/master/helpers/README.md) e vou te adicionar no nosso canal de mentores no Slack.

Depois é só aguardar alguém procurar sua ajuda.

**OBS: podem existir algumas issues abertas procurando mentoria que você pode ajudar, de uma olhada lá primeiro. Busque das issues mais antigas primeiro. :)**
