### ISSUE TITLE
Gostaria de um mentor para FullStack JavaScript.

### ISSUE THREAD

**Issue by desenv-marcelo-silva** [training-center/mentoria#485]
Preciso de um mentor para me ajudar com o FullStack JavaScript.
Meu nome é Marcelo Lopes, tenho 43 anos e tenho tido bastante dificuldade em direcionar os estudos e evoluir nesse assunto.
Sou um programador que atua com Delphi e que trabalha também com ASP e PHP.  
Meu objetivo é conhecer JavaScript e seu ecossistema a ponto de criar coisas sozinho com HTML/CSS/Javascript/DB (NoSQL ou não) e as ferramentas mais produtivas. 
Entender um pouco de design também e mudar minha carreira, evoluir, ganhar melhor, trabalhar melhor.
Apesar de fazer vários cursos parece que fazer um produto do zero é bem complicado, mesmo que pequeno nesse mundo Web.

Agradeço a todos!

Contatos: desenv.marcelo.silva@gmail.com

**Comment by danilovaz** [comment]
E aí @desenv-marcelo-silva tudo bem?

O processo de conseguir um Mentor ou Mentora mudou. 

Agora é só entrar em contato direto com quem estiver disponível na lista de mentores, [aqui](https://github.com/training-center/mentoria/tree/master/mentores)

Da uma olhada [nesse post](https://medium.com/trainingcenter/menos-burocracia-para-conseguir-um-mentor-ou-mentora-d571ed9cc3e0) para entender melhor como funciona agora.

As issues antigas continuam abertas, porém as novas são fechadas pra não confundir. :smile:

**Comment by desenv-marcelo-silva** [comment]
Nossa, desculpe, realmente eu fui bem apressado. 
Li uma.matéria a respeito, depois li rapidamente o material no Github e já mandei. Valeu!

Enviado do meu smartphone Sony Xperia™

---- Danilo Vaz escreveu ----

**Comment by danilovaz** [comment]
@desenv-marcelo-silva Tranquilo, cara! Sem problemas. Os posts citados acima dão uma ideia legal de como mudou, mas se tiver qualquer dúvida é só nos procurar :beers:

**Comment by kivervinicius** [comment]
Olá @desenv-marcelo-silva  tenho intenção de ser mentor, mas ainda não em cadastrei na lista de mentores, tenho a mesma stack que vc (Delphi, ASP e PHP) e sou fullstack front, caso possa aguardar eu me cadastrar na lista de mentores estamos ai para ajudar

**Comment by desenv-marcelo-silva** [comment]
Cara, que legal... 
Aguardo sim, sem problemas.... 
Você me indicará o momento? 

Valeu, valeu, valeu e valeu!!!

Enviado do meu smartphone Sony Xperia™

---- Kiver Vinicius escreveu ----
