### ISSUE TITLE
Quero ser mentor de Front-end FullStack e Delphi

### ISSUE THREAD

**Issue by kivervinicius** [training-center/mentoria#487]
# Nome

Kiver Teixeira

### Perfil

Sou formado em Analise e Desenvolvimento de Software desde 2010 e possuo especialização em S.I e didática do ensino superior, já atuo na área de desenvolvimento a 10 anos sendo praticamente toda vida dedicada a front-end(CSS, JS, HTML), mas também desenvolvo a muito tempo com Delphi, PHP, JavaEE, C#, não possuo experiência na prática de nenhum framework modinha, mas estudo muito React e VueJS, atuei como docente da UNIC (Kroton) de 2013 até 2015 e possuo uma boa didática atuando como docente desde 2010 (mini-cursos entre outras empresas).

### Contato

[E-mail](kivervinicius@gmail.com)

[Github](https://github.com/kivervinicius)

**Comment by woliveiras** [comment]
Fala @kivervinicius!

Experiência interessante! 

Você já leu as [responsabilidades do mentor](https://github.com/training-center/mentoria/blob/master/mentores/responsibility.md) e está de acordo com a ideia do projeto?

**Comment by kivervinicius** [comment]
@woliveiras sim estou de acordo.

**Comment by woliveiras** [comment]
Perfeito cara! 

Logo te daremos uma resposta viu. 

Se puder, já entra no nosso Slack e vamos conversar um pouco. 😄

**Comment by woliveiras** [comment]
Fala @kivervinicius 

Consegue entrar no nosso Slack?

**Comment by kivervinicius** [comment]
Desculpe, estava sem acesso, estou entrando agora

**Comment by woliveiras** [comment]
Fala @kivervinicius, conseguiu entrar no nosso Slack?

**Comment by kivervinicius** [comment]
Estou la :) só não posso entrar no trampo, somente a noite.

**Comment by woliveiras** [comment]
Opa, sucesso, cara! 

Vou te mandar uma mensagem. :D 

Valeeeus!

**Comment by woliveiras** [comment]
Fala @kivervinicius!

Pode criar seu perfil aqui no projeto.

Assim que receber o Pull Request eu adiciono seu perfil do GitHub a nossa organização aqui.

Também me da um toque no Slack se eu esquecer de te adicionar no canal privado dos mentores. :)

**Comment by kivervinicius** [comment]
Feito @woliveiras

**Comment by woliveiras** [comment]
Perfeito mano!
