### ISSUE TITLE
Preciso de um Mentor de Javascript

### ISSUE THREAD

**Issue by andreneto97** [training-center/mentoria#49]
Meu nome é André Neto, sou trabalho com JavaScript e Html5, e gostaria de receber ajuda para poder aprimorar minhas habilidades em programação Front-End, nível de conhecimento iniciante mas com muita força de vontade!
Facebook:  https://facebook.com/Andrenetoo

**Comment by woliveiras** [comment]
Boa @andreneto97 

Força de vontade é o principal!

Vamos compartilhar sua issue pra ver se aparece alguém para te ajudar.
Compartilha também para agilizar o processo. 😄

cc: @training-center/moderators

**Comment by akfzambrana** [comment]
Como o @andreneto97 é iniciante, se não tiver nenhum outro(a) mentor(a) melhor qualificado(a) eu poderia ajudar a trilhar o caminho inicial até chegar num nível mais avançado.

**Comment by woliveiras** [comment]
Acho EXCELENTE!

**Comment by matmarsiglio** [comment]
Olha esse menino aqui! Mostrei pra ele o training-center e não é que veio mesmo? Estará em boas mãos com a @akfzambrana. :+1:

**Comment by woliveiras** [comment]
Booa mano

**Comment by woliveiras** [comment]
Está rolando alguma conversa entre @andreneto97 e @akfzambrana?

**Comment by akfzambrana** [comment]
Não mano, honestamente não sei qual seria o procedimento depois de eu me oferecer como mentora :astonished:

**Comment by woliveiras** [comment]
AHIAHIAHIAIHA

Ai é só trocar ideia por algum canal de comunicação que seja legal para os dois.

Pode ser por Facebook, Skype, Slack, etc. 😬 

Fora isso tem de criar o perfil de pupilo e atualizar o de mentor.
O pupilo cria o dele e o mentor atualiza o próprio também. 😄

**Comment by akfzambrana** [comment]
ja estamos conversando, vou atualizar meu perfil, ele sera meu pupilo :stuck_out_tongue_winking_eye:

**Comment by woliveiras** [comment]
Shoooow

Preferem manter a issue aberta ou fechamos?

**Comment by akfzambrana** [comment]
Assim que o @andreneto97 criar o perfil dele pode fechar, pq dai eu altero meu perfil linkando o dele ja. :smile:

**Comment by woliveiras** [comment]
Show de bola! 😄

**Comment by woliveiras** [comment]
Fala @andreneto97, faltou subir seu perfil aqui no repo. 😬

**Comment by woliveiras** [comment]
Galera, posso fechar essa issue?

**Comment by akfzambrana** [comment]
@woliveiras posso eu criar o perfil dele?

**Comment by woliveiras** [comment]
Pode sim @akfzambrana 😄

**Comment by akfzambrana** [comment]
@woliveiras ja pode fechar a issue

**Comment by woliveiras** [comment]
Perfeito!
