### ISSUE TITLE
Quero ser mentor para SQA's (Analistas de Testes, Analistas de Testes Automatizados)

### ISSUE THREAD

**Issue by patota** [training-center/mentoria#491]
Nome: Érik Patekoski
Descrição: Estou na área de T.I desde sempre.
Nunca fiz outra coisa profissionalmente.
Estou na área desde os 14 anos, hoje tenho 29 e trabalho a 10 anos com Qualidade de Software.
Já passei por diversos ramos de atividades. Como por exemplo: telecom, e-commerce, seguros, jogos, varejo, internet e no momento energias :).
Antes disso trabalhei com manuteção de micros e redes. Da época que um roteador 10/100 era topssimo e notebook era duas alegrias uma quando comprava e 
outra quando vendia.
Conheço um pouco de desenvolvimento, porém o que gosto de fazer é testes e meu foco é teste automatizado. Seja front-end, back-end, serviços e 
qualquer outra coisa que dê para validar e garantir o funcionamento da aplicação.

Frameworks:
Selenium WebDriver
Cucumber
Calabash
ProtractorJS
Rest Assured
Http Party

Linguagens:
Java
Ruby on Rails
C#

Contatos:

[Site Pessoal]( http://www.xplife.com.br)
[Facebook](https://www.facebook.com/erik.patekoski)
[Linkedin](https://www.linkedin.com/in/erik-patekoski-30239622/)

Retribuição:
Manda um salve nas redes sociais que é nóis!

**Comment by woliveiras** [comment]
Que legal @patota!!

Estamos mesmo precisando de profissionais em QA!

Você já leu as [responsabilidades do mentor](https://github.com/training-center/mentoria/blob/master/mentores/responsibility.md) e está de acordo com a ideia do projeto?

**Comment by patota** [comment]
Oi @woliveiras lí sim e estou de acordo.

**Comment by woliveiras** [comment]
Perfeito cara, os @training-center/mentors irão avaliar seu perfil e logo te damos uma resposta.

Enquanto isso você pode entrar no nosso Slack para conversarmos mais. Que tal?

**Comment by patota** [comment]
Opa, fechou. vou conectar.

**Comment by woliveiras** [comment]
Show de bola!

Aí é só me chamar lá: @woliveiras

**Comment by woliveiras** [comment]
Fala @patota!

Pode criar seu perfil aqui no projeto.

Assim que receber o Pull Request eu adiciono seu perfil do GitHub a nossa organização aqui.

Também me da um toque no Slack se eu esquecer de te adicionar no canal privado dos mentores. :)

**Comment by patota** [comment]
Opa!
Maravilha @woliveiras obrigado!
Pode deixar, aviso sim.
Vlw.

**Comment by woliveiras** [comment]
Fechando a issue por já ter o perfil atualizado.

Valeu @patota
