### ISSUE TITLE
Quero ser Mentor [os primeiros]

### ISSUE THREAD

**Issue by woliveiras** [training-center/mentoria#5]
Se você deseja ser mentor, deixe aqui seu sinal de interesse com links sobre você.

*Ex.:*

```
*Nome:* XXX

*Mini descrição:* Formado em X, trabalho a X tempo com Y.

*Alguns links sobre mim:*
* Facebook:
* Twitter:
* LinkedIn:
```

**Comment by jlamim** [comment]
*Nome:* Jonathan Lamim Antunes

*Mini descrição:* Programador web/mobile desde 2005, larga experiência em desenvolvimento frontend (HTML, CSS, JS) e backend (PHP, MySQL, SQL SERVER), mobile (Swift, Objective-C, Cordova/Phonegap). Mais de 300 artigos/tutoriais escritos ao longo desses 10 anos. Já atuei em projetos para BIC Brasil, Ponto Frio, trabalhei como programador na Rede Gazeta (afiliada da Rede Globo no ES) entre outras empresas e startups.

*Alguns links sobre mim:*
* Facebook: http://www.facebook.com/jonathanLamim
* Twitter: http://www.facebook.com/jlamim
* Site: http://www.jlamim.com.br
* Outros links: http://www.universidadecodeigniter.com.br | http://www.livrocodeigniter.com.br | https://www.oficinadanet.com.br/autor/172-jonathan-lamim

**Comment by rafaDfaria** [comment]
@jlamim Que bagagem!, seus sites são fantásticos cara, parabéns!

**Comment by woliveiras** [comment]
É um monstro! Da até vergonha de me colocar aqui, mas ai vai...

**Comment by woliveiras** [comment]
*Nome:* William de Oliveira Souza

*Mini descrição:* Desenvolvedor Front End desde 2014. Trabalho com informática desde os 16 anos (2007), mais ou menos, quando comecei a mexer com Manutenção de Computadores, passei por Infraestrutura e Suporte Técnico até conhecer a área de desenvolvimento e me apaixonar em 2011/12, quando conheci o PHP. Dei uma desviada da carreira de Desenvolvimento para SysAdmin em 2013, mas voltei e fiquei de vez em Desenvolvimento de Software que é minha paixão! Como o perfil do Front End é bem diversificado eu prefiro dizer que sou o cara que gosta mais de JavaScript e Arquitetura Front End (Escalabilidade, Padrões de Projetos, Desenvolvimento de SPA's) do que da parte de Motion Design, UX, etc, porém gosto muito de tudo o que envolve Desenvolvimento de Software, principalmente no Client Side. Sou apaixonado por Open Source e compartilhar conhecimento. Gosto de tudo o que envolve Desenvolvimento, então já dei uma estudada, por cima, em Python, PHP, MySQL, PostgreSQL, Nodejs, Java (urg), Android e vivo brincando. ;D

*Alguns links sobre mim:*
* Facebook: http://www.facebook.com/woliveira542
* Twitter: http://www.twitter.com/w_oliveiras
* LinkedIn: https://www.linkedin.com/in/woliveira542
* Site: http://www.woliveiras.com.br

**Comment by rafaDfaria** [comment]
@woliveiras  Vergonha de passar seus conhecimentos adiante? JAMAIS!
Vergonha é ser egoísta e mesmo tendo tempo e conhecimento, não disseminá-los. 
Tenho certeza que qualquer pupilo que for mentorado por você sairá com uma bagagem muito melhor do que a inicial.

**Comment by woliveiras** [comment]
\o/

Valeu ein @rafaDfaria

**Comment by dorianneto** [comment]
*Nome:* Dorian Neto

*Mini descrição:* Desenvolvedor Web apaixonado por web standards, metodologias ágeis e open source. Possuo experiência em Desenvolvimento de Software desde 2011, autodidata e evangelista PHP com conhecimentos em PHP, Node.js, Design Patterns, OOP, Javascript. Comecei como front end e depois encontrei minha paixão que é back end, porém, ainda estudo e trabalho muito como front end.

*Alguns links sobre mim:*
* Facebook: https://www.facebook.com/doriansampaioneto
* Twitter: https://twitter.com/doriansneto
* LinkedIn: https://www.linkedin.com/in/dorianneto
* Site: http://www.dorianneto.com.br

**Comment by akfzambrana** [comment]
*Nome:* Andréa Zambrana

*Mini descrição:* Desenvolvedora front-end desde 2007. Não tenho formação superior, sou 100% autodidata. Atualmente trabalho no time *Multicanal e mobile* na Amil. Meu foco é em desenvolvimento de HTML, semântico e acessível, e CSS pra grandes aplicações e que tem skins diferentes. Eu amo CSS :smile:. Tenho um blog mas que não tem muitos artigos técnicos. Faço parte da comunidade @front-ladies do ABC e atualmente estou dando um [curso básico gratuito de front-end para mulheres via Hangout](https://www.youtube.com/channel/UCpruvBgT4fET_h42IIxPDjA). Não tenho muita coisa no meu github e não tenho portfolio, mas fiz uma grande parte da base do CSS dos sites [Amil](http://www.amil.com.br/portal/web/institucional), [One Health](http://www.onehealth.com.br/portal/web/institucional), [Next Saúde](http://www.nextsaude.com.br/portal/web/institucional) e outros que ainda não estão em produção. Não tenho certeza de se posso ser uma mentora, mas se eu puder, nem que seja um pouco, agregar conteúdo e mudar vida de alguém para mim ja é suficiente. 

*Alguns links sobre mim:*
* Facebook: https://www.facebook.com/akfzambrana
* Twitter: https://twitter.com/akfzambrana
* LinkedIn: https://br.linkedin.com/in/akfzambrana
* Blog: http://andreazambrana.com.br/

**Comment by woliveiras** [comment]
Galera, essa issue está confundindo o pessoal, então vou fechar ela, mas podem deixar suas descrições aqui mesmo que vamos utilizar isso. :)

**Comment by woliveiras** [comment]
@akfzambrana @dorianneto podem fazer PR com seus perfis! \o/

Vamos tocar lenha nesse negócio logo
