### ISSUE TITLE
Preciso de um mentor de Scrum com TFS

### ISSUE THREAD

**Issue by jsellos** [training-center/mentoria#50]
Me chamo Jonatas Sellos,
sou gerente de projetos e desenvolvedor em uma pequena empresa de desenvolvimento de softwares.

Sou bacharel em Administração, possuo pós em Gestão de Tecnologia da Informação, fiz um curso presencial de Scrum Fundamentals e outros online. Nunca implantei Scrum, e agora estou com esse desafio pessoal de ajudar minha equipe a trabalhar com o TFS 2013 (que já usamos para controle de versão) e o Scrum.

Preciso muito de alguém que possa me ajudar a usar o TFS juntamente com o Scrum de maneira simples e funcional.

Meus contatos:
E-mail: jonatas@sellos.com.br
Skype: jonatas@sellos.com.br
Telegram: @jsellos
LinkedIn: http://linkedin.com/in/jsellos
Facebook: http://fb.com/jsellos

**Comment by woliveiras** [comment]
Boa @jsellos! 

Vamos compartilhar sua issue pra ver se aparece alguém para te ajudar. Compartilha também para agilizar o processo. 😄

cc: @training-center/moderators

**Comment by woliveiras** [comment]
Alguém consegue ajudar essa alma, jovens @training-center/mentors?

**Comment by woliveiras** [comment]
Algum dos novos @training-center/mentors consegue ajudar esse jovem?

**Comment by woliveiras** [comment]
Estamos com todos os Mentores e Mentoras ocupados no momento, adicionei a label `wait for new mentors` para que os próximos busquem pelas issues mais antigas primeiro.

**Comment by patota** [comment]
@jsellos  fala ai brother, td bem? eu sou mentor de QA, porém trabalho a um bom tempo em projetos ágeis e já utilizei scrum com tfs. se quiser bater um papo, é nois :)

**Comment by woliveiras** [comment]
Fechando a issue por falta de interação.

**Comment by jsellos** [comment]
Ei @patota! Eu não tinha visto sua postagem... Mano, tenho muito interesse. Já evolui no TFS com Scrum, mas ainda tenho algumas dúvidas que gostaria de compartilhar contigo...

**Comment by patota** [comment]
Opa, fala ai mano!
Te mandei um e-mail. Se quiser trocar ideia por lá, é nois :)
