### ISSUE TITLE
Preciso de um mentor sobre Desenvolvimento Front End

### ISSUE THREAD

**Issue by heijosh** [training-center/mentoria#51]
Fabiano Souza

Sou Visual Designer e ilustrador, trabalho há 5 anos como designer e agora quero aprender a desenvolver. Já fiz o primeiro módulo de HTML e CSS da Codecademy mas agora não sei para onde ir ou o que aprender em seguida. Abaixo seguem minhas informações de contato:

Facebook: https://www.facebook.com/heijosh
Twitter: https://twitter.com/fabian0souza
Skype: fabiano.arquo

Valeu!

**Comment by matmarsiglio** [comment]
@heijosh Esse piá aqui vem comigo, vai vendo, ó!

@woliveiras é amigo meu, mostrei o projeto e em breve teremos mais um no lado negro da força. 🎉

**Comment by woliveiras** [comment]
Boa cara!

Você mesmo que vai ajudar ele então né?

**Comment by matmarsiglio** [comment]
@woliveiras Vou! Já estou, na real. :)

**Comment by woliveiras** [comment]
Boa cara!

A hora que der é só atualizar os perfis aqui no repo então.

Show de bola! \o/

**Comment by woliveiras** [comment]
Se quiser podemos fechar a issue.
