### ISSUE TITLE
Preciso de um(a) Mentor(a) para Front end e UX/UI

### ISSUE THREAD

**Issue by guinicola** [training-center/mentoria#514]
Nome: Guilherme Nicola

Descrição: Boa noite pessoal! Estou precisando de um(a) mentor(a) que possa me auxiliar na profissão de Front-end e ajudar com conceitos de UX/UI.

Moro em Jaú, interior de SP. Sou formado em Web Design desde 2008, porém fiquei alguns anos na inatividade. Mas, uma oportunidade em uma agência web da cidade apareceu, e eu decidi agarrar, mesmo não tendo tanta experiência. A empresa em questão, no qual trabalho até hoje, tinha uma maneira meio antiga de se trabalhar, e eu, por ser curioso, sempre vendo o andamento da comunidade front-end, comecei a me incomodar e resolvi buscar uma atualização. Sem 'apoio' da empresa, busquei novos conhecimentos e aos poucos, fui aplicando nos trabalhos da empresa. Porém, com o avanço de novas tecnologias, fui ficando um pouco pra trás novamente. Tenho problemas com gerenciamento dos projetos com meu chefe também, e principalmente, com a designer, que acha que sabe tudo, mas não sabe nem organizar as layers de um layout... são detalhes que posso contar melhor ao meu/minha mentor(a) para talvez dar um norte de como seguir as atividades.

Conhecimentos:
HTML5
CSS3
Node basico
GruntJS Basico
Wordpress
PHP básico
Design Basico

Contatos
[Linkedin](https://www.linkedin.com/in/guilherme-nicola-617a3a2b/)
[Facebook](https://www.facebook.com/guilhermenicola)
[E-mail](mailto:guilherme.nicola@outloo.com)

**Comment by woliveiras** [comment]
Fala @guinicola, não precisa mais abrir issue.

Da uma olhada aqui: https://medium.com/trainingcenter/menos-burocracia-para-conseguir-um-mentor-ou-mentora-d571ed9cc3e0

E aqui: https://github.com/training-center/mentoria#preciso-de-uma-mentora

E já entra no nosso Slack para trocar ideia com a galera. 😄

**Comment by guinicola** [comment]
Opa @woliveiras ! Entrei em contato com um mentor já. Estou no aguardo do e-mail dele.

**Comment by woliveiras** [comment]
Sucesso @guinicola 

Boa sorte!

Precisando de alguma coisa é só chamar no Slack :D
