### ISSUE TITLE
Preciso de um mentor(a) para JavaScript

### ISSUE THREAD

**Issue by matheus-souza** [training-center/mentoria#523]
**Preciso de um mentor para me ajudar com o JavaScript!!**

Gostaria de um mentor de pudesse me dar uma ajuda com JS, devido a imensa quantidade de cursos, artigos, etc, fico perdido em como começar. Estou começando a estudar NodeJS e React Native. Também tenho conhecimento em Android nativo e JavaEE, mas quero migrar para tecnologias web e desenvolvimento hibrido como falei antes.

Agradeço a todos!

Contatos
Facebook: https://www.facebook.com/mh.matheussouza

**Comment by woliveiras** [comment]
Fala @matheus-souza, não se abre mais issue para conseguir um mentor.

Da uma olhada: https://github.com/training-center/mentoria#preciso-de-uma-mentora

Como já está no nosso Slack, podemos continuar conversando por lá até conseguirmos um(a) mentor(a) pra você.
