### ISSUE TITLE
Preciso de um(a) mentor(a) sobre Desenvolvimento Front-End e JavaScript FullStack

### ISSUE THREAD

**Issue by marcusvcribeiro** [training-center/mentoria#526]
Nome: Marcus Vinicius Costa Ribeiro

Descrição: Boa tarde, mentores! Procuro um(a) mentor(a) que possa me ajudar nessa jornada de Front-end e JavaScript.

Sou estudante de sistemas de informação, e há 2 anos, comecei a estagiar em uma agencia,trabalhando exclusivamente com WordPress, e logo após 3 meses virei freelancer nessa mesma agencia, depois fui trabalhar como webmaster e hoje sou estagiário em 3 locais, pela manhã estagio em uma agencia de publicidade, no qual mexo com Frontend com PHP, SASS, GULPe JS.(Drupal, WordPress) e  Backend com .NET, Fluent NHibernate. No estágio de tarde mexo com PHP CodeIgniter e Joomla. No Estágio Remoto trabalho exclusivamente com WordPress.
Enfim, uma breve introdução a meu momento profissional.

Procuro me aprimorar o desenvolvimento Front-end, ando consumindo muito conteúdo da internet, desde de cursos do Alura a pesquisas feitas no stackoverflow.  

Procuro um mentor para me mostrar quais os caminhos certos que devo trilhar e me ajudar bastante na minha vida profissional.

Agradeço desde já quem quiser me ajudar nessa, e espero que meu pouco conhecimento possa contribuir também :)

Nível de conhecimento atual:
HTML, CSS, Javascript, JQuery - Intermediário
Angular 2 - básico
WordPress - Intermediário 

Mentor no qual me identifiquei :
- Lucas Pinto

Porem se algum outro tutor quiser me ajudar nessa jornada, agradecerei imensamente.

Contatos:
[LinkedIn](https://www.linkedin.com/in/marcusvcrd/)
Gmail -> marcusvcrd@gmail.com

**Comment by woliveiras** [comment]
Fala @marcusvcribeiro!

O processo de conseguir mentores mudou, da uma olhada aqui: https://github.com/training-center/mentoria#preciso-de-uma-mentora

Agora não se abrem mais issues.

Entra no nosso Slack para conversarmos mais. 😄 😄 😄
