### ISSUE TITLE
Preciso Mentor Front-End (HTML, CSS, JS)

### ISSUE THREAD

**Issue by Edusar** [training-center/mentoria#529]
Meu nome é Eduardo, sou Web Designer e quero me aprofundar no Front End para trabalhar também com isso, quero ter mais autonomia nos meus projetos e conseguir um bom emprego na área. Eu já tenho conhecimentos básicos de HTML e CSS, mas ainda preciso aprender a escrever códigos limpos, escaláveis, usar controle de versão e javascript.

**Comment by woliveiras** [comment]
Fala @Edusar, o processo de conseguir um mentor ou mentora mudou.

Da uma olhada: https://github.com/training-center/mentoria#preciso-de-uma-mentora

Agora não deixamos mais as issues abertas, é só mandar email para os mentores. :)

**Comment by Edusar** [comment]
Valeu William,

obrigado pelo aviso. Já enviei um email para o Kiver Teixeira.

Até mais!

*Eduardo Sulzbach de Araujo*
--------------------------------------------
*Portfolio -* be.net/esar
*Email -* eduardosdearaujo@gmail.com
*Fone -* 51 9852 5555



2017-04-05 16:06 GMT-03:00 William Oliveira <notifications@github.com>:
