### ISSUE TITLE
Preciso de um mentor sobre Desenvolvimento Back End em PHP

### ISSUE THREAD

**Issue by iagoqueiroz** [training-center/mentoria#53]
**Nome:** Iago Queiroz

------------------------------------------------------------

**Descrição:**
O meu desejo, é montar uma agência de soluções web e mobile no futuro. Mas gostaria de, antes disso, me especializar como um desenvolvedor PHP. Mas não sei que rumo tomar, se eu preciso fazer faculdade (e qual ?), ou se posso atingir esse objetivo por conta própria. Apesar de ter uma idéia do que preciso estudar, ainda não sei o que fazer pra começar isso. Montar um cronograma de estudo. As vezes fico lendo e lendo sobre, mas sinto que apesar de estar adquirindo mais algumas informações, não estou saindo do lugar.

------------------------------------------------------------

**Nível de conhecimento atual:**
PHP não é uma linguagem nova pra mim, sei os conceitos básicos e intermediários de tanto revisar isso em video-aulas e tutoriais.
Sei os conceitos de Orientação a Objetos (classe, estrutura, herança, visibilidade). 
Já fiz alguns sistemas simples de site e gerenciamento de conteúdo, mas nada muito completo. 
Não sei trabalhar com arquivos e imagens
Conheço o padrão de desenvolvimento MVC, mas nunca cheguei a usá-lo na prática em algum projeto (mesmo que só para estudo)

------------------------------------------------------------

**Contatos:**
E-mail: iago.queiroz@hotmail.com
Facebook: https://www.facebook.com/iago.queiroz.14

**Comment by dorianneto** [comment]
Fala Iago, tranquilo?

Da uma olhadinha no [meu perfil](https://github.com/training-center/mentoria/blob/master/mentores/perfis/dorian_neto.md) e vê se te agrada. Se sim, estou disposto a ser seu mentor :D

Abraço!

**Comment by iagoqueiroz** [comment]
Opa Dorian, tudo tranquilo ! E contigo ?

Caramba, foi bem rápida a resposta, sinceramente pensei que só ia receber algo no outro dia.
Gostaria muito que você pudesse ser meu mentor, ficaria muito grato !

Foi você que respondeu uma dúvida minha no grupo do PHP com Rapadura né ?

E se possivel, poderia me explicar um pouco como será feita a mentoria ?
Abraço!

Date: Thu, 16 Jun 2016 06:11:09 -0700

**Comment by woliveiras** [comment]
Opa, essa explicação sobre como funciona é legal pra gente melhorar a descrição.

Qual sua dúvida sobre o processo @iagoqueiroz?

**Comment by iagoqueiroz** [comment]
@woliveiras 
Assim, se o mentor apenas nos dá uma lista de afazeres e dicas.
Ou tem todo um acompanhamento, pra ver o progresso, se é proposto alguns desafios, etc.

**Comment by dorianneto** [comment]
Galera aqui é rápida :P

Cara, fui eu sim :)

Com relação ao funcionamento, primeiro vamos definir um local bacana para trocarmos ideias. Slack, messenger, telegram, whatsapp etc, o que for melhor pra você. Após a definição da ferramenta de comunicação, começaremos a mentoria. O meu papel será te orientar com relação a suas dúvidas para o mercado de trabalho, estudos etc.

**Comment by dorianneto** [comment]
@iagoqueiroz entenda a mentoria como uma troca de experiências de vida e profissional com uma pessoa que já passou por caminhos nos quais você deseja passar.

**Comment by iagoqueiroz** [comment]
@dorianneto Ah, agora entendi. Poxa, fazer disso um serviço de ajuda gratuita é bem admirável.

Mas então, no momento acho que o melhor local seria através do facebook (não conheço o Slack).

**Comment by dorianneto** [comment]
Que bom que você gostou! É isso que nos motiva a continuar com esse projeto foda!!

Não esquece de dar uma lida na [documentação completa](https://github.com/training-center/mentoria) para entender as responsabilidades que você, como um [pupilo](https://github.com/training-center/mentoria#preciso-de-uma-mentora), deve ter. Depois de ler tudo direitinho, cria lá teu perfil de pupilo e ai podemos começar!

Já te adicionei no facebook ;)

**Comment by woliveiras** [comment]
Boooa! Respondida pelo @dorianneto 

Vou tentar melhorar isso na descrição. Valeu @iagoqueiroz 😄

**Comment by dorianneto** [comment]
@woliveiras já iniciamos a conversa. Acho que pra fechar a issue só falta o @iagoqueiroz criar o perfil dele como pupilo.

**Comment by woliveiras** [comment]
Show de bola! 

Feito.
