### ISSUE TITLE
Preciso de um mentor sobre Desenvolvimento Front End

### ISSUE THREAD

**Issue by brunorafael8** [training-center/mentoria#54]
Sempre gostei muito de usar o computador e faz uns meses que decidir entra nessa área, faço Analise e Desenvolvimento de sistemas. A parte que gostei muito foi o Front-end.

**Nome: Bruno Rafael Vieira Silva
**Nível de conhecimento atual: Fiz um projeto para a faculdade a parte do front(mas o sistema n deu certo), manjo um pouco de HTML e CSS3(SASS) e um pouco de JS, além de ter visto algumas coisas de Node e Angular.
**Contatos: -Facebook: https://www.facebook.com/bruno.rafael.1485
                   -Twitter: https://twitter.com/Ares8_8

OBG : )

**Comment by woliveiras** [comment]
Bem vindo cara!

Vamos ver se alguém pode te ajudar. :smile: 

Uma dúvida: Você aprendeu Sass na Faculdade cara???

cc: @training-center/moderators

**Comment by brunorafael8** [comment]
N, aprendi sozinho kkk, estou no primeiro período da faculdade

**Comment by woliveiras** [comment]
Boa cara!

**Comment by sibelius** [comment]
Dicas 

- aprenda a usar o git e o github
- contribua para projetos open source 
- consiga um estágio, mesmo se não for receber nada, você só vai aprender mesmo em projetos reais em produção 
- utilize-se de cursos on-line, Freecodecamp, codeacademy, entre outros
- aprenda inglês se não souber
- participe de meetups de desenvolvimento 
- não se limite a somente aprender frontend, backend ou mobile
- aprender os conceitos dos frameworks é mais importante que aprender a usar o framework
- siga os devs no Twitter 
- aprenda React
- aprenda Redux, vai fazer você programar muito melhor
- programe pelo menos 10 horas por dia

Mentoria reduzida, pode entrar em contato comigo se tiver alguma dúvida

**Comment by woliveiras** [comment]
Fala @sibelius! 

Bora virar mentor?

**Comment by danilorb** [comment]
@brunorafael8 
Se precisar de algo pode me chamar.

**Comment by brunorafael8** [comment]
Obrigado pelas dicas @sibelius  :)

**Comment by brunorafael8** [comment]
Ok, @danilorb

**Comment by sibelius** [comment]
@woliveiras tenho diversos projetos que podem ajudar quem realmente quer aprender.

só entrar em contato comigo, mas vai ter que programar muito

**Comment by woliveiras** [comment]
Fala @danilorb!

Bora virar mentor também? 😄

**Comment by woliveiras** [comment]
@sibelius ai é sucesso cara!

Botar a galera pra praticar é o que estamos tentando no Training Center! \o/

Da uma olhada: https://github.com/training-center/study-groups

**Comment by brunorafael8** [comment]
@sibelius vou falar com vc pelo twitter, sobre isso

**Comment by gusribeiro** [comment]
estou disposto a ajudar, caso precise ;)

**Comment by leonardo403** [comment]
Se precisar estou a disposição.

**Comment by brunorafael8** [comment]
Obrigado a todos pela disposição :+1:  :)

**Comment by woliveiras** [comment]
Caso já esteja sendo atendido, posso fechar a issue @brunorafael8?

**Comment by brunorafael8** [comment]
sim sim
