### ISSUE TITLE
Gostaria de ser um mentor de Desenvolvimento Front-end

### ISSUE THREAD

**Issue by DiogoCercilio** [training-center/mentoria#540]
Olá! 
Meu nome é Diogo Cercílio, sou desenvolvedor fullstack na Guichê Virtual, e trabalho com desenvolvimento web há cerca de sete anos. Conheci este projeto através do devnaestrada, e achei bem bacana. 

Perfil Codepen:
http://codepen.io/dcweb/

Certificação Imasters - Javascript Boas Práticas
http://certificacao.imasters.com.br/users/diogo-cercilio-da-silva

Portfólio (Tb tá antigão... mas dá pra ter uma noção sobre meus conhecimentos):
diogocercilio.github.com

Perfil Workana (Meio antigo, mas possui avaliação de clientes com quem trabalhei, e algumas certificações que a plataforma disponibiliza):
https://www.workana.com/freelancer/ebaa245fc698c9d8b4b582c25f77e109

**Comment by woliveiras** [comment]
Olá @DiogoCercilio!!

Fico feliz por sua vontade de contribuir.

Você já leu as [responsabilidades do mentor](https://github.com/training-center/mentoria/blob/master/mentores/responsibility.md) e está de acordo com a ideia do projeto?

**Comment by DiogoCercilio** [comment]
Olá William! Já li sim. estou de acordo. ;)

2017-04-17 10:48 GMT-03:00 William Oliveira <notifications@github.com>:

**Comment by woliveiras** [comment]
Sucesso demais @DiogoCercilio 

Os @training-center/mentors irão avaliar seu perfil e logo te daremos uma resposta.

Obrigado pelo seu interesse em colaborar com essa comunidade e com a carreira de outras pessoas de maneira gratuita e sem pretensões.

**Comment by DiogoCercilio** [comment]
Legal! Eu que agradeço!

**Comment by woliveiras** [comment]
@DiogoCercilio, pode criar seu perfil! 

😄 

Assim que seu perfil estiver criado eu vou aceitar o PR fechando essa issue, te adiciono na organização e passo mais informações sobre como tudo funciona.

Você tem usuário no Telegram? 

Usamos o app para comunicação entre moderadores do Training Center (lembrando que como Mentor, você pode responder como Moderador, se quiser).

**Comment by DiogoCercilio** [comment]
Fala William, blz?
Telegram: diogocercilio

Já enviei o pr também. Qualquer coisa é só avisar.
Fico no aguardo dos próximos passos.

Abraço 😎!

Em 18 de abril de 2017 22:58, William Oliveira <notifications@github.com>
escreveu:

**Comment by woliveiras** [comment]
Merged #544
