### ISSUE TITLE
[Quero ser mentor] de Desenvolvimento Web - Focado em PHP e JS

### ISSUE THREAD

**Issue by ftonato** [training-center/mentoria#541]
## Nome
Ademílson F. Tonato

## Perfil

Tenho 23 anos, sou graduando em Análise e Desenvolvimento de Sistemas. Atuo como Desenvolvedor Web, também desenvolvo Apps Híbridos e sou atualmente escritor do blog da BrazilJS. Trabalho com desenvolvimento de sites há ~4,5 anos e procuro sempre manter-me atualizado nas tecnologias que trabalho e nas novas que surgem a cada momento no mercado. Já fiz (e continuo fazendo) diversos cursos na área de desenvolvimento e conheço algumas linguagens e tecnologias. Gosto muito do desenvolvimento Front-End, porém prefiro o desenvolvimento Back-End e minhas linguagens preferidas são PHP e JS.
Eu gosto de construir aplicações web, dividir conhecimento, escrevendo artigos e contribuindo para projetos de código aberto.

## Links

* [Twitter](https://twitter.com/ftonato)
* [LinkedIn](https://www.linkedin.com/in/ftonato/)
* [BrazilJS - Author](https://braziljs.org/blog/author/ademilson-f-tonato/)
* [Telegram](https://web.telegram.org/#/im?p=@ftonato)

**Comment by woliveiras** [comment]
Ai sim!!!! 

Você já leu as [responsabilidades do mentor](https://github.com/training-center/mentoria/blob/master/mentores/responsibility.md) e está de acordo com a ideia, mano?

**Comment by ftonato** [comment]
@woliveiras Yeah!

- [X] Ler as responsabilidades do mentor.
- [X] Concordar com as responsabilidades do mentor.
- [ ] Ser aprovado para a equipe de mentores.

**Comment by woliveiras** [comment]
Sucesso @ftonato 

Só aguardar então. Valeu! :D

**Comment by woliveiras** [comment]
@ftonato, pode criar seu perfil! 

😄 

Assim que seu perfil estiver criado eu vou aceitar o PR fechando essa issue, te adiciono na organização e passo mais informações sobre como tudo funciona.

Você tem usuário no Telegram? 

Usamos o app para comunicação entre moderadores do Training Center (lembrando que como Mentor, você pode responder como Moderador, se quiser).

**Comment by ftonato** [comment]
@woliveiras, envio-te os dados do Telegram pelo Slack.

**Comment by woliveiras** [comment]
Perfeito, @ftonato 

Adicionado no Telegram e aqui na org! :D
