### ISSUE TITLE
Alguns links quebrados

### ISSUE THREAD

**Issue by ftonato** [training-center/mentoria#542]
No arquivo de [Responsabilidades do Mentor(a)](https://github.com/training-center/mentoria/blob/master/profiles/mentors/responsibility.md) há alguns links quebrados...

**Comment by woliveiras** [comment]
Valeu pelo report @ftonato

**Comment by ftonato** [comment]
No arquivo de [Responsabilidades do Pupilo](https://github.com/training-center/mentoria/blob/master/profiles/pupils/responsibility.md) também há links quebrados...

**Comment by Ladeia** [comment]
PR #550 com correção dos links de pupilos

**Comment by ftonato** [comment]
Boa @Ladeia, pode nesse mesmo _PR_ enviar a correção para os links quebrados nas **Responsabilidades do Mentor(a)**?

**Comment by Ladeia** [comment]
claro! um momento.

**Comment by Ladeia** [comment]
Atualizado @ftonato

**Comment by ftonato** [comment]
@Ladeia não querendo ser chato, mas já sendo, ainda no arquivo inicial da minha sugestão, o arquivo de [Responsabilidades do Mentor(a)](https://github.com/training-center/mentoria/blob/master/profiles/mentors/responsibility.md) há alguns links quebrados, pode corrigir esse para nós? <3

**Comment by Ladeia** [comment]
@ftonato 
Já foram corrigidas, estão no PR https://github.com/training-center/mentoria/pull/550
O ticket é https://github.com/training-center/mentoria/pull/550/commits/2a1c28b9f59ac550f4d1c6f0aa29c3deafc470d3

**Comment by ftonato** [comment]
Ah desculpe, eu não tinha visto que tinham dois arquivos no _PR_.
Chego a ver a sugestão que deixei no arquivo do [README.md](https://github.com/training-center/mentoria/pull/550/files/a010e0f0a81aa4e96b14f4e1b70dfde9cd664dd2#diff-04c6e90faac2675aa89e2176d2eec7d8)?

Valeu @Ladeia, obrigado pelas contribuições!
