### ISSUE TITLE
Preciso de um mentor para o mundo Front-end.

### ISSUE THREAD

**Issue by richmanzoli** [training-center/mentoria#543]
**Nome:** Richard Manzoli

**Objetivo:** Ampliar meu conhecimento na criação de sites.
**Interesses:** Meu foco é conhecer a fundo Javascript, ele puro.

**Meu conhecimento:**

- HTML

- CSS

- Apenas logica em Javascript

- Bootstrap

**Contato:**
**E-mail:** manzoliriichard@gmail.com
**Linkedin:** https://www.linkedin.com/in/richard-manzoli-67388a139/

**Comment by woliveiras** [comment]
Faaaaala @richmanzoli! :) 

O processo para conseguir mentores mudou. Da uma olhada: https://github.com/training-center/mentoria#preciso-de-uma-mentora

Vou fechar a issue por que ela vai ficar sem interação depois.
