### ISSUE TITLE
Quero ser mentor de Bitcoin e Blockchain.

### ISSUE THREAD

**Issue by Anderson-Juhasc** [training-center/mentoria#546]
Nome: Anderson Juhasc
Desenvolvedor Full-stack e Blockchain Engineer, administrador e mentor no grupo[ Bitcoin Brasil Desenvolvedores](https://www.facebook.com/groups/btcbrdev), ajudei a orientar vários desenvolvedores na área de desenvolvimento com bitcoin e blockchain. Trabalho há quase 4 anos na área de bitcoin e blockchain, sou um profissional autodidata.

Facebook: https://www.facebook.com/anderson.jhc
Twitter: https://twitter.com/Anderson_Juhasc
Website: http://andersonjuhasc.com/
E-mail: anderson.juhasc@gmail.com

**Comment by woliveiras** [comment]
Nooooooooooooossa! 

Vai ser uma MEGA ajuda, @Anderson-Juhasc!

Você já leu as [responsabilidades do mentor](https://github.com/training-center/mentoria/blob/master/mentores/responsibility.md) e está de acordo com a ideia do projeto?

**Comment by Anderson-Juhasc** [comment]
@woliveiras Já li sim e estou de acordo.

**Comment by woliveiras** [comment]
Perfeito @Anderson-Juhasc 

Os @training-center/mentors irão analisar seu perfil e logo logo te dou uma resposta.

Provavelmente hoje mesmo.

**Comment by Anderson-Juhasc** [comment]
Ok, no aguardo.

**Comment by woliveiras** [comment]
Fala @Anderson-Juhasc 

Pode criar seu perfil, cara! :D 

Assim que tiver o PR aceito eu te adiciono aqui na org no GitHub e também no nosso canal de moderação no Telegram. 😄

**Comment by woliveiras** [comment]
Closed #557
