### ISSUE TITLE
Quero ser mentor de backend

### ISSUE THREAD

**Issue by Ladeia** [training-center/mentoria#547]
**Nome:** Antonio Ladeia
**Descrição:** Analista de sistemas atualmente trabalhando num instituto de pesquisa, atuo com embarcados e backend, sou apaixonado por arquitetura de software e padrões de projeto.
**Contatos:**
Facebook: https://www.facebook.com/antoniofsladeia
Twitter: https://twitter.com/antoniofsladeia
Website: http://antonioladeia.com
E-mail: contato at antonioladeia dot com

**Comment by woliveiras** [comment]
Fala @Ladeia!

Você já leu as [responsabilidades do mentor](https://github.com/training-center/mentoria/blob/master/mentores/responsibility.md) e está de acordo com a ideia do projeto?

**Comment by Ladeia** [comment]
opa @woliveiras já li sim e estou de acordo.

**Comment by woliveiras** [comment]
Sucesso demais, @Ladeia 

Os @training-center/mentors irão avaliar seu perfil e logo logo te dou uma resposta.

**Comment by Ladeia** [comment]
@woliveiras estou no aguardo

**Comment by woliveiras** [comment]
@Ladeia, pode criar seu perfil! 🙌

**Comment by Ladeia** [comment]
Vlw @woliveiras faço isso agora!

**Comment by woliveiras** [comment]
Fechando a issue, pois o perfil já foi adicionado a org
