### ISSUE TITLE
Quero ser mentor Full Stack

### ISSUE THREAD

**Issue by gnuwilliam** [training-center/mentoria#554]
**Nome:** William W. Oliveira
**Descrição:** Desenvolvedor web com mais de 8 anos de experiência, atualmente trabalhando pra uma empresa americana chamada Startgrid, localizada em Mountain View. Mini bio http://gnuwilliam.com/about. Posso ajudar com JavaScript, Go, Elixir, Elm e qualquer coisa interessante. Também tenho uma boa experiência com OOP (Object Oriented Programming) e FP (Functional Programming), além de Design Patterns e TDD, etc.
**Contatos:** sudowilliam@gmail.com

Já li os termos e estou de acordo.

**Comment by woliveiras** [comment]
Faaaala @gnuwilliam 

Eu vou comentar sobre seu perfil com os @training-center/mentors!

**Comment by woliveiras** [comment]
@gnuwilliam, pode criar seu perfil, cara! 🙌

**Comment by woliveiras** [comment]
closed #558
