### ISSUE TITLE
Preciso de um mentor(a) pra JavaScript (e Frameworks)!

### ISSUE THREAD

**Issue by Werberth** [training-center/mentoria#556]
Preciso de um mentor que me ajude com o JavaScript (Quero começar a estudar Jquery, Ajax e Angular. Já venho estudando Orientação Objeto há um tempo). Sou desenvolvedor Back-end, e to querendo mergulhar no universo Front-end devido as grandes oportunidades de emprego que essa área também proporciona.
Já conversei com o [Ademílson Tonato](https://goo.gl/cM2ntR) e ele aceitou ser meu mentor!!

[MEU PERFIL](https://goo.gl/09fkds)

Abraço a todos!!

**Comment by woliveiras** [comment]
Olá @Werberth! 

Rapaz, não usamos mais issues para pedir ajuda dos mentores, da uma olhada: https://github.com/training-center/mentoria#preciso-de-uma-mentora

Como o @ftonato já conversou contigo, então é só subir seu perfil mesmo. 😄 

Ai é só sucesso e partir pros estudos.
