### ISSUE TITLE
Preciso de um(a) mentor(a) de JavaScript

### ISSUE THREAD

**Issue by LajackBR** [training-center/mentoria#57]
**Nome:** Luiz Lázaro
**Descrição:** A pouco tempo atrás me interessei por programação e depois de aprender lógica de programação fui testando o básico de várias linguagens, tais como C#,  Java, Python e etc., mas as que mais me interessaram foram JS e PHP, contudo, pretendo seguir com JS e assim me tornar um deus de tal linguagem. O meu objetivo principal aqui na mentoria é adquirir o conhecimento necessário para conseguir meu primeiro job na área.
**Nível de conhecimento atual:** Lógica de Programação, HTML, CSS, JavaScript Básico e jQuery
**Contatos:** [Facebook](https://facebook.com/LajackBR) - [Twitter](https://twitter.com/LajackBR)

Fiz esse projetinho com o pouco que aprendi: http://sorteieme.esy.es , queria fazer o backend com NodeJS, mas como ainda sei pouco sobre JS fiz com PHP mesmo e usei JS para algumas funcionalidades no Front.

**Comment by woliveiras** [comment]
Fala @LajackBR! 

Seria JavaScript para o Front ou Back End?

Vamos ver se a galera aqui pode te ajudar, @training-center/moderators :smile:

**Comment by LajackBR** [comment]
Opa @woliveiras!
Agora seria para o Front mesmo. Vlw!

**Comment by woliveiras** [comment]
Show de bola @LajackBR 

É pra eu colocar as tags certinho 

:grimacing:

**Comment by matmarsiglio** [comment]
ALGUEM FALOU... JAVASCRIPT!?

![jack-nicholson-the-shining-333035738](https://cloud.githubusercontent.com/assets/5414299/16729537/7e15a1d0-4743-11e6-9825-110a0acb718b.jpg)

**Comment by matmarsiglio** [comment]
Se o @LajackBR achar interessante, eu posso assumir daqui, começamos a trocar ideia por algum lugar!

**Comment by woliveiras** [comment]
Boa!

**Comment by LajackBR** [comment]
Show @matmarsiglio , acho ótimo! Posso te adicionar no Facebook para conversarmos ou prefere outro meio?

**Comment by woliveiras** [comment]
Assim que começarem, podem criar os perfis lá e fechamos essa issue. 😄

**Comment by suissa** [comment]
💛

**Comment by suissa** [comment]
Eu tenho vários pupilos, aconselho a todos com experiência a serem mentores.
Alias eu tb co-oriento alunos de TCC.

<3

**Comment by woliveiras** [comment]
É uma troca de experiência muito boa, né não @suissa?

**Comment by mbrufatto** [comment]
Eu tb estou a procura de um mentor em JS para Front.

**Comment by matmarsiglio** [comment]
@LajackBR me procure no facebook, twitter, onde quiser. Eu sou bem ativo até no Telegram, então posso falar por lá facil. 

https://www.facebook.com/matheusmarsiglio
https://www.twitter.com/matmarsiglio

Já faz seu processo aí de pupilo para adicionar as informações aqui, e bora fechar essa issue e partir pra _trocação_ de ideias!

**Comment by woliveiras** [comment]
Ai é sucesso!

**Comment by LajackBR** [comment]
Blz @matmarsiglio. 

@woliveiras  já criei o perfil, acho que pode fechar essa issue.

**Comment by woliveiras** [comment]
Fechado cara! Bem vindo. :smile:
