### ISSUE TITLE
Quero ser mentor Back-end e Front-end

### ISSUE THREAD

**Issue by lflimeira** [training-center/mentoria#571]
**Nome:** Luiz Felipe de Oliva Limeira
**Descrição:** Sou formado em Ciências da Computação, realizei e realizo diversos cursos da área de desenvolvimento de software buscando sempre estar atualizado sobre as novas tecnologias. Trabalho atualmente na Secretaria de Saúde do estado de São Paulo, e trabalho como desenvolvedor a 6 anos. Em paralelo com meu atual serviço possuo, juntamente com outros envolvidos, um projeto de startup, no qual estamos no processo de desenvolvimento do produto, que é o WatchMyCar.
 
**Contatos:**
Linkedin: https://www.linkedin.com/in/luiz-felipe-de-oliva-limeira-42060678/
Twitter: https://twitter.com/lflimeira02
Startup: https://watchmycar.com.br/

**Comment by woliveiras** [comment]
Bem vindo @lflimeira 

Você já leu as [responsabilidades do mentor](https://github.com/training-center/mentoria/blob/master/mentores/responsibility.md) e está de acordo com a ideia do projeto?

**Comment by lflimeira** [comment]
Obrigado @woliveiras .

Já li sim, e estou plenamente de acordo.

**Comment by woliveiras** [comment]
🙌 

Show de bola @lflimeira 

Os @training-center/mentors irão conversar e logo logo te trago uma resposta.

Por enquanto você pode me chamar no Telegram: `@woliveiras`?

**Comment by lflimeira** [comment]
Obrigado @woliveiras , estou no aguardo, e vou chamar no Telegram sim.

**Comment by woliveiras** [comment]
@lflimeira, você trabalha com qual/quais linguagem(s)?

**Comment by lflimeira** [comment]
@woliveiras,  atualmente trabalho com PHP, mais voltado para back-end, mas conheço outras linguagens como: Java, C# e Node.JS. Quanto ao front sei HTML, CSS e JavaScript.

**Comment by woliveiras** [comment]
Perfeito, @lflimeira 

Valeu!

**Comment by woliveiras** [comment]
@lflimeira, pode criar seu perfil! 😄 

Assim que enviar o PR eu passo mais informações e te adiciono no grupo de mentores.

**Comment by lflimeira** [comment]
@woliveiras vou providenciar ainda hoje.

Muito obrigado.

**Comment by woliveiras** [comment]
Perfeito! Valeu, @lflimeira
