### ISSUE TITLE
Quero ser mentor Backend PHP

### ISSUE THREAD

**Issue by vanildosouto** [training-center/mentoria#573]
## Nome

**Vanildo Souto Mangueira**

## Perfil

Sou desenvolvedor PHP a mais de 4 anos, atualmente sou líder de um equipe de 3 desenvolvedores em uma editora de revistas

## Contatos

**Email:** vanildo.souto@gmail.com

**Telegram:** https://t.me/vanildo_souto

**Linkedin:** https://br.linkedin.com/in/vanildosouto

**Meu site:** http://blog.toneladas.com.br

**Comment by woliveiras** [comment]
Bem vindo @vanildosouto!!

Você já leu as [responsabilidades do mentor](https://github.com/training-center/mentoria/blob/master/profiles/mentors/responsibility.md) e está de acordo com a ideia do projeto?

**Comment by vanildosouto** [comment]
Já li sim e estou de acordo.

**Comment by woliveiras** [comment]
Aeeee!!!

Os @training-center/mentors vão avaliar seu perfil e até amanhã te dou uma resposta.

Me da uma chamada no Telegram para conversarmos mais: `@woliveiras`

**Comment by woliveiras** [comment]
@vanildosouto, pode criar seu perfil! 😄 

Assim que enviar o PR eu passo mais informações e te adiciono no grupo de mentores.
