### ISSUE TITLE
Preciso de um mentor full stack java script 

### ISSUE THREAD

**Issue by devrdias** [training-center/mentoria#576]
Olá pessoal !

Me chamo Rafael e entro em contato com vocês para saber da disponibilidade de alguém em ser meu mentor(a) na carreira Full Stack.

Tenho 35 anos de idade e mais de 10 de experiência trabalhando com TI. Minha experiência é toda adquirida no Banco do Brasil, onde comecei a trabalhar mesmo antes de me formar em Ciência da Computação. 

Como sempre trabalhei somente para o Banco do Brasil, fiquei muito preso a tecnologias de alta plataforma, desenvolvendo somente para ambiente mainframe. Gostaria de me tornar um desenvolvedor Full Stack e vi aqui nesse grupo a oportunidade de me tornar o que desejo ser um dia,  um desenvolvedor Full Stack! 

Estou seguindo a trilha JavaScript no freeCodeCamp (#238) e também realizando o curso the-web-developer-bootcamp, da Udemy (60% concluído). 

Obrigado !! 

Atenciosamente,

Rafael

**Comment by ftonato** [comment]
Fala @devrdias!

O processo de conseguir mentores mudou, dê uma olhada aqui: https://github.com/training-center/mentoria#preciso-de-uma-mentora

Agora não abrimos mais _issues_ para isso, então vou te orientar a dar uma olhada na [nossa lista de mentores](https://github.com/training-center/mentoria/tree/master/profiles/mentors) disponíveis e entrar em contato diretamente com o escolhido.

Caso não consigas com nenhum deles, por favor entre em contato comigo que te ajudarei nesse processo de encontrar um mentor...

**Comment by woliveiras** [comment]
@ftonato 👍
