### ISSUE TITLE
Preciso de um(a) mentor(a) de Front End.

### ISSUE THREAD

**Issue by ytalobessa** [training-center/mentoria#58]
Meu nome é Ítalo Bessa, preciso de um mentor que me ajude a trilhar o melhor caminho de acordo com os meus objetivos, pra evitar ficar perdido sabe ;), acredito que com um mentor posso estudar o que realmente é necessário, inicialmente minhas dúvidas são sobre mercado, minha intenção é puxar pro lado UI / UX. 

Meu nívell é iniciante, estudo 04 horas por dia, mas estudo sozinho, acredito que com um mentor posso utilizar esse tempo da melhor forma possível e mais produtiva! Não faço nenhum curso técnico ou faculdade, paguei um curso de HTML5 e CSS3, depois continuei estudando JavaScript pelo Youtube e afins ^^.

Contatos: 
[Facebook](https://www.facebook.com/brenda.rayane.564)
[Linkedin](https://br.linkedin.com/in/ítalo-bessa-1a291111a)
[Twitter](https://twitter.com/italobessaa)
italobessa.ib@gmail.com

**Comment by woliveiras** [comment]
Boa cara!

Vamos ver se a galera do @training-center/moderators consegue ajudar. 😄

**Comment by akfzambrana** [comment]
eu poderia ajudar com a parte de front voltado pra UI, sobre UX não tenho conhecimento suficiente então tal vez tenha alguem melhor qualificado :wink: ou toca primeiro uma parte comigo e depois a outra com outro(a) mentor(a) :smile:

**Comment by woliveiras** [comment]
Boooa @akfzambrana

**Comment by ytalobessa** [comment]
Sera que vai rolar um mentor(a) aí? rsrsrs ;)

**Comment by woliveiras** [comment]
Vai sim @ytalobessa. \o/

Logo menos a @akfzambrana finaliza aqui. :)

**Comment by akfzambrana** [comment]
opa, é nois! me add no facebook e a gente vai se conversando por la inicialmente

**Comment by woliveiras** [comment]
\o/

Shooooow

**Comment by woliveiras** [comment]
@ytalobessa e @akfzambrana, podemos fechar essa issue?

**Comment by ytalobessa** [comment]
Opa @woliveiras vamos sim, estou recebendo algumas orientações da minha mentora @akfzambrana , já vamos preparar para preencher a vaga de pupilo ^^

**Comment by woliveiras** [comment]
Aeee! Show de bola mano! 

Assim que der da aquela atualizada no perfil e sobe pra gente. Ai podemos fechar a issue. Sucesso.

**Comment by woliveiras** [comment]
Fala @ytalobessa ainda falta subir seu perfil, ein? 😬

**Comment by ytalobessa** [comment]
Opa @woliveiras, mals aí, passei um tempo fora. Só não sem bem como fazer, mas vou pesquisar!

**Comment by woliveiras** [comment]
Opa, beleza cara. Se precisar de ajuda, chama a gente viu. 😄

**Comment by akfzambrana** [comment]
@ytalobessa vc precisa fazer um fork do repositorio, clonar, adicionar o arquivo com seu perfil e enviar um pull request. Da uma olhada em como funciona o workflow de forks https://www.atlassian.com/git/tutorials/comparing-workflows/forking-workflow

**Comment by woliveiras** [comment]
Tudo certo entre vocês @akfzambrana e @ytalobessa?

Se estiver tudo OK, posso fechar a issue?

**Comment by akfzambrana** [comment]
Pode fechar @woliveiras, tamos andando já :smile_cat:

**Comment by woliveiras** [comment]
\o/
