### ISSUE TITLE
Preciso de um(a) mentor(a) em Desenvolvimento Web com PHP.

### ISSUE THREAD

**Issue by WilliamMeneses** [training-center/mentoria#59]
**Nome:**
William Meneses

**Descrição:**
Sou William Meneses, desenvolvedor iniciante apaixonado por web. Estudante do 6º Semestre de Ciência da Computação na UECE. Há 4 meses, iniciei a minha primeira experiência (de verdade) em desenvolvimento (consegui um estágio de desenvolvedor PHP). 
A cada dia gosto mais da área de web. Estudo sempre nas horas vagas(e até nas horas não vagas as vezes) mas todo dia estudo um pouco. As vezes me perco tentando aprender várias coisas ao mesmo tempo ('ficar bom' em front e back), mas de um tempo pra cá venho tentando focar em uma habilidade de cada vez. 

**Nível de conhecimento atual:**
Possuo um bom conhecimento em Html e Css (de javaScript quase nada). E um bom conhecimento em PHP (já trabalhei com alguns frameworks no estágio mas nada aprofundado). 

**Contatos:**
E-mail: jwilliam.anjos@gmail.com
Facebook: https://www.facebook.com/williameneses

------------------------------------------------------------

**Comment by woliveiras** [comment]
Beleza @WilliamMeneses? 😄 

Vamos ver se alguém do @training-center/moderators pode ajudar.

É só aguardar.

**Comment by WilliamMeneses** [comment]
Valeu @woliveiras. 

Vou aguardar.

**Comment by dorianneto** [comment]
Opa, posso tentar ajudar :)

**Comment by WilliamMeneses** [comment]
Show @dorianneto. 
Ficarei muito grato por você ser meu mentor nessa caminhada.

Vamos se comunicar por onde?

**Comment by dorianneto** [comment]
@WilliamMeneses normalmente eu tenho me comunicado com os outros pupilos através do messenger. O que você acha?

**Comment by WilliamMeneses** [comment]
Pode ser @dorianneto. Tranquilo. 
Te mandei um convite no facebook.

Já posso criar o perfil de pupilo?

**Comment by dorianneto** [comment]
@WilliamMeneses, aceitei seu convite.

Claro! Também já podemos dar início a mentoria ;)

**Comment by woliveiras** [comment]
Boooooa @WilliamMeneses! 

Taca pau nesse perfil ai cara. :smile:

**Comment by dorianneto** [comment]
@woliveiras pode fechar esta Issue. A mentoria está rolando tranquilamente pelo messenger ;)

**Comment by woliveiras** [comment]
\o/

Sucesso mano!
