### ISSUE TITLE
Regras de conduta para mentores e pupilos

### ISSUE THREAD

**Issue by woliveiras** [training-center/mentoria#6]
Devemos planejar as regras de conduta para ambas as partes para evitar transtornos.

**Comment by woliveiras** [comment]
**Mentor**

* O Mentor não pode cobrar em dinheiro para ajudar o pupilo, mas o pupilo pode doar para ele.
Caso alguém relate a cobrança, devemos tomar medidas contra o Mentor. Nesse caso acho justo expulsar o mesmo do projeto, afinal está bem claro que não é para ser cobrado a ajuda.

**Pupilo**

* O pupilo não deve cobrar disponibilidade 24hs, 7 dias por semana do seu Mentor, afinal o Mentor possui vida fora desse projeto e o projeto é só uma ajuda para a comunidade.
* O pupilo deve nos avisar, imediatamente, caso um Mentor venha cobrar financeiramente por sua mentoria.

**Responsabilidade de ambas as partes**

* Ambos devem se respeitar. Não deve acontecer nenhum tipo de repudia, humilhação, discriminação por cor, etnia, opção sexual, religião, padrão de vida ou qualquer outro tipo por nenhuma das partes.

Dúvidas:

Em que momento um Mentor pode deixar de mentoriar um pupilo por ele demonstrar, por exemplo, falta de vontade de aprender ou um comportamento ruim?

**Comment by jlamim** [comment]
Sobre o momento de deixar de ser mentor de alguém, acho que devemos seguir o caminho de resultados de avaliação, como foi proposto na issue #4 . Assim como os pupilos vão dar feedback sobre o mentor, o mentor fazer avaliações com o pupilo, para observar o rendimento e se estão evoluindo.

Se o rendimento não for satisfatório, então, o pupilo não receberá mais a mentoria e outro será alocado na vaga.

**Comment by jlamim** [comment]
Acho interessante adicionar o seguinte item às regras de conduto dos pupilos:

- O mentor não tem obrigação de entregar código ou solução pronta para as suas dúvidas. Ele vai te orientar e ajudar a chegar na solução ideal para o problema.

Hoje vejo muita gente que não quer nem procurar no Google ou ler documentação, já quer logo a solução pronta, a famosa geração Ctrl+C / Ctrl+V.

**Comment by woliveiras** [comment]
Atualizado @jlamim :D

**Comment by woliveiras** [comment]
@training-center/moderators, se tudo estiver OK, vou fechar essa issue e já criar o arquivo de conduta. :)

**Comment by baltazarparra** [comment]
Mano, tenho alguns adendos a fazer, mas estou no corre hoje, mas hoje a noite eu pego pra trabalhar nisso com vocês. Não fecha ainda não.

**Comment by woliveiras** [comment]
Opa, combinado mano. Sem problemas.

**Comment by baltazarparra** [comment]
Acho que o foco deveria ser muito menos técnico, sobre a relação entre mentor e 'pupilo', havia pensando em algo mais relacionado as dúvidas sobre como se posicionar no meio de tantas vertentes de desenvolvimento, possíveis caminhos profissionais, uma visão imparcial sobre as principais tecnologias e tal. Deixar essa parte mais técnica pros próprios grupos de estudo.

Dito isso, um dos pontos mais importante seria a necessidade do Mentor se posicionar sempre imparcial, deixando de lado gosto pessoais.

**Comment by WendellAdriel** [comment]
Mano @woliveiras quero participar, onde posso me inscrever para essa parada dos mentores?

**Comment by woliveiras** [comment]
Pow mano @baltazarparra, muito boa ein... A questão técnica, acho importante somente ser um profissional que esteja no mercado que o pupilo quer entrar.

Ex.:

Pupilo quer se tornar um Mestre Jedi em Front End, um cara que trabalha com Front vai entrar em contato.

Por que o cara precisa estar no mercado que o pupilo quer? Por que ele pode ensinar os caminhos a seguir sobre quais tecnologias realmente estudar. O pupilo vê um mundo de coisas na internet, em palestras, vídeos, etc e as vezes fica sem rumo.

**Comment by woliveiras** [comment]
@WendellAdriel, só tacar pau em abrir uma issue que tem o Template lá. Segue o template de [Quero ser Mentor]. :smile:

**Comment by baltazarparra** [comment]
Sim mano @woliveiras, isso é importante, tipo, o mentor precisa ser referência em alguma área, pra ter uma base boa pra passar, sem achismo e imparcial,

**Comment by woliveiras** [comment]
Show mano, se todos estiverem de acordo, já fechamos a issue e taco lenha na descrição no projeto.

cc: @training-center/moderators

**Comment by danilovaz** [comment]
De acordo

**Comment by baltazarparra** [comment]
agree

**Comment by rafaDfaria** [comment]
Agree e ansioso para me inscrever como pupilo desse projeto, tenho certeza que será de extrema importância no meu desenvolvimento.

**Comment by woliveiras** [comment]
Feito galera, avisem ou ajustem se tiver algo errado lá ein. :D
