### ISSUE TITLE
Quero ser um mentor back-end!

### ISSUE THREAD

**Issue by devmacedo** [training-center/mentoria#604]
Quero ser mentor de Desenvolvimento PHP.

# **Nome** 
Filipe Luiz Macedo

# Descrição 
Atualmente sou estudante do curso superior de sistemas de informações. Tenho um bom conhecimento na linguagem de acordo com as boas práticas de desenvolvimento e atualmente atuo dando suporte em fóruns de desenvolvimento como o **imasters** por exemplo.
Viso estar sempre estudando coisas relacionadas, para prezar um bom código.

## Principais focos de estudos:

- POO (A verdadeira orientação a objetos)
- SOLID
- Design patterns (Ainda não é o meu forte, mas um dia eu chego lá)
- UML

# Contato:
Email: devmacedo@gmail.com

**Comment by woliveiras** [comment]
Bem vindo @devmacedo 

Você já leu as [responsabilidades do mentor](https://github.com/training-center/mentoria/blob/master/profiles/mentors/responsibility.md) e está de acordo com a ideia do projeto?

**Comment by devmacedo** [comment]
Estou sim.
Em 17 de mai de 2017 3:59 PM, "William Oliveira" <notifications@github.com>
escreveu:

**Comment by woliveiras** [comment]
Sucesso demais, @devmacedo 

Os @training-center/mentors irão avaliar seu perfil e logo te trago a resposta.

Muito obrigado pelo interesse em nos ajudar.

**Comment by devmacedo** [comment]
Disponha, amigo.
Em 17 de mai de 2017 4:07 PM, "William Oliveira" <notifications@github.com>
escreveu:

**Comment by woliveiras** [comment]
@devmaced estamos discutindo um novo modelo para o Mentoria e por isso a demora em aceitar o seu perfil.

Já estamos de acordo com sua entrada na organização, porém aguarde mais um pouco, pois em breve trarei as novidades e solicito seu PR, viu. :)

**Comment by woliveiras** [comment]
@devmacedo nosso processo mudou: https://medium.com/trainingcenter/e-o-mentoria-mudou-mais-uma-vez-5ad8725bc778

Vendo essa mudança, ainda deseja participar do projeto?

**Comment by devmacedo** [comment]
Sim.

**Comment by woliveiras** [comment]
Perfeito, @devmacedo

Então pode criar seu perfil seguindo os guidelines: https://github.com/training-center/mentoria/#quero-ser-mentora

**Comment by woliveiras** [comment]
Olá, @devmacedo 

Está nos devendo um PR, ein. ;D

**Comment by devmacedo** [comment]
É verdade, ando meio ocupado com desenvolvimento de bot, estudos em AI...
Mas vou ver se entro no slack depois.
Obrigado pelo e-mail.

Em 9 de jul de 2017 8:54 PM, "William Oliveira" <notifications@github.com>
escreveu:

**Comment by woliveiras** [comment]
Vou fechar a issue e assim que tiver um tempinho pra voltar é só abrir o PR, mano :smile:
