### ISSUE TITLE
Quer ser mentor de Java, backend e sistemas operacionais

### ISSUE THREAD

**Issue by lasombra** [training-center/mentoria#607]
**Nome:** Ingo Hoffmann
**Descrição:** Desenvolvedor Java  a mais de 1 ano, trabalhei alguns anos com Grails em sistemas para a área educacional e ajudei em alguns projetos Java de amigos. Tenho mais de 15 anos de experiência como administrador de redes e sistemas com foco em Linux, design de data centers e redes.
**Contatos:** [Twitter](https://twitter.com/lasombra_br), `lasombra` no Slack CT

**Comment by woliveiras** [comment]
Que experiência ein @lasombra 

Imagino que nem preciso perguntar se você já leu as [responsabilidades do mentor](https://github.com/training-center/mentoria/blob/master/profiles/mentors/responsibility.md) e está de acordo com a ideia do projeto?

😂

**Comment by lasombra** [comment]
Nem tanto ;-)

Li sim.

**Comment by woliveiras** [comment]
@lasombra estamos discutindo um novo modelo para o Mentoria e por isso a demora em aceitar o seu perfil.

Já estamos de acordo com sua entrada na organização, porém aguarde mais um pouco, pois em breve trarei as novidades e solicito seu PR, viu. :)

**Comment by lasombra** [comment]
Sem pressa @woliveiras :-)

**Comment by woliveiras** [comment]
@lasombra nosso processo mudou: https://medium.com/trainingcenter/e-o-mentoria-mudou-mais-uma-vez-5ad8725bc778

Vendo essa mudança, ainda deseja participar do projeto?

**Comment by lasombra** [comment]
@woliveiras Não vi uma mudança significativa em relação ao mentor. Então ainda tenho vontade de participar.

Outra coisa, você pode me colocar em devops também. :-)

**Comment by woliveiras** [comment]
Perfeito, @lasombra 

Então pode criar seu perfil seguindo os guidelines: https://github.com/training-center/mentoria/#quero-ser-mentora

**Comment by lasombra** [comment]
Valeu @woliveiras. O board no Trello tá com o link errado?

**Comment by woliveiras** [comment]
Não, @lasombra. Eu te mando depois que você criar seu perfil e estiver no nosso Telegram 😄

**Comment by lasombra** [comment]
Aaaahhh, beleza então. Já mandei o PR :-)

**Comment by woliveiras** [comment]
Fechando a issue, pois o perfil já foi adicionado a org. :)
