### ISSUE TITLE
Quero ser mentor de desenvolvimento fullstack

### ISSUE THREAD

**Issue by beckenkamp** [training-center/mentoria#615]
Nome: Marcus Beckenkamp
Descrição: Trabalho como desenvolvedor web há 14 anos. Sou autodidata e trabalhei em diversas empresas, tanto de tecnologia como em departamentos de tecnologia de empresas de outras áreas. Hoje trabalho em uma startup como desenvolvedor sênior. Adoro metodologias ágeis e também passar a diante coisas que aprendi durante os anos. 
Contatos: http://blog.mbeck.com.br - http://twitter.com/beckenkamp - @beckenkamp no Telegram

**Comment by woliveiras** [comment]
Aeeee!

Bem vindo @beckenkamp 


Você já leu as [responsabilidades do mentor](https://github.com/training-center/mentoria/blob/master/profiles/mentors/responsibility.md) e está de acordo com a ideia do projeto?

**Comment by beckenkamp** [comment]
Obrigado, @woliveiras!

Li sim. Por mim está tudo de acordo. =)

**Comment by jeffersondesouza** [comment]
@woliveiras , no caso eu que procuro exatamente de um mentor de fullstack? Como procedo?  (Já estou no slack)

**Comment by woliveiras** [comment]
Fala @jeffersondesouza, pode seguir esse esquema aqui: https://github.com/training-center/mentoria#preciso-de-uma-mentora

E boa sorte mano.

Ter um mentor ou mentora é show de bola!

**Comment by woliveiras** [comment]
Perfeito, @beckenkamp 

Os @training-center/mentors irão avaliar seu perfil e logo logo retorno o contato contigo.

Acredito que amanhã a tarde já consigo te responder viu. 🤘

**Comment by sibelius** [comment]
Eu dou mentoria fullstack e bleeding edge no slack do react brasil - http://react-brasil-slack.herokuapp.com/

Artigo de um dos meus mentorados https://medium.com/entria/how-to-discover-that-you-dont-know-what-you-don-t-know-a6fcff20018

by @jgcmarins

Minha mentoria é um pouco diferente da tradicional, vou te passar uma lista de links que eu acho importante você ler e saber e coisas para você implementar.
Te ajudo a digerir esse conhecimento e em algumas implementações, mas o aprendizado parte do aluno

**Comment by khaosdoctor** [comment]
Opa @beckenkamp você pode criar uma PR aqui no repositório com o mesmo modelo que o pessoal está criando lá? Ai podemos aprovar mais facilmente :)

**Comment by khaosdoctor** [comment]
Fechando por falta de atividade

**Comment by beckenkamp** [comment]
Estou aguardando o review no meu pull request #666

**Comment by khaosdoctor** [comment]
Opa, vamos lá então :D
