### ISSUE TITLE
Preciso de um(a) mentor(a) de Front-end na parte de CSS.

### ISSUE THREAD

**Issue by enieber** [training-center/mentoria#62]
**Nome:** Enieber Cunha
**Descrição:** A algum tempo tenho estudado sobre desenvolvimento web e gostei muito da parte de front-end, mas sempre tive muita dificuldade em desenvolver um front-end limpo principalmente na parte de css, ja tentei utilizar sass, mas a configuração dele é muito extença para projetos que não sejam ruby, então eu comecei a usar stylus, gostei muito, mas ainda tenho muita dificuldade em como organinzar um projeto com um css bacana.
**Nível de conhecimento atual:**  js e html intermediario, css basico e alguns tasks runners.
**Contatos:** [Twitter](https://twitter.com/enieber) - [Facebook](https://www.facebook.com/enieber.cunha) - [Github](https://github.com/enieber)

**Comment by woliveiras** [comment]
Fala @enieber! Vamos ver se alguém do @training-center/moderators pode te ajudar.

Acho que a @akfzambrana seria a pessoa perfeita pra isso ein!

**Comment by ogiansouza** [comment]
Hey @enieber posso te ajudar!

**Comment by woliveiras** [comment]
\o/

Sucesso! 

@enieber já pode enviar seu perfil via PR. Bem vindo.
