### ISSUE TITLE
Quero ser mentor de Javascript / NodeJS / AngularJS 1.x / EmberJS / .NET / Java

### ISSUE THREAD

**Issue by Belline** [training-center/mentoria#63]
Hey, olá! :)

Me chamo Lucas Pinto, atualmente sou Javascript Developer numa empresa de Nova York, trabalhando de forma remota chamada Clevertech, tenho mais de 5 anos de experiencia e adoraria ajudar os mais novatos, e consequentemente evoluir junto! :)

Possuo um site pessoal que fala muito sobre mim e minha carreira: http://lucaspinto.me . Ele está todo em inglês, mas suponho que inglês para leitura seja algo obrigatório hoje em dia.

No meu site tambem há link para as redes sociais/linkedin.

Abraços! :)

**Comment by woliveiras** [comment]
Show de bola! 

A galera do @training-center/moderators vai avaliar @Belline 

Logo menos te damos a resposta.

Valeu pela iniciativa. 😄

**Comment by Belline** [comment]
Tranquilo @woliveiras 😄  

Ajudar é sempre bom,

Abs!

**Comment by woliveiras** [comment]
Fala @Belline, pode tacar pau criar seu perfil de Mentor e vamos agitar! :smile:

**Comment by Belline** [comment]
@woliveiras Abri um Pull request la! :smile: Outra coisa, eu recebi o convite para o Gitter, mas ta dizendo que não tenho permissão para acessar a chat room, da uma olhada depois se possivel, abs!

**Comment by woliveiras** [comment]
Eita, vamos resolver pra já!

**Comment by woliveiras** [comment]
@Belline acho que é por que ainda precisa aceitar o invite pra entrar na org. Verifica se chegou no seu email o invite e, se não chegou, eu posso mandar de novo aqui. :smile:

**Comment by felipeorlando** [comment]
@Belline, tudo certo?! Sou mentor (atualmente inativo) aqui no CT. Estou precisando justamente de um mentor de Javascript / NodeJS / AngularJS 1.x / EmberJS rs

Quero aprimorar meus conhecimentos em JS. 😃

**Comment by woliveiras** [comment]
Show de bola ein!

Eu vou fechar a issue só pra não ficar parada na aba de issues, mas se quiserem podem continuar se comunicando por aqui galera.
