### ISSUE TITLE
Preciso de um Mentor Front-End

### ISSUE THREAD

**Issue by heitoor** [training-center/mentoria#64]
# Heitor Augusto Borges Pereira
_Estudante de Sistemas para Internet e atualmente estou fazendo o Nanodegree Front-End na Udacity._
_Pretendo me tornar um Full Stack Web Developer utilizando Python. (Django)_
_Mas primeiro, quero me aperfeiçoar em Front, para conseguir um emprego na área e depois ir para o back-end._

* Conhecimento basico em front-end, mas já mexi com python e swift. (Tenho 2 apps publicados)
* [Facebook](http://facebook.com/heitorpereira)
* [Github](http://github.com/heitoor)
* heitoor@gmail.com

**Comment by woliveiras** [comment]
Fala @heitoor!

A galera do @training-center/moderators vai tentar ajudar.

😄

**Comment by Belline** [comment]
Vou entrar em contato com o @heitorr para combinar horarios e tal e ele ser meu pupilo 😄

**Comment by woliveiras** [comment]
Suuuuucesssuuuuuu

**Comment by woliveiras** [comment]
Está rolando a Mentoria, galera?

**Comment by woliveiras** [comment]
Posso fechar a issue @heitoor e @Belline?

**Comment by Belline** [comment]
Pode sim @woliveiras ! 😄

**Comment by woliveiras** [comment]
Perfeito!
