### ISSUE TITLE
Preciso de um(a) Mr(s) Miyagi de desenvolvimento front end (html/css e JS).

### ISSUE THREAD

**Issue by satanboss** [training-center/mentoria#65]
Olá! Meu nome é Ivan Rodrigues. Trabalho com marketing digital desde 2009, entre planejamento, mídia e SEO, mas meu sonho mesmo sempre foi desenvolver. Assim como o Daniel San, sei até dar um murro torto no código, como trabalhei por anos com SEO, aprendi a ler o código e entender como funciona, a estrutura e a lógica do CSS, de JS não sei nem como começar. 

Mas se eu abrir um arquivo e começar a codar, nada sai, esqueço o pouco que sei e fecho. Não sei se é um deficit de atenção ou se falta uma metodologia de estudo e prática. Quero aprender pintando cerca, lavando carro e ficando com equilibrado em uma madeira no meio do mar, gostaria que me ajudasse a trilhar esse caminho e assim como o Daniel San, aprender o golpe da garça do dev e conquistar o objetivo!  

facebook: [www.facebook.com/oivanrodrigues](http://www.facebook.com/oivanrodrigues)
twitter: [www.twitter.com/oivanrodrigues](http://www.twitter.com/oivanrodrigues)

**Comment by woliveiras** [comment]
Fala @satanboss 

Bela descrição! kkkk

Vamos ver se alguém do @training-center/moderators pode te ajudar. 😄

**Comment by Belline** [comment]
Opa @satanboss ! Vou entrar em contato contigo para voce ser meu pupilo, prepare-se! 😄

**Comment by woliveiras** [comment]
\o/

Sucesso!

**Comment by woliveiras** [comment]
Fala galera, está rolando a Mentoria?

**Comment by woliveiras** [comment]
Podemos fechar a issue @Belline e @satanboss?

**Comment by Belline** [comment]
@woliveiras infelizmente o pupilo nao respondeu quando entrei em contato com ele via facebook. Se ele tiver interesse em me procurar, estou a disposição. Sugiro fechar a issue for the time being, mas fica a seu critério.

**Comment by woliveiras** [comment]
Perfeito @Belline
