### ISSUE TITLE
Preciso de um(a) mentor(a) de NodeJS e Testes

### ISSUE THREAD

**Issue by douglastenn** [training-center/mentoria#66]
## Helloo

Gostaria de aprimorar meus conhecimentos com nodejs e principalmente com testes. Hoje já desenvolvo em nodejs, es6, javascript, etc. Porém meu conhecimento em testes é um pouco vago e queria aprender mais, desde como criar as rotinas de testes até criar alguns hooks no git para rodar os testes certinho. 

**Dados:**
- Douglas Tenório
- Sou web developer faz uns 2 anos mais ou menos, já trabalhei com php, nodejs e pouco de ruby e python.
- Nível de conhecimento atual: Intermediário com nodejs
- Skype: douglastenn 
- Twitter: [@douglastenn](http://twitter.com/douglastenn )
- Github: @douglastenn
- Email: douglas.develop@gmail.com

Agradeço a ajuda desde já :)

💙

**Comment by douglastenn** [comment]
Valeu @woliveiras 

Fico no aguardo 😃

**Comment by woliveiras** [comment]
Algum manjador de Nodejs pra ajudar o @douglastenn no @training-center/mentors?

**Comment by wbruno** [comment]
Eu dou aulas de NodeJS/MongoDB. (com testes)
Podemos conversar =)

**Comment by woliveiras** [comment]
\o/

Chega junto do Mentoria @wbruno 😬

**Comment by douglastenn** [comment]
@wbruno Qual seria o melhor canal para conversarmos ? :)

**Comment by suissa** [comment]
E aí já deu certo? Estou iniciando um material sobre testes e caso alguém queira implementar estará aqui https://github.com/suissa/AutomaticMongooseTest

**Comment by woliveiras** [comment]
Boa ein @suissa

**Comment by woliveiras** [comment]
Tá rolando alguma coisa @wbruno e @douglastenn?

**Comment by wbruno** [comment]
troquei uns emails com o Douglas, estou esperando ele me enviar o projeto para continuar ajudando.

**Comment by woliveiras** [comment]
Sucesso!

Se quiser criar seu perfil de mentor aqui no projeto pra galera poder entrar em contato contigo, será sucesso cara. 🙌 

Assim que estiverem conversando, podemos fechar a issue.

**Comment by woliveiras** [comment]
Fechando a issue galera, qualquer problema é só reabrir ou avisar em algum canal de comunicação.
