### ISSUE TITLE
Quero ser mentor de Front-End

### ISSUE THREAD

**Issue by jessuircleydson** [training-center/mentoria#69]
Opa /o/
Me chamo Jessuir, sou formando em Sistemas de Informação 4º período, mas já trabalho com Front-end a uns 5 anos. Procurava uma iniciativa assim, então estou a disposição para ajudar quem precisar. Posso ajudar com: Como iniciar o front-end, que ferramentas usar, css3, html5, Sass, javascript, jquery, Angular, ajax, responsividade e ferramentas como gulp, git, bower,browser-sync.

Contatos
[Facebook](https://www.facebook.com/jessuir.cleydson)
[Linkedin](https://br.linkedin.com/in/jessuir-cleydson-8223b640)
E-mail: jessuircleydson@gmail.com

**Comment by woliveiras** [comment]
Boa @jessuircleydson 

Só aguardar a galera do @training-center/moderators avaliar. \o/

**Comment by woliveiras** [comment]
@jessuircleydson, já pode mandar um [PR com seu perfil de mentor](https://github.com/training-center/mentoria#quero-ser-um-mentora)! :smile:

**Comment by felipeorlando** [comment]
Estaremos no aguardo, @jessuircleydson! 😃

**Comment by dorianneto** [comment]
Show!

**Comment by jessuircleydson** [comment]
Vlw :D ta lá o pull

**Comment by woliveiras** [comment]
Tá lá! :smile:
