### ISSUE TITLE
Problemas com filas de espera para conseguir mentoria

### ISSUE THREAD

**Issue by woliveiras** [training-center/mentoria#710]
## Problema

Muitas pessoas estão reclamando de enviarem seus dados via formulário de contato e não conseguirem mentoria (mesmo após alguns meses de espera).

## O que já identificamos

Isso acontece por que:

* a quantidade de pessoas mentorando é pequena em relação a quantidade de pessoas que enviam o formulário
* a fila de espera já está imensa no nosso board

## Pontos de atenção

Independente da solução que chegarmos nessa issue, devemos ter como ponto de atenção a qualidade do "atendimento" que estamos prestando quanto mentores e mentoras. Devemos tomar cuidado para que o projeto não se torne uma linha de produção e se perca essa qualidade.

As pessoas devem ser o nosso ponto mais importante em todo o processo. Se atendermos muitas pessoas e não ajudarmos ninguém, não estamos conseguindo cumprir nosso objetivo com o projeto.

## Importante

Nós já sabemos do problema da fila de espera, então tome cuidado para não responder essa issue dizendo que enviou seus dados a `x` tempo e ainda não obteve resposta, pois isso pode desviar o nosso foco na conversa e essa issue é justamente para encontrarmos uma solução juntos.

Portanto, se você tiver uma dica para melhorarmos o processo de Mentoria, pode comentar a vontade, mas se for somente dizer que já tentou e não conseguiu ajuda utilize [este formulário](https://trainingcenter2.typeform.com/to/T3zgTq). Isso não é para te calar quanto a um problema que você passou, mas para que não desviemos o foco da conversa, viu. :heart:

**Comment by Rubensdsj** [comment]
Talvez  uma solução possível fosse reestruturar a questão dos mentores em si ... eu entendo que mentoria é algo que deve agregar conhecimento técnico, experiencia e habilidade de comunicação. 
Acredito que algumas das pessoas que estão sendo mentoradas podem ser mentores de outros menos experientes. Se um mentor atualmente pode ter 10 discípulos alguns desses discípulos poderiam ser mentores de um ou dois menos experientes que eles dependendo das suas habilidades e vontade.

**Comment by CharlesAgra** [comment]
Eu sou novo aqui então não conheço o processo de vocês. Uma dica para nós é tentar ligar o conhecimento dos pupilos e ver par a par e quem sabe mais a frente nós possamos montar um grupo onde o mentor possa "trabalhar" e os pupilos sem ajudarem entre sí.

**Comment by gabrielferreiraa** [comment]
@Rubensdsj pensei nisso também. Vou dar um exemplo:

Mentor X: tem 4 pupilos.

Vocês da coordenação do projeto, entram em contato com os mentores, e veem se tem algum pupilo que tem condições de se tornar mentor parcial, por indicação do seu mentor, com um certo de nível de experiência. Os pupilos podem continuar sendo pupilos, porém também podem ser mentores de um pessoal que está iniciando, ou não.

**Comment by Rubensdsj** [comment]
@gabrielferreiraa bem isso mesmo, porque com o tempo esses mentores parciais podem se tornar mentores efetivamente. é bacana porque diminui a fila de espera e forma novos mentores ... 
A gente pode colocar a ideia do @CharlesAgra nisso tbm...
Acho q se lapidar bem pode funcionar ...

**Comment by nicholasess** [comment]
Olá, gostaria de saber quanto tempo leva o ciclo de mentoria? Pois, isso determina a disponibilidade dos mentores.

**Comment by nicholasess** [comment]
Pensa como um curso, um professor pode ajudar 10 alunos.
Se temos 300 pessoas, com 30 professores conseguimos atender essa demanda, mas só é possível se existir um fim, caso contrário, será apenas acumulativo...

**Comment by CharlesAgra** [comment]
Você falou tudo @nicholasess. Quando já sabemos que um púpilo já está pronto? Quanto em média pode levar a mentoria? São essas as perguntas a serem respondidas.

**Comment by cotts** [comment]
Poderia ser feito como o pessoal tem sugerido, mas por exemplo avaliar interesses e ir repassando o conhecimento... por exemplo: O mentor tem 10 pupilos, cada um deles pega um de inicio e vai repassando, como se fosse uma pirâmide.

**Comment by Rubensdsj** [comment]
Concordo com o lance de que precisamos saber como e quando o cara esta pronto ... mas isso acho q é uma avaliação que o mentor pode fazer, acredito que com um ou dois meses de conversa da pra saber se o pupilo tem nível técnico e perfil para mentorar (existe esse verbo??) alguém.

**Comment by nicholasess** [comment]
A mentoria tem uma causa humana, mas para eficiência do processo, precisamos enxergar como números.
Quanto tempo dura uma mentoria?
Quantos pessoas serão mentoradas?
Terá data de término? Se houver mais pessoas do que comporta, cria-se fila de espera.

O quantitativo se torna qualitativo, quando o mentor 'forma' bons devs.

**Comment by abnersajr** [comment]
Uma coisa que acho que ainda é meio nebulosa é O QUE É UM MENTOR. Qual o REAL papel de um mentor. Muitas pessoas vem aqui buscando quase que um curso. Ou tudo mastigadinho. Causando muitas vezes um desgaste do próprio mentor e tornando "a mentoria" muito extensa.

A questão do tempo de mentoria acredito que possa variar. É difícil limitar um prazo uma vez que dúvidas vão surgindo. Não vejo um problema alguém ter 10 pupilos. Desde que o mesmo consiga se organizar.

Acho que os Mentores é quem devem dizer: ó pupilo. Te passei a base dos meus ensinamentos, tirei suas dúvidas agora é sua hora. Mas saiba que estarei aqui para te ajudar. Apenas não te darei mais tanta atenção, afinal já te ensinei suficiente para você ficar forte e sair por ai desbravando o mundo.

**Comment by woliveiras** [comment]
Fala, galera!

Estão chegando excelentes comentários, valeu pela participação, desde já.

Sobre o que já foi dito estou coletando as seguintes ideias:

## Treinar pessoas para que elas também se tornem novos mentores e mentoras

É muito bom.

O que fazemos atualmente é preparar a pessoa pro mercado e ensinar a contribuir com a comunidade, mas não damos tanta ênfase para que a pessoa ajude **aqui** especificamente.

OBS: *Só não podemos forçar quem não se sente confortável em ensinar*

**Comment by woliveiras** [comment]
O @nicholasess mandou ótimos pontos de atenção:

> Olá, gostaria de saber quanto tempo leva o ciclo de mentoria?

Normalmente não temos um ciclo, mas vamos ajudando até a pessoa se sentir confortável e pudermos "largar" ela pro mundo.

> Quanto tempo dura uma mentoria?
> Quantos pessoas serão mentoradas?
> Terá data de término? 

Só temos um número "limite" para quantidade de mentorados(as): "1 até, no máximo, 10 pessoas".

Mas não temos um tempo determinado e nem data de término.

**Comment by woliveiras** [comment]
O que eu faço com as pessoas que ajudo: preparamos todo um plano de estudos que elas vão seguir e deixo elas irem seguindo e vou ajudando.

Coloco elas em um grupo onde estão todos os pupilos.

Um deve ajudar o outro, pois todos tem conhecimento e podem trocar e conversar entre si.

Eu interajo mais quando aparece algo muito cabuloso que eu percebo que ninguém consegue ajudar, mas as pessoas que já ajudei estão mandando muito bem em responder os novos que coloco. :grimacing:

**Comment by nicholasess** [comment]
@woliveiras a escrita deixa a desejar quando se tem muita informação, que tal criar videos explicativos? Assim esses pontos que são levantados, podem ser solucionados rapidamente.
Não precisa ter muita enrolação, basta ser direto.

**Comment by Rubensdsj** [comment]
Legal a explicação @woliveiras , acredito que isso ja de uma base melhor pra gente discutir.
Acho que mentoria não é um curso porque um mentor não deveria (na minha opinião) ser algo como um professor particular, é mais uma relação entre duas pessoas e como tal não precisa de prazo de encerramento. O mentor não vai fazer nada por voce, só vai te mostrar um caminho baseado noque ele ja conhece. Dicas de conteúdos mais relevantes pra conhecer ou melhor forma de resolver um determinado tipo de problemas.
Acredito que seja isso que estamos buscando incentivar.

**Comment by alinebastos** [comment]
@woliveiras gostei da ideia do grupo, colocar os pupilos lá e eles se ajudarem! Que tipo de grupo tu cria? É no slack mesmo?
Acho uma ótima ideia pra centralizar a mentoria!
Eu to com 4 pupilos, mas meio que estamos sem ter contato já faz um tempinho. Pensei agora em criar um grupo assim também pra centralizar, pra eles se ajudarem, aí de repente me sinto mais segura pra pegar mais pupilos, e também posso já jogar a ideia de mentoria pra eles tb, de uma vez só.
Gostei!

**Comment by CharlesAgra** [comment]
Só pra deixar no ar eu preciso de um mentor rs.

**Comment by nicholasess** [comment]
@alinebastos você pode criar uma direct message e mencionar mais de um user, acredito que se torna um 'grupo'

**Comment by alinebastos** [comment]
Sim, @nicholasess, eu sei. Queria saber é se ele cria no slack, no telegram, no whats, pra ter uma ideia de onde fica melhor.
Mas como não tenho paciência de esperar, perguntei direto pra ele, e ele já me respondeu que é no whats ;)

**Comment by lflimeira** [comment]
Galera, como foi citado, acho que um ponto importante seria colocar um tempo para toda mentoria, obviamente que o tempo para adquirir conhecimento vai variar de pessoa para pessoa, mas temos o Slack e outras formas de tirar duvida para que as pessoas possam seguir estudando (fora que o mentor n se negaria a tirar duvidas mesmo após o termino da mentoria). 

Esse tempo limite tbm seria bom para manter os pupilos engajados, já que ele sabe que ele tem aquele tempo para aproveitar ao máximo o mentor.

Estimular eles a virarem mentor é uma boa ideia, a parte mais difícil, acho que é tirar o receio de não ter conhecimento suficiente, mas isso pode ser trabalhado nos nossos grupos e pelo próprio mentor.

Acredito que poderíamos desafogar um pouco as filas com projetos que já existem. Como o de grupos de estudo, pois se a pessoa quiser mentoria em algo muito especifico, um grupo de estudos pode ser mais enriquecedor do que um mentor.

**Comment by Rubensdsj** [comment]
@lflimeira eu discordo um pouco disso de colocar um limite de tempo na mentoria.  Se o mentor vai continuar ajudando os pupilos mesmo depois desse tempo, então a mentoria vai continuar sem prazo, mas o mentor vai ganhar mais pupilos e vai acabar afogando ele. Claro que os pupilos possivelmente vão ter um bom senso de não pedir ajuda pra tudo, mas se esperamos esse bom senso porque não esperar o pupilo se sentir confortável para parar a mentoria e talvez se tornar mais um mentor ? 
Pra mim, o mais  legal da mentoria é a relação mais informal entre os dois devs. Burocratizar isso com prazos me tira um pouco dessa relação.
Sei la acho que poderíamos trabalhar melhor a ideia de os pupilos serem mentores de outras pessoas. Com o tempo o próprio pupilo vai perceber que não precisa mais de tanta ajuda, exatamente por ver que ele tem conhecimento suficiente pra ajudar e pesquisar coisas por conta própria para auxiliar seus pupilos.
Se um mentor tem 5 pupilos (a metade do limite, um numero que faz com que o mentor não se afogue) e cada pupilo dele tem outros 2 pupilos, são 15 pessoas atingidas ao mesmo tempo. Se a relação acontece por tempo demoraria 3 ciclos pra essas mesmas pessoas serem atingidas.

**Comment by lflimeira** [comment]
@Rubensdsj, eu n falei que ele vai continuar ajudando, mas sim que ele pode tirar duvidas. Eu n me nego a tirar duvidas, posso demorar um pouco para responder por causa da correria do dia dia, mas eu deixo isso claro. O importante é o mentor alinhar isso com o pupilo. 

E o tempo é importante, pois tem casos em que o pupilo consegue o mentor, mas n da continuidade na mentoria, e após o término, o pupilo pode mandar novamente o pedido para ter um mentor. Principalmente pelo fato de que muitas pessoas procuram ser fullstack, dessa forma ele poderia pegar um mentor back e ter uma base boa, depois ele poderia pegar um front, e por ai vai.

E n descartei a ideia dos pupilos virarem mentores, pelo contrário, essa ideia é muito boa e deve ser incentivada. A questão é que temos novas pessoas procurando mentoria todos os dias, a fila só cresce, e mesmo incentivando os pupilos a virarem mentores, não creio que isso seria uma solução para diminuir as filas, talvez a longo prazo. Temos que pensar em algo para atender toda essa galera que procura por mentoria. 

E a questão de que "Com o tempo o próprio pupilo vai perceber..." esse tempo é muito relativo e pode demorar. 

E como eu disse, temos vários canais e formas do pupilo ter suporte no crescimento dele. A ideia é ninguém ficar desamparado e receber ajuda. :smile:

**Comment by Rubensdsj** [comment]
@lflimeira entendo essa necessidade de diminuir a fila, ajudar a galera é a função da comunidade. Possivelmente não entendo esse lance do "tempo limite" da mentoria por não ser um mentor nem um pupilo. Acredito que a relação entre os dois no fim vai continuar praticamente a mesma como @woliveiras  que tem um canal de contato com os pupilos dele. Mas ai fica a cargo de cada uma das partes.
O maior problema é que se a fila tem aumentado a cada dia a decisão tem que ser analisada e implementada o mais rápido possível.
Quanto tempo seria essa prazo? Talvez devesse ver com todos os mentores o tempo médio que eles entende ser bom.

**Comment by lflimeira** [comment]
Sim sim, acho que muita coisa vai variar conforme a conversa do mentor com o pupilo.

Sim o quanto antes melhor, mas temos que alinhar e achar a melhor solução, todas as ideias são validas para isso.

Quanto ao tempo, caso tenha, tem que ser alinhado. Eu pensei algo em torno de 6 meses.

**Comment by rafaelbezerra195** [comment]
Boa tarde pessoal, 

Acho interessante a ideia do ciclo de mentoria. Se tiver um roteiro/caminho/mapa e talvez desafios/atividades para "avaliar" o pupilo( lógico que cada um no seu tempo), é possível estimar quando este já consegue "caminhar com as próprias pernas", como o @lflimeira citou, o mentor( e todos da comunidade ) ainda estariam disponíveis para tirar dúvidas. 

Acho q todos temos que estar cientes que a quantidade de pessoas solicitando alguma ajuda é considerável, e ajudar a comunidade nesse sentido é importante, talvez se dedicando para "liberar" o mentor( sem comprometer seu próprio aprendizado ) ou se tornando um, se isso for de seu interesse.

É interessante também deixar claro, de alguma maneira, que eu ainda não sei exatamente rsrs, quais os conhecimentos necessários para ser um mentor de um determinado assunto, talvez ter alguma plataforma como exemplo, tipo alguma certificação lá do FreeCodeCamp, algo do tipo pode ajudar.

**Comment by quinalia** [comment]
Não sei se já existe, mas para acalmar a ansiedade da galera, e até para que possam se programar, poderia ser divulgado uma listagem da fila de espera do pessoal. Não sei se é divido por assunto, ou linguagem etc...

**Comment by woliveiras** [comment]
Ideia interessante, @quinalia

**Comment by mayronceccon** [comment]
Criar um roadmap para os pupilos seguirem. Penso que a maioria está em busca de um norte, assim, poderia ser criado este roadmap dos assuntos com maiores dúvidas e disponibilizado aos pupilos. Com essa ajuda o pupilo poderia ir estudando até conseguir o tutor, ou somente utilizar o mapa.

**Comment by woliveiras** [comment]
Fizemos uma reunião no dia 11/09/2017 com o intuito de pegar melhorias a se fazer no projeto Mentoria.

Rendeu um grande documento onde vamos melhorar muita coisa por aqui.

Por agora vou fechar essa issue por que logo vou criar um projeto (aqui no GitHub mesmo) para listar tudo o que vamos fazer.

Até mesmo se alguém que comentou aqui quiser pegar algo pra resolver das coisas que virão, é só ficar de olho no repo que logo irão aparecer as tarefas. :+1:
