### ISSUE TITLE
Preciso de um(a) mentor(a) de Front-End

### ISSUE THREAD

**Issue by brunooomelo** [training-center/mentoria#72]
## Bruno Xavier de Melo

 Estou terminando minha faculdade de Engenharia da computação e atualmente estudo por conta propria
Pretendo me tornar um Full Stack Web Developer.
Mas primeiro, quero me aperfeiçoar em Front, para conseguir um emprego na área e depois ir para o back-end.(PHP ou RUBY)

Conhecimentos:
- HTML
- CSS
- SASS
- GIT BASICO
- Começando Estudo com gulp e bower.

Links.
[GITHUB](https://github.com/brunooomelo)
[FACEBOOK](https://www.facebook.com/brunooomelo)

Agradeço desde já.

**Comment by woliveiras** [comment]
Show de bola cara! 

Vamos ver se alguém dos @training-center/mentors consegue te ajudar. :smile:

**Comment by jessuircleydson** [comment]
Já tem alguém?

**Comment by woliveiras** [comment]
Ainda não @jessuircleydson :smile: 

Se estiver na disposição em ajudar essa alma, será sucesso.

**Comment by jessuircleydson** [comment]
@woliveiras rapaz por mim ajudava uns 30 mas não sou tão assíncrono assim ainda, mas 2 dá hehe.
@brunooomelo Podemos tentar man, me adiciona no [Facebook](https://www.facebook.com/jessuir.cleydson). Ai agente vai vendo como fazer :)

**Comment by woliveiras** [comment]
KKKKK

**Comment by nandomoreirame** [comment]
@woliveiras, @jessuircleydson eu posso ajudar o @brunooomelo pra mim tá tranquilo.

**Comment by woliveiras** [comment]
Fala @nandomoreirame, o @jessuircleydson já começou o trampo. 😄 

Valeu cara.

**Comment by nandomoreirame** [comment]
:metal:
