### ISSUE TITLE
Consolidação de perfis em áreas

### ISSUE THREAD

**Issue by khaosdoctor** [training-center/mentoria#722]
Hoje temos, na lista de mentores, uma divisão meio inconsistente, porque temos algumas áreas inteiras, como front-end, back-end e também temos linguagens de programação (como Java).

O que eu proponho é consolidar tudo em áreas maiores e não misturar com linguagens específicas.

O que acham?

**Comment by lflimeira** [comment]
Eu acho que seria melhor manter o model antigo, e dividir por áreas e não por linguagem, pq a lista vai ficar enorme se a galera colocar o nome em cada lista de skill que souberem.

**Comment by woliveiras** [comment]
Concordo, galera.

**Comment by khaosdoctor** [comment]
Vamos deixar a issue rolar mais um tempo para o pessoal opinar, ai vamos criando as PR's

**Comment by kivervinicius** [comment]
Concordo, eu mesmo estou em 3 áreas hehe

**Comment by JamileLima** [comment]
Concordo. Acho que também seria legal pedir para os mentores colocarem em seus respectivos perfis as linguagens/skills em geral que estão oferecendo a mentoria.

**Comment by kivervinicius** [comment]
Acredito que a separação por linguagens seja interessante mas poderia ser como um agrupamento geral, pois para o pupilo entrar um a um para saber a especificação tbm pode ser ruim.

**Comment by cenoura** [comment]
Ao inserir meu perfil, notei que tem alguns perfis que estão em várias áreas. Penso que não há problema, caso não tenha como evitar, mas, se a pessoa deseja ser mentor em `Frontend` e `Backend`, por exemplo, deveria colocar apenas em `Full Stack`, em vez das três, não acham?
Talvez se criássemos a lista de mentores em uma tabela e tivéssemos colunas, por exemplo, linguagem principal e linguagens secundárias, assim facilitando a busca pelos pupilos do que querem aprender.

| Nome                       | Linguagem Principal | Demais Linguagens/Ferramentas/etc      |
|----------------------------|---------------------|----------------------------------------|
| Guilherme Augusto Henschel | PHP                 | Javascript, CSS, Laravel, WordPress... |
| ...                        | ...                 | ...                                    |

**Comment by khaosdoctor** [comment]
Eu acho que isso que o @kivervinicius falou lá em cima não é tão ruim, por exemplo, uma pessoa pode ser fullstack, mas fullstack não é uma área, é só uma denominação para a junção das outras três.

O problema com isso @cenoura, na minha opinião, é que ficaria muito oneroso escrever o README, é uma boa ideia, mas pode ser que poluísse demais com muitos dados

**Comment by ftonato** [comment]
Estou com uma dúvida @khaosdoctor, visto que os `pupilos` não escolhem o mentor, mas sim o contrário (pois eles cadastram-se no _trello_ e nós mentores selecionamos eles conforme cada perfil), por qual motivo precisaríamos mudar a estrutura atual dos nossos perfis?

Penso que nosso perfil deveria servir apenas para descrever um pouco do nossa trajetória profissional para que ao entrarmos em contato com os `pupilos` eles julgarem se o nosso perfil se encaixa ao que ele busca ou não...

Por favor, me corrija se eu estiver errado...

**Comment by woliveiras** [comment]
E se, ao invés de deixar tudo separado, montarmos uma lista com os nomes de todos os mentores e mentoras que participam do projeto, mas deixarmos em formato de tabelinha informando só o que a pessoa faz?

Ex.:

| Nome                       |  Área de atuação
|----------------------------|---------------------
| William Oliveira |  front end
| Lucas Humberto |  full stack

Acho que separar por linguagem pode aumentar muito o tamanho da nossa lista e como o @ftonato falou: hoje em dia somos nós quem entramos em contato com as pessoas que buscam ajuda, então acho que nem faz tanto sentido deixar tanta separação.

**Comment by khaosdoctor** [comment]
Acho que é válido também, melhor do que separar por áreas mesmo, se criarmos um listão de todo mundo que participa e as áreas de atuação realmente fica melhor!

**Comment by woliveiras** [comment]
Eu consigo atualizar isso entre esse e o outro final de semana.

Se alguém quiser pegar pra fazer é só mandar o PR monstro! :metal:

**Comment by khaosdoctor** [comment]
Eu vou estar viajando D: mas qualquer coisa eu posso dar os pitacos _from overseas_ auehuaeh

**Comment by woliveiras** [comment]
Galera, vou colocar essa tarefa a se fazer junto as melhorias que estamos planejando.

Logo logo vai aparecer uma atualização monstra no Mentoria.

ref: #710
