### ISSUE TITLE
Quero ser mentor de front-end

### ISSUE THREAD

**Issue by ogiansouza** [training-center/mentoria#73]
Me chamo Gian, tenho experiência na área trabalhando como desenvolvedor web e front-end, sempre trabalhei em agências digitais e de publicidade, agora trabalho com produto.
Posso ajudar com HTML, CSS, SASS, jQuery, Javascript e WordPress, além de coisas não técnicas como carreira.

Links:
[portfólio](http://giansouza.com)
[linkedin](http://linkedin.com/in/ogiansouza)

**Comment by woliveiras** [comment]
Boa @ogiansouza 

Vamos aguardar o pessoal do @training-center/moderators avaliar seu perfil. :smile:

**Comment by dorianneto** [comment]
Vai com tuuudo!

**Comment by ogiansouza** [comment]
@woliveiras @dorianneto valeuu!

**Comment by idlua** [comment]
Boa!!
