### ISSUE TITLE
Preciso de um mentor Front end

### ISSUE THREAD

**Issue by Marcelosilva10** [training-center/mentoria#76]
Preciso de um mentor pela seguinte situação sei html e css e básico em Javascript minha dificuldade e pegar um conteúdo em psd e transformar em html e css não sei por onde começar já trabalhei 11 meses em um projeto para um banco mais nunca tive experiência com layouts do zero porque as páginas já vinha pré definidas, com header, section, footers.
Quem faz o layouts em photoshop e o design pelo que sei o front não faz esse papel?
Minha duvida e como ter as nomeclaturas certas no css, ou como criar praticamente do zero.

**Nome:*Marcelo Henrique de Souza e Silva*
**Descrição:*Quero ser ótimo em front end*
**Nível de conhecimento atual:*Basico*
**Contatos:*https://www.facebook.com/maassilva*
**marcelo-h-silva@hotmail.com**

**Comment by jessuircleydson** [comment]
Posso ajudar

**Comment by woliveiras** [comment]
Booooa, foi mais rápido que meu primeiro comentário ein @jessuircleydson 

kkkkkkk

Acho que já conseguiu ajuda @Marcelosilva10 

Só abrir um PR com seu perfil. Bem vindo!

**Comment by jessuircleydson** [comment]
hasuahusha, tamo aqui pra isso 😄

**Comment by jessuircleydson** [comment]
@Marcelosilva10 
E aew Marcelo blz?
Só mandar um [PR com seu perfil](https://github.com/training-center/mentoria/tree/master/pupilos) seguindo o [template](https://github.com/training-center/mentoria/blob/master/pupilos/pupilo_template.md).
Se tiver dúvida como mandar um Pull Request só falar. Me add no [Facebook](https://www.facebook.com/jessuir.cleydson) que agente ver a melhor forma pra tocar as aulas.

**Comment by Marcelosilva10** [comment]
Podeixar @jessuircleydson. já te adcionei no facebook.

**Comment by jessuircleydson** [comment]
Estamos definindo as coisas no facebook, o @Marcelosilva10 tinha um compromisso mas vai subir o perfil dele hoje, após isso atualizo o meu. 👍

**Comment by woliveiras** [comment]
\o/

Sucesso @jessuircleydson

**Comment by woliveiras** [comment]
Agora ficou bonito!

Valeu galera. :metal:
