### ISSUE TITLE
Preciso de um mentor front-end

### ISSUE THREAD

**Issue by matefs** [training-center/mentoria#768]
## Meu Nome

Mateus Schverz

## Qual meu sonho na carreira?

Criar coisas novas, e que possam ajudar outras pessoas.

## Alguns links para me conhecer melhor

https://www.facebook.com/profile.php?id=100007176466031
https://twitter.com/MateFS

**Comment by kellfluz** [comment]
@matefs recomendo você ler o texto [https://github.com/training-center/mentoria](url) na parte "Preciso de um(a) Mentor(a)"
Nele explica como solicitar um Mentor, inclusive preencher um formulário e aguardar um mentor disponível entrar em contato com você. ;)

**Comment by woliveiras** [comment]
Valeu, @kellfluz 

É exatamente isso!

Vou fechar a issue, @matefs.

Qualquer dúvida é só mandar.
