### ISSUE TITLE
Quero ser mentor de Front-end

### ISSUE THREAD

**Issue by nandomoreirame** [training-center/mentoria#77]
**Nome:** Fernando Moreira
**Descrição:** Moro em Curitiba/ Paraná. Trabalho como desenvolvedor front-end na @pipefy e amo tudo relacionado a web, sou obcecado por performance e desenvolvimento ágil, gosto de códigos legíveis, semânticos e reutilizáveis.

Hoje sou especializado em desenvolvimento web usando **Wordpress** com foco em **front-end** eu sempre cuido da usabilidade e performance de um site.

**Contatos:**

[Site/blog](https://nandomoreira.me/)
[Twitter](https://twitter.com/Pia_FrontEnd)
[Facebook](https://www.facebook.com/pia.frontend)
Email: nandomoreira.me@gmail.com

:metal:

**Comment by woliveiras** [comment]
:metal: 

Boa mano!

Vou compartilhar com os @training-center/moderators

**Comment by felipeorlando** [comment]
É válido lembrar que o @nandomoreirame tem uns temas FODAS em Jekyll também! A equipe de mentores está ficando mais foda a cada dia. :smiley:

**Comment by nandomoreirame** [comment]
já tenho um pupilo aqui, o @ garherro gostou da ideia de vocês montarem uma mentoria pra isso e quer entrar pra aprender comigo \o

**Comment by woliveiras** [comment]
Que da hora @nandomoreirame! 

Já pode abrir um PR com seu perfil cara. \o/

**Comment by nandomoreirame** [comment]
Tá lá! PR #80

**Comment by woliveiras** [comment]
Sucesso!!
