### ISSUE TITLE
Avaliação dos Mentores

### ISSUE THREAD

**Issue by woliveiras** [training-center/mentoria#8]
Definido como deve ser o perfil dos Mentores (#1), como faremos a avaliação para os Mentores?

**Comment by woliveiras** [comment]
Precisamos de sugestões ou de voluntários para a bancada que vai avaliar os perfis.

**Comment by danilovaz** [comment]
Acredito que ao invés de ter uma issue de "Quero ser mentor", deveríamos indicar que quem quer ser um mentor crie uma issue [Quero ser mentor] - Fulano de Tal e nessa issue ele faça sua apresentação. Dessa maneira, conseguimos dialogar em separado com cada mentor, diretamente em sua issue.

Devemos também criar labels, por exemplo, [Quero ser mentor] - Fulano de Tal [label JS] [label Ember.js] por questão de organização.

O mentor no caso, deverá prover o maior número de informações para que a bancada possa avaliar de maneira justa. Portfólios, links de projetos realizados, links de repositórios e até recomendações no Linkedin, podem ser muito importantes pois será possível ter uma dimensão concreta das aptidões do mentor.

A avaliação do mentor, acredito que deva ser feita por todos os envolvidos no projeto. E de maneira transparente. As labels vão servir para que possamos identificar quais perfis somos capazes de avaliar também. Por exemplo, Membro 1 tem conhecimentos em JavaScript e um candidato a mentor tem conhecimentos em Ruby. O Membro 1 não é capaz de avaliar o candidato tecnicamente, em termos da linguagem, mas pode avaliar tecnicamente no contexto geral com base nos projetos realizados, artigos e/ou posts escritos pelo mesmo.

**Comment by woliveiras** [comment]
Pow, proposta maneira essa dos membros avaliarem mano.

Em seguida, os mentores, já em exercício, podem entrar na Org para ajudarem nisso também. Que tal?

Sobre as Labels, da hora, excelente ideia cara.

O esquema de cada candidato abrir a issue com seu nome já é o proposto, só a primeira issue que abri e deixei pra quem quisesse colocar lá por ser para os primeiros.

Se for interessante, posso dividir ela agora!!!! :smile:

**Comment by woliveiras** [comment]
Criei algumas [labels](https://github.com/training-center/mentoria/labels) pra começar essa bagaceira!

**Comment by rafaDfaria** [comment]
@woliveiras Boa, poderia colocar umas com relação aos pupilos né? #aluno #newbie #aprendiz #pupilo #cafécomleite, etc. Acho que será interessante.

**Comment by JGcarv** [comment]
Acho que podemos pensar em um sistema de classificação dos mentores, pois os próprios pupilos tem "níveis" de conhecimento diferentes.

Por exemplo, um determinado candidato a mentor pode não ser "apto" a acompanhar um pupilo que já tem x anos de experiência e tem o objetivo de conseguir uma vaga no exterior, mas pode ser muito útil a um pupilo que está apenas começando e tentando entender lógica de programação.

Assim, além de aumentar o número de pupilos impactados, pode se instaurar uma cultura de ajudar/ser ajudado simultaneamente, o que reforça um pouco a ideia da comunidade.

O que acham?

**Comment by jlamim** [comment]
Bastante pertnente essa questao do nivelamento.

Fazer isso manualmente pode ser bem trabalhoso, pois teriamos que ficar
analisando os perfis de mentor e pupilo, pra saber se realmente o mentor
sera util para o avanco do pupilo, ou se precisa de um mentor com mais
experiencia.

Ja trabalhei com mentoria dentro da comunidade Mozilla Brasil, e as vezes
alguem se colocava como mentor, montava o seu grupo de pupilos, mas os
pupilos nao evoluiam ou nao atingiam os objetivos, pq o mentor nao tinha
bagagem suficiente.

Em terça-feira, 12 de abril de 2016, JGcarv <notifications@github.com>
escreveu:

> Acho que podemos pensar em um sistema de classificação dos mentores, pois
> os próprios pupilos tem "níveis" de conhecimento diferentes.
>
> Por exemplo, um determinado candidato a mentor pode não ser "apto" a
> acompanhar um pupilo que já tem x anos de experiência e tem o objetivo de
> conseguir uma vaga no exterior, mas pode ser muito útil a um pupilo que
> está apenas começando e tentando entender lógica de programação.
>
> Assim, além de aumentar o número de pupilos impactados, pode se instaurar
> uma cultura de ajudar/ser ajudado simultaneamente, o que reforça um pouco a
> ideia da comunidade.
>
> O que acham?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/training-center/mentoria/issues/8#issuecomment-208963530>
>


-- 

*Jonathan Lamim Antunes*


*Desenvolvedor Web/Mobile & Palestrante*
*Tel: *+55 27 3082-4437 | 27 995 125 164

www.jlamim.com.br
www.github.com/jlamim
www.facebook.com/jlamim.projetos

**Comment by woliveiras** [comment]
Ideia muito boa @JGcarv!

Será que colocar um esquema de classificação não vai dar mais trabalho?

A ideia inicial seria do Mentor mesmo entrar em contato com o Pupilo.

A avaliação (no caso verificar o perfil dele) só aconteceria para a aprovação dos Mentores.

Depois ele entra nas issues e escolhe alguém que ele consegue ajudar.

**Comment by dorianneto** [comment]
Ideias muito massa! Com relação ao assunto levantado pelo @JGcarv, acho que não deveria ser responsabilidade da organiação verificar o nível do mentor e sim do pupilo. Na minha visão, o papel da organização é acompanhar de perto (mensalmente ou semanalmente) o avanço da mentoria, colher feedback do pupilo com relação ao mentor e fazer uma boa escolha dos mentores, pois assim, não engessaríamos o processo de escolha dos mentores pelos pupilos.

**Comment by woliveiras** [comment]
Galera, pra fechar esse assunto e tacarmos lenha nessa fogueira:

* Temos na issue_template como a pessoa deve se apresentar para ser mentor
* Temos algumas pessoas querendo ser os primeiros mentores na issue #5 

Só faltou definir, como escolheremos os mentores mesmo, pois acabamos levantando vários pontos muito bons e enrolou tudo. kkkkk

Os pontos que consegui fazer um merge mental, aqui:

* A organização precisa se responsabilizar pelos mentores que deixamos entrar
* Caso o mentor aja fora do código de conduta, os membros da Org podem remover o mesmo

Sobre o processo de avaliação:

O processo de avaliação deveria ser somente sobre o perfil da pessoa e com base no perfil interpessoal para que o mesmo possa ajudar alguém conforme ele ache que é apto, ele mesmo escolhe o pupilo nas issues.
Caso o mesmo não tenha um bom rendimento (assumindo um compromisso com algum pupilo mais avançado que ele ou coisa do tipo) o próprio pupilo vai passar isso pra gente via Feedback e podemos tomar alguma medida.

Podemos colocar esse compromisso de só ser Mentor de alguém que ele saiba que é apto no código de conduta.

Mergeei corretamente até aqui? ;D

**Comment by dorianneto** [comment]
por mim ta de boa ;)

**Comment by woliveiras** [comment]
@training-center/moderators posso aceitar os primeiros mentores pra começarmos a tacar lenha nesse trabalho?

Dentre eles (#5), conheço a @akfzambrana, tem eu que, caso vocês achem ruim posso não ser mentor, não tem problema, e dei uma bela espiada nos outros candidatos, o @dorianneto e o @jlamim que parecem ser bem profissionais e vão agregar valor ao projeto.

**Comment by WendellAdriel** [comment]
Poxa velho, vou me inscrever lá, esqueci de inscrever

**Comment by woliveiras** [comment]
Abre uma issue mano @WendellAdriel, aquela lá era só exemplo. kkk

Se todos estiverem de acordo, já vou fechar essa aqui e aceitar a galera. Vamos acompanhando o desempenho do pessoal e seguir o esquema do Código de conduta.

**Comment by baltazarparra** [comment]
Como vai ser o modelo? Vamos dispor os mentores e aguardar fechar uma turma de pelo menos 5 desenvolvedores?

**Comment by WendellAdriel** [comment]
Mas é pra eu abrir uma issue e não comentar aquela então???

**Comment by woliveiras** [comment]
Não mano @baltazarparra, os pupilos abrem a issue e os mentores podem entrar em contato conforme sua disponibilidade.

Carmae que vou subir um arquivo pra ficar mais fácil de entender sabagacera. :)

**Comment by woliveiras** [comment]
Isso mesmo mano @WendellAdriel, abre outra. :)

**Comment by WendellAdriel** [comment]
Abri lá mano @woliveiras

**Comment by woliveiras** [comment]
Tá lá @training-center/moderators!

Agora os pupilos podem abrir as issues e aguardar os mentores (que podem ser esses 5 primeiros, incluindo o @WendellAdriel) entrarem em contato.

Cada mentor vai ter atrelado em seu perfil 5 pupilos até 10 e eles mesmos quem entram em contato com os pupilos através das issues e definem como vão se comunicar e dali pra frente.

Os pupilos vão ter um espacinho reservado para os contatos deles, também, para a galera se conhecer e fazer network. :smile: 

Os próprios mentores atualizam os [perfis deles](https://github.com/training-center/mentoria/tree/master/mentores) com os pupilos que estão atrelados e os pupilos também colocam seus [perfis](https://github.com/training-center/mentoria/tree/master/pupilos) se quiserem.

**Comment by woliveiras** [comment]
Comecei mergear e aceitar os mentores @training-center/moderators 

Vamos tocar lenha nesse negócio!
