### ISSUE TITLE
Criar um FAQ para o projeto

### ISSUE THREAD

**Issue by woliveiras** [training-center/mentoria#801]
Reunir as perguntas frequentes nessa issue para adicionarmos um FAQ no projeto.

O FAQ será criado em forma de Wiki, para utilizarmos melhor a integração do GitHub ao invés de criar mais um .md.

Postar a pergunta em forma de comentário e se já tiver a resposta adicionar abaixo no seguinte formato:

```
## Pergunta

*Resp.:* 
```

**Comment by woliveiras** [comment]
## Um mentor pode ser mentorado de outro mentor?

*Resp.:* Sim! Uma pessoa que esteja prestando mentoria, também pode receber mentoria de outra pessoa ainda mais experiente ou de outra área. Ex.: um mentor de frontend pode receber ajuda de outro mentor de backend para aprender mais sobre o funcionamento de APIs.

**Comment by woliveiras** [comment]
## O mentor pode ajudar alguém sem ser pelo Trello?

*Resp.:* Sim! Como mentor, você pode ajudar quem você se sentir motivado a ajudar. Em nosso Trello já utilizamos esse formato, onde você deve pegar o contato de alguém que você se identifique ou que seja um desafio pra você. O Trello deve ser nossa prioridade, mas você não estará impedido de ajudar alguém que entrou em contato com você por outros meios. Só tente sempre priorizar o Trello e depois os demais contatos.

**Comment by woliveiras** [comment]
## Não tenho muitos anos de experiência, posso ser mentor(a)?

*Resp.:* Sim! Você pode ajudar mentorando alguém com menos experiência do que você e, a partir do momento em que ambos estiverem no mesmo nível, liberar essa pessoa para que outro(a) mentor(a) a ajude. Ex.: você pode ser mentor(a) de lógica de programação, ajudando as pessoas a entenderem e praticarem lógica (não dando aulas, viu).

**Comment by khaosdoctor** [comment]
Eu não sei como responder, mas ai vão uns questionamentos que eu já recebi:

- Quanto tempo dura uma mentoria
- Posso parar de ser mentorado e voltar depois?
- Como posso mostrar a minha evolução na mentoria?
- Posso ter mais de um mentor?
- Qual é o papel de um mentor?

**Comment by woliveiras** [comment]
Boa, @khaosdoctor

**Comment by woliveiras** [comment]
Com a criação da plataforma, essa issue já não nos faz mais tanto sentido.
