### ISSUE TITLE
Alterar o formato da lista de mentores(as)

### ISSUE THREAD

**Issue by woliveiras** [training-center/mentoria#803]
Hoje temos uma lista com nomes de pessoas prestando mentoria e suas áreas de atuação.

Vamos mudar, com base nessa conversa https://github.com/training-center/mentoria/issues/722#issuecomment-324123838, para o formato de tabela onde teremos:

| Nome                       |  Área de atuação
|----------------------------|---------------------
| William Oliveira |  front end
| Lucas Humberto |  full stack

Onde o nome da pessoa também será o link para seu perfil dentro do projeto

**Comment by woliveiras** [comment]
Será necessário padronizar nomes que podem ser escritos de diversas maneiras, como frontend/front end/front-end.

Acho que poderíamos usar esse formato:

* frontend
* backend
* fullstack
* android
* ios
* iot
* agile
* management
* devops
* desktop
* uxdesign
* uidesign
* graphicdesign
* quality
* security

**Comment by lasombra** [comment]
Como fica quando a pessoa tem mais de uma área de atuação? Separa-se com vírgulas?

**Comment by woliveiras** [comment]
Isso mesmo, @lasombra 

Veja se acha legal:

| Nome                       |  Área de atuação
|----------------------------|---------------------
| William Oliveira |  frontend, mobile
| Lucas Humberto |  fullstack, devops

**Comment by lasombra** [comment]
Acho que sim. Acho que não tem forma melhor :-)

**Comment by lasombra** [comment]
Eu adicionaria uma coluna, tecnologias.

Nome | Área de atuação|Tecnologias
-- | --|--
William Oliveira | frontend, mobile|HTML5, CSS, JavaScript, ES6
Lucas Humberto | fullstack, devops|Ruby on Rails, JavaScript, Linux

**Comment by kivervinicius** [comment]
@lasombra  concordo pois por exemplo, sou backend em diversas linguagens, seria bacana poder citar as principais.

**Comment by woliveiras** [comment]
O ruim de citar linguagens é que acaba ficando uma lista imensa.

Isso fica ruim pra leitura.

A lista é só para ter um registro das pessoas que ajudam mentorando, ai seria melhor manter uma consistência que é ter somente o perfil da pessoa (back, front, mobile, desk, etc).

Pois, imagina:

Quem for colocar HTML, pode colocar HTML, Twig,  Jinja, Jinja2, Pug, Closure Template, Mustashe, Handlebars, etc.

Quem for colocar JS, pode colocar JavaScript, Angular, React, ReactJS, Vue, Vue2, VueJS, VueJS2, Angular2, Angular+, Angular4... 

Vish! :joy:

Ficaria bem feio.

Por mais que a gente queira padronizar, gerariam diversas tretas futuras de gente querendo adicionar 4000 coisas na lista ao invés de simplificar colocando as tecnologias principais.

**Comment by woliveiras** [comment]
Será que não faria mais sentido colocar algo como: mentor(a) nível junior, pleno, senior, master, exódia?

Por que ai já da pra saber que a pessoa tem conhecimento das coisas principais.

Ex.: front end pleno já sabemos que a pessoa deve conhecer algo disso aqui: https://github.com/woliveiras/front-end-career/blob/master/translations/pt-br/sources/engineer.md#front-end-engineer-pleno

**Comment by khaueviana** [comment]
@woliveiras acho que classificar em níveis jr, pleno, senior, pode gerar muita discussão e dificultar a classificação. Acredito que nome e área já está de bom tamanho. Até porque, pode rolar algum "jazz" se a pessoa é pleno, mas quer se candidatar ou de pupilos só quererem seniors...

E na boa, essas classificações são mais subjetivas que qualquer coisa nessa área rsrs Não curto classificar assim ninguém e nada, apesar de sermos obrigados em alguns momentos hehe

**Comment by lasombra** [comment]
Sem níveis. Isso torna as coisas muito subjetivas como o @khaueviana falou. Eu concordo que tecnologias/linguagens pode sair do controle, porém é a forma mais rápida e intuitiva para se fazer isso. Nem que tenhamos que usar só uma lista de tecnologias aceitas.

Por exemplo, para backend só pode ser Node.js, Ruby on Rails, Python, Java, SQL; frontend só JavaScript, CSS3, HTML5, Angular; e por aí vai.

**Comment by kivervinicius** [comment]
@woliveiras no caso o ideal seria citar de forma genérica e breve. E não fazer daqui um linkedin hehe

**Comment by woliveiras** [comment]
O ruim é que a galera vai tentar fazer e alguma hora pode passar, @kivervinicius :joy: 

É melhor deixar somente o perfil e não citar cada coisa que a pessoa faz.

**Comment by lasombra** [comment]
OK. Eu ainda acho que pelo menos um apanhado geral ajuda a o mentor e quem está procurando mentoria.

**Comment by khaueviana** [comment]
Acho que Nome, Área de Atuação, Tecnologias e o Linkedin já estaria bacana!

**Comment by woliveiras** [comment]
É que a intenção da lista é só mostrar que temos mentores(as) de xyz, não é bem pra mostrar o que cada um usa/sabe, viu galera.

Deixar a lista muito grande por conta da quantidade de tecnologias que cada um pode colocar é meio ruim pra usabilidade geral e ainda fica informação desnecessária lá.

**Comment by lasombra** [comment]
Eu concordo que a lista pode ficar grande, por isso eu sugeri limitar o número de tecnologias aceitáveis. Imagina que alguém está procurando por um mentor que saiba Vue.js. Ele vai ter que clicar em uma lista consideravelmente grande de mentores de frontend até achar alguém. Isso também não tem uma boa usabilidade.

A gente pode limitar o número de tecnologias a 3 ou 4 por mentor e limitar as opções para evitar ficar muito zoado.

**Comment by woliveiras** [comment]
Não, pô...

A pessoa **não deve procurar mentor(a)** pela lista.

Esse não é o objetivo.

Quem entra em contato com a pessoa que busca ajuda é o mentor ou mentora. A pessoa que recebe contato deve olhar se o nome da pessoa que entrou em contato está na lista. Só por isso que a lista existe: pra confirmar que quem entrou em contato com alguém é ou não mentor(a) aqui no nosso projeto.

Da uma olhada, galera:

> basta responder esse formulário e aguardar o contato de algum mentor ou mentora.

https://github.com/training-center/mentoria/#preciso-de-uma-mentora

Nós recebemos contato pelo form e pegamos o email da pessoa pra entrar em contato pelo nosso Trello.

**Comment by khaosdoctor** [comment]
Eu sou a favor de colocar só o nome e a área mesmo (mas eu sou muito mais a fim do tracinho haha tipo em 'back-end'), podemos iniciar já uma PR com isso e colocar as áreas com o que tem hoje. Vou iniciar lá e mando a PR aqui.

**Comment by woliveiras** [comment]
Perfeito, @khaosdoctor!

Deu pra entender como ficará a lista no final?

Uma listona única, ordenada alfabeticamente, com nome e área de atuação.

(https://github.com/training-center/mentoria/issues/803#issuecomment-330319211)

**Comment by khaosdoctor** [comment]
Yep, isso ai mesmo, podemos iniciar uma PR e ir fazendo aos poucos. Mas acho que tem que ser uma pessoa só porque se não isso vai gerar muitos conflitos

**Comment by woliveiras** [comment]
Siiim, mano!

**Comment by woliveiras** [comment]
Quem for fazer assina a tarefa para si.

Se tiver alguém que possa pegar isso é só assinar ou comentar aqui. :metal: 

OBS: O ideal é que, ao menos, 3 pessoas aprovem o PR dessa alteração.

**Comment by hdamaich** [comment]
Vou fazer essa alteração 😄

**Comment by hdamaich** [comment]
@woliveiras me enrolei por aqui e ainda não iniciei, mas me diz uma coisa, será valido esse investimento em arruma isso aqui, com nossa plataforma em desenvolvimento? (Isso também é valido para varias outras issues (#806 #807 #830 #838) que estão abertas por aqui)

**Comment by khaosdoctor** [comment]
Eu acho que não, porque se tiver esse desenvolvimento ai eu acho que é desnecessário mesmo...

**Comment by lbighetti** [comment]
cara acho que não tb, bora limpar e fechar esses tudo ai e focar na `PRATAFORMA`

**Comment by woliveiras** [comment]
Boa @lbighetti e @hdamaich

**Comment by woliveiras** [comment]
Essa issue não faz sentido visto que iremos criar uma plataforma que resolve esses problemas.
