### ISSUE TITLE
Estimular pessoas de outras áreas a se envolverem com o Mentoria

### ISSUE THREAD

**Issue by woliveiras** [training-center/mentoria#804]
O Mentoria foi iniciado por um front end.

Por isso a maioria das pessoas que participam do projeto são frontendeiras ou fullstackerzeiras, o que implica em uma falha no "atendimento" a backenders, designers, desktopers, mobilers, etc.

Precisamos bolar uma estratégia de divulgação para que pessoas de outras áreas conheçam nosso projeto.

**Comment by khaueviana** [comment]
Posso ajudar a divulgar nas comunidades .NET hehe

Não consigo pensar em uma estratégia, acho que temos que reforçar a comunicação além das comunidades front-end.

**Comment by woliveiras** [comment]
Boooooa!

**Comment by khaosdoctor** [comment]
Acho que seria uma boa termos "champions" de diversas áreas que teriam a responsabilidade de divulgar, assim podemos abranger mais comunidades

**Comment by woliveiras** [comment]
Como vocês acham que conseguimos atingir outras comunidades?

A intenção do TC é ter gente de várias comunidades pra que as pessoas (iniciantes) cheguem até nós e nós consigamos indicar para as outras comunidades, direcionar as pessoas para outros grupos, mas estarmos lá pra poder ajudar a pessoa em questões menos técnicas.

**Comment by khaosdoctor** [comment]
Eu acho que é através desses embaixadores ai que eu falei, você coloca a responsa de ser um tipo de embaixador em outras comunidades e vai evangelizando a galera haha

**Comment by anegrelli** [comment]
Opa, tudo bem pessoal, sou novo aqui e vou comentar algumas coisa ok, eu encontrei vcs por um post no face, acredito sim que vcs estão no caminho certo mas precisam formar mais parcerias com outras comunidades de desenvolvimento e negocios. Em relação a encontrar mentores acredito que se tiverem alguma forma de dar recompensa NÃO FINANCEIRA,  mas um status ou certificado de algum parceiro como a Microsoft, Google ou qualquer outro que apoie este tipo de iniciativa seria interessante, a pergunta é como... a resposta é network, sempre tem alguém que conhece alguém, enfim quero poder contribuir e vcs estão de parabéns pela iniciativa.

**Comment by woliveiras** [comment]
Fala, @anegrelli!

Achei interessante seu comentário, mas também não entendi muito bem.

Pode expandir um pouco mais seus pontos? O certificado de mentor(a) que você diz é do training-center ou de parceiros da comunidade?

**Comment by lflimeira** [comment]
Pessoal, acha que uma das dificuldades em envolver pessoas de outras comunidades no Training Center, é o fato de essas pessoas não conseguirem acompanhar o que está acontecendo no TC pelo Slack. Quando a pessoa entra no slack, ela automaticamente entra nos principais Channels, não seria interessante diminuir essas quantidades de Channels para deixar menos impactante?

**Comment by woliveiras** [comment]
Diminuir os canais que a pessoa entra por padrão, @lflimeira?

**Comment by lflimeira** [comment]
Isso, o que acha? Alias, ainda está assim? kkkkkk Posso estar falando besteira :rofl: :rofl: :rofl:

**Comment by woliveiras** [comment]
Opa! Eu alterei lá, mano. 

Boa! :D

**Comment by lflimeira** [comment]
Boaaa 😃

**Comment by woliveiras** [comment]
Galera, obrigado por participarem desta discussão.

Conforme já conversamos, vamos focar na plataforma e depois voltamos a fazer algo para movimentar mais o projeto.
