### ISSUE TITLE
Criação de um roadmap do(a) Mentor(a)

### ISSUE THREAD

**Issue by woliveiras** [training-center/mentoria#805]
Muita gente pensa em ajudar, porém nunca recebeu mentoria para saber como funciona.

Muita gente também não sabe quando pode pegar outra pessoa para ajudar.

--- 

Com base na https://github.com/training-center/mentoria/issues/802, devemos definir um roadmap do processo de mentoria com prazo de finalização.

**Comment by woliveiras** [comment]
Da maneira que eu faço eu peço para que a pessoa especifique suas tarefas e para que adicione prazos em tudo o que for fazer.

Se for o caso, a própria pessoa pode definir até quando um(a) mentor(a) irá auxiliar em sua trilha.

Depois essa pessoa pode passar a ser mentor(a) também, se assim quiser, ou se envolver com outros projetos dentro da comunidade.

**Comment by woliveiras** [comment]
Como parte do roadmap, a pessoa sendo mentorada poderia ter que manter seu perfil no LinkedIn atualizado e adicionado o Training Center lá.

[Adicione o Training Center em seu perfil do LinkedIn](https://medium.com/trainingcenter/adicione-o-training-center-em-seu-perfil-do-linkedin-c00181d831a3).

Pode ser uma das primeiras tarefas junto a adicionar o perfil de mentorado(a) no nosso GitHub.

**Comment by woliveiras** [comment]
Pensar em uma maneira de estimular as pessoas a criarem projetos para seu portfólio (CodePen, GitHub, etc)

**Comment by woliveiras** [comment]
Pensar em como estimular as pessoas a escreverem artigos sobre o que estão aprendendo

**Comment by woliveiras** [comment]
Pensar em como estimular as pessoas a fazerem pequenas apresentações sobre o que estão aprendendo (meetups, vídeos, etc)

**Comment by woliveiras** [comment]
Será necessário um esquema de timestamp onde colocamos no perfil da pessoa quando acabou seu processo de mentoria.

**Comment by IuryAlves** [comment]
@woliveiras  Coloca esses pontos que você levantou numa lista no primeiro comentário da issue, na minha opinião fica mais legível.

**Comment by khaueviana** [comment]
@woliveiras acho que são varias ideias, de alguns problemas diferentes. 

**GuideMentor(a)**

Cara, acho que tem muito post bacana no medium e bastante coisas no github, explicando como o projeto funciona como um todo. Mas acredito que é preciso de algumas coisas mais diretas, mais simples de visualizar e tudo mais e centralizadas.

Isso tudo pode estar em uma WIKI, onde explica todos os passos do programa de mentoria, desde como ingressar, atividades exigidas, sugestões de roadmap do mentor, algumas solicitações importantes que o mentor deve fazer para o pupilo, funcionamento do trello e por aí vai. Tudo isso poderia estar em uma WIKI. Facilita a indexação, manutenção e tudo mais. Com cara de Guide, enfim, acho que deu pra entender a ideia haha

**Guide Pupilo(a)**

Da mesma forma que é legal existir um guide pro mentor, tbm poderia ter para o pupilo, explicando como ingressar, sugestões de atividades de compartilhamento do que tem aprendido, atualizações no linkedin, enfim, as diversas coisas bacanas que esses caras podem ou devem fazer durante o processo de mentoria.

Dentro desse guide podem ter dicas de criação de projetos próprios dos pupilos e por ai vai...

**Resumindo minha ideia***

Dentro do projeto de mentoria, guides para o mentor e pupilo, de como entrar no projeto e fazer as coisas certinhas >)

**Comment by anegrelli** [comment]
Opa, eu aqui denovo, o @khaueviana esta certo, no GitHub esta muito espalhado e disperso as informações, se tivesse uma forma de centralizar seria melhor.

A outra questão é a seguinte, mentoria é quando uma pessoa que já passou por determinada situação ajuda outra que esta passando pela mesma situação, exemplo: Tenho uma empresa de comercio varejista e quero expandir, ai o Abilio Diniz me da mentoria de como expandir o meu comercia pois eles já passou por isso no Pão de Açúcar, deu pra entender a ideia... Aqui vcs estão fazendo uma mistura de Mentoria, Coach e Suporte e isso não é errado mas precisa ser desenvolvido um método ou um guia para facilitar para o mentor e para o mentorado, poderia criando um formulario para a pessoa que quer mentoria preencher ou algo do tipo para facilitar, mas nada complexo pois é ideia não é ingressar o processo e sim ser dinâmico, porem vejo varias informações dispensas no Slack ou lá é pra ser assim mesmo?? enfim eu tenho alguns modelos e métodos que estou compilando acredito que poderia ajudar o que vcs acham?? bora trocar ideia e co-criar???

**Comment by woliveiras** [comment]
Fala @anegrelli!

Valeu pelo comentário, mas não entendi muito bem seus pontos.

> Tenho uma empresa de comercio varejista e quero expandir, ai o Abilio Diniz me da mentoria de como expandir o meu comercia pois eles já passou por isso no Pão de Açúcar, deu pra entender a ideia... Aqui vcs estão fazendo uma mistura de Mentoria

Essa descrição abaixo não é a mesma coisa que você comentou sobre expandir a empresa? 

>  O Mentoria é uma iniciativa comunitária com a premissa de unir pessoas com experiência em uma área de atuação com quem deseja entrar nessa área ou deseja eveluir profissionalmente.
> Queremos ajudar iniciantes a não passarem por certos problemas que passamos e também quem já está no mercado e sente necessidade de direcionamento para crescer seu nível profissional.

Alguém quer crescer profissionalmente e alguém já tem experiência de mercado, então essa pessoa com XP ajuda a outra. Alguém quer se tornar dev e alguém é dev, então essa pessoa ajuda a outra a se tornar dev.

A parte de suporte a tirar dúvidas não é do projeto mentoria. Acho que a confusão está por isso. Temos diversas iniciativas pra ajudar o pessoal e o mentoria é uma delas, da uma olhada: https://github.com/training-center/sobre

O formulário para receber mentoria também já existe: https://github.com/training-center/mentoria#preciso-de-uma-mentora

O que seriam as informações dispersas no Slack?

O roadmap de mentor(a) é justamente esse compilado do que fazer como mentor(a). Já estamos desenvolvendo, mas demos uma pausa aqui pra agilizar nossa plataforma: https://github.com/training-center/plataforma :raised_hands: :raised_hands: :raised_hands: 

Com a plataforma vai acontecer essa centralização.

Estão acontecendo diversas mudanças na comunidade, aguarde novidades em breve. :joy:

**Comment by anegrelli** [comment]
Obrigado @woliveiras pelo retorno, 

Sim vc esta correto em relação ao ponto que tentei exemplificar, lendo a documentação do Training Center novamente me dei conta que o propósito esta alinhado rsrsrs... é que este propósito está em uma linha onde os metodos se cursam "Mentoria", "Coach" e afins, mas isso foi apenas uma reflexão o que importa mesmo a poder ajudar de alguma forma.

Em relação ao que comentei sobre o suporte é que não tinha entendido as outras iniciativas pois estava focado na questão de mentoria, e esta na mesma linha sobre o que comentei do Slack, não tive a intenção de criticar no viés negativo. 

Esta tudo muito bem organizado e vcs estão de parabéns, quero poder colaborar de alguma forma, não sou desenvolvedor mas entendo de desenvolvimento rsrsrs...

Mais uma vez obrigado e forte abraço.

**Comment by woliveiras** [comment]
Valeu pela participação na issue, galera!

Enviaram boas ideias. 

Vou fechar essa issue por que ela não fará mais sentido com a criação da plataforma (apesar de que o "roadmap" estará na plataforma).

Qualquer problema agora podemos discutir direto sobre a plataforma.
