### ISSUE TITLE
Fazer uma revisão no Board do Trello

### ISSUE THREAD

**Issue by woliveiras** [training-center/mentoria#806]
Precisamos reorganizar nosso board.

Antes de mover tudo lá, precisamos definir:

* labels
* colunas
* dados importantes que precisamos de possíveis mentorados(as)

Pois utilizaremos esse padrão no Zapier para a integração com o TypeForm.

**Comment by alinebastos** [comment]
Dados importantes:
- Você faz parte de algum grupo sub-representado?
- Se a resposta foi sim na pergunta anterior, de qual grupo você faz parte? (resposta não obrigatória aqui, ou a opção 'prefiro não dizer')

**Comment by khaueviana** [comment]
Sugestões paras as labels:

- Tecnologias que o pupilo deseja desenvolver: Back-End / Front-End / Full-Stack e Tecnologias: JS, React, .NET, Java, CSS e ....
**Isso vai ajudar a encontrar mentores, com isso bem classificado, fica fácil a indexação e divulgação das necessidades dessa comunidade.**

- Situação no mercado: Estagiário, Querendo ingressar, Apenas Curioso e ...
**Ajuda o mentor a selecionar com qual perfil de pupilo deseja trabalhar**

- Análise da base de dados.
Talvez, de acordo com as classificações e cards, seria legal extrair alguns gráficos e expor isso, com base nisso é possível medir onde é necessário colocar gente para trabalhar. Como por exemplo, demanda de pupilos sem mentores por tecnologia.

**Comment by khaosdoctor** [comment]
O que eu acho muito complicado são as labels do Trello

**Comment by woliveiras** [comment]
Galera, essa issue não faz sentido visto que iremos criar uma plataforma que resolve esses problemas.

Podemos fechar?

**Comment by khaosdoctor** [comment]
Podemos
