### ISSUE TITLE
Mentoria encerrada: Atualizar perfil

### ISSUE THREAD

**Issue by theandersonn** [training-center/mentoria#807]
Galera, como posso colocar no meu perfil que não estou mais sendo mentorado?

Devido ao corre do dia a dia, tanto eu como meu mentor o Luiz, tivemos que fazer uma pausa. Sem previsão para retomar; como funciona a atualização de perfil?

https://github.com/training-center/mentoria/blob/master/profiles/pupils/profiles/AndersonNascimento.md

**Comment by woliveiras** [comment]
Vamos discutir isso, @theandersonn 

Já está nos nossos planos mudar e adicionar um prazo final no processo.

Precisaremos de um campo pra adicionar quando foi que parou.

@training-center/mentors poderiam nos ajudar a decidir como manter isso.

**Comment by khaosdoctor** [comment]
Eu acredito que você possa remover sim ou então colocar como "pausado" e a data da pausa para podermos saber sem problemas :)

**Comment by woliveiras** [comment]
Colocar como pausado é legal ein, @khaosdoctor 

Mas, no caso, indica que um dia será retomado... E para casos onde foi finalizado o período de mentoria, o que indica, mano?

**Comment by khaosdoctor** [comment]
Podemos colocar tipo uma lista de mentores, como se o mentorado fosse "passando" de mentores. Então colocaria o primeiro mentor e os seguintes, dessa forma:

## Mentores

- Mentor 1
  - Iniciado: dd/mm/yyyy
  - Finalizado: dd/mm/yyyy
- Mentor 2
  - Iniciado: dd/mm/yyyy

**Comment by woliveiras** [comment]
Interessante, ein @khaosdoctor 

Como ficaria isso no nosso [template](https://github.com/training-center/mentoria/blob/master/profiles/pupils/pupil_template.md)?

Algo assim `- [Nome de seu mentor ou mentora](/profiles/mentors/profiles/perfil_do_seu_mentor_ou_mentora.md) (de xx/xx/xxxx até xx/xx/xxxx (ou atual))`?

Onde fica como um curriculum `de`, `até`, `atual`.

```
# Mentor(a) responsável por mim

- [Nome de seu mentor ou mentora](/profiles/mentors/profiles/perfil_do_seu_mentor_ou_mentora.md) (de xx/xx/xxxx até xx/xx/xxxx (ou atual))

## Meu Nome

Seu nome

## Qual meu sonho na carreira?

Adicione qual seu sonho de carreira aqui.

## Alguns links para me conhecer melhor

- [Facebook](link)
- [Twitter](link)
- [LinkedIn](link)
- [Email](mailto:seu@email.com)
```

**Comment by khaosdoctor** [comment]
Ficaria desse jeito que eu falei mesmo kk

```md
# Mentor(a) responsável por mim

- [Nome de seu mentor ou mentora](/profiles/mentors/profiles/perfil_do_seu_mentor_ou_mentora.md)
  - _Início da mentoria:_ **DD/MM/YYYY**
  - _Final da mentoria:_ **DD/MM/YYYY** (Atual se estiver em progresso)

## Meu Nome

Seu nome

## Qual meu sonho na carreira?

Adicione qual seu sonho de carreira aqui.

## Alguns links para me conhecer melhor

- [Facebook](link)
- [Twitter](link)
- [LinkedIn](link)
- [Email](mailto:seu@email.com)
```

**Comment by woliveiras** [comment]
Galera, essa issue não faz sentido visto que iremos criar uma plataforma que resolve esses problemas.

Vou fechar e qualquer coisa reabrimos.
