### ISSUE TITLE
Estrutura para Mentoria com Rotação Periódica

### ISSUE THREAD

**Issue by lbighetti** [training-center/mentoria#818]
Proponho uma estrutura para a Mentoria que tenha tempo de duração, e _checkpoints_ periódicos para acompanhar o progresso do pupilo.

#### Timeframe base:
* Duração: 3 meses
* Checkpoints: a cada 2 semanas

---

Isso traria 3 benefícios:

1. Maior vazão de pupilos devido a rotação
2. Reavaliação da relação Mentor-Pupilo a cada 3 meses (apenas renovar se fizer sentido)
3. Reforçar o foco a resultados devido a uma data limite

## Exemplo

Não acho que deveríamos enforçar o formato, mas para ilustrar, segue um exemplo genérico de uma mentoria sendo feita nesse formato:

### Semanas
1. Introdução, definição de objetivos e plano de ação
> O Mentor e o Pupilo se conhecem, alinham qual o objetivos e resultados esperados e juntos traçam um plano de ação para as 12 semanas
2. Ajuste do plano de ação
> As duas primeiras semanas o pupilo tenta seguir o plano, e conforme conhece as condições iniciais melhor percebe que o plano pode ser ajustado melhor
3. Progresso e resolução de problemas
4. Progresso e resolução de problemas
5. Progresso e resolução de problemas
> Com um plano mais realista, o pupilo vai tomar as ações do plano e a nestes 3 checkpoints o mentor o ajuda a resolver problemas e tirar obstáculos do caminho (parte principal que deve haver maior progresso).
6. Revisão e conclusão
> Mentor e Pupilo analisam o que foi feito, o que pode ser melhorado, quais os próximos passos e decidem se vão renovar para mais 3 meses mentorado ou não.

**Comment by khaueviana** [comment]
Acredito que poderíamos formatar em um modelo de gestão ágil, sendo assim, o pupilo já teria um contato inicial com esse tipo de gestão. Que possivelmente ele encontrará no mercado.

**Comment by lbighetti** [comment]
Sensacional @khaueviana!
Poderiam ser sprints de 2 semanas, e com certeza sem Daily Stand-ups como mencionado. :ok_hand:

**Comment by khaueviana** [comment]
Bacana! Acho que a cadência pode ficar em aberto, assim como os métodos ágeis trabalgam, 1 ou 2 semanas parece bom :)

**Comment by jessuircleydson** [comment]
Confesso que quando li o titulo pensei: "isso vai dar certo não" (suhausahusha), devido a tempo disponível por pupilos e tbm alguns mentores, mas lendo a ideia percebo que é uma boa ter uma meta assim até pra medir o avanço, acho que é possível encaixar mesmo com tempo de alguns ou ambos diferentes. Encaixar os métodos ágeis da melhor forma para ambos.

**Comment by woliveiras** [comment]
Fala, galera!

Obrigado pela participação!

Coletamos muitas ideias boas e vamos tentar levar para frente.
