### ISSUE TITLE
Criação da Wiki do Mentoria

### ISSUE THREAD

**Issue by woliveiras** [training-center/mentoria#821]
Com base na issue https://github.com/training-center/sobre/issues/29 vamos começar a criar uma Wiki para o Mentoria.

## Importante

Inicialmente precisamos deixar o conteúdo no README como está e ir montando a Wiki. Somente depois de termos tudo OK na Wiki, devemos *linkar* no README para cada tópico da documentação.

## Instruções

Nessa Wiki devemos ser mais descritivos do que fomos no README, adicionando mais imagens de como as coisas acontecem aqui no GitHub (principalmente na parte de novos(as) mentorados(as)) e informações mais específicas ainda, pois percebemos que o texto usado no documento principal não está claro.

No README do nosso projeto ficará somente a descrição do que é, links importantes e a chamada para a Wiki.

## O que precisamos ter na Wiki

Inicialmente eu vejo a necessidade de termos esses tópicos na Wiki:

- como me tornar mentor(a) no projeto Mentoria
- como conseguir um(a) mentor(a)
- como criar meu perfil de mentor(a)
- como criar meu perfil de mentorado(a)

## Links úteis

Para facilitar a criação da Wiki temos os links administrativos:

- https://github.com/training-center/mentoria/tree/master/admin/helpers
- https://github.com/training-center/mentoria/blob/master/admin/helpers/CREATE_PUPIL_PROFILE.md

**Comment by lbighetti** [comment]
@woliveiras man, vamo cancelar essa jossa e focar na plataforma ?

**Comment by woliveiras** [comment]
Opa! Verdade, cara

Fechando
