### ISSUE TITLE
Quero ser mentor de Front-end e JavaScript (talvez de UX e UI)

### ISSUE THREAD

**Issue by cezarlz** [training-center/mentoria#83]
**Nome:** Cezar Luiz Sampaio
**Descrição:** Atualmente sou desenvolvedor front-end pleno no EBANX, em Curitiba/PR. Trabalho na área desde 2009 e conforme consigo procuro sempre criar soluções que enfrento no dia-a-dia e repassar para a comunidade em forma de artigos, libs, etc. Sou graduado em Análise e Des. de Sistemas pela Universidade Positivo e autodidata nos tempos livres. Adoro ler, escrever, ensinar e passar meus conhecimentos.

**Contatos:**

* Email: cezarluiz.c@gmail.com
* Blog: http://cezarlz.github.io/
* Linkedin: https://www.linkedin.com/in/cezarluiz
* Twitter: https://twitter.com/cezarlz
* npm: https://www.npmjs.com/~cezarluiz0

Cheers!

**Comment by woliveiras** [comment]
Fala @cezarlz 

Pode mandar um PR com seu perfil cara. Vamos partir pra cima!

Falando em UI, não gostaria de ajudar [nesse outro](https://github.com/woliveiras/front-end-career/issues/20) projeto também?

**Comment by ogiansouza** [comment]
Sucesso \o/

**Comment by dorianneto** [comment]
Pra cima!
