### ISSUE TITLE
Sobre a criação de uma plataforma para o Mentoria

### ISSUE THREAD

**Issue by woliveiras** [training-center/mentoria#830]
Durante a conversa sobre a criação ou não de uma Wiki (#821) para o nosso projeto surgiu a dúvida se não estamos somente jogando a sujeira para debaixo do tapete.

Tivemos uma conversa extensa no Slack, porém ficou inconclusivo.

Ainda estamos muito divididos entre fazer logo uma plataforma ou continuar utilizando o GitHub para cadastro de mentores e mentorados + documentação.

Essa issue servirá para levantar maiores vantagens e desvantagens de cada ideia para votarmos em qual devemos focar.

---

### Vantagens do GitHub

Nós gostamos de forçar o uso do Git & GitHub por que entendemos a importância de se aprender Git e também da utilização do GitHub para desenvolvedores(as).

Tentamos fazer com que as pessoas percam o medo de usar a linha de comando e o GitHub através de nosso apoio aqui na plataforma.

É uma excelente plataforma social.

### Desvantagens do GitHub

Nós entendemos, por experiência desde que começamos com o Mentoria, que a maioria das pessoas que entram em contato conosco buscando mentoria não conhecem Git e muito menos GitHub a fundo para interagir sem dores de cabeça com a plataforma.

Isso gera um desconforto nas pessoas por que se sentem atrás das demais no mercado de trabalho, muitas vezes sentindo vontade de desistir de continuar sua busca por se tornar programador(a). Nós temos que assumir que as pessoas que buscam mentoria não tem experiência e estão fortemente inclinadas a desistir da área se se sentirem assim.

O GitHub acabou não escalando muito bem como plataforma onde armazenamos tudo sobre o mentoria, pois quando temos que mudar algo precisamos alterar em diversos arquivos e ficar caçando possíveis erros.

Muito trabalho manual.

### Vantagens da plataforma

Podemos criar algo diretamente focado em nossas regras de negócio.

Conseguiremos coletar mais informação de pessoas que entram e fazer um acompanhamento automatizado melhor.

Um simples cadastro de usuários facilitaria a criação de uma API para consumo de outras plataformas (como a integração com uma empresa de vagas que estamos planejando).

### Desvantagens da plataforma

Teremos que desenvolver tudo do zero.

Movimentaremos mais pessoas para a criação disso.

As pessoas que já estão cadastradas terão que acessar a plataforma e adicionar seus dados e relacionamentos.

---

## Votação

Quem for a favor do GitHub vota no comentário do GitHub e quem for a favor da plataforma vota no comentário da plataforma aqui nessa issue.

**Comment by woliveiras** [comment]
Vote aqui se você é a favor do GitHub

**Comment by woliveiras** [comment]
Vote aqui se você é a favor da Plataforma

**Comment by thiamsantos** [comment]
+1 para construção de uma plataforma. Pode contar com a minha ajuda ;)

**Comment by woliveiras** [comment]
Galera, foi criado o repositório `plataforma`.

Podemos seguir as discussões sobre o assunto diretamente lá.
