### ISSUE TITLE
Criação de um Developer Roadmap

### ISSUE THREAD

**Issue by lbighetti** [training-center/mentoria#836]
Proponho criarmos um Roadmap do Desenvolvedor, similar a este (link by @hdamaich): 

* https://github.com/kamranahmedse/developer-roadmap

Em português, baseado na nossa experiência de carreira e aqui no CT.
Isso seria especialmente útil pra quem vai entrar agora nessa área, está começando ou num nível intermediário.
Além de ajudar as pessoas que **não tem mentor atualmente**, a se guiar por algum caminho de aprendizado.

O que acham ?

**Comment by hdamaich** [comment]
Vamo que vamo, pego junto em traduzir tudo, com tempo podemos ir montando links para cada tópico desses, com livros, artigos e video aulas que os mentores estão indicando para seus mentorados.

Acho que vai ser super valido para nosso projeto. Inclusive para ajudar os proprios mentores a mentorar inclusive em linguagens que não tem 100% de dominio.

**Comment by rafaelbezerra195** [comment]
Alguns pontos : 
1. Seria legal traduzir esse, como opção.
2. Poderíamos linkar com a Awesome list https://github.com/sindresorhus/awesome.

**Comment by lbighetti** [comment]
Tem esse projeto/ issue
outra pergunta é, fazemos no mentoria ou nesse outro projeto
https://github.com/training-center/roadmap/issues/2

**Comment by rafaelbezerra195** [comment]
Na Issue sobre melhorias no processo de mentoria, algumas pessoas citaram isso( criar os roadmaps ) visando desafogar os mentores. Acho q poderia ficar lá mesmo e encerrar essa issue.

**Comment by lbighetti** [comment]
Concordo, acho que faz sentido - e acho que de fato ajudaria a desafogar mentores.
Partiu, vou iniciar lá a parte de backend então. ❤️
