### ISSUE TITLE
Adição de novos campos no formulário de solicitação de mentor

### ISSUE THREAD

**Issue by jlamim** [training-center/mentoria#838]
Novos campos a serem inseridos no formulário de solicitação de mentor:

- **idade** (com esse campo fica melhor para que o mentor possa decidir se pode ou não ajudar, pois alguns mentores não se sentem confortáveis em ajudar pessoas muito novas ou com idade um pouco mais avançada) [sugestão do Jonathan Lamim]

**Comment by alinebastos** [comment]
Novos campos:

- **Pertence a algum grupo sub-representado?**
  - Sim
  - Não

- **A qual grupo sub-representado você pertence?**
  - Mulheres; 
  - Comunidade Negra; 
  - Comunidade LGBT;
  - Baixa renda (aí tem que ver como fazer essa classificação, se tem computador e internet em casa eu não consideraria baixa renda);
  - Algum outro grupo que eu não coloquei;
  - Prefiro não responder.

@oieusouamiguel me ajuda a conferir essa lista? :)

**Comment by lbighetti** [comment]
__Github user__
é meio um problema de ovo e a galinha, mas acho valido colocar o campo

**Comment by oieusouamiguel** [comment]
Ok, está bom, mas quero que tu se atente nessas coisas:

1) Eu considero pessoas que tenham computadores e celulares em casa como baixa renda porque trabalho diretamente com essa galera e sim, as vezes eles não sabem como usar e/ou usam da escola/trabalho/conhecidos. Já dei aula pra muita gente também que É baixa renda, ou seja, não tem condição de pagar nem a passagem pra ir pra curso/evento porque tem que colocar comida em casa. Então bora pensar um pouco nesse aspecto socio-economico que não é só ligado a não ter bens materiais e, sim, não ter condições de fazer outras coisas e ter outros privilégios por falta de grana. Por isso acho EXTREMAMENTE válido baixa renda estar nessa lista.

2) Acrescente LGBTQIA+ porque é mais inclusive com a galera Queer (não binários, por exemplo), Intersexo (que é a galera que tem dois sexos biológicos) e a galera Assexual (que não se relaciona sexualmente ou amorosamente com ngm). O "+" é para dar ênfase em outras orientações sexuais e identidades de gênero. :)

Não consigo lembrar de mais coisas do que isso, então acho que tu foi ótima em pensar hahaha

**Comment by oieusouamiguel** [comment]
Inclusive, desculpe a demora para responder :)

**Comment by alinebastos** [comment]
Sim, baixa renda tem que ter! A dúvida que eu tenho, mas quero deixar isso certo antes de criar, é como classificar alguém como baixa renda, quais critérios usar pra isso.

Sobre o LGBTQIA+, obrigada, eu nunca sei o termo certo, hehe :D

**Comment by woliveiras** [comment]
Galera, essa issue não faz sentido visto que iremos criar uma plataforma que resolve esses problemas.

Vou fechar e qualquer coisa reabrimos.
