### ISSUE TITLE
Preciso de um mentor(a) para desenvolvimento web com PHP e JS

### ISSUE THREAD

**Issue by giovannicruz97** [training-center/mentoria#84]
# Giovanni Cruz

## Sobre mim
Cursando Análise e Desenvolvimento de Sistemas no Instituto Federal de São Paulo (IFSP). Desenvolvedor Back-End Jr na ACS Desenvolvimento e amante de códigos feitos por Jedis. Estudo PHP por conta própria e procurando aprender o "Javascript side of the Force"

## Conhecimentos
PHP (Padawan em CodeIgniter e Laravel)
HTML
CSS (100% Padawan haha)
Git (Padawan)
Shell (Padawan)
Linux (Ubuntu 16.04)
Vagrant

## Fale comigo!
[Facebook](https://www.facebook.com/giovanni.cruz.1485)
[Twitter](https://twitter.com/giovanni_cruz97)
[GitHub](https://github.com/giovannicruz97)
[LinkedIn](https://br.linkedin.com/in/giovanni-cruz-1011a6104)

## Observação
Já possuo Mentor/Mestre Jedi (@WendellAdriel) e só estou oficializando.

**Comment by WendellAdriel** [comment]
Mano @woliveiras, fale para nosso amigo @giovannicruz97 quais os próximos passos!!! :wink:

**Comment by woliveiras** [comment]
Que sucesso @giovannicruz97! Vai se dar bem com esse apoio. 😄 

Agora é só criar seu perfil de pupilo e subir o Pull Request, depois o @WendellAdriel atualiza o perfil dele e fica bonito.

**Comment by woliveiras** [comment]
Já podemos até fechar a issue, né?
