### ISSUE TITLE
Atualização de documento de responsabilidade dos mentores

### ISSUE THREAD

**Issue by wilcorrea** [training-center/mentoria#850]
Oi pessoal, gostaria de saber como podemos atualizar o [documento que discrimina](https://github.com/training-center/mentoria/blob/master/profiles/mentors/responsibility.md) as responsabilidades de um mentor seguindo os passos descritos no [documento que descreve os passos para ser um mentor](https://github.com/training-center/mentoria#quero-ser-mentora).

Atualmente parece que os dois estão desencontrados :smile:

**Comment by woliveiras** [comment]
Já foi corrigido, né @wilcorrea?

**Comment by wilcorrea** [comment]
Não muito bem @woliveiras carecia de dar uma revisada melhor nos documentos sobre o papel do mentor e o processo de mentorar.

**Comment by woliveiras** [comment]
Fala, @wilcorrea 

Como vamos melhorar tudo com a plataforma, acho que essa issue já não faz mais sentido.

O que acha?

**Comment by wilcorrea** [comment]
Concordo @woliveiras, por falar nisso como que está o andamento da plataforma? Como que faz para participar?

**Comment by woliveiras** [comment]
Opa! Está voltando a rodar, mano: https://github.com/training-center/plataforma

:raised_hands:

**Comment by woliveiras** [comment]
Opa! Está voltando a rodar, mano: https://github.com/training-center/plataforma

:raised_hands:
