### ISSUE TITLE
Canecas personalizadas do Training Center

### ISSUE THREAD

**Issue by giovannicruz97** [training-center/mentoria#859]
E ai amigos, beleza?
Durante uma conversa no canal #pastelcast no nosso Slack junto ao @woliveiras, surgiu a ideia de criarmos canecas para tomarmos nossos cafés produtores de código. O que vocês acham? É uma boa ideia? Precisamos cotar preços e definir como será feito, caso desejem. Deixe sua opinião e sua ideias, todo apoio é bem vindo! 🐛

**Comment by khaosdoctor** [comment]
A galera pode dar umas ideias de design aqui

**Comment by giovannicruz97** [comment]
@khaosdoctor Boa! Eu tava pensando em um modelo em preto com a logo do TC, mas o modelo branco tbm pode dar um destaque legal

**Comment by alinebastos** [comment]
Tem que ver em que pé estava o papo do @adeonir com o pessoal do Eu Compraria, pois pensamos deles produzirem nossas camisetas, adesivos, etc, e vender junto com os produtos deles, aí ficaria mais fácil de todos adquirirem. Aí já colocamos as canecas junto. O que acham?

**Comment by giovannicruz97** [comment]
@alinebastos Isso é vdd. Se a gnt centralizasse isso em um serviço só seria mais fácil. Vamos checar isso com o @woliveiras

**Comment by woliveiras** [comment]
Acho ótimo!

Já conversamos sobre isso uma vez e a nossa intenção nem é arrecadar dinheiro com isso, mas levar o Training Center pra todo lado.

Vou chamar o Guilherme pra essa conversa aqui.

**Comment by adeonir** [comment]
Opa.

O Guilherme me passou que poderia fazer os adesivos sem problemas, mas no caso de camisetas e canecas, temos que definir uma quantidade por causa dos custos de produção.

**Comment by khaueviana** [comment]
Sensacional!!!!

**Comment by lflimeira** [comment]
Pessoal, acho que antes de continuar com essas ideias (que são muito boas) temos que finalizar o processo de reestruturação do nosso logo e mascotes, resumindo da marca TC. Pois se lançar adesivos, canecas, camisetas e outras coisas, vamos divulgar um logo que já está "ultrapassado" por nós mesmos. O que acham @adeonir @woliveiras @khaosdoctor @alinebastos?

**Comment by woliveiras** [comment]
Siiiim, @lflimeira 

O @adeonir está a frente do time de design e estão fazendo tudo lá

Vou ver se não conseguimos um esquema de comunicação melhor pra gente ficar sabendo de tudo o que está rolando

**Comment by lflimeira** [comment]
Sim, estou ciente, o que eu quis dizer, é que para dar continuidade com essas ideias, é melhor finalizar as questões da identidade do TC antes :smile:

**Comment by khaosdoctor** [comment]
Concordo com o @lflimeira

**Comment by woliveiras** [comment]
Aaaaa, saquei, meu rei!

Então se liguem nessa! 

https://github.com/training-center/brand-guide/pull/2

**Comment by woliveiras** [comment]
Galera, vou fechar essa issue por que vamos tratar isso em outra hora.

Por hora vamos focar na criação da plataforma do Mentoria.
