### ISSUE TITLE
Definir Mudanças de regras do Mentoria

### ISSUE THREAD

**Issue by woliveiras** [training-center/mentoria#888]
Estou abrindo esta issue para discutirmos sobre uma possível mudança de regras no esquema de mentoria para melhoria de nossos processos.

A algum tempo atrás já havíamos discutido as falhas nos processos do Mentoria e por isso mudamos o nosso formato. Novamente estamos identificando algumas falhas que devem ser solucionadas.

Essa discussão surgiu no Slack e estamos trazendo para cá para guardar histórico e manter públicas as nossas decisões e problemas no projeto.

## Problemas

Conforme o tempo foi se passando percebemos que o formato do mentoria não está sendo muito efetivo.

**1. Tempo de mentoria**

Muitas vezes seguramos por muito tempo alguma pessoa que já está com seu "plano de carreira" ou "plano de estudos" montado e agora seria somente seguir e tirar dúvidas exporádicas no nosso Slack (e agora em nosso [fórum](https://github.com/training-center/forum/)).

**2. Falta de foco na nossa proposta**

Também identificamos por diversas vezes que não estamos de fato sendo mentores e mentoras, mas professores e professoras particulares.

Algumas de nossas responsabilidades seriam:

- ajudar as pessoas a entenderem nossas áreas de atuação e dizer como se prepararem para trabalhar com ela
- ajudar as pessoas a entenderem o que é programação e dizer como elas aprenderem a programar
- ajudar as pessoas a entenderem as mais diversas áreas de atuação em desenvolvimento de software e dizer como se prepararem para as áreas

Essa ajuda não é especificamente dar aulas para as pessoas, mas conselhos e dicas para não caírem em algumas armadilhas que já caímos. Específicamente se tratando de carreira ou como aprender algo.

A falta de foco no processo pode ser devido a nossa má documentação [do mesmo](https://github.com/training-center/mentoria#o-que-%C3%A9-uma-mentora).

**3. Sobre as dúvidas que respondemos**

Deveríamos ajudar com coisas como:

- como é trabalhar em x?
- como eu faço para entrar na área x?
- o que eu preciso aprender agora se já sei x, y, z?

Mas, pelo contrário, estamos tirando dúvidas de como melhorar código x, sendo que deveríamos indicar para a pessoa que use o [code-review](https://github.com/training-center/code-review/) para tal ou, literalmente, dando aulas.

**4. Processos**

Fora o problema de falta de foco no nosso formato, temos o problema da falta de rigidez em seguirmos os processos.

Como temos o trabalho de ajudar pessoas, muitas vezes agimos de "coração mole" e ficamos durante meses tentando marcar contato com uma pessoa que não está tão comprometida a se ajudar a aprender. O que deixa a fila de espera imensa.

**Comment by woliveiras** [comment]
Nesta issue já discutimos alguns formatos de rotação: https://github.com/training-center/mentoria/issues/818

**Comment by woliveiras** [comment]
Nesta issue já discutimos sobre o que faz uma pessoa que está mentorando: https://github.com/training-center/mentoria/issues/802

**Comment by khaosdoctor** [comment]
Eu vou mais além, em uma mudança mais radical ainda, mas eu acho que devemos mandar e-mails (ou qualquer outro tipo de comunicação) para todos os mentorad@s cadastrados no mentoria e todos os mentores(as) também cadastrados.

Para os mentorad@s perguntamos quem é o mentor del@ se o mentorad@ demorar mais do que 7 dias para responder o e-mail el@ é automaticamente removi@ da lista da mentoria e terá de fazer o cadastro novamente se desejar continuar. Assim podemos filtrar quem está querendo ainda e quem não está. Eu sei que é uma base muito grande de gente mas precisamos manter o controle de todos que estão ou não cadastrados, porque se não damos prioridade pra alguém que na verdade não quer mais ou deixamos as pessoas cairem no "limbo".

Para os mentores(as) perguntamos quais são seus mentorad@s e se eles(as) entraram em contato recentemente. Este é um ponto para removermos também quem não quer mais, porque com essas duas informações podemos cruzar ambos os dados e saber claramente quem está mentorando quem e quem está sendo mentorado por quem para saber como está nosso "mapa de mentoria" (até seria bem legal a gente fazer um desenho pra mostrar pro pessoal depois como é grande).

Também perguntaremos ao mentor(a) se ele deseja continuar na mentoria ou se deseja dar um tempo, no caso de sair, todos terão de fazer o processo novamente como se fossem novos mentores(as).

Assim podemos fazer uma task force só para limpar o repositório e saber quem está ou não de fato dentro do mesmo.

**Comment by lbighetti** [comment]
Muito bom! @woliveiras 

+1 pra idéia do @khaosdoctor pra dar essa limpa de ambos os lados e termos uma visão real das pessoas interessadas, tanto mentorados como mentores.

**Comment by woliveiras** [comment]
@khaosdoctor, não escreva assim `mentorad@s`, meu rei... Atrapalha leitores de tela.

Achei a ideia muito boa!

Assim vamos além do além, mano! Vamos **ao infinito e além**!

AHIAIHAIAHIHAI

## Emails

A parte de entrar em contato com quem solicitou mentoria nos últimos meses é muito fácil, visto que usamos o TypeForm e e nele temos todos os emails. :) 

De mentores(as) eu possuo uma planilha com todos os contatos também.

Então seu plano é show de bola, cara!!!

## Um adendo

Só essa parte que não achei legal:

> Também perguntaremos ao mentor(a) se ele deseja continuar na mentoria ou se deseja dar um tempo, no caso de sair, todos terão de fazer o processo novamente como se fossem novos mentores(as).

Pois o que fazemos hoje é: se a pessoa não consegue mais mentorar, simplesmente para de pegar gente para ajudar, pois o perfil dela no repositório não influi em nada, visto que é só para mostrar quem pode entrar em contato com futuros(as) mentorados(as).

Quando a pessoa "dá um tempo", ela pode voltar depois só olhando o board e entrando em contato com a galera dos cards.

## Uma dúvida

Fora isso tudo que você indicou, precisamos revisar o formato. De nada vai adiantar removermos pessoas inativas, limpar a fila, e depois a fila voltar por que nosso formato não está mudando.

A sua proposta seria fazer essa "limpeza" + a reformulação?

**Comment by khaueviana** [comment]
Sobre o ponto: **3. Sobre as dúvidas que respondemos**

Um plano de estudos ajuda?

**Comment by lbighetti** [comment]
@woliveiras pra mim sim, tem que ter "limpeza" como solução curto prazo, mas tem que ter reformulação como solução longo prazo.

O ponto central pra mim aqui pra gente acertar são esses:

* Precisa existir um nível mínimo de comprometimento tanto do lado do mentor como do mentorado.
* Um processo para avaliar e enforçar o ponto acima.

E pra mim é problemático **tanto mentorados que perderam o interesse quanto mentores**. Concordam ?

## Idéias

1. __Formatos de tempo para rotação__

Como o @woliveiras falou, discutidos no #818, ter períodos pré-definidos de mentoria para haver uma rotação maior de mentorados.

 Aqui vale também enforçar os tempos, por exemplo temos uma regra atualmente que sem contato por 2 semanas a mentoria é terminada (que inclusive eu não conhecia e não apliquei nos meus mentorados 😛 , e já fica de exemplo de algo que posso melhorar)

2. __Capacidade de cada Mentor__

Por exemplo, `Leandro, mentorados 4 de 6, áreas: Elixir, Java, Backend, trabalho no exterior.`
Claro, quem define a capacidade é o próprio mentor, e pode alterar quando quiser.
O ponto é ter uma.

3. __Capacidade mínima = 1__

Pra mim não faz sentido ter mentor sem mentorado. Se a pessoa não tem disponibilidade para se comprometer a nem 1 mentorado, acredito que consiga ajudar mais em outros projetos do CT que são mais assíncronos. 

4. __Lista mestre de todos os mentores e mentorados__

Para visualizarmos o status atual das coisas e os mentores conseguirem ajudar uns aos outros.

5. __Admins do Board do Mentoria / Facilitadores__

Uma idéia, se fizermos os pontos acima, é ter pessoas que focam em processar o board e tentar facilitar o processo entre mentorados e mentores.
Especialmente com a capacidade, um facilitador pode olhar o board, por exemplo ver uma pessoa pedindo mentoria em Elixir e ver que eu estou disponível.
Isso diminuiria a barra de entrada pra mentores também.

**Comment by khaosdoctor** [comment]
> A sua proposta seria fazer essa "limpeza" + a reformulação?

Sim sim, que nem eu disse ali, precisamos da limpeza pra tirar o que não podemos controlar e depois reformular quem quer ficar:

> Assim podemos fazer uma task force só para limpar o repositório e saber quem está ou não de fato dentro do mesmo, **só depois de ter essa noção, podemos aplicar as regras que você propôs**, porque ai vamos de fato estar falando com todos que realmente querem participar.

Sobre a parte de ter o perfil do mentor mesmo que ele não esteja mentorando, eu acho ruim, podemos manter o perfil dele, mas ai imagina que vamos ter uma lista de 60 mentores, pra gente esses 60 caras são totalmente ativos, mas na verdade temos 20 mentores porque os outros 40 não estão ativos. Então é uma forma de a gente manter realmente só quem está ativo na plataforma, se não a gente remove o perfil e pede para criar outra PR (mais por meio de controle).

-----

Sobre os tópicos do @lbighetti acho que casa bastante com o que eu falei nesse último parágrafo. Temos que ter mentores com perfis cadastrados somente se eles já tiverem um mentorado, então vamos supor, a pessoa quer entrar como mentor(a), ela é totalmente nova, não tem nenhum mentorado ainda, ela abre a PR a gente ve o perfil e aprova (igual o que a gente faz hoje), mas antes de incluir de fato o perfil ela precisa procurar alguém para dar a mentoria, ai com essa pessoa já tendo um mentorado podemos incluir o perfil dela.

Concordo muito sobre a lista mestre e o board, acho que até podemos criar uma espécie de grafo para ligar os mentores aos mentorados e ter uma noção boa do que acontece.

**Comment by woliveiras** [comment]
@khaueviana tanto um grupo de estudos quanto o forum ajudam muuuuuito. :D

Por isso estamos incentivando pessoas que entram em contato buscando algo muito específico a criarem grupos de estudos.

Por exemplo: busco mentoria para aprender Reactjs.

Incentivamos que crie um grupo de estudos, pois é muito mais específico para x ou y e ainda ajuda outras pessoas com o mesmo objetivo.

Quando é algo direto também, como: quero saber como arrumar emprego sem ter portfólio, então é ideal que a pessoa abra a pergunta no forum. :)

**Comment by woliveiras** [comment]
@lbighetti sobre o `Capacidade de cada Mentor`

Se o mentor deseja ensinar somente uma tecnologia, então é melhor que ele crie um grupo de estudos ou então escreva posts, crie vídeo aulas pra gente.

A ideia de ser mentor é identificar falhas no processo de aprendizagem da pessoa e ajudar ela. Então não deveria influenciar se é python ou ruby, por exemplo.

Imagina se eu fosse mentor de React, ajudaria um monte de pessoas de SP, mas e o restante do país?

Se nos focarmos em uma tecnologia, então limitamos o número de pessoas que podemos ajudar em regiões que usam essas tecnologias, sendo que poderíamos só ser mentores de backend, frontend ou mobile, por exemplo, e poder ajudar a pessoa a escolher a tecnologia.

Lembrando que o objetivo aqui não é e nem deve ser ensinar uma tecnologia, isso se faz no grupo de estudos ou nos outros canais que falei agora também.

Agora se a capacidade que você falou for quantidade de mentorados por mentor, então já existe esse "limite":

> Cada mentor(a) deverá ajudar entre 1 até, no máximo, 10 pessoas, dependendo de sua disponibilidade, disposição, etc.

https://github.com/training-center/mentoria#quero-ser-mentora

---

Talvez isso aqui, que você disse, seja o que me convence de que, se a pessoa não está mentorando, não faz sentido estar na lista, como o @khaosdoctor está falando:

> Capacidade mínima = 1
>  acredito que consiga ajudar mais em outros projetos do CT que são mais assíncronos.

Concordo 100%!

---

Não entendi esse ponto: `Lista mestre de todos os mentores e mentorados`

---

Isso aqui seria muito louco!

> Admins do Board do Mentoria / Facilitadores

Mas com a entrada da plataforma, isso faz sentido?

**Comment by woliveiras** [comment]
Só estou com uma dúvida em relação a isso da lista de mentores:

Se a pessoa mentora por um mês e depois não pega mais mentorados, ela deve ser "expulsa" da org, do canal privado do Slack e coisas afins?

Eu acho que não... Ela pode continuar ali dando opinião para melhorias, que é mais async também, e depois é só atualizar o perfil e voltar a pegar mentorados.

Só que estou achando que estamos pensando muito no fluxo atual de mentoria ao invés de imaginar o uso da plataforma ao invés de focar em `1. Tempo de mentoria`, `2. Falta de foco na nossa proposta`, `3. Sobre as dúvidas que respondemos` e `4. Processos` conforme foi descrito na issue.

**Comment by khaosdoctor** [comment]
> Eu acho que não... Ela pode continuar ali dando opinião para melhorias, que é mais async também, e depois é só atualizar o perfil e voltar a pegar mentorados.

Acho que não também, eles podem ficar no canal, mas terão de sair da lista de mentores do site.

> Só que estou achando que estamos pensando muito no fluxo atual de mentoria ao invés de imaginar o uso da plataforma ao invés de focar em 1. Tempo de mentoria, 2. Falta de foco na nossa proposta, 3. Sobre as dúvidas que respondemos e 4. Processos conforme foi descrito na issue.

O problema aqui é que precisamos da plataforma pra saber como vai funcionar o fluxo, mas precisamos do fluxo pra saber como vai funcionar a plataforma

**Comment by lbighetti** [comment]
@woliveiras @khaosdoctor 

Bons pontos !!
Acho que estamos caminhando pras soluções. 

Eu acho que devíamos prosseguir como a "limpeza" a curto prazo, e a longo prazo, segue algumas propostas pros pontos apresentados no issue original, baseado no que discutimos até agora.

---

### `1. Tempo de mentoria`

* __Enforçar um tempo de rotação de mentoria (por exemplo 1, 2 ou 3 meses)__
* __Enforçar a regra de finalizar a mentoria quando o mentorado não responde por dias/não está interessado__

_Nota: sim isso já existe, mas quase não aplicamos_

### `2. Falta de Foco da Proposta`

* __Reduzir drasticamente as opções de Mentoria para: Backend e Frontend__

Talvez Fullstack e Mobile também? me digam o que acham. Mas o ponto principal é remover todas as tecnologias específicas principalmente, e categorias que menores.

O ideal pra mim é na hora da pessoa se inscrever só existir apenas 2-4 opções. E ai os mentores também se inscrevem para apenas essas opções e fica mais fácil de controlar e acelerar o fluxo.

* __Mentores listados são apenas os ativos, ou seja,  pelo menos 1 mentorado__

Não acho que deveríamos tirar do slack também não, mas eu acho sim que atrapalha como o @khaosdoctor falou ter mentores listados que não tem nenhum mentorado, faz o controle das coisas ficar mais difícil e confusa. 

### `3. Sobre as dúvidas que respondemos`

* __Indicar outros projetos para perguntas que não caibam na mentoria__

Com esse foco maior da mentoria em direção geral da carreira, e perguntas de aprendizado, vamos passar a mensagem de que devemos indicar o `code-review`, iniciar grupos de estudos ou até o slack para perguntas específicas de tecnologias ou frameworks ou resolução de problemas específicos.

### `4. Processos`

* __Mentor deixar explícito qual a capacidade total e qual a atualmente utilizada, e em qual áreas__

Por exemplo: `Leandro, 4 de 7 mentorados, Backend`
Eu sei que temos de 1 a 10 mas não é explícito, só o próprio mentor sabe qual é esse número. Com esses números ficará mais fácil os pontos abaixo:

* __Lista mestre de Mentores/Mentorados__

Com esse foco da mentoria em poucas categorias, vai ser muito mais fácil enxergar o fluxo de mentorados se tivermos uma lista com todo mundo relacionado e capacidades possíveis de cada mentor e área.

* __Facilitadores / Admin do Board (e futuramente da plataforma)__

Eu acho bem "helpful" ter uma ou várias pessoas nessa função facilitando o fluxo de mentorados inscritos inicialmente e o mentor. Isso vai ser mais fácil de implementar se tivermos as poucas categorias bem definidas.

Sobre o ponto da `plataforma`, eu acho que podemos aplicar o mesmo conceito lá. E pode existir admins/facilitadores lá fazendo a mesma função de "match" de mentorado com mentor.

**Comment by alinebastos** [comment]
Eu acho ótimo diminuir pra somente front, back (talvez mobile, fullstack e devops, algo assim). 

Não dar opções pra pessoa colocar React, Angular, etc. Como disse o Leandro, tem opções de grupos de estudos, tirar dúvidas no slack, e tem o code-review. O mentorado tem que ter mentoria sobre a base mesmo, depois fica mais fácil aprender um framework.

Deixando claro que também temos o fórum para início de carreira acho que diminuiria mais a quantidade de pessoas que não tem ideia de onde começar.

**Comment by lbighetti** [comment]
Vamos começar nesse passo inicial de diminuir as categorias que parece fazer sentido pra todo mundo o que acham ?

Eu me voluntario para começar mudando o trello, deixando só as categorias: `Backend`, `Frontend`, `DevOps`, `UX/UI`, `Mobile`, `Fullstack`

Da um like para votar nesse comment @woliveiras @alinebastos @khaosdoctor @khaueviana e quem mais estiver lendo! 👍 

O que acham ?

**Comment by alinebastos** [comment]
Acho que essas categorias cobrem bem tudo :)
Se quiser ajuda no Trello me avisa!

**Comment by hdamaich** [comment]
@lbighetti Como vamos fazer para as requisições especificas que temos hoje no trello?

**Comment by lbighetti** [comment]
@hdamaich diria para vermos caso a caso. A princípio eu diria pra tentarmos encaixar nessas categorias. Se é por exemplo PHP, nodejs backend, Python, C#, Java, Elixir, Scala, Clojure => vira Backend. Se é React, Angular, Vue, vira Frontend. Android ou IOs, Mobile.
E assim por diante.

Os que não se encaixarem podemos discutir individualmente no slack ou aqui, e talvez contatar o mentorado e rever qual caberia melhor!

o que acha ?

**Comment by hdamaich** [comment]
Parece bom, estava pensando no caso que o mentorado já fosse bala em Front-End, mas querendo aprender apenas React, mas acho que nesses casos quando mentor entrar em contato pela primeira vez o mentor da o direcionamento mais adequado, como um study-group.

O que acha?

**Comment by lbighetti** [comment]
@hdamaich isso ai, acho top! Encaminhar pra fazer um grupo de estudos sobre, ou se for código pronto pro code review.

Se o mentor tiver realmente animado pra ensinar uma coisa, pode fazer uma live sobre o assunto e/ou criar um grupo de estudos junto com a pesoa.
Ai conseguimos atingir mais pessoas com o ensinamento, e mantemos o foco da mentoria mais em carreira mesmo, plano de estudo, progressão de objetivos e tal.

**Comment by woliveiras** [comment]
> Parece bom, estava pensando no caso que o mentorado já fosse bala em Front-End, mas querendo aprender apenas React, mas acho que nesses casos quando mentor entrar em contato pela primeira vez o mentor da o direcionamento mais adequado, como um study-group.

Exato, meu rei! 

É isso ai galera!

**Comment by woliveiras** [comment]
> Se o mentor tiver realmente animado pra ensinar uma coisa, pode fazer uma live sobre o assunto e/ou criar um grupo de estudos junto com a pesoa.

Booooa, também!

**Comment by woliveiras** [comment]
Seria legal criar uma issue aqui avisando que vai fazer essa alteração no Trello, @lbighetti 

Botar um checklist e tudo mais também.

Depois é ideal juntar na lista de mentores(as) que existe hoje também.

**Comment by lbighetti** [comment]
>Seria legal criar uma issue aqui avisando que vai fazer essa alteração no Trello, @lbighetti
>Botar um checklist e tudo mais também.
>Depois é ideal juntar na lista de mentores(as) que existe hoje também.

toppersss mestre!! farei!

**Comment by abap-pacheco** [comment]
> A princípio eu diria pra tentarmos encaixar nessas categorias. Se é por exemplo PHP, nodejs backend, Python, C#, Java, Elixir, Scala, Clojure => vira Backend. Se é React, Angular, Vue, vira Frontend. Android ou IOs, Mobile.

Acho bem legal separar assim, mas, aonde se encaixaria o grupo de fullstack?

**Comment by woliveiras** [comment]
Bem lembrado, @abap-pacheco!

Fora os que já falamos, tem o full-stack, @lbighetti

**Comment by lbighetti** [comment]
Boa! @abap-pacheco @woliveiras 

Então, temos:
`Backend`, `Frontend`, `DevOps`, `UX/UI`, `Mobile`, `Fullstack`

@abap-pacheco então ai teria que ver os atuais caso a caso, mas por exemplo se a pessoa coloca que precisa de mentoria em Java e Javascript, ou em Ruby e JS/Angular, PHP e React, seria apropriado  mudar pra fullstack. Faz sentido ?

Vou começar a mudar no Trello!

**Comment by woliveiras** [comment]
Se a pessoa precisa de mentoria para aprender front && back, então é full-stackerzeira mesmo, mano

**Comment by rodolfomendes** [comment]
Sobre as categorias: eu vi alguns cartões pedindo mentoria para data science também. Acho que vale a pena ter uma categoria separada.

**Comment by lbighetti** [comment]
@khaosdoctor Bom ponto. E normalmente a pessoa começa em Backend ou Frontend e depois aprende as coisas pra completar e virar Fullstack.

Então talvez se a pessoa é Front-end por exemplo e quer virar fullstack faz sentido ter uma mentoria Back-end ?

**Comment by khaosdoctor** [comment]
@lbighetti Acho que faz sentido, tipo, a pessoa ter uma necessidade por uma mentoria fullstack faz sentido, porque as vezes a pessoa precisa aprender um pouco de cada coisa ou então está já na área e precisa de umas dicas. Mas não faz sentido o mentor ser fullstack... Acho que ele precisa estar repetido mesmo

**Comment by woliveiras** [comment]
Galera, como vamos focar na criação da plataforma, essa issue será fechada para prosseguirmos por lá. 

Coletamos diversas ideias muito boas! 

Valeu por participarem da discussão. \o/ <3
