### ISSUE TITLE
Implementar Mudanças no Mentoria

### ISSUE THREAD

**Issue by lbighetti** [training-center/mentoria#894]
Pessoal, conforme discutido no #888, vamos implementar as seguintes mudanças:

- [ ] **Reduzir as opções do Mentoria para:** `Backend`, `Frontend`, `DevOps`, `UX/UI`, `Mobile`, `Fullstack`
  - [x] Comunicar Mentores das mudanças e recomendações
  - [ ] Fazer mudanças no Trello (~70%)
  - [ ] Mudar na lista de Mentores Github
- [ ] **Revisar Mentores ativos** (Ativo = pelo menos 1 mentorado)
- [ ] **Lista mestre de Mentores/Mentorados**

---

Conforme vamos definindo os próximos passos vou colocando na lista.

**Comment by hdamaich** [comment]
Antes de mudar a lista de mentores não deveriamos mandar email para eles e verificar quem ainda está ativo no projeto?

**Comment by lbighetti** [comment]
@hdamaich boa mano, vou colocar na verdade outro item pra isso!

**Comment by woliveiras** [comment]
@lbighetti tenho a lista dos emails aqui

Posso te mandar por Slack

**Comment by lbighetti** [comment]
@woliveiras Toppers! claro, manda! ❤️

**Comment by woliveiras** [comment]
Galera, visto que vamos congelar o Mentoria para focar na plataforma (https://github.com/training-center/mentoria/issues/903), podemos fechar essa issue aqui, certo?
