### ISSUE TITLE
Dúvidas sobre temas para solicitar mentoria ou ser mentor

### ISSUE THREAD

**Issue by ftonato** [training-center/mentoria#90]
Fala galera, beleza?

Tenho acompanhado o projeto conforme disponilidade, e estava esperando alguém abrir alguma _issue_ com os conteúdos de meu interesse, como não aconteceu, resolvi abrir essa _issue_ :)

No [template de issue](https://github.com/training-center/mentoria/blob/master/issue_template.md) temos o seguinte trecho:

> Coloque no título da issue algo como: Preciso de um(a) mentor(a) de **X**.
> Onde X pode ser a área de atuação ou ferramenta, **etc**.

A minha dúvida é o que se enquadra em **ETC**, pois eu por exemplo tenho dúvidas sobre Testes de Softwares e Inglês e queria de fato ajuda (um mentor sobre tais conteúdos), mas como percebi que até então as solicitações tem sido sobre linguagens, fiquei na dúvida se seria possível tal mentoria... 

Acredito que seria uma opção válida, visto que é algo bastante importante na nossa área e ajuda a moldar a carreira de todo bom profissional!

Abraço

**Comment by jessuircleydson** [comment]
Opa @ftonato blz man?
Então, você pode abrir sim, só no momento não temos mentores especificamente para inglês e testes de softwares[não oficialmente pelo menos srsr], mas uma das coisas que fazemos é procurar mentores para quem ainda não tem. Inclusive temos uma mentora de SEO que foge desse padrão de apenas linguagens :D
Pode abrir a issue que assim que aparecer alguém você ficará sabendo /o/

**Comment by ftonato** [comment]
Tranquilo fera :)

Pois é, assim que eu abri a issue eu vi que tinha uma que era fora do padrão (a que falava sobre SEO), mas beleza vou abrir a issue!

Grato pela atenção @jessuircleydson

**Comment by woliveiras** [comment]
É isso ai @ftonato 

Valeu pela ajuda também.

Se tiver Mentor, tentamos ajudar em qualquer coisa. :raised_hands:

**Comment by ftonato** [comment]
Legal fera @woliveiras!

Estive pensando aqui, não julgas que seria legal se essa minha dúvida fosse de certa forma explicada no README do projeto?

Pois assim aqueles que o lerem, já saberão que podem fazer perguntas sobre Front/Back/Ferramenta/[Linguagens de programação, Línguas], ...
Enfim detalhar melhor sobre algumas opções de mentorias, mas deixar claro que se existir a dúvida sobre o quão válido/interessante algum assunto é que seja criado uma issue para tratar de tal...

Fica minha humilde opinião :)

Abraço

**Comment by woliveiras** [comment]
Ficaria legal se colocarmos uma sessão `Em que um Mentor pode te ajudar?` e listar lá as tecnologias mais comuns e colocar que pode ser solicitado mentoria de algo não listado?

Depois colocamos um alerta de: caso ainda possua alguma dúvida sobre o projeto você pode abrir uma issue e vamos te ajudar.

Que tal?

**Comment by ftonato** [comment]
@woliveiras isso aí!
Legal a idéia, creio que será bastante útil :dancer:
