### ISSUE TITLE
Proposta de novo formato para o Mentoria

### ISSUE THREAD

**Issue by woliveiras** [training-center/mentoria#903]
Olá pessoal!

Conforme o tempo está passando, o formato do Mentoria está parecendo ser inviável (pouco escalável) no formato aberto como fazemos. 

São muitos processos que precisamos implementar e muito feedback necessário por parte de mentores(as) e mentorados(as).

A criação de uma plataforma para o Mentoria pode ser uma solução para o problema do primeiro contato com GitHub por parte de mentorados(as), porém o problema de uma fila de espera e outros processos podem não ser solucionados com isso.

## Problemas

Os problemas que acho que não serão solucionados com a plataforma:

- pessoas não atualizam seus perfis
- pessoas somem e não nos dão retorno
- pessoas somem e não dão retorno para seus pares (mentores(as) e mentorados(as))
- pessoas adicionam seus perfis como mentores(as) e somem
- falta de feedback das pessoas envolvidas nas mentorias

Não sei se esses problemas serão resolvidos com automação. :disappointed: 

## Proposta

Pensei em mudarmos o formato do Mentoria para algo direto no nosso Slack onde:

1. a pessoa entra no Slack e pode fazer suas perguntas sobre carreira direto nos canais específicos (mentoria-frontend, mentoria-backend, mentoria-devops, talvez) e qualquer pessoa poderia ajudar, mesmo não sendo diretamente mentores
1. teríamos uma lista de pessoas que aceitam receber mensagem direta no Slack com questões de mentoria (essas pessoas seriam nossos mentores e mentoras)
1. o único processo seria ter uma lista de mentores(as) que aceitam receber contato via DM no Slack, nada mais
1. a lista seria unicamente com campos de atuação e não com tecnologias específicas (frontend, não React, backend, não Django)

Pensando no primeiro tópico, isso até aumentaria as discussões produtivas a respeito de carreira dentro do nosso Slack.

---

O que vocês acham?

**Comment by DWoonD** [comment]
Acho a ideia válida pois você meio que "mata" a fila de espera pois vai ter vários mentores atendendo vários mentorados ao invés de esperar eles encontrarem um par e começar a discutir a respeito.

Acho que futuramente poderiamos reunir alguns mentorados com grupos em comuns e criar algumas listas com o "básico" a ser seguido e deixar o canal para dúvidas mais específicas e dificuldades mais pontuais e também como uma forma de evitar repetição.

Meu  único problema com o slack é que no casa a empresa que trabalho atualmente bloqueia o mesmo, mas fora isso acho a ideia muito boa.

**Comment by Diego-Brocanelli** [comment]
@woliveiras acho a idéia boa, e quando alguém fizer uma pergunta tbm fosse produzido um post ou vídeo  para que possamos criar conteúdo  no CT?

**Comment by liviagabos** [comment]
Poderia dar uma sugestão de utilizar algum gerenciador de conteúdo como uma wikipedia para referenciar conteúdos? Quase um bookmark coletivo.
Com o tempo as pessoas sempre passam por algumas dúvidas ou conteúdos básicos e são passadas as mesmas referências. 
Eu acho que com um lugar para agregar as informações, acho que ficaria mais fácil. Pensando também que a dúvida de um, pode ser a de muitos. 
Isso ajudaria até a criar conteúdos como o @Diego-Brocanelli comentou.

Me desculpem a sugestão se vocês já tem isso. Porque eu só acompanho o trabalho de vocês como externo. ^^

**Comment by woliveiras** [comment]
@DWoonD,

> Acho que futuramente poderiamos reunir alguns mentorados com grupos em comuns e criar algumas listas com o "básico" a ser seguido e deixar o canal para dúvidas mais específicas e dificuldades mais pontuais e também como uma forma de evitar repetição.

Não da pra deixar no Slack por que não guardamos histórico. :joy:

Quando a dúvida for muito relevante para guardar, da pra seguir a ideia do @Diego-Brocanelli e fazer um post ou vídeo. :grin:

> @woliveiras acho a idéia boa, e quando alguém fizer uma pergunta tbm fosse produzido um post ou vídeo para que possamos criar conteúdo no CT?

**Comment by woliveiras** [comment]
@liviagabos, valeu demais pela participação.

> Poderia dar uma sugestão de utilizar algum gerenciador de conteúdo como uma wikipedia para referenciar conteúdos? Quase um bookmark coletivo.

Nós até já tentamos um esquema desse, mas como o grupo é muito dinâmico (acelerado) o conteúdo lá fica desatualizado por que esquecemos de mudar. :joy: 

Acho que o melhor caminho pra mover as coisas para fora do Slack seria o forum: https://github.com/training-center/forum

Ou o conteúdo gerado através de dúvidas das pessoas mesmo. :+1:

**Comment by woliveiras** [comment]
Mas fora essas ideias novas da externalização de conteúdo pra fora do Slack, vocês acham que o formato proposto está legal, galera?

@DWoonD @Diego-Brocanelli @liviagabos

**Comment by angeliski** [comment]
Eu gosto da ideia dos canais abertos, realmente evita o modelo de filas. Só levanto a observação que pode também gerar casos sem resposta (Cachorro com dois donos morre de fome).

A ideia do Direct é boa, MAS como iriamos evitar uma sobrecarga?
 Exemplo, suponha que eu tenha como mentor a _Fernanda Bernardo_ e o _Isaias Leite_. Eu num primeiro momento, ia enviar a mensagem para a _Fernanda_, porque eu já vi ela num evento e coisa e tal. Nesse ponto, as pessoas mais "conhecidas" podem ser sobrecarregadas o que também não é ideal.
Uma ideia para lidar com a sobrecarga seria um ponto único de entrada (um bot talvez?) onde o cara lança a pergunta, talvez usando tags, e um sistema define o próximo mentor da fila de respostas.

**Comment by mahenrique94** [comment]
Acho as idéias válidas, porem fazer tudo no Slack acredito que irá ficar complicado de lidar e controlar o que esta acontecendo, ainda acredito que uma plataforma seria o melhor caminho, com alguns controles de atividades(para saber quem esta participando) e emails(para notificar atualizações e tals) poderia ser uma solução, isso seria só o básico, deporia viria os relatórios, gráficos e por ai vai....

**Comment by jlamim** [comment]
As discussões são muito válidas, ideias fantásticas, mas juntando todas elas há uma fuga no que diz respeito a mentoria.

Quando falamos em mentoria, seja ela individual ou em grupo, estamos falando de um acompanhamento constante entre mentor e mentorado(s), com uma linha de desenvolvimento bem definida (início, meio e fim), com foco em um objetivo comum.

Se colocar de forma aberta no Slack, para que as pessoas possam ir comentando nos respectivos canais, o conceito de mentoria já se perdeu, e criou-se apenas um fórum dinâmico de dúvidas e respostas.

Mentoria é mais do que responder dúvidas. Em um programa de mentoria ajudamos o mentorado a trilhar o caminho mais eficiente rumo ao seu objetivo, compartilhando com ele nossos conhecimentos, usando ferramentas para que ele possa evoluir e acima de tudo, precisamos mensurar toda essa evolução.

Como o @angeliski disse, se o mentorado entra em um canal com vários mentores e cada um tem uma linha de pensamento, coitado do mentorado, vai ficar sem saber pra onde ir.

Sobre problemas de falta de feedback, mentores e mentorados desaparecem do nada, isso é extremamente normal quando se fala de voluntariado e serviços gratuitos.

Eu atendo alguns clientes de processo de coaching em programa "pro-bono", sem nenhum custo para eles, e o índice de desistência, falta de comprometimento e outras coisas é bem grande.

Sabendo que há fila de interessados em mentoria, mas sem saber exatamente quanto são os mentores, minha proposta é a seguinte:

- Mapear quem são os mentores que desejam realmente ajudar no programa de mentoria
- Pegar esses mentores interessados e fazer um programa de mentoria com eles para prepará-los para o processo (eu me disponho a ajudar nessa parte)
- Após preparar os mentores, mapear a fila de espera e dividir em grupos (mentoria-frontend, mentoria-backend, mentoria-devops...) 
- Com os grupos e mentores definidos, colocar um mentor responsável por cada grupo (podem haver vários grupos do memso tema)
- Feito isso, inicia-se o processo com um tempo determinado e enquanto isso uma nova fila de espera vai sendo formada e novos grupos organizados

Fazendo dessa forma todos os mentores e mentorados terão a chance de obter os melhores resultados, seguindo um modelo padrão do processo, o que facilitará a supervisão de todo esse trabalho para realmente verificar quais grupos estão engajados, comprometidos e quais mentores estão de fato levando o programa a sério.

Mentoria não é brincadeira, como mentores, estamos mostrando para os mentorados o melhor caminho a seguir com base em nossa experiência, e nesse caso, não é experiência em escrever código, mas construir uma carreira de sucesso, com resultados positivos, que é o que a maior parte dos mentorados almeja.

**Comment by lflimeira** [comment]
Eu acho a ideia bacana, mas eu vejo um problema, as pessoas já perguntam nos canais atuais, e criar um novo canal, vai ser mais um canal para as pessoas administrarem e mais informação distribuída que vai se perder no slack. A ideia de gerar conteúdo é boa, só que já possuímos algo do tipo, criar mais uma forma acho ruim, talvez possamos divulgar melhor o que já existe e mudar um pouco a dinâmica.

Já que trazer problemas sem solução n agrega em nada kkkkk aqui vai minha "soluçao". Eu criaria grupos de mentorados, para 1 ou no máximo 2 mentores pois dessa forma não perde aquele contato mais pessoal e dentro desses grupos rolaria a mentoria com foco em carreira, e dúvidas técnicas poderiam ser encaminhadas para criar conteúdo e/ou para o forum. Deu para entender ou eu fui confuso na explicação? 😅 se deu para entender, faz sentido?

**Comment by mblodorn** [comment]
Achei os pontos 1,2 e 3 válidos, porém não concordo com o 4º ponto. As áreas são muito complexas e quanto mais conseguirmos fracionar elas melhor. Ser identificado como programador front-end não diz nada sobre o desenvolvedor, ele pode entender só de css e js puro ou conhecer ecossistemas complexos como o do angular ou react.  

Minha sugestão para o quarto item é:

-> Identificar o mentor como front-end, back-end ou fullstack
-> Fornecer "insignias" para o mentor de determinadas tecnologias (angular, express, react) quando o mesmo completar desafios propostos pelo training center.

Dessa forma temos uma ludificação (a ideia das insignias vem do pokemon) e fornecemos aos mentores novos desafios para continuarem se capacitando enquanto ensinam.

**Comment by FelipeSGAndrade** [comment]
O meu maior problema como mentor (ou tentativa de mentor) é ir atrás de um mentorado pra ver se ele tem interesse, aí tem o problema da pessoa n estar engajada e eu ter que procurar outro e tudo o mais...

Eu curti a idéia do @angeliski sobre ter uma forma automatizada de ligar mentorados com mentores. No fim, se a cabeça dos dois não bater ou algum deles parar de responder, um dos dois poderia solicitar uma nova conexão que seria sorteada. Lógico que isso seguiria alguns critérios como área de atuação ou o q mais acharem necessário, mas esses critérios poderiam ser preenchidos como, por exemplo, uma razão para solicitar uma nova conexão.

Exemplo: Eu fui sorteado para mentorar uma pessoa e, no primeiro contato, essa pessoa me diz que quer algo voltado pra front-end, sendo que eu sou backend, por algum motivo o sistema ainda n tinha essa informação então eu, ou a pessoa, pode solicitar uma nova conexão com o motivo de que o mentorado quer front-end e essa informação já ficaria gravada no sistema, tipo um preenchimento dinâmico do perfil conforme os acontecimentos

**Comment by lasombra** [comment]
Eu concordo 101% com o @jlamim. Eu acho que devemos mater as coisas separadas e evitar o aumento de canais.

Eu faço parte de outra comunidade de mentoria, http://recworks.co.uk/meet-a-mentor, que a gente pode usar como modelo.

A pessoa que faz a escolha dos mentores oferece cerca de 3 ou 4 baseado no que o mentorado está procurando. Cada mentor e também mentorado tem um perfil, daí no Slack essa pessoa apresenta as escolhas de mentor para o mentorado, o mentorado escolhe o mentor que acha mais adequado, baseado na biografia, e a pessoa "introduz" os 2 lados.

Se vocês quiserem eu posso mostrar como a biografia é escrita no Slack.

**Comment by rgcavalcanti** [comment]
Talvez seria interessante, no caso de ser criada uma plataforma de acompanhamento, adicionar um sistema de metas no formato de um checklist. Assim seria possível ter um controle das atividades dos mentores e dos alunos. Por exemplo: um aluno diz que conseguiu alcançar uma meta X, então ele marcaria na lista, depois o mentor poderia verificar com ele se realmente o que foi planejado foi entendido direito e marcar aquela meta como completa.

Se só o aluno marcar as metas e o mentor não verificar, então o mentor estaria ausente. O mesmo ia valer para um aluno ausente que não corre atrás das suas metas.

Não sei se isso seria uma ideia interessante por não saber como é o lado de um mentor, mas deixo aqui minha sugestão.

**Comment by woliveiras** [comment]
Ponto muito foda, @jlamim!

Acho que isso aqui já invalida total a minha ideia dos canais específicos:

> Se colocar de forma aberta no Slack, para que as pessoas possam ir comentando nos respectivos canais, o conceito de mentoria já se perdeu, e criou-se apenas um fórum dinâmico de dúvidas e respostas.

Acho que a proposta do @jlamim já mata tudo o que precisamos e podemos fazer o processo de congelamento do mentoria, preparar os mentores que desejam continuar mentorando e começar o ano que vem de uma maneira mais organizada.

Depois deixamos um onboarding para novos mentores, onde: quando entrar uma pessoa nova, essa pessoa recebe "mentoria de como ser mentor". Pois o processo que fazemos hoje de deixar tudo nas mãos de quem entra está ruim por conta da pessoa se perder em um mundo de informações.

Enquanto isso acontece, em paralelo, rola o desenvolvimento da plataforma e ano que vem o bicho pega!

Vou abrir outra issue com essa proposta de melhoria e congelamento do mentoria até a criação da plataforma, o que vocês acham? - congelamento do mentoria seria para não chegar mais gente na fila de espera, não significa parar de ajudar quem já recebe ajuda, viu. :)

**Comment by woliveiras** [comment]
Galera, coletamos diversas informações e a issue já pode ser fechada.

Vamos congelar o Mentoria para organizar a casa e focar na plataforma.

Assim que tudo estiver OK, voltaremos com tudo!

**Comment by mahenrique94** [comment]
Boa, se precisar de ajuda com a plataforma, só falar
