### ISSUE TITLE
Preciso de um(a) mentor(a) em programação

### ISSUE THREAD

**Issue by SilvaAllan** [training-center/mentoria#919]
Meu nome é Allan 
Eu recentemente terminei a faculdade de ADS mas realmente vejo que meu conhecimento é pouco e não consigo ir pra frente, me sinto perdido sem saber qual o próximo passo é não tenho ninguém pra me guiar. Única certeza é que quero ser bom em Java por enquanto mas claro que existem outras exigências que empresas pedem e não consegui se quer um estágio ainda por falta de conhecimento. Por favor me ajudem, eu quero saber programar de verdade *_*
Contatos 
allanmaximo73@gmail.com
Obrigado pessoal

**Comment by khaosdoctor** [comment]
Opa @SilvaAllan tudo bem? Você já está no nosso Slack? Dá uma passada lá e me chama por favor (meu nick é lhs.santoss) para eu poder te explicar melhor como o mentoria está funcionando :)

Vou fechar essa issue ok?
