### ISSUE TITLE
Preciso de um(a) mentor(a) de Inglês

### ISSUE THREAD

**Issue by ftonato** [training-center/mentoria#92]
**Nome:** Ademílson F. Tonato

**Descrição:** Tenho estudado inglês por conta própria a praticamente dois meses, todavia tenho certas dificuldades em mensurar meu nível de evolução durante o período, gostaria da ajuda de vocês para entender se aquilo que procuro estudar é algo útil e/ou se tens algumas outras recomendações.
Atualmente tenho várias técnicas de estudo (que prefiro compartilhar com o mentor em si), mas posso dizer que material para estudo já tenho só falta saber o quão relevante/importante eles são e conseguir mensurar se eles me ajudarão da forma que desejo...

**Nível de conhecimento atual:** Básico

**Contatos:**
- [Twitter](https://twitter.com/ftonato)
- [Telegram](https://web.telegram.org/#/im?p=@ftonato)
- Skype/Hangouts: ademilsonft
- E-mail: ademilsonft@outlook.com

Abraços

**Comment by woliveiras** [comment]
Show de bola @ftonato 

Vamos ver se já temos alguém pra ajudar nos @training-center/mentors 

Se quiser, pode compartilhar seu esquema de estudo com essa galera: https://github.com/training-center/study-groups

No Slack. :smile:

**Comment by woliveiras** [comment]
Alguém consegue ajudar essa alma?

cc: @training-center/mentors

**Comment by woliveiras** [comment]
Algum dos novos @training-center/mentors consegue ajudar esse jovem?

**Comment by cantoniazzi** [comment]
Me interesso nesse tipo de ajuda também :+1:

**Comment by woliveiras** [comment]
Acho que agora tem uns novos @training-center/mentors que podem ajudar vocês, ein. :smile:

**Comment by ftonato** [comment]
@woliveiras <3 UHULLL
Como procedemos agora? @cantoniazzi?

**Comment by woliveiras** [comment]
Como não conseguimos um Mentor pra isso, que tal vocês tocarem, juntos, um [grupo de estudos](https://github.com/training-center/study-groups)?

**Comment by vyper** [comment]
Eu topo participar do grupo! (:

**Comment by cantoniazzi** [comment]
Boa, pode ser. O que você acha @ftonato ?
Só não tenho nenhuma ideia boa de plano de estudos/técnicas/ações/etc para focar nisso.
Eu estou trabalhando de casa e minha ideia era manter um horário fixo pra estudar coisas deste tipo. (talvez pela manhã bem cedo)
Poderiamos colocar em algum lugar e o pessoal que tem um bom entendimento/boa prática poderia sugerir conteúdos e a gente vai criando uma árvore de conhecimento hierárquica e vamos estudando por ordem. 
O que achas @woliveiras ?

**Comment by ftonato** [comment]
Fala @cantoniazzi, blz?
Cara eu acho legal, mas para montarmos a árvore de conteúdo precisaríamos de um "mentor", penso eu!

Eu tenho um material e poderia organizar p/ os níveis básicos, mas depois deles eu não sabia mais estrutura, é aí que deveria entrar o "mentor".

Durante meus estudos, li muitas coisas de professores e as dicas deles era: Não estude com pessoas que não saibam inglês, justamente para não estragar aquilo que a pessoa já sabe.

Apesar de eu concordar com isso, eu entendo que podemos sim estudar juntos, cada qual no seu ritmo, e as dúvidas deveremos tirar com pessoas com conhecimento elevado =)

A minha sugestão é: Criarmos um repositório, organizar o conteúdo por níveis (básico I, básico II, ... , Avançado III) e irmos estudando no nosso ritmo, e assim que conseguirmos um mentor, ele valida os conteúdos conosco. Além disso, podemos criar um grupo no Slack, um grupo fechado p/ no máximo 5 pessoas (só aqui, já temos três: eu, você e o @vyper) e irmos trocando ideias lá, conforme vamos aprendendo...

O conteúdo que temos que não puder ser distribuído por GitHub (seja pelo motivo que for), a gente conversa sobre através do Slack também!

O que acham?

_Sobre inglês, eu tirei muita informação útil dessa [issue](https://github.com/frontendbr/forum/issues/109), vocês podem mensurar o que julgam legal lá e que conseguiremos fazer, visto a disponibilidade de cada qual, e adicionar ao nosso repo_

**Comment by woliveiras** [comment]
Está rolando alguma interação entre vocês, pessoal?

**Comment by woliveiras** [comment]
Estamos com todos os Mentores e Mentoras ocupados no momento, adicionei a label `wait for new mentors` para que os próximos busquem por essas issues primeiro.

**Comment by ftonato** [comment]
@woliveiras Mudança de planos!
Vou criar um repositório p/ meus estudos da língua inglesa, caso alguém esteja interessado e queira participar do grupo, basta conversar comigo pelas issues e/ou os portais que disponibilizei acima!

Para os interessados, o link do repositório é esse -> https://github.com/ftonato/learn-english

//cc @cantoniazzi @vyper @raymonsanches @diegoponciano

**Comment by woliveiras** [comment]
Perfeito @ftonato
