### ISSUE TITLE
Reativação do mentoria: limpeza da lista de mentores(as)

### ISSUE THREAD

**Issue by woliveiras** [training-center/mentoria#921]
O mentoria está voltando!

Para isso foi criado um modelo paleativo até a criação da plataforma (https://github.com/training-center/plataforma).

O novo modelo já consta no README deste repositório e podemos voltar a divulgar o projeto em tudo que é lugar.

Precisamos ler e seguir fortemente o modelo proposto, pois será o modelo que utilizaremos de agora em diante.

Esta é uma boa issue para iniciantes, portanto deixe alguém que ainda não domina muito de Git e GitHub contribuir conosco. :) 

Caso você saiba de alguém, ajude essa pessoa a enviar o PR.

---

Para uma reativação efetiva, vamos limpar a lista de mentores(as) e aguardar que as pessoas ativas retornem seus nomes a lista.

## Como proceder

`Se você quiser resolver esta issue, comente aqui para aguardarmos o seu PR.`

Quem pegar esta issue para resolver deve baixar o projeto em sua máquina, ir até a lista de mentores (https://github.com/training-center/mentoria/blob/master/profiles/mentors/README.md) e deletar o seu conteúdo, deixando somente o seguinte conteúdo (que pode ser copiado e colado daqui para a lista):

```
# Lista de mentores(as)

> Conheça os(as) mentores(as) do projeto.

## Para novos(as) mentores(as)

Adicione nesta lista somente seu nome e área de atuação.

Ex.: 

| Nome  | Especialidade |
| ------------- | ------------- |
| William Oliveira  | Frontend  |

## Áreas de atuação

Estas são as áreas de atuação, conforme acordado no formulário de cadastramento de mentores(as):

| Especialidades |
| -------------------- |
| frontend |
| backend |
| bancos de dados |
| infraestrutura |
| fullstack |
| data science |
| agile |
| seo |
| marketing digital |
| mobile-android |
| mobile-ios |
| segurança da informação |

Caso você queira adicionar outra área de atuação, deve abrir uma issue para informar as pessoas de sua necessidade.

## Lista de mentores e mentoras

| nome | especialização  |
| -------  | --------------------  |
|           |                           |

```

**Comment by mahenrique94** [comment]
A lista ainda esta no padrão antigo.

**Comment by woliveiras** [comment]
É pra limpar a lista mesmo, mano...

Deixar só o conteúdo que está ali na issue.

Mas esta issue seria ideal para alguém iniciante de tudo. Precisamos ajudar a galera a se envolver com GitHub. :grimacing:

**Comment by angelilton** [comment]
alguém já fez esse aqui?

**Comment by woliveiras** [comment]
Valeu pelo PR, @angelilton
