### ISSUE TITLE
Reorganização do mentoria

### ISSUE THREAD

**Issue by woliveiras** [training-center/mentoria#922]
Como não fazemos mais a avaliação do perfil da pessoa via Pull Request, mas via triagem na planilha, acredito também que podemos deletar os perfis da pasta `profiles` (https://github.com/training-center/mentoria/tree/master/profiles), deixando somente dois documentos:

- a lista de mentores(as)
- a lista de mentorados(as)

O que acham?

Related to #921

**Comment by mahenrique94** [comment]
Mas como os mentorados iram avaliar nosso perfil?

**Comment by woliveiras** [comment]
Mas os mentorados não avaliam os perfis, mano.

É o contrário que acontece.

Na real foram pouquíssimas as pessoas que vieram buscar ajuda e avaliaram os perfis. No máximo viram se os nomes estavam na lista, mas fora isso eles estão desesperados por ajuda. :joy:

**Comment by mahenrique94** [comment]
Saquei.

**Comment by woliveiras** [comment]
O projeto foi reformulado.

https://github.com/training-center/mentoria/pull/948
