### ISSUE TITLE
Novas áreas de atuação

### ISSUE THREAD

**Issue by liviagabos** [training-center/mentoria#929]
Pensei que poderia ter uma área de atuação para Experiência do Usuário (UX) e Full Stack Designer também. Esse último ajudaria a separar o Full Stack do desenvolvedor voltado para backend.

**Comment by khaosdoctor** [comment]
Eu concordo com o UX, é uma área bem relevante.

Eu só não entendi a parte do Full Stack Designer, porque um programador com o título de Full Stack seria não só back-end mas também o front end e infraestrutura, a _stack toda_ da aplicação. O Full Stack Designer seria UX/UI + Front-end?

**Comment by woliveiras** [comment]
De fato fullstack que é realmente fullstack, pela boca do povo, deveria saber até design. :joy: 

Mas nunca pesquisei se existe separação entre fullstack frontend dev, fullstack backend dev ou fullstack designer pelo mercado de trabalho.

Também estou achando que o full + design seja a pessoa frontend ui/ux developer (que é o que está faltando no [carreira frontend](https://github.com/woliveiras/front-end-career/blob/master/translations/pt-br/README.md), por sinal), como o mano @khaosdoctor.

Sobre não ter UX e UI no mentoria, foi falha minha na hora de reescrever a documentação, foi mal galera. :scream: 

@liviagabos, acho que da pra mandar PR com essas áreas de atuação: `design de produto`, `ux design`, `ui design`, `design`.

O que acham?

**Comment by liviagabos** [comment]
Qual seria a diferença de design de produto e design ?

**Comment by khaosdoctor** [comment]
Acho que o __Design de produto__ focaria mais nos aspectos de negócio, desenho do produto em si, como ele funcionaria, quais seriam as features e quais seriam os casos de uso, personas e etc, seria o trabalho de um PO por exemplo.

O design seria o UX/UI, desenhando a experiencia de usuário, gráficos e etc.

Mas isto é a __minha opinião__ haha

**Comment by liviagabos** [comment]
@khaosdoctor talvez o termo design poderia estar a mais, porque tem um ui design.
Ou a pessoa poderia selecionar mais de uma especialidade, assim confunde menos.

**Comment by khaosdoctor** [comment]
@liviagabos Qual seria a sua ideia?

**Comment by liviagabos** [comment]
**design de produto, ux design, ui design**

Mas mais porque para mim design em si é muito abrangente e pode confundir a pessoa para selecionar as opções.

**Comment by khaosdoctor** [comment]
Acho que "Design de produto" talvez não fosse uma boa, porque isto é bastante relacionado a gerencia de projetos e etc. Podemos separar em Design Gráfico, UX/UI. 

Isto porque ter muitas categorias gerava um grande problema antes, porque as pessoas as vezes tinham uma categoria que era extremamente específica, se juntarmos o pessoal que tem afinidade com um tema podemos filtrar através das respostas dos formulários.

**Comment by liviagabos** [comment]
Concordo! Já existe gestão nas opções, pode confundir sim.
Acho que essas são boas opções.
blz @woliveiras ?

**Comment by woliveiras** [comment]
Opa! 

Desculpem a demora, galera.

Feito!

Adicionei as possibilidades: UI Design, UX Design e Design Gráfico. :raised_hands: 

Aqui os forms para validação:

- Buscam mentoria: https://trainingcentr.typeform.com/to/FRJkDb
- Querem mentorar: https://trainingcentr.typeform.com/to/mZWcXX

**Comment by khaosdoctor** [comment]
LOCO! Fechando a issue então :D
