### ISSUE TITLE
Preciso de um mentor para html e css

### ISSUE THREAD

**Issue by kAMAILEONTAs** [training-center/mentoria#930]
# Mentor(a) responsável por mim

## Meu Nome

David Valente Sampaio

## Qual meu sonho na carreira?

Ser um desenvolvedor com conhecimentos de front e back end

## Alguns links para me conhecer melhor

- [Facebook](https://www.facebook.com/bur.david)

- [Instagram](https://www.instagram.com/kamaileontas)

-  [Email](savne@yahoo.com.br)

**Comment by crisgon** [comment]
Olá, deu uma lida no readme e preencheu o formulário? Pelo que sei o programa de mentoria ta passando por mudanças, então pode ser que demore um pouco para conseguir um. Mas entra no slack, qualquer coisa é só deixar uma mensagem lá que a gente te ajuda. 😄 
https://ctgroups.slack.com

**Comment by kAMAILEONTAs** [comment]
Preenchi sim. Beleza. Tô meio travado na questão de posicionamento de divs. Vi várias vídeo aulas mas não sanei minha dúvida. Vou ver se posto lá no slack. Valeu pelo feedback! 

Enviado do Yahoo Mail no Android 
 
  Em qua, 21 21e fev 21e 2018 às 0:26, Cristiano Gonçalves&It;notifications@github.com> escreveu:   
Olá, deu uma lida no readme e preencheu o formulário? Pelo que sei o programa de mentoria ta passando por mudanças, então pode ser que demore um pouco para conseguir um. Mas entra no slack, qualquer coisa é só deixar uma mensagem lá que a gente te ajuda. 😄
https://ctgroups.slack.com

**Comment by woliveiras** [comment]
Fala, @kAMAILEONTAs 

Não conseguimos mentores(as) através de issues. 

É só responder o form e aguardar, meu querido. :raised_hands: 

Logo alguém entra em contato contigo, viu. :pray: 

Vou fechar a issue por não ser o fluxo correto de conseguir mentoria.

Qualquer dúvida estamos a disposição para ajudar.
