### ISSUE TITLE
Troca de mentorias

### ISSUE THREAD

**Issue by danilosilvadev** [training-center/mentoria#932]
e se a  mentoria fosse uma troca? em vez de mentor poderia ser assim, eu te ensino X em troca vc me ensina Y. Ae marcam no skype, uma hora com X e uma com Y.

**Comment by woliveiras** [comment]
Fala, mano!

Rapaz, isso não seria mentoria, mas uma troca de experiências... 

Mentoria é acompanhar o processo da pessoa, é conhecer o que motiva a outra pessoa e planejar a carreira dela em conjunto.

Mas essa sua ideia é muito maneira para outro tipo de projeto.

Existia um site para fazer essa troca de XP, mas não encontrei ele aqui. :/

**Comment by woliveiras** [comment]
O mentoria foi reformulado.

https://github.com/training-center/mentoria/pull/948
