### ISSUE TITLE
Preciso de um mentor de programação!

### ISSUE THREAD

**Issue by tconcordio** [training-center/mentoria#933]
# Mentor(a) responsável por mim
(aguardando definição)

## Meu Nome
Thiago Concórdio

## Qual meu sonho na carreira?
Tenho 34 anos. Sempre empreendi em negócios próprios ou de terceiros. Muitas vezes esbarrei na necessidade de uma função num software existente e na constatação da necessidade de criar um software do zero, que atendesse a minha visão de negócios e principalmente às demandas do mercado, do consumidor, da empresa, dos colaboradores, da sociedade, etc. Meu sonho é estar pronto para produzir, testar e implementar um software atendendo essas demandas, pois a constatação de que tudo começa por um software sempre vem a tona.

## Alguns links para me conhecer melhor
[Facebook do Pupilo de Castro](https://www.facebook.com/tconcordio)
[Twitter do Pupilo de Castro](https://twitter.com/tconcordio)
[LinkedIn de Thiago Concórdio](https://www.linkedin.com/in/tconcordio/)
[GitHub do Thiago Concórdio](https://github.com/tconcordio)

**Comment by woliveiras** [comment]
Olá, @tconcordio!

O procedimento é via formulário de contato.

Da uma conferida nessa parte da doc: https://github.com/training-center/mentoria#preciso-de-mentoria

Já mande e aguarde o contato, pois estamos correndo atrás de mentores(as)! \o/

E boa sorte na sua caminhada, cara.

Vou fechar a issue para não atrapalhar o fluxo.

Qualquer dúvida é só abrir outra issue `com a questão`.

Valeu!
