### ISSUE TITLE
Preciso de um Mentor(a)

### ISSUE THREAD

**Issue by apocalipse51** [training-center/mentoria#935]
**Nome**: Gabriel Antonio
**Descrição:** Orientações de Carreira, boas práticas, tdd, design patterns, web.
**Nível de conhecimento atual**:  Fiz alguns semestres de Ciência da Computação, e fiz um Técnico em Informática onde iniciei a trajetória na programação, atualmente trabalho com dev jr em uma empresa de automação de serviços para call center, eu desenvolvo ferramentas internas como: controle de ponto, registro de horas de projeto, relátorios, e até alguns protótipos de BI...  Uso C# no back end, e AngularJS no front end atualmente.
**Contatos**: gabrielantonio20111@hotmail.com

**Comment by woliveiras** [comment]
Fala, @apocalipse51!

Mano, o processo para conseguir mentor é esse aqui: https://github.com/training-center/mentoria#preciso-de-mentoria

Demora um pouco, mas será atendido, viu. :pray:
