### ISSUE TITLE
Proposta para o Mentoria

### ISSUE THREAD

**Issue by woliveiras** [training-center/mentoria#946]
Olá, pessoal!

Venho aqui mais uma vez questionar sobre o formato do Mentoria (me desculpem).

No formato atual temos o seguinte processo:

- uma pessoa que deseja se tornar mentor(a) se cadastra no formulário e nós fazemos uma triagem do seu perfil para avaliar se está apto(a) a prestar mentoria; com tudo OK nós damos acesso para essa pessoa a planilha de mentorados(as) e também damos acesso a este repositório
- uma pessoa que deseja ser mentorada se cadastra no formulário e aguarda contato

Este foi o modelo mais simplificado que chegamos depois que percebemos que o GitHub é uma grande barreira para nossos mentorados.

## Problemas

A triagem pode demorar muito, pois dependemos do tempo livre das pessoas que estão cuidando da triagem. Além disso acabamos sobrecarregando essa pessoa quando não temos tempo para ajudar.

Não acompanhamos novos mentores (uma espécie de integração) para ajudar a se inteirar sobre como o mentoria funciona e também como ajudar as pessoas e tirar suas dúvidas no começo porque estamos quebrando cabeça com a triagem.

## Por que não criamos uma plataforma para o Mentoria?

Já tentamos, porém isso demanda muita mão de obra para a criação do projeto, manutenção e, além do fator humano, custa dinheiros para manter a hospedagem e nós não temos meios interessantes para adquirir dinheiro sem dar privilégios para pessoas mais abastadas e desequilibrar a balança que nós queremos manter em equilíbrio, que é disponibilizar conhecimento gratuito para as pessoas mudarem de vida.

---

## Proposta de novo modelo

Nós já tentamos, de diversos modos, fazer o projeto mentoria rodar como um sistema, porém temos diversos problemas com essa abordagem, como:

- falta braço para manter o sistema
- as pessoas tem preguiça de usar o projeto como nós pedimos para que usem (elas atuam mentorando via Slack ou até pessoalmente, porém não seguem o fluxo proposto aqui no repositório)
- mentorados se perdem no processo

Agora eu acho que chegou a hora de darmos o braço a torcer e partir para o modelo mais simples de todos que é:

- o mentor ou a mentora coloca seu nome e a maneira como deseja receber contato aqui no repositório e as pessoas procuram sua ajuda

Exemplo:

Eu deixaria aqui no repositório o seguinte

| Nome | Presta mentoria em... | Contato
| --- | --- | --- |
| William Oliveira | Front End | Telegram: `@woliveiras`

Mas este é só um exemplo bem cru da ideia.

O que vocês acham?

**Restrições**

- novos mentores e mentoras terão que fazer um pull request aqui no repositório para colocar seu nome na lista

> Caso ninguém se manifeste contra essa ideia, o projeto será alterado para esse novo formato para que voltemos a ajudar as pessoas, afinal o mentoria está aqui e está "parado" por muito tempo com algumas pessoas gastando seu tempo na triagem e, muitas vezes, gastando sua energia mental por esse projeto. É uma questão muito importante para a comunidade Training Center reavivar essa iniciativa.

**Comment by anegrelli** [comment]
Ola Willian tudo bem, a forma que você demonstrou o projeto está bem simples e acredito que funcional, minha sugestão é só estruturar um pouquinho mais, por exemplo no formato de um coach com sessões de mentoria em determinado assunto e área de conhecimento do mentor que o mentirado tem interece. Isso para delimitar o que será transmitido e o que o mentiradonura aprender, tipo uma grade curricular para cada mentor. Outro ponto poderiam utilizar alguma ferramenta gratuita e tuitava para gerenciar isso como o Pipefy ou até mesmo o trello, o Git é muito bom mas não para este objetivo. Se eu puder contribuir com alguma coisa ficarei feliz, forte abraço.

**Comment by liviagabos** [comment]
@anegrelli talvez o que você sugeriu venha de encontro com a minha ideia de lives para ajudar o pessoal com as mentorias. Para ajudar os mentores e para incentivar pessoas a serem mentores.
Mas se você puder explicar melhor, pq o que eu tinha pensado não era algo individual.

@woliveiras eu acho melhor, porque ajuda a pessoa a saber no que pode ou não ajudar os outros. E as pessoas que procuram mentoria isso talvez ajude a saber o que estão procurando.
Eu estou mentorando uma pessoa, mas não em programação e sim na parte de engenharia de software.

**Comment by lasombra** [comment]
Em termos de processo, poderíamos criar um canal no Slack onde a pessoa que está procurando mentore/as simplesmente descrevem o que estão procurando, seja linguagem, tecnologia ou processo, por exemplo, e usa algumas palavras-chave onde, cada mentor, teria um highlight configurado.

Por exemplo "Oi, me chamo José e estou procurando mentoria em #javascript #backend #nodejs". # ou @ ou qualquer outro carácter para ajudar no highlight.

**Comment by lbighetti** [comment]
Pra mim __menos__, é __melhor__.

To contigo @woliveiras !

e a idéia da @liviagabos de lives é excepcional na minha opinião, porque fazendo lives 1 mentor atinge N mentorados, muito mais efetivo do que 1 a 1.

Entendo que o 1 a 1 tem o seu lugar ainda e pra assuntos que não cabem em lives, e nesse caso acho muito boa essa simplificação !

**Comment by mahenrique94** [comment]
Como diz o Fogaça: **Menos é mais**.

Concordo com o método @woliveiras.

Também concordo com a proposta de lives da @liviagabos, mas, um tempinho no individual também ajuda muito, muitos deixam de perguntar por conta de outras pessoas.

O único problema que eu vejo é a sobrecarga no mentor, pois essa forma, um ou N mentorados podem chamá-lo para contato.

**Comment by enieber** [comment]
mas nesse caso o mentor ficaria responsável por se organizar @mahenrique94 , algo semelhante ao que acontece nos QA session do pessoal do React Brazil

**Comment by mahenrique94** [comment]
Eu to ligado que ele ficaria responsável por se organizar @enieber, mas imagine sua caixa de email lotada de emails sobre os mentorados ou inúmeros chats no telegram, será que é uma boa? A ideia é boa, mas isso me incomodaria um pouco.

**Comment by luizbills** [comment]
Essa é um das raras vezes que não sou contra um breaking change.

**Comment by WendellAdriel** [comment]
Eu estava no time para ajudar a gerenciar o Mentoria e pelos meus problemas pessoais acabei ficando muito por fora, já peço desculpas @woliveiras, mas eu concordo que menos é mais. Quanto menos passos e quanto menor a burocracia, mais fácil é de se ajudar.

Eu não estou mentorando mais, mas mesmo assim sempre aparecem pessoas em minhas redes sociais perguntando sobre algo e sempre ajudo na medida do possível, então meio que continuo como mentor, apenas não é algo fixo e estruturado que fazia com meus antigos mentorados!!! xD

Como mencionei na outra issue da organização do TC, quero ajudar nos projetos do TC, só precisamos conversar para ver qual será a melhor forma de eu conseguir ajudar sem interferir nos problemas que mencionei na outra issue!!! xD

**Comment by matuklong** [comment]
Concordo também em deixar o processo mais simples para ganhar tração. As Lives para orientar o mentor são importantes para manter a qualidade. Minha preocupação é a gente não conseguir manter a qualidade e a mentoria se tornar um forum de ajuda.

Estou iniciando agora como mentor e tenho muitas dúvidas de como conduzir a mentoria após a seleção do candidato. Para ajudar, algumas "boas práticas" e orientações para o mentor podem ajudar:
- Duração de 1 a 3 meses.
- Quantidade de vezes e tempo que falaremos com mentorado na semana.
- Avaliações durante o processo de mentoria.
- Avaliação no final do processo.

Acredito que isto seria algo mínimo que o mentor deveria fazer, e assim seria possível nos avaliarmos entre si, e evoluir.

**Comment by liviagabos** [comment]
Acho que podemos deixar um indicador no template da pessoa que quer dar mentoria, se ela está aberta a aceitar mentores ou não.
tirar dúvidas no cotidiano, as pessoas sempre tiram...mas acho que com um indicador a pessoa vai ficar menos perdida procurando.

**Comment by woliveiras** [comment]
Galera, muito boa essa conversa aqui! 

Vocês são feras!!! 

Eu abri o PR (#948) e podemos discutir diretamente por lá agora. :heart:
