### ISSUE TITLE
Legendas

### ISSUE THREAD

**Issue by luizbills** [training-center/mentoria#969]
Notei que na lista de mentores tem um dos mentores que está com :snowflake: na coluna CONTATO. Provavelmente significa que ele não está dando mentoria. Seria legal adicionar uma **legenda** no arquivo para evitar dúvidas.

**Comment by woliveiras** [comment]
Boa ideia, @luizbills!!!

**Comment by woliveiras** [comment]
Feito, mano! :D 

[lista](https://github.com/training-center/mentoria/blob/master/mentors-list.md)
