### ISSUE TITLE
Adicionar pupilos a organização

### ISSUE THREAD

**Issue by woliveiras** [training-center/mentoria#98]
@training-center/pupils 

Galera, adicionei vocês na organização.

Coloquem a participação de vocês na org como publico da seguinte maneira:

- Acessem esse link: https://github.com/orgs/training-center/people
- Localizem seu perfil
- Mudem onde está **private** para **public**

**Comment by woliveiras** [comment]
@training-center/future-mentors 

Todos já colocaram a participação como public no perfil?

**Comment by woliveiras** [comment]
@training-center/pupils, alguém?

Me respondam pra eu não ficar triste gente. kkkkk

**Comment by jessuircleydson** [comment]
Ainda falta gente.
Isso é pra que mesmo?

**Comment by woliveiras** [comment]
Faltam 8 aceitarem ainda. 😞 

É pra eles ganharem um badgezinho da org pra ter no GitHub. 😄

**Comment by marcoblos** [comment]
@woliveiras eu estou acompanhando aqui, mas isso ainda não é pra mim, né?

**Comment by woliveiras** [comment]
Assim que subir seu perfil, eu te adiciono na org mano. 

Se quiser, pode subir seu perfil e depois só atualizar com o mentor que for te ajudar. 😄

**Comment by marcoblos** [comment]
Boa!
Assim que eu subir o perfil eu te marco aqui.
:+1:

**Comment by idlua** [comment]
Done! ^^

**Comment by LajackBR** [comment]
Já coloquei! :smile:

**Comment by marcoblos** [comment]
Só falta aceitar o [PR](https://github.com/training-center/mentoria/pull/101)
:dancer:

**Comment by woliveiras** [comment]
Ta lá @marcoblos! :raised_hands:

**Comment by woliveiras** [comment]
Já adicionei todo mundo!

Alguns pupilos não aceitaram ainda, mas já estamos atrás do pessoal. :grin:
