### ISSUE TITLE
Quero ser mentor de full-stack (foco em javascript).

### ISSUE THREAD

**Issue by wesleycoder** [training-center/mentoria#99]
**Nome:** Wésley Queiroz

**Descrição:** estou me dispondo à participar deste projeto com o fim de ajudar aos iniciantes e também expandir minha visão como desenvolvedor no processo.
Atuo na área de desenvolvimento à 6 anos e já passei por bons e maus bocados como todos que já estão à algum tempo na área, rsrs.

Iniciei a faculdade de Sistemas de Informação em uma faculdade privada com bolsa pelo ProUni. Porém devido à minha natureza autodidata me desmotivei com o curso que apresentava conteúdos pobres e muito desatualizados e poucos professores que realmente se preocupavam com a sede de conhecimento que alguns poucos alunos apresentavam.
Abandonei o curso após um ano e meio e corri atrás de me atualizar por conta própria, algo que não deixei de fazer nenhum dia sequer até hoje (e ninguém deveria deixar de fazer não é mesmo?).

Faz um bom tempo que procuro uma oportunidade de mentorar, recentemente apareceu um rapaz que aparenta estar bem empolgado com a área aqui na cidade onde eu moro (Poá - SP) e estou procurando auxiliá-lo com o que eu tenho para passar.
Porém acho que será algo bom poder ajudar os pupilos que aparecerem por aqui neste projeto também.

Atualmente estou fazendo freelances aqui e ali, enquanto encontro uma oportunidade que se encaixe com minha sede de conhecimento insaciável.

Minha especialidade é sem dúvida JavaScript, procuro sempre manter esta adaga afiada para enfrentar todos os desafios por aí. Ainda mais nos últimos anos onde essa adaga se tornou uma arma cada vez mais poderosa e não parece que vai perder este poder por tanto tempo. (Até parece que estou narrando um RPG hahaha).

Onde me sinto mais confortável é sim no front-end com os mais diversos frameworks experimentando desde as misturas entre jQuery com Mustache.js passando por Angular e terminando no meu querido React, porém tenho adquirido bastante experiência no mundo Node.js com frameworks como o popular express ou Koa e até mesmo trabalhando com nossa linha de comando em alguns scripts exploratórios com a finalidade de me divertir.

Tenho conhecimentos em CSS, acessibilidade (a11y), componentização e modularização, git em equipe, webpack, jspm, gulp, yeoman, slush, Ruby, Python, ASP Net e PHP (dois dos quais não tenho muito orgulho de dizer que conheço, mas ninguém é perfeito né?).

Também tenho experiência com modelagem de BD relacionais com MySQL, Postgres e Sqlite.
E também uma paixão por bancos não relacionais como o amado MongoDB ou Redis, Elastic Search, CouchDB e MemcacheDB. 

**Contatos:**
[Facebook](https://facebook.com/wesleycoder)
[Twitter](https://twitter.com/wesleycoder)
[Github](https://github.com/wesleycoder)
[E-mail](mailto:wesley.coder@gmail.com)

**Comment by woliveiras** [comment]
Passei pelo mesmo com uma faculdade cara...

Se der, chama o rapaz que você já ajuda para criar um perfil aqui também. :)

PHP até vai cara, mas ASP.NET... UUUUURGH!

Já pode criar seu perfil rapaz!

Se tiver um conhecimento maneiro de Rails, daria até pra já começar ajudando esse cara aqui, https://github.com/training-center/mentoria/issues/34, junto com o @jessuircleydson 

:smile:

**Comment by raulfdm** [comment]
Olá @wesleycoder. 
Acabei de ler seu post e fiquei muito interessado em ser seu pupilo.
Eu acabei de conhecer esse projeto de mentoria e fiquei maravilhado com a proposta, acho que é exatamente isso que eu preciso, uma vez que eu venho estudando e tentando trilhar meu caminho por conta própria.

Eu faço faculdade de Sistemas de Informação, compartilho do mesmo sentimento que você a respeito disso, entretanto, um dos meus planos de vida é morar em outro país e eu descobri que em alguns deles um simples diploma de graduação de 4 anos, conta como 10 anos de experiencia e abre as portas para um possível visto de residente. 

Quando entrei na faculdade (2013), possuía uma noção muito básica de programação. Tive contato com C, depois C++ e em seguida Java e Android. Entretanto, apesar de me aventurar nessas linguagens, meu objetivo de vida mesmo é ser um dev full stack com foco no JS. 

Há 2 meses eu estou estudando todos os dias JavaScript e fazendo cursos sobre tudo o que envolve. Tenho assinatura do Alura, e fiz os cursos, básicos e avançados de JS e Node. Estou aplicando os conceitos em um projeto de pessoal de Controle de Ponto (ta no meu github).

Por fim, caso você tenha interesse em ser meu mentor, eu ficaria extremamente grato!

**Comment by wesleycoder** [comment]
@raulfdm exatamente, um diploma é um peso grande quando se trata de migrar para fora do Brasil.
Apesar de eu ter abandonado meu curso eu me arrependo de não ter insistido mais nisso. Continue insistindo no seu curso até o fim, é chato absorver conteúdo desatualizado e não relacionado com o que você quer de verdade, mas conhecimento nunca é demais e de uma forma ou de outra vai ser útil para você.

Javascript para mim é a linguagem que mais lhe recompensa por se apaixonar por ela.
O mercado têm crescido exponencialmente, apesar de o Brasil estar muito atrasado como sempre, mas continua crescendo. Isso possibilita que você não necessite se sobrecarregar tanto com conhecimentos variados e possa se focar em aprimorar o conhecimento em uma ferramenta poderosa.

Estou interessado sim em me tornar teu mentor. Crie seu perfil aqui e então podemos entrar em contato para combinar como faremos.

**Comment by raulfdm** [comment]
@wesleycoder acabei de criar o perfil. Porém na hora de colocar o mentor, eu não encontrei você na lista!

De qualquer forma, segue meu [facebook](https://www.facebook.com/raulfdm), caso  queira trocar uma ideia.

**Comment by wesleycoder** [comment]
Ah sim, fiz o pull request à pouco #102. Está pendente de aprovação mas em breve você poderá encontrar-me na lista.

**Comment by woliveiras** [comment]
Tá lá @wesleycoder!

Agora é só tacar lenha ajudando esse povão. :smile: 

Se precisar de alguma ajuda é só chamar alguém do time! :punch::punch::punch:
